//! Generated by tsz compiler — d93_dashboard_full [nodes.zig]
//! Source: d93_dashboard_full.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const handlers = @import("handlers.zig");

// [origin:d93_dashboard_full:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d93_dashboard_full.tsz:120 — <Pressable>
pub var _arr_0 = [_]Node{ .{ .text = "Overview", .font_size = 11, .text_color = Color.rgb(0, 0, 0) } }; // NavItem
// tsz:d93_dashboard_full.tsz:120 — <Pressable>
pub var _arr_1 = [_]Node{ .{ .text = "Users", .font_size = 11, .text_color = Color.rgb(0, 0, 0) } }; // NavItem
// tsz:d93_dashboard_full.tsz:120 — <Pressable>
pub var _arr_2 = [_]Node{ .{ .text = "Events", .font_size = 11, .text_color = Color.rgb(0, 0, 0) } }; // NavItem
// tsz:d93_dashboard_full.tsz:136 — <Pressable>
pub var _arr_3 = [_]Node{ .{ .text = "", .font_size = 9, .text_color = Color.rgb(148, 163, 184) } };
// tsz:d93_dashboard_full.tsz:139 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "", .font_size = 8, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d93_dashboard_full.tsz:129 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "Dashboard", .font_size = 13, .text_color = Color.rgb(0, 0, 0) }, .{ .style = .{ .height = 8 } }, .{ .style = .{ .padding = 8, .border_radius = 6, .background_color = Color{} }, .handlers = .{ .on_press = handlers._handler_press_0 }, .children = &_arr_0 }, .{ .style = .{ .padding = 8, .border_radius = 6, .background_color = Color{} }, .handlers = .{ .on_press = handlers._handler_press_1 }, .children = &_arr_1 }, .{ .style = .{ .padding = 8, .border_radius = 6, .background_color = Color{} }, .handlers = .{ .on_press = handlers._handler_press_2 }, .children = &_arr_2 }, .{ .style = .{ .flex_grow = 1 } }, .{ .style = .{ .padding = 6, .border_radius = 4, .background_color = Color.rgb(51, 65, 85) }, .handlers = .{ .on_press = handlers._handler_press_3 }, .children = &_arr_3 }, .{ .style = .{ .background_color = Color.rgb(239, 68, 68), .border_radius = 10, .padding_left = 6, .padding_right = 6, .padding_top = 2, .padding_bottom = 2, .align_self = .start }, .children = &_arr_4 } };
// tsz:d93_dashboard_full.tsz:146 — <Pressable>
pub var _arr_6 = [_]Node{ .{ .text = "", .font_size = 14, .text_color = Color.rgb(148, 163, 184) } };
// tsz:d93_dashboard_full.tsz:145 — <Box>
pub var _arr_7 = [_]Node{ .{ .style = .{ .padding = 6 }, .handlers = .{ .on_press = handlers._handler_press_4 }, .children = &_arr_6 }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(100, 116, 139) } };
// tsz:d93_dashboard_full.tsz:153 — <Box>
pub var _arr_9 = [_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 8, .flex_wrap = .wrap } } };
// tsz:d93_dashboard_full.tsz:160 — <Box>
pub var _arr_11 = [_]Node{ .{ .text = "Recent Events", .font_size = 11, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .gap = 4 } } };
// tsz:d93_dashboard_full.tsz:159 — <Box>
pub var _arr_12 = [_]Node{ .{ .style = .{ .flex_grow = 1, .background_color = Color{}, .border_radius = 8, .padding = 12, .gap = 4, .overflow = .auto }, .children = &_arr_11 } };
// tsz:d93_dashboard_full.tsz:153 — <>
pub var _arr_13 = [_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 8, .flex_wrap = .wrap }, .children = &_arr_9 }, .{ .style = .{ .flex_direction = .row, .gap = 12 }, .children = &_arr_12 } };
// tsz:d93_dashboard_full.tsz:176 — <Pressable>
pub var _arr_14 = [_]Node{ .{ .text = "Sort", .font_size = 9, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d93_dashboard_full.tsz:179 — <Pressable>
pub var _arr_15 = [_]Node{ .{ .text = "", .font_size = 9, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d93_dashboard_full.tsz:175 — <Box>
pub var _arr_16 = [_]Node{ .{ .style = .{ .padding = 6, .background_color = Color.rgb(51, 65, 85), .border_radius = 4 }, .handlers = .{ .js_on_press = "sortUsers()" }, .children = &_arr_14 }, .{ .style = .{ .padding = 6, .background_color = Color{}, .border_radius = 4 }, .handlers = .{ .js_on_press = "toggleFilter()" }, .children = &_arr_15 }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(100, 116, 139) } };
// tsz:d93_dashboard_full.tsz:174 — <Box>
pub var _arr_19 = [_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 6 }, .children = &_arr_16 }, .{ .style = .{ .gap = 8 } } };
// tsz:d93_dashboard_full.tsz:199 — <Pressable>
pub var _arr_20 = [_]Node{ .{ .text = "+ Add", .font_size = 8, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d93_dashboard_full.tsz:197 — <Box>
pub var _arr_21 = [_]Node{ .{ .text = "Event Log", .font_size = 11, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .padding = 4, .background_color = Color.rgb(51, 65, 85), .border_radius = 4 }, .handlers = .{ .js_on_press = "addEvent('Manual event #' + eventCount,0)" }, .children = &_arr_20 } };
// tsz:d93_dashboard_full.tsz:203 — <ScrollView>
pub var _arr_24 = [_]Node{ .{} };
// tsz:d93_dashboard_full.tsz:196 — <Box>
pub var _arr_25 = [_]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between }, .children = &_arr_21 }, .{ .style = .{ .overflow = .scroll, .flex_grow = 1 }, .children = &_arr_24 } };
// tsz:d93_dashboard_full.tsz:144 — <Box>
pub var _arr_26 = [_]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center }, .children = &_arr_7 }, .{ .children = &_arr_13 }, .{ .style = .{ .background_color = Color{}, .border_radius = 8, .padding = 12, .gap = 8 }, .children = &_arr_19 }, .{ .style = .{ .background_color = Color{}, .border_radius = 8, .padding = 12, .gap = 4 }, .children = &_arr_25 } };
// tsz:d93_dashboard_full.tsz:128 — <Box>
pub var _arr_27 = [_]Node{ .{ .style = .{ .width = 150, .background_color = Color{}, .padding = 12, .gap = 4, .border_color = Color{}, .border_width = 1 }, .children = &_arr_5 }, .{ .style = .{ .flex_grow = 1, .padding = 16, .gap = 12, .overflow = .auto }, .children = &_arr_26 } };
// [origin:d93_dashboard_full:root]
pub var _root = Node{ .style = .{ .background_color = Color{}, .width = -1, .height = -1, .flex_direction = .row, .overflow = .hidden }, .children = &_arr_27 };

