//! Generated by tsz compiler — d45_union_type_alias [handlers.zig]
//! Source: d45_union_type_alias.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:d45_union_type_alias:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:d45_union_type_alias:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobalInt("filterByKind", 0);
}

// [origin:d45_union_type_alias:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobalInt("filterByKind", 1);
}

// [origin:d45_union_type_alias:handler:_handler_press_2]
pub fn _handler_press_2() void {
    qjs_runtime.callGlobalInt("filterByKind", 2);
}

// [origin:d45_union_type_alias:handler:_handler_press_3]
pub fn _handler_press_3() void {
    qjs_runtime.callGlobalInt("filterByKind", 3);
}

