//! Generated by tsz compiler — d45_union_type_alias [logic.zig]
//! Source: d45_union_type_alias.tsz


// [origin:d45_union_type_alias:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\var entries = [];
    \\// OA initial data
    \\setEntries([ { label : "" , kind : 0 , payload : 0 , detail : "" } ]);
    \\var filter = 0;
    \\function setFilter(v) { filter = v; __setState(0, v); }
    \\var output = '';
    \\function setOutput(v) { output = v; __setStateString(1, v); }
    \\var visibleCount = 0;
    \\function setVisibleCount(v) { visibleCount = v; __setState(2, v); }
    \\var feed = [
    \\  { label: 'Login success', kind: 0, payload: 200, detail: 'user: alice' },
    \\  { label: 'Payment received', kind: 1, payload: 4999, detail: 'order #1234' },
    \\  { label: 'API timeout', kind: 2, payload: 504, detail: 'GET /users' },
    \\  { label: 'Signup complete', kind: 0, payload: 201, detail: 'user: bob' },
    \\  { label: 'Refund issued', kind: 1, payload: 1500, detail: 'order #1189' },
    \\  { label: 'Disk warning', kind: 2, payload: 92, detail: '92% full' },
    \\  { label: 'Session start', kind: 0, payload: 200, detail: 'user: carol' }
    \\];
    \\setEntries(feed);
    \\setVisibleCount(feed.length);
    \\
    \\function filterByKind(k) {
    \\  setFilter(k);
    \\  if (k === 0) {
    \\    setVisibleCount(feed.length);
    \\    setEntries(feed);
    \\    setOutput('showing all');
    \\    return;
    \\  }
    \\  var result = [];
    \\  for (var i = 0; i < feed.length; i++) {
    \\    if (feed[i].kind === k - 1) result.push(feed[i]);
    \\  }
    \\  setEntries(result);
    \\  setVisibleCount(result.length);
    \\  setOutput('filtered kind=' + (k - 1));
    \\}
    \\function setEntries(v) { entries = v; __setObjArr0(v); }
    \\if (entries && entries.length > 0) setEntries(entries);
    \\
;

// [origin:d45_union_type_alias:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

