//! Generated by tsz compiler — d88_data_table [handlers.zig]
//! Source: d88_data_table.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:d88_data_table:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:d88_data_table:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobalStr("applyFilter", "");
}

// [origin:d88_data_table:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobalStr("applyFilter", "admin");
}

// [origin:d88_data_table:handler:_handler_press_2]
pub fn _handler_press_2() void {
    qjs_runtime.callGlobalStr("applyFilter", "dev");
}

// [origin:d88_data_table:handler:_handler_press_3]
pub fn _handler_press_3() void {
    qjs_runtime.callGlobalStr("applyFilter", "design");
}

// [origin:d88_data_table:handler:_handler_press_4]
pub fn _handler_press_4() void {
    qjs_runtime.callGlobal("sortByName");
}

