//! Generated by tsz compiler — d88_data_table [state.zig]
//! Source: d88_data_table.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d88_data_table:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: page (int)
// slot 1: sortCol (int)
// slot 2: filterRole (string)
// slot 3: selectedRow (int)
// slot 4: totalRows (int)
comptime { if (5 != 5) @compileError("state slot count mismatch"); }

// [origin:d88_data_table:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_1: []const u8 = "";

pub const qjs = @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
pub const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// [origin:d88_data_table:state]
// ── Object arrays ───────────────────────────────────────────────
pub const _oa_alloc = std.heap.page_allocator;

pub fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

pub fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

pub var _oa0_name: [][]const u8 = &[_][]const u8{};
pub var _oa0_name_lens: []usize = &[_]usize{};
pub var _oa0_name_cap: usize = 0;
pub var _oa0_email: [][]const u8 = &[_][]const u8{};
pub var _oa0_email_lens: []usize = &[_]usize{};
pub var _oa0_email_cap: usize = 0;
pub var _oa0_role: [][]const u8 = &[_][]const u8{};
pub var _oa0_role_lens: []usize = &[_]usize{};
pub var _oa0_role_cap: usize = 0;
pub var _oa0_status: []i64 = &[_]i64{};
pub var _oa0_status_cap: usize = 0;
pub var _oa0_len: usize = 0;
pub var _oa0_dirty: bool = false;

pub fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_name_cap) return;
    const new_cap = @max(needed, if (_oa0_name_cap == 0) @as(usize, 64) else _oa0_name_cap * 2);
    if (_oa0_name_cap == 0) {
        _oa0_name = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_name_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens, 0);
    } else {
        const _old_cap = _oa0_name_cap;
        _oa0_name = _oa_alloc.realloc(_oa0_name.ptr[0.._old_cap], new_cap) catch return;
        _oa0_name_lens = _oa_alloc.realloc(_oa0_name_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens[_old_cap..new_cap], 0);
    }
    _oa0_name_cap = new_cap;
    if (_oa0_email_cap == 0) {
        _oa0_email = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_email_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_email[_j] = &[_]u8{};
        @memset(_oa0_email_lens, 0);
    } else {
        const _old_cap = _oa0_email_cap;
        _oa0_email = _oa_alloc.realloc(_oa0_email.ptr[0.._old_cap], new_cap) catch return;
        _oa0_email_lens = _oa_alloc.realloc(_oa0_email_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_email[_j] = &[_]u8{};
        @memset(_oa0_email_lens[_old_cap..new_cap], 0);
    }
    _oa0_email_cap = new_cap;
    if (_oa0_role_cap == 0) {
        _oa0_role = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_role_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_role[_j] = &[_]u8{};
        @memset(_oa0_role_lens, 0);
    } else {
        const _old_cap = _oa0_role_cap;
        _oa0_role = _oa_alloc.realloc(_oa0_role.ptr[0.._old_cap], new_cap) catch return;
        _oa0_role_lens = _oa_alloc.realloc(_oa0_role_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_role[_j] = &[_]u8{};
        @memset(_oa0_role_lens[_old_cap..new_cap], 0);
    }
    _oa0_role_cap = new_cap;
    if (_oa0_status_cap == 0) {
        _oa0_status = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_status, 0);
    } else {
        _oa0_status = _oa_alloc.realloc(_oa0_status.ptr[0.._oa0_status_cap], new_cap) catch return;
        @memset(_oa0_status[_oa0_status_cap..new_cap], 0);
    }
    _oa0_status_cap = new_cap;
}

// [origin:d88_data_table:oa:_oa0_unpack]
pub fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "name");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_name[_i], &_oa0_name_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_name[_i] = _oaDupString(sl); _oa0_name_lens[_i] = _oa0_name[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "email");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_email[_i], &_oa0_email_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_email[_i] = _oaDupString(sl); _oa0_email_lens[_i] = _oa0_email[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "role");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_role[_i], &_oa0_role_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_role[_i] = _oaDupString(sl); _oa0_role_lens[_i] = _oa0_role[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "status");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_status[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa0_len) {
        for (count.._oa0_len) |_trim_i| {
            _oaFreeString(&_oa0_name[_trim_i], &_oa0_name_lens[_trim_i]);
            _oaFreeString(&_oa0_email[_trim_i], &_oa0_email_lens[_trim_i]);
            _oaFreeString(&_oa0_role[_trim_i], &_oa0_role_lens[_trim_i]);
        }
    }
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa1_name = [_][]const u8{ "Alice Chen", "Bob Kim", "Carol Wu", "Dave Park", "Eve Liu", "Frank Lee", "Grace Ho", "Hank Li", "Iris Ng", "Jack Ma" };
pub var _oa1_name_lens = [_]usize{ 10, 7, 8, 9, 7, 9, 8, 7, 7, 7 };
pub var _oa1_email = [_][]const u8{ "alice@co.io", "bob@co.io", "carol@co.io", "dave@co.io", "eve@co.io", "frank@co.io", "grace@co.io", "hank@co.io", "iris@co.io", "jack@co.io" };
pub var _oa1_email_lens = [_]usize{ 11, 9, 11, 10, 9, 11, 11, 10, 10, 10 };
pub var _oa1_role = [_][]const u8{ "admin", "dev", "admin", "dev", "design", "dev", "design", "admin", "dev", "design" };
pub var _oa1_role_lens = [_]usize{ 5, 3, 5, 3, 6, 3, 6, 5, 3, 6 };
pub var _oa1_status = [_]i64{ 1, 1, 0, 1, 1, 0, 1, 1, 1, 0 };
pub var _oa1_len: usize = 10;
pub var _oa1_dirty: bool = false;


pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

