import type { Theme } from '../types';
import { defaultTypography, defaultSpacing, defaultRadii } from '../defaults';

const draculaPalette: Record<string, string> = {
  background: '#282a36',
  currentLine: '#44475a',
  foreground: '#f8f8f2',
  comment: '#6272a4',
  cyan: '#8be9fd',
  green: '#50fa7b',
  orange: '#ffb86c',
  pink: '#ff79c6',
  purple: '#bd93f9',
  red: '#ff5555',
  yellow: '#f1fa8c',
};

export const draculaThemes: Record<string, Theme> = {
  dracula: {
    name: 'dracula',
    displayName: 'Dracula',
    colors: {
      bg: '#282a36',
      bgAlt: '#21222c',
      bgElevated: '#44475a',
      text: '#f8f8f2',
      textSecondary: '#bfbfbf',
      textDim: '#6272a4',
      primary: '#bd93f9',
      primaryHover: '#caa4fa',
      primaryPressed: '#d4b5fb',
      surface: '#44475a',
      surfaceHover: '#4d505e',
      border: '#44475a',
      borderFocus: '#bd93f9',
      accent: '#ff79c6',
      error: '#ff5555',
      warning: '#ffb86c',
      success: '#50fa7b',
      info: '#8be9fd',
      palette: { ...draculaPalette },
    },
    typography: defaultTypography,
    spacing: defaultSpacing,
    radii: defaultRadii,
  },
  'dracula-soft': {
    name: 'dracula-soft',
    displayName: 'Dracula Soft',
    colors: {
      bg: '#2d2f3f',
      bgAlt: '#252737',
      bgElevated: '#44475a',
      text: '#f2f2e8',
      textSecondary: '#b8b8b0',
      textDim: '#6272a4',
      primary: '#bd93f9',
      primaryHover: '#caa4fa',
      primaryPressed: '#d4b5fb',
      surface: '#44475a',
      surfaceHover: '#4d505e',
      border: '#44475a',
      borderFocus: '#bd93f9',
      accent: '#ff79c6',
      error: '#ff5555',
      warning: '#ffb86c',
      success: '#50fa7b',
      info: '#8be9fd',
      palette: { ...draculaPalette },
    },
    typography: defaultTypography,
    spacing: defaultSpacing,
    radii: defaultRadii,
  },
};
