import type { Theme } from '../types';
import { defaultTypography, defaultSpacing, defaultRadii } from '../defaults';

const nordPalette: Record<string, string> = {
  nord0: '#2e3440',
  nord1: '#3b4252',
  nord2: '#434c5e',
  nord3: '#4c566a',
  nord4: '#d8dee9',
  nord5: '#e5e9f0',
  nord6: '#eceff4',
  nord7: '#8fbcbb',
  nord8: '#88c0d0',
  nord9: '#81a1c1',
  nord10: '#5e81ac',
  nord11: '#bf616a',
  nord12: '#d08770',
  nord13: '#ebcb8b',
  nord14: '#a3be8c',
  nord15: '#b48ead',
};

export const nordThemes: Record<string, Theme> = {
  nord: {
    name: 'nord',
    displayName: 'Nord',
    colors: {
      bg: '#2e3440',
      bgAlt: '#3b4252',
      bgElevated: '#434c5e',
      text: '#eceff4',
      textSecondary: '#d8dee9',
      textDim: '#4c566a',
      primary: '#88c0d0',
      primaryHover: '#8fbcbb',
      primaryPressed: '#81a1c1',
      surface: '#3b4252',
      surfaceHover: '#434c5e',
      border: '#434c5e',
      borderFocus: '#88c0d0',
      accent: '#b48ead',
      error: '#bf616a',
      warning: '#d08770',
      success: '#a3be8c',
      info: '#5e81ac',
      palette: { ...nordPalette },
    },
    typography: defaultTypography,
    spacing: defaultSpacing,
    radii: defaultRadii,
  },
  'nord-light': {
    name: 'nord-light',
    displayName: 'Nord Light',
    colors: {
      bg: '#eceff4',
      bgAlt: '#e5e9f0',
      bgElevated: '#d8dee9',
      text: '#2e3440',
      textSecondary: '#3b4252',
      textDim: '#4c566a',
      primary: '#5e81ac',
      primaryHover: '#81a1c1',
      primaryPressed: '#88c0d0',
      surface: '#d8dee9',
      surfaceHover: '#e5e9f0',
      border: '#d8dee9',
      borderFocus: '#5e81ac',
      accent: '#b48ead',
      error: '#bf616a',
      warning: '#d08770',
      success: '#a3be8c',
      info: '#5e81ac',
      palette: { ...nordPalette },
    },
    typography: defaultTypography,
    spacing: defaultSpacing,
    radii: defaultRadii,
  },
};
