import type { Theme } from '../types';
import { defaultTypography, defaultSpacing, defaultRadii } from '../defaults';

const tokyoNightPalette: Record<string, string> = {
  bg: '#1a1b26',
  bg_dark: '#16161e',
  bg_highlight: '#292e42',
  terminal_black: '#414868',
  fg: '#c0caf5',
  fg_dark: '#a9b1d6',
  fg_gutter: '#3b4261',
  dark3: '#545c7e',
  comment: '#565f89',
  dark5: '#737aa2',
  blue0: '#3d59a1',
  blue: '#7aa2f7',
  cyan: '#7dcfff',
  blue1: '#2ac3de',
  blue2: '#0db9d7',
  blue5: '#89ddff',
  blue6: '#b4f9f8',
  blue7: '#394b70',
  magenta: '#bb9af7',
  magenta2: '#ff007c',
  purple: '#9d7cd8',
  orange: '#ff9e64',
  yellow: '#e0af68',
  green: '#9ece6a',
  green1: '#73daca',
  green2: '#41a6b5',
  teal: '#1abc9c',
  red: '#f7768e',
  red1: '#db4b4b',
};

export const tokyoNightThemes: Record<string, Theme> = {
  'tokyo-night': {
    name: 'tokyo-night',
    displayName: 'Tokyo Night',
    colors: {
      bg: '#1a1b26',
      bgAlt: '#16161e',
      bgElevated: '#24283b',
      text: '#c0caf5',
      textSecondary: '#a9b1d6',
      textDim: '#565f89',
      primary: '#7aa2f7',
      primaryHover: '#7dcfff',
      primaryPressed: '#2ac3de',
      surface: '#24283b',
      surfaceHover: '#292e42',
      border: '#292e42',
      borderFocus: '#7aa2f7',
      accent: '#bb9af7',
      error: '#f7768e',
      warning: '#e0af68',
      success: '#9ece6a',
      info: '#7dcfff',
      palette: { ...tokyoNightPalette },
    },
    typography: defaultTypography,
    spacing: defaultSpacing,
    radii: defaultRadii,
  },
  'tokyo-night-storm': {
    name: 'tokyo-night-storm',
    displayName: 'Tokyo Night Storm',
    colors: {
      bg: '#24283b',
      bgAlt: '#1f2335',
      bgElevated: '#292e42',
      text: '#c0caf5',
      textSecondary: '#a9b1d6',
      textDim: '#565f89',
      primary: '#7aa2f7',
      primaryHover: '#7dcfff',
      primaryPressed: '#2ac3de',
      surface: '#292e42',
      surfaceHover: '#292e42',
      border: '#292e42',
      borderFocus: '#7aa2f7',
      accent: '#bb9af7',
      error: '#f7768e',
      warning: '#e0af68',
      success: '#9ece6a',
      info: '#7dcfff',
      palette: { ...tokyoNightPalette },
    },
    typography: defaultTypography,
    spacing: defaultSpacing,
    radii: defaultRadii,
  },
};
