//! Generated by tsz compiler — d72_typeof_operator [maps.zig]
//! Source: d72_typeof_operator.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const nodes = @import("nodes.zig");
const st = @import("state.zig");

// [origin:d72_typeof_operator:maps]
// ── Map pools ───────────────────────────────────────────────────
pub var _pool_arena: std.heap.ArenaAllocator = std.heap.ArenaAllocator.init(std.heap.page_allocator);
pub const MAX_MAP_0: usize = 4096;
pub var _map_pool_0: []Node = std.mem.zeroes([]Node);
pub var _map_count_0: usize = 0;
pub var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_0: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_1: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_2: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_2: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_lua_bufs_0_0: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_0: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_0() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_0[_i][0..47], "__mapPress_0_0({d})", .{_i}) catch continue;
        _map_lua_bufs_0_0[_i][n.len] = 0;
        _map_lua_ptrs_0_0[_i] = @ptrCast(_map_lua_bufs_0_0[_i][0..n.len :0]);
    }
}
// [origin:d72_typeof_operator:map:_rebuildMap0]
pub fn _rebuildMap0() void {
    _map_count_0 = @min(st._oa0_len, MAX_MAP_0);
    _map_pool_0 = _pool_arena.allocator().alloc(Node, _map_count_0) catch unreachable;
    for (0.._map_count_0) |_i| {
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ st._oa0_name[_i][0..st._oa0_name_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{d}", .{ st._oa0_val[_i] }) catch "";
        _map_texts_0_2[_i] = std.fmt.bufPrint(&_map_text_bufs_0_2[_i], "{s}", .{ st._oa0_kind[_i][0..st._oa0_kind_lens[_i]] }) catch "";
        const _pi__arr_3_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_3_0, &[_]Node{ .{ .text = _map_texts_0_1[_i], .font_size = 10, .text_color = Color.rgb(110, 231, 183) }, .{ .text = _map_texts_0_2[_i], .font_size = 9, .text_color = Color.rgb(124, 58, 237) } });
        const _inner_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_inner_0, &[_]Node{ .{ .text = _map_texts_0_0[_i], .font_size = 11, .text_color = Color.rgb(226, 232, 240) }, .{ .style = .{ .flex_direction = .row, .gap = 6 }, .children = _pi__arr_3_0 } });
        _map_pool_0[_i] = .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .padding = 8, .background_color = Color.rgb(30, 41, 59), .border_radius = 4 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_0[_i] }, .children = _inner_0 };
    }
    nodes._arr_5[0].children = _map_pool_0[0.._map_count_0];
}


