//! Generated by tsz compiler — 64_tw_sizing [nodes.zig]
//! Source: 64_tw_sizing.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:64_tw_sizing:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:64_tw_sizing.tsz:8 — <Box>
pub var _arr_0 = [_]Node{ .{ .style = .{ .width = 32, .height = 20, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .width = 64, .height = 20, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .width = 96, .height = 20, .background_color = Color.rgb(255, 152, 0) } }, .{ .style = .{ .width = 128, .height = 20, .background_color = Color.rgb(244, 67, 54) } }, .{ .style = .{ .width = 192, .height = 20, .background_color = Color.rgb(156, 39, 176) } } };
// tsz:64_tw_sizing.tsz:17 — <Box>
pub var _arr_1 = [_]Node{ .{ .style = .{ .width = 0.5, .height = 20, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .width = 0.33, .height = 20, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .width = 0.67, .height = 20, .background_color = Color.rgb(255, 152, 0) } } };
// tsz:64_tw_sizing.tsz:25 — <Box>
pub var _arr_2 = [_]Node{ .{ .text = "w-full", .text_color = Color.rgb(255, 255, 255), .font_size = 10 } };
// tsz:64_tw_sizing.tsz:24 — <Box>
pub var _arr_3 = [_]Node{ .{ .style = .{ .width = -1, .height = 30, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_2 } };
// tsz:64_tw_sizing.tsz:32 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "min-w-20 max-w-30", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:64_tw_sizing.tsz:35 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "flex-1", .text_color = Color.rgb(255, 255, 255), .font_size = 10 } };
// tsz:64_tw_sizing.tsz:31 — <Box>
pub var _arr_6 = [_]Node{ .{ .style = .{ .flex_grow = 1, .min_width = 80, .max_width = 120, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_4 }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_5 } };
// tsz:64_tw_sizing.tsz:42 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "square", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:64_tw_sizing.tsz:45 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "video", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:64_tw_sizing.tsz:41 — <Box>
pub var _arr_9 = [_]Node{ .{ .style = .{ .width = 60, .aspect_ratio = 1, .background_color = Color.rgb(76, 175, 80) }, .children = &_arr_7 }, .{ .style = .{ .width = 120, .aspect_ratio = 1.778, .background_color = Color.rgb(33, 150, 243) }, .children = &_arr_8 } };
// tsz:64_tw_sizing.tsz:3 — <Box>
pub var _arr_10 = [_]Node{ .{ .text = "Tailwind verification: sizing", .font_size = 18 }, .{ .text = "VERIFY: w-8 through w-48 increasing widths, fractional widths, min/max constraints", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "Fixed widths: w-8(32) w-16(64) w-24(96) w-32(128) w-48(192)", .font_size = 11 }, .{ .style = .{ .flex_direction = .column, .gap = 4, .width = 300, .background_color = Color.rgb(51, 51, 51), .padding = 4 }, .children = &_arr_0 }, .{ .text = "Fractional: w-1/2(50%) w-1/3(33%) w-2/3(67%)", .font_size = 11 }, .{ .style = .{ .flex_direction = .column, .gap = 4, .width = 300, .background_color = Color.rgb(51, 51, 51), .padding = 4 }, .children = &_arr_1 }, .{ .text = "w-full(100%) inside container", .font_size = 11 }, .{ .style = .{ .width = 200, .background_color = Color.rgb(51, 51, 51), .padding = 4 }, .children = &_arr_3 }, .{ .text = "min-w, max-w constraints", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 40, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_6 }, .{ .text = "Aspect ratio: aspect-square(1) aspect-video(16/9)", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .gap = 8, .align_items = .start }, .children = &_arr_9 } };
// [origin:64_tw_sizing:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 6, .overflow = .hidden }, .children = &_arr_10 };

