//! Generated by tsz compiler — d64_multi_import [nodes.zig]
//! Source: d64_multi_import.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d64_multi_import:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d64_multi_import.tsz:46 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "Users (import A)", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .gap = 4 } } };
// tsz:d64_multi_import.tsz:54 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "Permissions (import B)", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .style = .{ .gap = 4 } } };
// tsz:d64_multi_import.tsz:45 — <Box>
pub var _arr_4 = [_]Node{ .{ .style = .{ .flex_grow = 1, .gap = 4, .overflow = .auto }, .children = &_arr_1 }, .{ .style = .{ .flex_grow = 1, .gap = 4, .overflow = .auto }, .children = &_arr_3 } };
// tsz:d64_multi_import.tsz:42 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "Multi-Import", .font_size = 16, .text_color = Color.rgb(226, 232, 240) }, .{ .style = .{ .flex_direction = .row, .gap = 12 }, .children = &_arr_4 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(110, 231, 183) } };
// [origin:d64_multi_import:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(15, 23, 42), .padding = 20, .width = -1, .height = -1, .gap = 12, .overflow = .hidden }, .children = &_arr_5 };

