//! Generated by tsz compiler — d01_nested_maps [logic.zig]
//! Source: d01_nested_maps.tsz


// [origin:d01_nested_maps:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\// Ambient namespaces
    \\var time = {
    \\  get hour() { return new Date().getHours(); },
    \\  get minute() { return String(new Date().getMinutes()).padStart(2, "0"); },
    \\  get second() { return String(new Date().getSeconds()).padStart(2, "0"); },
    \\  get year() { return new Date().getFullYear(); },
    \\  get month() { return new Date().getMonth() + 1; },
    \\  get day() { return new Date().getDate(); },
    \\  get fps() { return typeof getFps === "function" ? getFps() : 0; },
    \\  get delta() { return 16; },
    \\  get elapsed() { return Date.now(); },
    \\  get timestamp() { return Date.now(); },
    \\};
    \\var sys = {
    \\  get user() { return typeof __os_user !== "undefined" ? __os_user : "user"; },
    \\  get uptime() { return Math.floor(Date.now() / 1000); },
    \\  get os() { return "linux"; },
    \\  get host() { return "localhost"; },
    \\  get kernel() { return "unknown"; },
    \\};
    \\var device = {
    \\  get width() { return 1280; },
    \\  get height() { return 800; },
    \\  get battery() { return 100; },
    \\  get online() { return true; },
    \\  get dpi() { return 96; },
    \\};
    \\var input = {
    \\  mouse: {
    \\    get x() { return typeof getMouseX === "function" ? getMouseX() : 0; },
    \\    get y() { return typeof getMouseY === "function" ? getMouseY() : 0; },
    \\  },
    \\  keys: { shift: false, ctrl: false, alt: false },
    \\  touch: { count: 0 },
    \\};
    \\
    \\var groups = [];
    \\// OA initial data
    \\setGroups([ { name : "" , items : [ { label : "" , value : 0 } ] } ]);
    \\var selected = 0;
    \\function setSelected(v) { selected = v; __setState(0, v); }
    \\var g = [
    \\  { name: 'Alpha', items: [{ label: 'a1', value: 10 }, { label: 'a2', value: 20 }, { label: 'a3', value: 30 }] },
    \\  { name: 'Beta', items: [{ label: 'b1', value: 40 }, { label: 'b2', value: 50 }] },
    \\  { name: 'Gamma', items: [{ label: 'g1', value: 60 }] }
    \\];
    \\setGroups(g);
    \\
    \\
    \\
    \\function setGroups(v) { groups = v; __setObjArr0(v); }
    \\if (groups && groups.length > 0) setGroups(groups);
    \\
;

// [origin:d01_nested_maps:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\-- State variables (mirroring Zig state slots)
    \\selected = 0
    \\
    \\function setSelected(v) selected = v; __setState(0, v) end
    \\
    \\groups = {}
    \\function setGroups(v) groups = v end
    \\function __mapPress_1_0(gi, ii)
    \\  setSelected(gi * 100 + ii)
    \\end
    \\
    \\
;

