//! Generated by tsz compiler — d01_nested_maps [nodes.zig]
//! Source: d01_nested_maps.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d01_nested_maps:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d01_nested_maps.tsz:12 — <ScrollView>
pub var _arr_3 = [_]Node{ .{}, .{ .text = "", .font_size = 10, .text_color = Color.rgb(83, 52, 131) } };
// [origin:d01_nested_maps:root]
pub var _root = Node{ .style = .{ .overflow = .scroll, .background_color = Color.rgb(26, 26, 46), .padding = 16, .width = -1, .height = -1 }, .children = &_arr_3 };

