//! Generated by tsz compiler — d126_key_event_router [logic.zig]
//! Source: d126_key_event_router.tsz


// [origin:d126_key_event_router:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\// Ambient namespaces
    \\var time = {
    \\  get hour() { return new Date().getHours(); },
    \\  get minute() { return String(new Date().getMinutes()).padStart(2, "0"); },
    \\  get second() { return String(new Date().getSeconds()).padStart(2, "0"); },
    \\  get year() { return new Date().getFullYear(); },
    \\  get month() { return new Date().getMonth() + 1; },
    \\  get day() { return new Date().getDate(); },
    \\  get fps() { return typeof getFps === "function" ? getFps() : 0; },
    \\  get delta() { return 16; },
    \\  get elapsed() { return Date.now(); },
    \\  get timestamp() { return Date.now(); },
    \\};
    \\var sys = {
    \\  get user() { return typeof __os_user !== "undefined" ? __os_user : "user"; },
    \\  get uptime() { return Math.floor(Date.now() / 1000); },
    \\  get os() { return "linux"; },
    \\  get host() { return "localhost"; },
    \\  get kernel() { return "unknown"; },
    \\};
    \\var device = {
    \\  get width() { return 1280; },
    \\  get height() { return 800; },
    \\  get battery() { return 100; },
    \\  get online() { return true; },
    \\  get dpi() { return 96; },
    \\};
    \\var input = {
    \\  mouse: {
    \\    get x() { return typeof getMouseX === "function" ? getMouseX() : 0; },
    \\    get y() { return typeof getMouseY === "function" ? getMouseY() : 0; },
    \\  },
    \\  keys: { shift: false, ctrl: false, alt: false },
    \\  touch: { count: 0 },
    \\};
    \\
    \\var keys = [];
    \\// OA initial data
    \\setKeys([ { name : "" , shift : 0 , ctrl : 0 , alt : 0 , meta : 0 , isNav : 0 , isWheel : 0 } ]);
    \\var activeKey = 0;
    \\function setActiveKey(v) { activeKey = v; __setState(0, v); }
    \\var clearSelection = 0;
    \\function setClearSelection(v) { clearSelection = v; __setState(1, v); }
    \\var focusMove = '';
    \\function setFocusMove(v) { focusMove = v; __setStateString(2, v); }
    \\var wheelMult = 0;
    \\function setWheelMult(v) { wheelMult = v; __setState(3, v); }
    \\var wheelDir = 0;
    \\function setWheelDir(v) { wheelDir = v; __setState(4, v); }
    \\var wheelTime = 0;
    \\function setWheelTime(v) { wheelTime = v; __setState(5, v); }
    \\var wheelMode = 0;
    \\function setWheelMode(v) { wheelMode = v; __setState(6, v); }
    \\var actionLog = '';
    \\function setActionLog(v) { actionLog = v; __setStateString(7, v); }
    \\var logCount = 0;
    \\function setLogCount(v) { logCount = v; __setState(8, v); }
    \\var keyDefs = [
    \\  { name: 'A',           shift: 0, ctrl: 0, alt: 0, meta: 0, isNav: 0, isWheel: 0 },
    \\  { name: 'Left',        shift: 0, ctrl: 0, alt: 0, meta: 0, isNav: 1, isWheel: 0 },
    \\  { name: 'Shift+Left',  shift: 1, ctrl: 0, alt: 0, meta: 0, isNav: 1, isWheel: 0 },
    \\  { name: 'Shift+Right', shift: 1, ctrl: 0, alt: 0, meta: 0, isNav: 1, isWheel: 0 },
    \\  { name: 'Shift+Up',    shift: 1, ctrl: 0, alt: 0, meta: 0, isNav: 1, isWheel: 0 },
    \\  { name: 'Shift+Down',  shift: 1, ctrl: 0, alt: 0, meta: 0, isNav: 1, isWheel: 0 },
    \\  { name: 'Shift+Home',  shift: 1, ctrl: 0, alt: 0, meta: 0, isNav: 1, isWheel: 0 },
    \\  { name: 'Shift+End',   shift: 1, ctrl: 0, alt: 0, meta: 0, isNav: 1, isWheel: 0 },
    \\  { name: 'Meta+Left',   shift: 0, ctrl: 0, alt: 0, meta: 1, isNav: 1, isWheel: 0 },
    \\  { name: 'Ctrl+C',      shift: 0, ctrl: 1, alt: 0, meta: 0, isNav: 0, isWheel: 0 },
    \\  { name: 'Alt+Tab',     shift: 0, ctrl: 0, alt: 1, meta: 0, isNav: 0, isWheel: 0 },
    \\  { name: 'WheelUp',     shift: 0, ctrl: 0, alt: 0, meta: 0, isNav: 0, isWheel: 1 },
    \\  { name: 'WheelDown',   shift: 0, ctrl: 0, alt: 0, meta: 0, isNav: 0, isWheel: 1 },
    \\  { name: 'Shift+Meta+Down', shift: 1, ctrl: 0, alt: 0, meta: 1, isNav: 1, isWheel: 0 },
    \\  { name: 'Enter',       shift: 0, ctrl: 0, alt: 0, meta: 0, isNav: 0, isWheel: 0 },
    \\  { name: 'Escape',      shift: 0, ctrl: 0, alt: 0, meta: 0, isNav: 0, isWheel: 0 }
    \\];
    \\setKeys(keyDefs);
    \\
    \\// Wheel acceleration state
    \\var wMult = 1;
    \\var wDir = 0;
    \\var wTime = 0;
    \\var wMode = 0;
    \\var halflife = 150;
    \\var step = 5;
    \\
    \\function shouldClear(k) {
    \\  if (k.isWheel === 1) return 0;
    \\  if (k.isNav === 1 && (k.shift === 1 || k.meta === 1)) return 0;
    \\  return 1;
    \\}
    \\
    \\function getFocusMove(k) {
    \\  if (k.shift === 0 || k.meta === 1) return 'none';
    \\  if (k.name === 'Shift+Left') return 'left';
    \\  if (k.name === 'Shift+Right') return 'right';
    \\  if (k.name === 'Shift+Up') return 'up';
    \\  if (k.name === 'Shift+Down') return 'down';
    \\  if (k.name === 'Shift+Home') return 'lineStart';
    \\  if (k.name === 'Shift+End') return 'lineEnd';
    \\  return 'none';
    \\}
    \\
    \\function simulateWheel(dir) {
    \\  var now = wTime + 50;
    \\  var gap = now - wTime;
    \\  wTime = now;
    \\  setWheelTime(now);
    \\
    \\  if (dir !== wDir && wDir !== 0) {
    \\    wMult = 1;
    \\    wDir = dir;
    \\    setWheelMult(1);
    \\    setWheelDir(dir);
    \\    return;
    \\  }
    \\  wDir = dir;
    \\  setWheelDir(dir);
    \\
    \\  var m = Math.pow(0.5, gap / halflife);
    \\  var cap = 6;
    \\  var next = 1 + (wMult - 1) * m + step * m;
    \\  if (next > cap) next = cap;
    \\  wMult = next;
    \\  var rows = Math.floor(wMult);
    \\  setWheelMult(rows);
    \\}
    \\
    \\function routeKey(idx) {
    \\  var k = keyDefs[idx];
    \\  setActiveKey(idx);
    \\
    \\  var clears = shouldClear(k);
    \\  setClearSelection(clears);
    \\
    \\  var fm = getFocusMove(k);
    \\  setFocusMove(fm);
    \\
    \\  if (k.isWheel === 1) {
    \\    var d = k.name === 'WheelUp' ? 1 : -1;
    \\    simulateWheel(d);
    \\  }
    \\
    \\  var desc = k.name + ' -> ';
    \\  if (k.isWheel === 1) {
    \\    desc = desc + 'scroll:' + Math.floor(wMult) + 'rows';
    \\  } else if (fm !== 'none') {
    \\    desc = desc + 'select:' + fm;
    \\  } else if (clears === 1) {
    \\    desc = desc + 'clearSelection';
    \\  } else {
    \\    desc = desc + 'passthrough';
    \\  }
    \\  setActionLog(desc);
    \\  setLogCount(logCount + 1);
    \\}
    \\function setKeys(v) { keys = v; __setObjArr0(v); }
    \\if (keys && keys.length > 0) setKeys(keys);
    \\function __mapPress_0_0(idx) {
    \\  var k = keys[idx];
    \\  var i = idx;
    \\  var idx = idx;
    \\  routeKey(idx);
    \\}
    \\
;

// [origin:d126_key_event_router:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

