//! Generated by tsz compiler — d126_key_event_router [state.zig]
//! Source: d126_key_event_router.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d126_key_event_router:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: activeKey (int)
// slot 1: clearSelection (int)
// slot 2: focusMove (string)
// slot 3: wheelMult (int)
// slot 4: wheelDir (int)
// slot 5: wheelTime (int)
// slot 6: wheelMode (int)
// slot 7: actionLog (string)
// slot 8: logCount (int)
comptime { if (9 != 9) @compileError("state slot count mismatch"); }

// [origin:d126_key_event_router:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [128]u8 = std.mem.zeroes([128]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_2: []const u8 = "";
pub var _dyn_buf_3: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_3: []const u8 = "";
pub var _dyn_buf_4: [159]u8 = std.mem.zeroes([159]u8);
pub var _dyn_text_4: []const u8 = "";
pub const qjs = @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
pub const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// [origin:d126_key_event_router:state]
// ── Object arrays ───────────────────────────────────────────────
pub const _oa_alloc = std.heap.page_allocator;

pub fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

pub fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

pub var _oa0_name: [][]const u8 = &[_][]const u8{};
pub var _oa0_name_lens: []usize = &[_]usize{};
pub var _oa0_name_cap: usize = 0;
pub var _oa0_shift: []i64 = &[_]i64{};
pub var _oa0_shift_cap: usize = 0;
pub var _oa0_ctrl: []i64 = &[_]i64{};
pub var _oa0_ctrl_cap: usize = 0;
pub var _oa0_alt: []i64 = &[_]i64{};
pub var _oa0_alt_cap: usize = 0;
pub var _oa0_meta: []i64 = &[_]i64{};
pub var _oa0_meta_cap: usize = 0;
pub var _oa0_isNav: []i64 = &[_]i64{};
pub var _oa0_isNav_cap: usize = 0;
pub var _oa0_isWheel: []i64 = &[_]i64{};
pub var _oa0_isWheel_cap: usize = 0;
pub var _oa0_len: usize = 0;
pub var _oa0_dirty: bool = false;

pub fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_name_cap) return;
    const new_cap = @max(needed, if (_oa0_name_cap == 0) @as(usize, 64) else _oa0_name_cap * 2);
    if (_oa0_name_cap == 0) {
        _oa0_name = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_name_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens, 0);
    } else {
        const _old_cap = _oa0_name_cap;
        _oa0_name = _oa_alloc.realloc(_oa0_name.ptr[0.._old_cap], new_cap) catch return;
        _oa0_name_lens = _oa_alloc.realloc(_oa0_name_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens[_old_cap..new_cap], 0);
    }
    _oa0_name_cap = new_cap;
    if (_oa0_shift_cap == 0) {
        _oa0_shift = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_shift, 0);
    } else {
        _oa0_shift = _oa_alloc.realloc(_oa0_shift.ptr[0.._oa0_shift_cap], new_cap) catch return;
        @memset(_oa0_shift[_oa0_shift_cap..new_cap], 0);
    }
    _oa0_shift_cap = new_cap;
    if (_oa0_ctrl_cap == 0) {
        _oa0_ctrl = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_ctrl, 0);
    } else {
        _oa0_ctrl = _oa_alloc.realloc(_oa0_ctrl.ptr[0.._oa0_ctrl_cap], new_cap) catch return;
        @memset(_oa0_ctrl[_oa0_ctrl_cap..new_cap], 0);
    }
    _oa0_ctrl_cap = new_cap;
    if (_oa0_alt_cap == 0) {
        _oa0_alt = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_alt, 0);
    } else {
        _oa0_alt = _oa_alloc.realloc(_oa0_alt.ptr[0.._oa0_alt_cap], new_cap) catch return;
        @memset(_oa0_alt[_oa0_alt_cap..new_cap], 0);
    }
    _oa0_alt_cap = new_cap;
    if (_oa0_meta_cap == 0) {
        _oa0_meta = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_meta, 0);
    } else {
        _oa0_meta = _oa_alloc.realloc(_oa0_meta.ptr[0.._oa0_meta_cap], new_cap) catch return;
        @memset(_oa0_meta[_oa0_meta_cap..new_cap], 0);
    }
    _oa0_meta_cap = new_cap;
    if (_oa0_isNav_cap == 0) {
        _oa0_isNav = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_isNav, 0);
    } else {
        _oa0_isNav = _oa_alloc.realloc(_oa0_isNav.ptr[0.._oa0_isNav_cap], new_cap) catch return;
        @memset(_oa0_isNav[_oa0_isNav_cap..new_cap], 0);
    }
    _oa0_isNav_cap = new_cap;
    if (_oa0_isWheel_cap == 0) {
        _oa0_isWheel = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_isWheel, 0);
    } else {
        _oa0_isWheel = _oa_alloc.realloc(_oa0_isWheel.ptr[0.._oa0_isWheel_cap], new_cap) catch return;
        @memset(_oa0_isWheel[_oa0_isWheel_cap..new_cap], 0);
    }
    _oa0_isWheel_cap = new_cap;
}

// [origin:d126_key_event_router:oa:_oa0_unpack]
pub fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "name");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_name[_i], &_oa0_name_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_name[_i] = _oaDupString(sl); _oa0_name_lens[_i] = _oa0_name[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "shift");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_shift[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "ctrl");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_ctrl[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "alt");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_alt[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "meta");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_meta[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "isNav");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_isNav[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "isWheel");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_isWheel[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa0_len) {
        for (count.._oa0_len) |_trim_i| _oaFreeString(&_oa0_name[_trim_i], &_oa0_name_lens[_trim_i]);
    }
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa1_name = [_][]const u8{ "A", "Left", "Shift+Left", "Shift+Right", "Shift+Up", "Shift+Down", "Shift+Home", "Shift+End", "Meta+Left", "Ctrl+C", "Alt+Tab", "WheelUp", "WheelDown", "Shift+Meta+Down", "Enter", "Escape" };
pub var _oa1_name_lens = [_]usize{ 1, 4, 10, 11, 8, 10, 10, 9, 9, 6, 7, 7, 9, 15, 5, 6 };
pub var _oa1_shift = [_]i64{ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0 };
pub var _oa1_ctrl = [_]i64{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 };
pub var _oa1_alt = [_]i64{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 };
pub var _oa1_meta = [_]i64{ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0 };
pub var _oa1_isNav = [_]i64{ 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0 };
pub var _oa1_isWheel = [_]i64{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0 };
pub var _oa1_len: usize = 16;
pub var _oa1_dirty: bool = false;


pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
    _ = state.createSlot(0);
}

