//! Generated by tsz compiler — d52_multi_handler_state [logic.zig]
//! Source: d52_multi_handler_state.tsz


// [origin:d52_multi_handler_state:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\var history = [];
    \\// OA initial data
    \\setHistory([ { action : "" , value : 0 } ]);
    \\var step = 0;
    \\function setStep(v) { step = v; __setState(0, v); }
    \\var name = '';
    \\function setName(v) { name = v; __setStateString(1, v); }
    \\var score = 0;
    \\function setScore(v) { score = v; __setState(2, v); }
    \\var rank = '';
    \\function setRank(v) { rank = v; __setStateString(3, v); }
    \\var histLen = 0;
    \\function setHistLen(v) { histLen = v; __setState(4, v); }
    \\var error = '';
    \\function setError(v) { error = v; __setStateString(5, v); }
    \\var log = [];
    \\
    \\function addScore(amount) {
    \\  if (locked === 1) {
    \\    setError('locked!');
    \\    return;
    \\  }
    \\  var newScore = score + amount;
    \\  if (newScore < 0) newScore = 0;
    \\  if (newScore > 1000) newScore = 1000;
    \\  setScore(newScore);
    \\  setError('');
    \\
    \\  var r = 'Novice';
    \\  if (newScore >= 100) r = 'Bronze';
    \\  if (newScore >= 300) r = 'Silver';
    \\  if (newScore >= 600) r = 'Gold';
    \\  if (newScore >= 900) r = 'Diamond';
    \\  setRank(r);
    \\
    \\  log.push({ action: (amount >= 0 ? '+' : '') + amount, value: newScore });
    \\  setHistory(log);
    \\  setHistLen(log.length);
    \\}
    \\
    \\function resetAll() {
    \\  setScore(0);
    \\  setRank('Novice');
    \\  setError('');
    \\  setStep(0);
    \\  log = [];
    \\  setHistory(log);
    \\  setHistLen(0);
    \\}
    \\
    \\var locked = 0;
    \\function toggleLock() {
    \\  locked = locked === 0 ? 1 : 0;
    \\  if (locked === 1) {
    \\    setError('locked');
    \\  } else {
    \\    setError('');
    \\  }
    \\}
    \\function setHistory(v) { history = v; __setObjArr0(v); }
    \\if (history && history.length > 0) setHistory(history);
    \\
;

// [origin:d52_multi_handler_state:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

