//! Generated by tsz compiler — d92_state_machine_complex [state.zig]
//! Source: d92_state_machine_complex.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d92_state_machine_complex:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: state (int)
// slot 1: prevState (int)
// slot 2: histLen (int)
// slot 3: error (string)
// slot 4: transitions (int)
// slot 5: denied (int)
// slot 6: streak (int)
comptime { if (7 != 7) @compileError("state slot count mismatch"); }

// [origin:d92_state_machine_complex:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [97]u8 = std.mem.zeroes([97]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [128]u8 = std.mem.zeroes([128]u8);
pub var _dyn_text_2: []const u8 = "";
pub var _dyn_buf_3: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_3: []const u8 = "";

pub const qjs = @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
pub const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// [origin:d92_state_machine_complex:state]
// ── Object arrays ───────────────────────────────────────────────
pub const _oa_alloc = std.heap.page_allocator;

pub fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

pub fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

pub var _oa0_from: []i64 = &[_]i64{};
pub var _oa0_from_cap: usize = 0;
pub var _oa0_to: []i64 = &[_]i64{};
pub var _oa0_to_cap: usize = 0;
pub var _oa0_valid: []i64 = &[_]i64{};
pub var _oa0_valid_cap: usize = 0;
pub var _oa0_desc: [][]const u8 = &[_][]const u8{};
pub var _oa0_desc_lens: []usize = &[_]usize{};
pub var _oa0_desc_cap: usize = 0;
pub var _oa0_len: usize = 0;
pub var _oa0_dirty: bool = false;

pub fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_from_cap) return;
    const new_cap = @max(needed, if (_oa0_from_cap == 0) @as(usize, 64) else _oa0_from_cap * 2);
    if (_oa0_from_cap == 0) {
        _oa0_from = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_from, 0);
    } else {
        _oa0_from = _oa_alloc.realloc(_oa0_from.ptr[0.._oa0_from_cap], new_cap) catch return;
        @memset(_oa0_from[_oa0_from_cap..new_cap], 0);
    }
    _oa0_from_cap = new_cap;
    if (_oa0_to_cap == 0) {
        _oa0_to = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_to, 0);
    } else {
        _oa0_to = _oa_alloc.realloc(_oa0_to.ptr[0.._oa0_to_cap], new_cap) catch return;
        @memset(_oa0_to[_oa0_to_cap..new_cap], 0);
    }
    _oa0_to_cap = new_cap;
    if (_oa0_valid_cap == 0) {
        _oa0_valid = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_valid, 0);
    } else {
        _oa0_valid = _oa_alloc.realloc(_oa0_valid.ptr[0.._oa0_valid_cap], new_cap) catch return;
        @memset(_oa0_valid[_oa0_valid_cap..new_cap], 0);
    }
    _oa0_valid_cap = new_cap;
    if (_oa0_desc_cap == 0) {
        _oa0_desc = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_desc_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_desc[_j] = &[_]u8{};
        @memset(_oa0_desc_lens, 0);
    } else {
        const _old_cap = _oa0_desc_cap;
        _oa0_desc = _oa_alloc.realloc(_oa0_desc.ptr[0.._old_cap], new_cap) catch return;
        _oa0_desc_lens = _oa_alloc.realloc(_oa0_desc_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_desc[_j] = &[_]u8{};
        @memset(_oa0_desc_lens[_old_cap..new_cap], 0);
    }
    _oa0_desc_cap = new_cap;
}

// [origin:d92_state_machine_complex:oa:_oa0_unpack]
pub fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "from");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_from[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "to");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_to[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "valid");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_valid[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "desc");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_desc[_i], &_oa0_desc_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_desc[_i] = _oaDupString(sl); _oa0_desc_lens[_i] = _oa0_desc[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa0_len) {
        for (count.._oa0_len) |_trim_i| _oaFreeString(&_oa0_desc[_trim_i], &_oa0_desc_lens[_trim_i]);
    }
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}


pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

