//! Generated by tsz compiler — 35_complex_dashboard [nodes.zig]
//! Source: 35_complex_dashboard.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:35_complex_dashboard:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:35_complex_dashboard.tsz:8 — <Box>
pub var _arr_0 = [_]Node{ .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(44, 44, 44) } }, .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(44, 44, 44) } }, .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(187, 134, 252) } } };
// tsz:35_complex_dashboard.tsz:4 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "Dashboard" }, .{ .text = "VERIFY: Material dark theme dashboard with icon sidebar, stat cards, bar chart, product list", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .style = .{ .flex_grow = 1 } }, .{ .style = .{ .flex_direction = .row, .gap = 8 }, .children = &_arr_0 } };
// tsz:35_complex_dashboard.tsz:16 — <Box>
pub var _arr_2 = [_]Node{ .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(187, 134, 252) } }, .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(44, 44, 44) } }, .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(44, 44, 44) } }, .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(44, 44, 44) } }, .{ .style = .{ .flex_grow = 1 } }, .{ .style = .{ .width = 32, .height = 32, .background_color = Color.rgb(44, 44, 44), .margin_bottom = 12 } } };
// tsz:35_complex_dashboard.tsz:29 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "2,847" }, .{ .text = "+12%" } };
// tsz:35_complex_dashboard.tsz:27 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "ACTIVE USERS" }, .{ .style = .{ .flex_direction = .row, .align_items = .end, .gap = 8 }, .children = &_arr_3 } };
// tsz:35_complex_dashboard.tsz:36 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "$94K" }, .{ .text = "+8%" } };
// tsz:35_complex_dashboard.tsz:34 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "REVENUE" }, .{ .style = .{ .flex_direction = .row, .align_items = .end, .gap = 8 }, .children = &_arr_5 } };
// tsz:35_complex_dashboard.tsz:43 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "3.2%" }, .{ .text = "-2%" } };
// tsz:35_complex_dashboard.tsz:41 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "CONVERSION" }, .{ .style = .{ .flex_direction = .row, .align_items = .end, .gap = 8 }, .children = &_arr_7 } };
// tsz:35_complex_dashboard.tsz:50 — <Box>
pub var _arr_9 = [_]Node{ .{ .text = "1.1%" }, .{ .text = "-0.3%" } };
// tsz:35_complex_dashboard.tsz:48 — <Box>
pub var _arr_10 = [_]Node{ .{ .text = "CHURN" }, .{ .style = .{ .flex_direction = .row, .align_items = .end, .gap = 8 }, .children = &_arr_9 } };
// tsz:35_complex_dashboard.tsz:26 — <Box>
pub var _arr_11 = [_]Node{ .{ .style = .{ .flex_direction = .column, .flex_grow = 1, .height = 100, .background_color = Color.rgb(30, 30, 30), .padding = 16, .justify_content = .space_between, .overflow = .auto }, .children = &_arr_4 }, .{ .style = .{ .flex_direction = .column, .flex_grow = 1, .height = 100, .background_color = Color.rgb(30, 30, 30), .padding = 16, .justify_content = .space_between, .overflow = .auto }, .children = &_arr_6 }, .{ .style = .{ .flex_direction = .column, .flex_grow = 1, .height = 100, .background_color = Color.rgb(30, 30, 30), .padding = 16, .justify_content = .space_between, .overflow = .auto }, .children = &_arr_8 }, .{ .style = .{ .flex_direction = .column, .flex_grow = 1, .height = 100, .background_color = Color.rgb(30, 30, 30), .padding = 16, .justify_content = .space_between, .overflow = .auto }, .children = &_arr_10 } };
// tsz:35_complex_dashboard.tsz:60 — <Box>
pub var _arr_12 = [_]Node{ .{ .style = .{ .flex_grow = 1, .height = 0.4, .background_color = Color.rgb(187, 134, 252) } }, .{ .style = .{ .flex_grow = 1, .height = 0.55, .background_color = Color.rgb(187, 134, 252) } }, .{ .style = .{ .flex_grow = 1, .height = 0.45, .background_color = Color.rgb(187, 134, 252) } }, .{ .style = .{ .flex_grow = 1, .height = 0.7, .background_color = Color.rgb(187, 134, 252) } }, .{ .style = .{ .flex_grow = 1, .height = 0.6, .background_color = Color.rgb(187, 134, 252) } }, .{ .style = .{ .flex_grow = 1, .height = 0.85, .background_color = Color.rgb(187, 134, 252) } }, .{ .style = .{ .flex_grow = 1, .height = 0.75, .background_color = Color.rgb(3, 218, 198) } }, .{ .style = .{ .flex_grow = 1, .height = 0.9, .background_color = Color.rgb(3, 218, 198) } } };
// tsz:35_complex_dashboard.tsz:58 — <Box>
pub var _arr_13 = [_]Node{ .{ .text = "Revenue Over Time" }, .{ .style = .{ .flex_direction = .row, .flex_grow = 1, .align_items = .end, .gap = 4, .padding_bottom = 4, .overflow = .auto }, .children = &_arr_12 } };
// tsz:35_complex_dashboard.tsz:75 — <Box>
pub var _arr_14 = [_]Node{ .{ .style = .{ .width = 8, .height = 8, .background_color = Color.rgb(187, 134, 252) } }, .{ .text = "Product A" }, .{ .style = .{ .flex_grow = 1 } }, .{ .text = "42%" } };
// tsz:35_complex_dashboard.tsz:81 — <Box>
pub var _arr_15 = [_]Node{ .{ .style = .{ .width = 8, .height = 8, .background_color = Color.rgb(3, 218, 198) } }, .{ .text = "Product B" }, .{ .style = .{ .flex_grow = 1 } }, .{ .text = "28%" } };
// tsz:35_complex_dashboard.tsz:87 — <Box>
pub var _arr_16 = [_]Node{ .{ .style = .{ .width = 8, .height = 8, .background_color = Color.rgb(207, 102, 121) } }, .{ .text = "Product C" }, .{ .style = .{ .flex_grow = 1 } }, .{ .text = "18%" } };
// tsz:35_complex_dashboard.tsz:93 — <Box>
pub var _arr_17 = [_]Node{ .{ .style = .{ .width = 8, .height = 8, .background_color = Color.rgb(255, 183, 77) } }, .{ .text = "Other" }, .{ .style = .{ .flex_grow = 1 } }, .{ .text = "12%" } };
// tsz:35_complex_dashboard.tsz:74 — <Box>
pub var _arr_18 = [_]Node{ .{ .style = .{ .flex_direction = .row, .align_items = .center, .gap = 8 }, .children = &_arr_14 }, .{ .style = .{ .flex_direction = .row, .align_items = .center, .gap = 8 }, .children = &_arr_15 }, .{ .style = .{ .flex_direction = .row, .align_items = .center, .gap = 8 }, .children = &_arr_16 }, .{ .style = .{ .flex_direction = .row, .align_items = .center, .gap = 8 }, .children = &_arr_17 } };
// tsz:35_complex_dashboard.tsz:72 — <Box>
pub var _arr_19 = [_]Node{ .{ .text = "Top Products" }, .{ .style = .{ .flex_direction = .column, .gap = 6 }, .children = &_arr_18 }, .{ .style = .{ .flex_grow = 1 } } };
// tsz:35_complex_dashboard.tsz:57 — <Box>
pub var _arr_20 = [_]Node{ .{ .style = .{ .flex_direction = .column, .flex_grow = 3, .background_color = Color.rgb(30, 30, 30), .padding = 16, .gap = 8, .overflow = .auto }, .children = &_arr_13 }, .{ .style = .{ .flex_direction = .column, .flex_grow = 1, .background_color = Color.rgb(30, 30, 30), .padding = 16, .gap = 8, .overflow = .auto }, .children = &_arr_19 } };
// tsz:35_complex_dashboard.tsz:25 — <Box>
pub var _arr_21 = [_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 16 }, .children = &_arr_11 }, .{ .style = .{ .flex_direction = .row, .flex_grow = 1, .gap = 16, .overflow = .auto }, .children = &_arr_20 } };
// tsz:35_complex_dashboard.tsz:15 — <Box>
pub var _arr_22 = [_]Node{ .{ .style = .{ .flex_direction = .column, .width = 56, .background_color = Color.rgb(30, 30, 30), .align_items = .center, .padding_top = 12, .gap = 8 }, .children = &_arr_2 }, .{ .style = .{ .flex_direction = .column, .flex_grow = 1, .padding = 16, .gap = 16, .overflow = .auto }, .children = &_arr_21 } };
// tsz:35_complex_dashboard.tsz:3 — <Box>
pub var _arr_23 = [_]Node{ .{ .style = .{ .flex_direction = .row, .height = 48, .background_color = Color.rgb(30, 30, 30), .align_items = .center, .padding_left = 16, .padding_right = 16, .gap = 16, .overflow = .auto }, .children = &_arr_1 }, .{ .style = .{ .flex_direction = .row, .flex_grow = 1, .overflow = .auto }, .children = &_arr_22 } };
// [origin:35_complex_dashboard:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .background_color = Color.rgb(18, 18, 18), .overflow = .hidden }, .children = &_arr_23 };

