//! Generated by tsz compiler (Zig) — do not edit
//!
//! Source: semantic-test.tsz

const std = @import("std");
const c = @import("c.zig").imports;
const layout = @import("layout.zig");
const text_mod = @import("text.zig");
const Node = layout.Node;
const Style = layout.Style;
const Color = layout.Color;
const LayoutRect = layout.LayoutRect;
const TextEngine = text_mod.TextEngine;
const image_mod = @import("image.zig");
const ImageCache = image_mod.ImageCache;
const events = @import("events.zig");
const mpv_mod = @import("mpv.zig");
const win_mgr = @import("windows.zig");
const watchdog = @import("watchdog.zig");
const bsod = @import("bsod.zig");
const leaktest = @import("leaktest.zig");
const input_mod = @import("input.zig");
const geometry = @import("geometry.zig");
const compositor = @import("compositor.zig");
const telemetry = @import("telemetry.zig");
const inspector = @import("inspector.zig");
const state = @import("state.zig");
const pty_mod = @import("pty.zig");
const vterm_mod = @import("vterm.zig");
const classifier_mod = @import("classifier.zig");
const testharness = @import("testharness.zig");

var g_text_engine: ?*TextEngine = null;
var g_image_cache: ?*ImageCache = null;
var _telem_frame: u32 = 0;

fn measureCallback(t: []const u8, font_size: u16, max_width: f32, letter_spacing: f32, line_height: f32, max_lines: u16, no_wrap: bool) layout.TextMetrics {
    if (g_text_engine) |te| { return te.measureTextWrappedEx(t, font_size, max_width, letter_spacing, line_height, max_lines, no_wrap); }
    return .{};
}

fn measureImageCallback(img_path: []const u8) layout.ImageDims {
    if (g_image_cache) |cache| { if (cache.load(img_path)) |img| { return .{ .width = @floatFromInt(img.width), .height = @floatFromInt(img.height) }; } }
    return .{};
}

// ── Generated node tree ─────────────────────────────────────────
var _arr_0 = [_]Node{ .{ .text = "", .font_size = 12, .text_color = Color.rgb(88, 91, 112) } };
var _arr_1 = [_]Node{ .{} };
var _arr_2 = [_]Node{ .{ .style = .{ .padding = 8, .background_color = Color.rgb(24, 24, 37) }, .children = &_arr_0 }, .{ .style = .{ .flex_grow = 1, .padding = 4, .background_color = Color.rgb(17, 17, 27) }, .handlers = .{ .on_key = _handler_key_0 }, .children = &_arr_1 } };
var root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(30, 30, 46), .flex_direction = .column }, .children = &_arr_2 };

// ── Dynamic text buffers ─────────────────────────────────────────
var _dyn_buf_0: [256]u8 = undefined;
var _dyn_text_0: []const u8 = "";

// ── Map pools ───────────────────────────────────────────────────
const MAX_MAP_0: usize = 256;
var _map_pool_0: [MAX_MAP_0]Node = [_]Node{.{}} ** MAX_MAP_0;
var _map_count_0: usize = 0;
var _map_inner_0: [MAX_MAP_0][2]Node = undefined;
var _map_text_bufs_0: [MAX_MAP_0][256]u8 = undefined;
var _map_texts_0: [MAX_MAP_0][]const u8 = [_][]const u8{""} ** MAX_MAP_0;

// ── Generated event handlers ────────────────────────────────────
fn _handler_key_0(_key: c_int, _mods: u16) void {
    pty_mod.handleKey(_key, _mods);
}


// ── Effect timer variables ──────────────────────────────────────
var _timer_1: u32 = 0;

// ── Generated effect functions ──────────────────────────────────
fn _effect_0() void {
    { pty_mod.spawn("/bin/bash", 24, 80); vterm_mod.initVterm(24, 80); }
}

fn _effect_1() void {
    _ = pty_mod.poll();
    state.setSlot(1, (state.getSlot(1) + 1));

}

fn updateDynamicTexts() void {
    _dyn_text_0 = std.fmt.bufPrint(&_dyn_buf_0, "Semantic Terminal | Frame: {d} | Cursor: {d},{d}", .{ state.getSlot(1), vterm_mod.getCursorRow(), vterm_mod.getCursorCol() }) catch "";
    _arr_0[0].text = _dyn_text_0;
}

fn _onTextInput(text: [*:0]const u8) void {
    input_mod.handleTextInput(text);
    pty_mod.handleTextInput(text);
}

fn _rebuildMap0() void {
    const items = state.getArraySlot(0);
    _map_count_0 = @min(items.len, MAX_MAP_0);
    for (0.._map_count_0) |_i| {
        const _item = items[_i];
        _map_texts_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0[_i], "{s}", .{ vterm_mod.getRowText(@intCast(_item)) }) catch "";
        _map_inner_0[_i] = [2]Node{ .{ .style = .{ .width = 3, .background_color = Color.rgb(88, 91, 112) } }, .{ .text = _map_texts_0[_i], .font_size = 13, .text_color = Color.rgb(205, 214, 244) } };
        _map_pool_0[_i] = .{ .style = .{ .flex_direction = .row, .height = 18 }, .children = &_map_inner_0[_i] };
    }
    _arr_1[0].children = _map_pool_0[0.._map_count_0];
}

var hovered_node: ?*Node = null;

fn brighten(color: Color) Color {
    return .{ .r = @min(255, @as(u16, color.r) + 30), .g = @min(255, @as(u16, color.g) + 30), .b = @min(255, @as(u16, color.b) + 30), .a = color.a };
}

var sel_node: ?*Node = null;
var sel_end_node: ?*Node = null;
var sel_start: usize = 0;
var sel_end: usize = 0;
var sel_anchor: usize = 0;
var sel_dragging: bool = false;
var sel_last_click: u32 = 0;
var sel_click_count: u32 = 0;
var sel_all: bool = false;
var sel_paint_state: u8 = 0;

fn collectAllText(node: *Node, buf: []u8, pos: usize) usize {
    var p = pos;
    if (node.text) |txt| {
        if (p > 0 and p < buf.len) { buf[p] = '\n'; p += 1; }
        const n = @min(txt.len, buf.len - p);
        if (n > 0) { @memcpy(buf[p..p+n], txt[0..n]); p += n; }
    }
    for (node.children) |*child| { p = collectAllText(child, buf, p); }
    return p;
}

fn collectSelectedText(node: *Node, buf: []u8, pos: usize, st: *u8) usize {
    var p = pos;
    if (node.text) |txt| {
        const is_start = (sel_node == node);
        const is_end = (sel_end_node == node);
        if (is_start and is_end) {
            const s0 = @min(sel_start, sel_end);
            const s1 = @max(sel_start, sel_end);
            if (s1 > s0) {
                if (p > 0 and p < buf.len) { buf[p] = '\n'; p += 1; }
                const n = @min(s1 - s0, buf.len - p);
                if (n > 0) { @memcpy(buf[p..p+n], txt[s0..s0+n]); p += n; }
            }
            st.* = 2;
        } else if (st.* == 0 and (is_start or is_end)) {
            const byte = if (is_start) sel_start else sel_end;
            if (byte < txt.len) {
                if (p > 0 and p < buf.len) { buf[p] = '\n'; p += 1; }
                const n = @min(txt.len - byte, buf.len - p);
                if (n > 0) { @memcpy(buf[p..p+n], txt[byte..byte+n]); p += n; }
            }
            st.* = 1;
        } else if (st.* == 1) {
            if (is_start or is_end) {
                const byte = if (is_start) sel_start else sel_end;
                if (byte > 0) {
                    if (p > 0 and p < buf.len) { buf[p] = '\n'; p += 1; }
                    const n = @min(byte, buf.len - p);
                    if (n > 0) { @memcpy(buf[p..p+n], txt[0..n]); p += n; }
                }
                st.* = 2;
            } else {
                if (p > 0 and p < buf.len) { buf[p] = '\n'; p += 1; }
                const n = @min(txt.len, buf.len - p);
                if (n > 0) { @memcpy(buf[p..p+n], txt[0..n]); p += n; }
            }
        }
    }
    for (node.children) |*child| { p = collectSelectedText(child, buf, p, st); }
    return p;
}

pub fn main() !void {
    if (c.SDL_Init(c.SDL_INIT_VIDEO) != 0) return error.SDLInitFailed;
    defer c.SDL_Quit();

    const window = c.SDL_CreateWindow("tsz app", c.SDL_WINDOWPOS_CENTERED, c.SDL_WINDOWPOS_CENTERED, 1280, 800, c.SDL_WINDOW_SHOWN | c.SDL_WINDOW_RESIZABLE) orelse return error.WindowCreateFailed;
    defer c.SDL_DestroyWindow(window);
    c.SDL_SetWindowMinimumSize(window, 320, 240);

    const renderer = c.SDL_CreateRenderer(window, -1, c.SDL_RENDERER_ACCELERATED | c.SDL_RENDERER_PRESENTVSYNC) orelse return error.RendererFailed;
    defer c.SDL_DestroyRenderer(renderer);
    _ = c.SDL_SetRenderDrawBlendMode(renderer, c.SDL_BLENDMODE_BLEND);

    var text_engine = TextEngine.init(renderer, "fonts/base/DejaVuSans-Regular.ttf") catch
        TextEngine.init(renderer, "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf") catch
        TextEngine.init(renderer, "/System/Library/Fonts/Supplemental/Arial.ttf") catch
        TextEngine.init(renderer, "/System/Library/Fonts/SFNS.ttf") catch
        TextEngine.init(renderer, "C:/Windows/Fonts/segoeui.ttf") catch
        TextEngine.init(renderer, "C:/Windows/Fonts/arial.ttf") catch return error.FontNotFound;
    defer text_engine.deinit();

    var image_cache = ImageCache.init(renderer);
    defer image_cache.deinit();
    defer mpv_mod.deinit();

    g_text_engine = &text_engine;
    g_image_cache = &image_cache;
    layout.setMeasureFn(measureCallback);
    layout.setMeasureImageFn(measureImageCallback);
    var win_w: f32 = 1280;
    var win_h: f32 = 800;

    geometry.init("semantic-test");
    if (geometry.load()) |geom| {
        c.SDL_SetWindowPosition(window, geom.x, geom.y);
        c.SDL_SetWindowSize(window, @intCast(geom.width), @intCast(geom.height));
        win_w = @floatFromInt(geom.width);
        win_h = @floatFromInt(geom.height);
        geometry.blockSaves();
    }

    _ = state.createArraySlot(&[_]i64{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 });
    _ = state.createSlot(0);
    _ = state.loadState();
    state.installSignalHandler();
    updateDynamicTexts();
    _rebuildMap0();
    _effect_0();
    _timer_1 = c.SDL_GetTicks();
    compositor.init(renderer, &text_engine, &image_cache);
    defer compositor.deinit();
    defer win_mgr.deinitAll();
    watchdog.init(512);
    defer pty_mod.deinit();
    if (testharness.envEnabled()) testharness.enable();

    const main_window_id = c.SDL_GetWindowID(window);
    var running = true;

    while (running) {
        var event: c.SDL_Event = undefined;
        while (c.SDL_PollEvent(&event) != 0) {
            const evt_window_id: u32 = switch (event.type) {
                c.SDL_WINDOWEVENT => event.window.windowID,
                c.SDL_MOUSEMOTION => event.motion.windowID,
                c.SDL_MOUSEBUTTONDOWN, c.SDL_MOUSEBUTTONUP => event.button.windowID,
                c.SDL_MOUSEWHEEL => event.wheel.windowID,
                c.SDL_KEYDOWN, c.SDL_KEYUP => event.key.windowID,
                else => main_window_id,
            };
            if (evt_window_id != main_window_id) {
                if (win_mgr.findByWindowId(evt_window_id)) |win_idx| {
                    switch (event.type) {
                        c.SDL_WINDOWEVENT => {
                            if (event.window.event == c.SDL_WINDOWEVENT_CLOSE) { win_mgr.handleClose(win_idx); }
                            else if (event.window.event == c.SDL_WINDOWEVENT_SIZE_CHANGED) { win_mgr.handleResize(win_idx, event.window.data1, event.window.data2); }
                        },
                        c.SDL_MOUSEMOTION => { win_mgr.handleMouseMotion(win_idx, @floatFromInt(event.motion.x), @floatFromInt(event.motion.y)); },
                        c.SDL_MOUSEBUTTONDOWN => { win_mgr.handleClick(win_idx, @floatFromInt(event.button.x), @floatFromInt(event.button.y)); },
                        c.SDL_MOUSEWHEEL => {
                            var mx_i: c_int = undefined; var my_i: c_int = undefined;
                            _ = c.SDL_GetMouseState(&mx_i, &my_i);
                            win_mgr.handleWheel(win_idx, @floatFromInt(mx_i), @floatFromInt(my_i), @floatFromInt(event.wheel.y));
                        },
                        else => {},
                    }
                    continue;
                }
            }
            switch (event.type) {
                c.SDL_QUIT => running = false,
                c.SDL_WINDOWEVENT => {
                    if (event.window.event == c.SDL_WINDOWEVENT_SIZE_CHANGED) {
                        win_w = @floatFromInt(event.window.data1);
                        win_h = @floatFromInt(event.window.data2);
                        geometry.save(window);
                    }
                    if (event.window.event == c.SDL_WINDOWEVENT_MOVED) {
                        geometry.save(window);
                    }
                },
                c.SDL_TEXTINPUT => {
                    _onTextInput(@ptrCast(&event.text.text));
                },
                c.SDL_KEYDOWN => {
                    const ctrl = (event.key.keysym.mod & c.KMOD_CTRL) != 0;
                    // Route to focused input first
                    if (input_mod.getFocusedId() != null) {
                        if (ctrl and input_mod.handleCtrlKey(event.key.keysym.sym)) {
                            // Ctrl+A/C/X/V/Z handled
                        } else if (event.key.keysym.sym == c.SDLK_ESCAPE) { input_mod.unfocus(); }
                        else { _ = input_mod.handleKey(event.key.keysym.sym); }
                    } else if (ctrl and event.key.keysym.sym == c.SDLK_a) {
                        // Ctrl+A — select all text on the page
                        sel_all = true;
                        sel_node = null;
                        sel_start = 0;
                        sel_end = 0;
                    } else if (ctrl and event.key.keysym.sym == c.SDLK_c) {
                        // Ctrl+C — copy selected text to clipboard
                        var clip_buf: [16384]u8 = undefined;
                        var clip_len: usize = 0;
                        if (sel_all) {
                            clip_len = collectAllText(&root, &clip_buf, 0);
                        } else if (sel_node != null and sel_end_node != null) {
                            var copy_state: u8 = 0;
                            clip_len = collectSelectedText(&root, &clip_buf, 0, &copy_state);
                        }
                        if (clip_len > 0 and clip_len < clip_buf.len) {
                            clip_buf[clip_len] = 0;
                            _ = c.SDL_SetClipboardText(@ptrCast(&clip_buf));
                        }
                    } else if (event.key.keysym.sym == c.SDLK_F12) { inspector.toggle(); }
                    else if (event.key.keysym.sym == c.SDLK_ESCAPE) {
                        if (inspector.isEnabled()) {
                            if (inspector.getSelectedNode() != null) {
                                inspector.clearSelection();
                            } else {
                                inspector.toggle();
                            }
                        } else { running = false; }
                    }
                    else { const sdl_mod = event.key.keysym.mod; const mods: u16 = @intCast(sdl_mod & 0xFFFF); if (hovered_node) |node| { if (node.handlers.on_key) |handler| handler(event.key.keysym.sym, mods); } }
                },
                c.SDL_MOUSEMOTION => {
                    const mx: f32 = @floatFromInt(event.motion.x); const my: f32 = @floatFromInt(event.motion.y);
                    inspector.mouseMoved(mx, my);
                    const prev = hovered_node; hovered_node = events.hitTest(&root, mx, my);
                    if (prev != hovered_node) { if (prev) |p| { if (p.handlers.on_hover_exit) |h| h(); } if (hovered_node) |n| { if (n.handlers.on_hover_enter) |h| h(); } }
                    // Text selection drag — may cross into different text nodes
                    if (sel_dragging) {
                        if (events.hitTestText(&root, mx, my)) |tnode| {
                            if (tnode.text) |txt| {
                                const pad_l = tnode.style.padLeft();
                                const pad_r = tnode.style.padRight();
                                const pad_t = tnode.style.padTop();
                                const local_x = mx - tnode.computed.x - pad_l;
                                const local_y = my - tnode.computed.y - pad_t;
                                const text_max_w = tnode.computed.w - pad_l - pad_r;
                                sel_end_node = tnode;
                                sel_end = g_text_engine.?.hitTestWrappedAligned(txt, local_x, local_y, tnode.font_size, text_max_w, tnode.style.text_align);
                            }
                        }
                    }
                },
                c.SDL_MOUSEBUTTONDOWN => {
                    const mx: f32 = @floatFromInt(event.button.x); const my: f32 = @floatFromInt(event.button.y);
                    if (inspector.handleClick(&root, mx, my)) { continue; }
                    sel_all = false; // Any click clears select-all
                    // Handler-based hit test (buttons, inputs, etc.)
                    if (events.hitTest(&root, mx, my)) |node| {
                        if (node.input_id) |iid| {
                            input_mod.focus(iid);
                            sel_node = null;
                        } else {
                            input_mod.unfocus();
                            if (node.handlers.on_press) |handler| handler();
                        }
                    } else {
                        input_mod.unfocus();
                    }
                    // Text selection — only if no pressable/input was hit
                    const pressed_handler = if (events.hitTest(&root, mx, my)) |n| (n.handlers.on_press != null or n.input_id != null) else false;
                    if (!pressed_handler) {
                    if (events.hitTestText(&root, mx, my)) |tnode| {
                        if (tnode.text) |txt| {
                            const pad_l = tnode.style.padLeft();
                            const pad_r = tnode.style.padRight();
                            const pad_t = tnode.style.padTop();
                            const local_x = mx - tnode.computed.x - pad_l;
                            const local_y = my - tnode.computed.y - pad_t;
                            const text_max_w = tnode.computed.w - pad_l - pad_r;
                            const now = c.SDL_GetTicks();
                            const byte_idx = g_text_engine.?.hitTestWrappedAligned(txt, local_x, local_y, tnode.font_size, text_max_w, tnode.style.text_align);
                            if (sel_node == tnode and now -% sel_last_click < 400) {
                                sel_click_count += 1;
                            } else {
                                sel_click_count = 1;
                            }
                            sel_last_click = now;
                            if (sel_click_count >= 3) {
                                sel_node = tnode;
                                sel_end_node = tnode;
                                sel_start = 0;
                                sel_end = txt.len;
                                sel_anchor = 0;
                                sel_dragging = false;
                            } else if (sel_click_count == 2) {
                                const wb = TextEngine.wordBoundsAt(txt, byte_idx);
                                sel_node = tnode;
                                sel_end_node = tnode;
                                sel_start = wb.start;
                                sel_end = wb.end;
                                sel_anchor = wb.start;
                                sel_dragging = false;
                            } else {
                                sel_node = tnode;
                                sel_end_node = tnode;
                                sel_anchor = byte_idx;
                                sel_start = byte_idx;
                                sel_end = byte_idx;
                                sel_dragging = true;
                            }
                        }
                    } else {
                        sel_node = null;
                        sel_end_node = null;
                        sel_start = 0;
                        sel_end = 0;
                    }
                    }
                },
                c.SDL_MOUSEBUTTONUP => {
                    sel_dragging = false;
                },
                c.SDL_MOUSEWHEEL => {
                    var mx_i: c_int = undefined; var my_i: c_int = undefined;
                    _ = c.SDL_GetMouseState(&mx_i, &my_i);
                    const mx: f32 = @floatFromInt(mx_i); const my: f32 = @floatFromInt(my_i);
                    if (events.findScrollContainer(&root, mx, my)) |scroll_node| {
                        scroll_node.scroll_y -= @as(f32, @floatFromInt(event.wheel.y)) * 30.0;
                        const max_scroll = @max(0.0, scroll_node.content_height - scroll_node.computed.h);
                        scroll_node.scroll_y = @max(0.0, @min(scroll_node.scroll_y, max_scroll));
                    }
                },
                else => {},
            }
        }

        if (state.isDirty()) {
            updateDynamicTexts();
            _rebuildMap0();
            state.clearDirty();
        }
        {
            const _now = c.SDL_GetTicks();
            if (_now -% _timer_1 >= 16) { _timer_1 = _now; _effect_1(); }
        }
        if (watchdog.check()) {
            win_mgr.deinitAll();
            c.SDL_DestroyRenderer(renderer);
            c.SDL_DestroyWindow(window);
            bsod.show(watchdog.getLastReason(), watchdog.getLastDetail());
            return;
        }
        mpv_mod.poll();
        telemetry.beginLayout();
        layout.layout(&root, 0, 0, win_w, win_h);
        telemetry.endLayout();
        inspector.updateHover(&root);
        compositor.setHoveredNode(hovered_node);
        telemetry.beginPaint();
        compositor.frame(&root, win_w, win_h, Color.rgb(24, 24, 32));
        telemetry.endPaint();
        win_mgr.layoutAll();
        win_mgr.paintAndPresent(brighten);
        _telem_frame +%= 1;
        if (_telem_frame % 30 == 0) _ = telemetry.countNodes(&root);
        if (_telem_frame % 60 == 0) telemetry.debugPrint();
        if (testharness.tick()) {
            const exit_code = testharness.runAll(&root, renderer);
            if (exit_code != 0) std.process.exit(exit_code);
            running = false;
        }
    }
    geometry.save(window);
}
