//! Generated by Smith (mod mode) — do not edit
//! Source: m08_nested_access.mod.tsz
//! Module: ecs

const std = @import("std");

pub const CompKind = enum {
    position,
    velocity,
    health,
};

pub const Vec2 = struct {
    x: f32 = 0,
    y: f32 = 0,
};

pub const Health = struct {
    current: i32 = 100,
    max: i32 = 100,
};

pub const Entity = struct {
    id: u8 = 0,
    alive: bool = true,
    pos: Vec2 = .{},
    vel: Vec2 = .{},
    hp: Health = .{},
};

var entities: [32]Entity = [_]Entity{.{}} ** 32;
var count: u8 = 0;

pub fn spawn(x: f32, y: f32) u8 {
    if (count >= 32) return 0;
    entities[count] = .{ .id = count, .alive = true, .pos = .{ .x = x, .y = y } };
    count += 1;
    return count - 1;
}

pub fn kill(id: u8) void {
    entities[id].alive = false;
    entities[id].hp.current = 0;
}

pub fn damage(id: u8, amount: i32) void {
    entities[id].hp.current -= amount;
    if (entities[id].hp.current <= 0) return;
    entities[id].alive = false;
}

pub fn tick_physics(dt: f32) void {
    var _i: usize = 0;
    while (_i < count) : (_i += 1) {
        if (entities[_i].alive == true) {
            entities[_i].pos.x += entities[_i].vel.x * dt;
            entities[_i].pos.y += entities[_i].vel.y * dt;
        }
    }
}

pub fn count_alive() i32 {
    var n: i32 = 0;
    var _i: usize = 0;
    while (_i < count) : (_i += 1) {
        if (entities[_i].alive == true) {
            n += 1;
        }
    }
    return n;
}
