//! Generated by Smith (mod mode) — do not edit
//! Source: m20_filesystem_workspace.mod.tsz
//! Module: workspace

const std = @import("std");
const libc_so = @cImport({ @cInclude("libc.so"); });

pub const EntryKind = enum {
    file,
    directory,
    missing,
};

pub const Entry = struct {
    path: []const u8 = "",
    kind: EntryKind = .file,
    size: i64 = 0,
    dirty: bool = false,
};

var root: []const u8 = "";
var entries: [64]Entry = [_]Entry{.{}} ** 64;
var entry_count: u8 = 0;
var selected: []const u8 = "";
var trash_count: u8 = 0;
var last_scan: []const u8 = "";
var scratch_path: []const u8 = "";
var buf: [512]u8 = undefined;

pub fn mount(path: []const u8) void {
    root = path;
    libc_so.fs_mkdir(path);
    last_scan = libc_so.fs_list(path);
}

pub fn select(path: []const u8) void {
    selected = path;
}

pub fn save(name: []const u8, body: []const u8) []const u8 {
    scratch_path = std.fmt.bufPrint(&buf, "{s}/{s}", .{ root, name }) catch "";
    libc_so.fs_write(scratch_path, body);
    entries[entry_count] = .{ .path = scratch_path, .kind = .file, .size = body.len, .dirty = true };
    entry_count += 1;
    return scratch_path;
}

pub fn load(name: []const u8) []const u8 {
    scratch_path = std.fmt.bufPrint(&buf, "{s}/{s}", .{ root, name }) catch "";
    return libc_so.fs_read(scratch_path);
}

pub fn remove(name: []const u8) void {
    scratch_path = std.fmt.bufPrint(&buf, "{s}/{s}", .{ root, name }) catch "";
    libc_so.fs_remove(scratch_path);
    trash_count += 1;
    var _i: usize = 0;
    while (_i < entry_count) : (_i += 1) {
        if (std.mem.eql(u8, entries[_i].path, scratch_path)) {
            entries[_i].kind = .missing;
            entries[_i].dirty = false;
        }
    }
}

pub fn find(name: []const u8) i64 {
    scratch_path = std.fmt.bufPrint(&buf, "{s}/{s}", .{ root, name }) catch "";
    var _i: usize = 0;
    while (_i < entry_count) : (_i += 1) {
        if (std.mem.eql(u8, entries[_i].path, scratch_path)) {
            return 1;
        }
    }
    return -1;
}

pub fn sync_metadata() void {
    var _i: usize = 0;
    while (_i < entry_count) : (_i += 1) {
        if (entries[_i].kind == .file and entries[_i].dirty == true) {
            libc_so.fs_stat(entries[_i].path);
            entries[_i].dirty = false;
        }
    }
}
