//! Generated by tsz compiler — d29a_json_parse_script [nodes.zig]
//! Source: d29a_json_parse_script.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d29a_json_parse_script:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d29a_json_parse_script.tsz:62 — <Pressable>
pub var _arr_0 = [_]Node{ .{ .text = "Admins", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d29a_json_parse_script.tsz:65 — <Pressable>
pub var _arr_1 = [_]Node{ .{ .text = "Users", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d29a_json_parse_script.tsz:68 — <Pressable>
pub var _arr_2 = [_]Node{ .{ .text = "Mods", .font_size = 10, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d29a_json_parse_script.tsz:71 — <Pressable>
pub var _arr_3 = [_]Node{ .{ .text = "All", .font_size = 10, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d29a_json_parse_script.tsz:74 — <Pressable>
pub var _arr_4 = [_]Node{ .{ .text = "Serialize", .font_size = 10, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d29a_json_parse_script.tsz:61 — <Box>
pub var _arr_5 = [_]Node{ .{ .style = .{ .padding = 6, .background_color = Color.rgb(124, 58, 237), .border_radius = 4 }, .handlers = .{ .js_on_press = "filterByRole('admin')" }, .children = &_arr_0 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(37, 99, 235), .border_radius = 4 }, .handlers = .{ .js_on_press = "filterByRole('user')" }, .children = &_arr_1 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(5, 150, 105), .border_radius = 4 }, .handlers = .{ .js_on_press = "filterByRole('mod')" }, .children = &_arr_2 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(51, 65, 85), .border_radius = 4 }, .handlers = .{ .js_on_press = "filterByRole('')" }, .children = &_arr_3 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(51, 65, 85), .border_radius = 4 }, .handlers = .{ .js_on_press = "serialize()" }, .children = &_arr_4 } };
// tsz:d29a_json_parse_script.tsz:78 — <Box>
pub var _arr_7 = [_]Node{ .{ .style = .{ .gap = 4 } } };
// tsz:d29a_json_parse_script.tsz:58 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "API Response", .font_size = 16, .text_color = Color.rgb(226, 232, 240) }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(100, 116, 139) }, .{ .style = .{ .flex_direction = .row, .gap = 6 }, .children = &_arr_5 }, .{ .style = .{ .gap = 4 }, .children = &_arr_7 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(72, 79, 88) } };
// [origin:d29a_json_parse_script:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(12, 12, 29), .padding = 20, .width = -1, .height = -1, .gap = 10, .overflow = .hidden }, .children = &_arr_8 };

