//! Generated by tsz compiler — d136_render_fn_calls [logic.zig]
//! Source: d136_render_fn_calls.tsz


// [origin:d136_render_fn_calls:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\// Ambient namespaces
    \\var time = {
    \\  get hour() { return new Date().getHours(); },
    \\  get minute() { return String(new Date().getMinutes()).padStart(2, "0"); },
    \\  get second() { return String(new Date().getSeconds()).padStart(2, "0"); },
    \\  get year() { return new Date().getFullYear(); },
    \\  get month() { return new Date().getMonth() + 1; },
    \\  get day() { return new Date().getDate(); },
    \\  get fps() { return typeof getFps === "function" ? getFps() : 0; },
    \\  get delta() { return 16; },
    \\  get elapsed() { return Date.now(); },
    \\  get timestamp() { return Date.now(); },
    \\};
    \\var sys = {
    \\  get user() { return typeof __os_user !== "undefined" ? __os_user : "user"; },
    \\  get uptime() { return Math.floor(Date.now() / 1000); },
    \\  get os() { return "linux"; },
    \\  get host() { return "localhost"; },
    \\  get kernel() { return "unknown"; },
    \\};
    \\var device = {
    \\  get width() { return 1280; },
    \\  get height() { return 800; },
    \\  get battery() { return 100; },
    \\  get online() { return true; },
    \\  get dpi() { return 96; },
    \\};
    \\var input = {
    \\  mouse: {
    \\    get x() { return typeof getMouseX === "function" ? getMouseX() : 0; },
    \\    get y() { return typeof getMouseY === "function" ? getMouseY() : 0; },
    \\  },
    \\  keys: { shift: false, ctrl: false, alt: false },
    \\  touch: { count: 0 },
    \\};
    \\
    \\var entries = [];
    \\// OA initial data
    \\setEntries([ { label : "" , commits : 0 , files : 0 , tests : 0 , passing : 0 , shortDay : "" , dotColor : 0x475569 } ]);
    \\var rangeDays = 5;
    \\function setRangeDays(v) { rangeDays = v; __setState(0, v); }
    \\var totalCommits = 0;
    \\function setTotalCommits(v) { totalCommits = v; __setState(1, v); }
    \\var totalFiles = 0;
    \\function setTotalFiles(v) { totalFiles = v; __setState(2, v); }
    \\  setEntries([
    \\    { label: "Day 1", commits: 5, files: 120, tests: 18, passing: 14, shortDay: "Apr 1", dotColor: 0x34d399 },
    \\    { label: "Day 2", commits: 3, files: 125, tests: 20, passing: 17, shortDay: "Apr 2", dotColor: 0xf59e0b },
    \\    { label: "Day 3", commits: 8, files: 131, tests: 22, passing: 20, shortDay: "Apr 3", dotColor: 0xf87171 },
    \\    { label: "Day 4", commits: 2, files: 134, tests: 24, passing: 22, shortDay: "Apr 4", dotColor: 0x60a5fa },
    \\    { label: "Day 5", commits: 6, files: 140, tests: 26, passing: 25, shortDay: "Apr 5", dotColor: 0x94a3b8 }
    \\  ]);
    \\
    \\
    \\
    \\var rangeDays = 5;
    \\function setRangeDays(v) { rangeDays = v; __setState(0, v); }
    \\var totalCommits = 0;
    \\function setTotalCommits(v) { totalCommits = v; __setState(1, v); }
    \\var totalFiles = 0;
    \\function setTotalFiles(v) { totalFiles = v; __setState(2, v); }
    \\function sumField(rows, field) {
    \\  var total = 0;
    \\  var i = 0;
    \\  while (i < rows.length) {
    \\    total = total + (rows[i][field] || 0);
    \\    i = i + 1;
    \\  }
    \\  return total;
    \\}
    \\
    \\function lastField(rows, field) {
    \\  if (rows.length === 0) return 0;
    \\  return rows[rows.length - 1][field] || 0;
    \\}
    \\
    \\function rangeLabel() {
    \\  if (rangeDays === 5) return 'last 5 days';
    \\  if (rangeDays === 3) return 'last 3 days';
    \\  return 'full span';
    \\}
    \\
    \\function formatWindow(rows) {
    \\  if (rows.length === 0) return '';
    \\  return rows[0].shortDay + ' -> ' + rows[rows.length - 1].shortDay;
    \\}
    \\
    \\setTotalCommits(sumField(entries, 'commits'));
    \\setTotalFiles(lastField(entries, 'files'));
    \\function setEntries(v) { entries = v; __setObjArr0(v); }
    \\if (entries && entries.length > 0) setEntries(entries);
    \\
;

// [origin:d136_render_fn_calls:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

