//! Generated by tsz compiler — d65_component_8_props [state.zig]
//! Source: d65_component_8_props.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d65_component_8_props:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: selected (int)
// slot 1: output (string)
comptime { if (2 != 2) @compileError("state slot count mismatch"); }

// [origin:d65_component_8_props:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_2: []const u8 = "";
pub var _dyn_buf_3: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_3: []const u8 = "";
pub var _dyn_buf_4: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_4: []const u8 = "";
pub var _dyn_buf_5: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_5: []const u8 = "";
pub var _dyn_buf_6: [162]u8 = std.mem.zeroes([162]u8);
pub var _dyn_text_6: []const u8 = "";

pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlotString("");
}

