//! Generated by tsz compiler — d130_progress_group_collapse [app.zig]
//! Source: d130_progress_group_collapse.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const engine = api.engine;
const qjs_runtime = api.qjs_runtime;
const nodes = @import("nodes.zig");
const st = @import("state.zig");
const maps = @import("maps.zig");
const logic = @import("logic.zig");

fn _updateDynamicTexts() void {
    st._dyn_text_0 = std.fmt.bufPrint(&st._dyn_buf_0, "{d} searches", .{ state.getSlot(2) }) catch "";
    nodes._arr_0[1].text = st._dyn_text_0;
    st._dyn_text_1 = std.fmt.bufPrint(&st._dyn_buf_1, "{d} reads", .{ state.getSlot(3) }) catch "";
    nodes._arr_1[1].text = st._dyn_text_1;
    st._dyn_text_2 = std.fmt.bufPrint(&st._dyn_buf_2, "{d} edits", .{ state.getSlot(4) }) catch "";
    nodes._arr_2[1].text = st._dyn_text_2;
    st._dyn_text_3 = std.fmt.bufPrint(&st._dyn_buf_3, "{d} events -> {d} rows", .{ state.getSlot(0), state.getSlot(1) }) catch "";
    nodes._arr_3[3].text = st._dyn_text_3;
    nodes._arr_0[0].style.background_color = if (0 == 0) Color.rgb(59, 130, 246) else if (0 == 1) Color.rgb(34, 197, 94) else if (0 == 2) Color.rgb(245, 158, 11) else Color.rgb(148, 163, 184);
    nodes._arr_1[0].style.background_color = if (1 == 0) Color.rgb(59, 130, 246) else if (1 == 1) Color.rgb(34, 197, 94) else if (1 == 2) Color.rgb(245, 158, 11) else Color.rgb(148, 163, 184);
    nodes._arr_2[0].style.background_color = if (2 == 0) Color.rgb(59, 130, 246) else if (2 == 1) Color.rgb(34, 197, 94) else if (2 == 2) Color.rgb(245, 158, 11) else Color.rgb(148, 163, 184);
}

fn _updateConditionals() void {
}


fn _appInit() void {
    st._initState();
    qjs_runtime.registerHostFn("__setObjArr0", @ptrCast(&st._oa0_unpack), 1);
    qjs_runtime.registerHostFn("__setObjArr1", @ptrCast(&st._oa1_unpack), 1);
    qjs_runtime.registerHostFn("__setObjArr2", @ptrCast(&st._oa2_unpack), 1);
    _updateDynamicTexts();
    _updateConditionals();
    maps._initMapLuaPtrs0_0();
    _ = maps._pool_arena.reset(.retain_capacity);
    maps._rebuildMap0();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts(); _updateConditionals();
        _ = maps._pool_arena.reset(.retain_capacity);
        maps._rebuildMap0();
 state.clearDirty(); }
}

export fn app_get_root() *Node { return &nodes._root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return logic.JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return logic.JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return logic.LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return logic.LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d130_progress_group_collapse"; }

export fn app_state_count() usize { return 5; }
const _slot_types = [_]u8{ 0, 0, 0, 0, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

pub fn main() !void {
    try engine.run(.{
        .title = "d130_progress_group_collapse",
        .root = &nodes._root,
        .js_logic = logic.JS_LOGIC,
        .lua_logic = logic.LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}

// ── Smith debug log ──
// DBG: [INLINE PROBE] Inlining component: CategoryDot bodyPos: 1112 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: CategoryDot bodyPos: 1112 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: CategoryDot bodyPos: 1112 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: OriginalEvent bodyPos: 1165 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: CategoryDot bodyPos: 1112 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: SummaryGroup bodyPos: 1291 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: CategoryDot bodyPos: 1112 token: < kind: 41
