//! Generated by tsz compiler — d130_progress_group_collapse [maps.zig]
//! Source: d130_progress_group_collapse.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const nodes = @import("nodes.zig");
const st = @import("state.zig");

// [origin:d130_progress_group_collapse:maps]
// ── Map pools ───────────────────────────────────────────────────
pub var _pool_arena: std.heap.ArenaAllocator = std.heap.ArenaAllocator.init(std.heap.page_allocator);
pub const MAX_MAP_0: usize = 4096;
pub var _map_pool_0: []Node = std.mem.zeroes([]Node);
pub var _map_count_0: usize = 0;
pub var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_0: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_1: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_2: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_2: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_3: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_3: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_4: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_4: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_5: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_5: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_lua_bufs_0_0: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_0: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_0() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_0[_i][0..47], "__mapPress_0_0({d})", .{_i}) catch continue;
        _map_lua_bufs_0_0[_i][n.len] = 0;
        _map_lua_ptrs_0_0[_i] = @ptrCast(_map_lua_bufs_0_0[_i][0..n.len :0]);
    }
}
// [origin:d130_progress_group_collapse:map:_rebuildMap0]
pub fn _rebuildMap0() void {
    _map_count_0 = @min(st._oa1_len, MAX_MAP_0);
    _map_pool_0 = _pool_arena.allocator().alloc(Node, _map_count_0) catch unreachable;
    for (0.._map_count_0) |_i| {
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ st._oa1_label[_i][0..st._oa1_label_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{s}", .{ st._oa1_items[_i][0..st._oa1_items_lens[_i]] }) catch "";
        _map_texts_0_2[_i] = std.fmt.bufPrint(&_map_text_bufs_0_2[_i], "{s}", .{ st._oa1_label[_i][0..st._oa1_label_lens[_i]] }) catch "";
        _map_texts_0_3[_i] = std.fmt.bufPrint(&_map_text_bufs_0_3[_i], "{s}", .{ if (st._oa2_value[@as(usize, @intCast(st._oa1_groupId[_i]))] == 1) @as([]const u8, "collapse") else @as([]const u8, "expand") }) catch "";
        _map_texts_0_4[_i] = std.fmt.bufPrint(&_map_text_bufs_0_4[_i], "{d}", .{ st._oa1_count[_i] }) catch "";
        _map_texts_0_5[_i] = std.fmt.bufPrint(&_map_text_bufs_0_5[_i], "{s}", .{ st._oa1_items[_i][0..st._oa1_items_lens[_i]] }) catch "";
        const _pi__arr_4_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_4_0, &[_]Node{ .{ .text = _map_texts_0_0[_i], .font_size = 10, .text_color = if (st._oa1_category[_i] == 2) Color.rgb(245, 158, 11) else Color.rgb(226, 232, 240) }, .{ .text = _map_texts_0_1[_i], .font_size = 8, .text_color = Color.rgb(71, 85, 105) } });
        const _pi__arr_5_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_5_0, &[_]Node{ .{ .style = .{ .width = 6, .height = 6, .border_radius = 3, .background_color = if (st._oa1_category[_i] == 0) Color.rgb(59, 130, 246) else if (st._oa1_category[_i] == 1) Color.rgb(34, 197, 94) else if (st._oa1_category[_i] == 2) Color.rgb(245, 158, 11) else Color.rgb(148, 163, 184) } }, .{ .style = .{ .flex_grow = 1, .gap = 1, .overflow = .auto }, .children = _pi__arr_4_0 } });
        const _pi__arr_6_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_6_0, &[_]Node{ .{ .text = _map_texts_0_2[_i], .font_size = 10, .text_color = if (st._oa1_category[_i] == 0) Color.rgb(59, 130, 246) else Color.rgb(34, 197, 94) } });
        const _pi__arr_7_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_7_0, &[_]Node{ .{ .text = _map_texts_0_4[_i], .font_size = 7, .text_color = Color.rgb(148, 163, 184) } });
        const _pi__arr_8_0 = _pool_arena.allocator().alloc(Node, 4) catch unreachable;
        @memcpy(_pi__arr_8_0, &[_]Node{ .{ .style = .{ .width = 6, .height = 6, .border_radius = 3, .background_color = if (st._oa1_category[_i] == 0) Color.rgb(59, 130, 246) else if (st._oa1_category[_i] == 1) Color.rgb(34, 197, 94) else if (st._oa1_category[_i] == 2) Color.rgb(245, 158, 11) else Color.rgb(148, 163, 184) } }, .{ .style = .{ .flex_grow = 1, .overflow = .auto }, .children = _pi__arr_6_0 }, .{ .text = _map_texts_0_3[_i], .font_size = 8, .text_color = Color.rgb(71, 85, 105) }, .{ .style = .{ .padding_left = 4, .padding_right = 4, .padding_top = 1, .padding_bottom = 1, .background_color = Color.rgb(51, 65, 85), .border_radius = 8 }, .children = _pi__arr_7_0 } });
        const _pi__arr_9_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_9_0, &[_]Node{ .{ .text = _map_texts_0_5[_i], .font_size = 8, .text_color = Color.rgb(100, 116, 139) } });
        const _pi__arr_10_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_10_0, &[_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 8, .align_items = .center }, .children = _pi__arr_8_0 }, .{ .style = .{ .margin_top = 6, .padding_left = 14, .gap = 2 }, .children = _pi__arr_9_0 } });
        _pi__arr_4_0[1].style.display = if (st._oa1_items[_i].len > 0) .flex else .none;
        _pi__arr_10_0[1].style.display = if (st._oa2_value[@as(usize, @intCast(st._oa1_groupId[_i]))] ==  1) .flex else .none;
        const _inner_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_inner_0, &[_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 8, .padding = 8, .align_items = .center }, .children = _pi__arr_5_0 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(30, 41, 59), .border_radius = 6 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_0[_i] }, .children = _pi__arr_10_0 } });
        _inner_0[0].style.display = if (st._oa1_type[_i] ==  0) .flex else .none;
        _inner_0[1].style.display = if (st._oa1_type[_i] ==  1) .flex else .none;
        _map_pool_0[_i] = .{ .children = _inner_0 };
    }
    nodes._arr_12[0].children = _map_pool_0[0.._map_count_0];
}


