//! Generated by tsz compiler — d130_progress_group_collapse [state.zig]
//! Source: d130_progress_group_collapse.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d130_progress_group_collapse:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: totalEvents (int)
// slot 1: totalGroups (int)
// slot 2: searchCount (int)
// slot 3: readCount (int)
// slot 4: editCount (int)
comptime { if (5 != 5) @compileError("state slot count mismatch"); }

// [origin:d130_progress_group_collapse:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_2: []const u8 = "";
pub var _dyn_buf_3: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_3: []const u8 = "";
pub const qjs = @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
pub const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// [origin:d130_progress_group_collapse:state]
// ── Object arrays ───────────────────────────────────────────────
pub const _oa_alloc = std.heap.page_allocator;

pub fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

pub fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

pub var _oa0_type: []i64 = &[_]i64{};
pub var _oa0_type_cap: usize = 0;
pub var _oa0_category: []i64 = &[_]i64{};
pub var _oa0_category_cap: usize = 0;
pub var _oa0_name: [][]const u8 = &[_][]const u8{};
pub var _oa0_name_lens: []usize = &[_]usize{};
pub var _oa0_name_cap: usize = 0;
pub var _oa0_detail: [][]const u8 = &[_][]const u8{};
pub var _oa0_detail_lens: []usize = &[_]usize{};
pub var _oa0_detail_cap: usize = 0;
pub var _oa0_groupId: []i64 = &[_]i64{};
pub var _oa0_groupId_cap: usize = 0;
pub var _oa0_len: usize = 0;
pub var _oa0_dirty: bool = false;

pub fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_type_cap) return;
    const new_cap = @max(needed, if (_oa0_type_cap == 0) @as(usize, 64) else _oa0_type_cap * 2);
    if (_oa0_type_cap == 0) {
        _oa0_type = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_type, 0);
    } else {
        _oa0_type = _oa_alloc.realloc(_oa0_type.ptr[0.._oa0_type_cap], new_cap) catch return;
        @memset(_oa0_type[_oa0_type_cap..new_cap], 0);
    }
    _oa0_type_cap = new_cap;
    if (_oa0_category_cap == 0) {
        _oa0_category = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_category, 0);
    } else {
        _oa0_category = _oa_alloc.realloc(_oa0_category.ptr[0.._oa0_category_cap], new_cap) catch return;
        @memset(_oa0_category[_oa0_category_cap..new_cap], 0);
    }
    _oa0_category_cap = new_cap;
    if (_oa0_name_cap == 0) {
        _oa0_name = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_name_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens, 0);
    } else {
        const _old_cap = _oa0_name_cap;
        _oa0_name = _oa_alloc.realloc(_oa0_name.ptr[0.._old_cap], new_cap) catch return;
        _oa0_name_lens = _oa_alloc.realloc(_oa0_name_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens[_old_cap..new_cap], 0);
    }
    _oa0_name_cap = new_cap;
    if (_oa0_detail_cap == 0) {
        _oa0_detail = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_detail_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_detail[_j] = &[_]u8{};
        @memset(_oa0_detail_lens, 0);
    } else {
        const _old_cap = _oa0_detail_cap;
        _oa0_detail = _oa_alloc.realloc(_oa0_detail.ptr[0.._old_cap], new_cap) catch return;
        _oa0_detail_lens = _oa_alloc.realloc(_oa0_detail_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_detail[_j] = &[_]u8{};
        @memset(_oa0_detail_lens[_old_cap..new_cap], 0);
    }
    _oa0_detail_cap = new_cap;
    if (_oa0_groupId_cap == 0) {
        _oa0_groupId = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_groupId, 0);
    } else {
        _oa0_groupId = _oa_alloc.realloc(_oa0_groupId.ptr[0.._oa0_groupId_cap], new_cap) catch return;
        @memset(_oa0_groupId[_oa0_groupId_cap..new_cap], 0);
    }
    _oa0_groupId_cap = new_cap;
}

// [origin:d130_progress_group_collapse:oa:_oa0_unpack]
pub fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "type");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_type[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "category");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_category[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "name");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_name[_i], &_oa0_name_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_name[_i] = _oaDupString(sl); _oa0_name_lens[_i] = _oa0_name[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "detail");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_detail[_i], &_oa0_detail_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_detail[_i] = _oaDupString(sl); _oa0_detail_lens[_i] = _oa0_detail[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "groupId");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_groupId[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa0_len) {
        for (count.._oa0_len) |_trim_i| {
            _oaFreeString(&_oa0_name[_trim_i], &_oa0_name_lens[_trim_i]);
            _oaFreeString(&_oa0_detail[_trim_i], &_oa0_detail_lens[_trim_i]);
        }
    }
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa1_type: []i64 = &[_]i64{};
pub var _oa1_type_cap: usize = 0;
pub var _oa1_groupId: []i64 = &[_]i64{};
pub var _oa1_groupId_cap: usize = 0;
pub var _oa1_category: []i64 = &[_]i64{};
pub var _oa1_category_cap: usize = 0;
pub var _oa1_count: []i64 = &[_]i64{};
pub var _oa1_count_cap: usize = 0;
pub var _oa1_label: [][]const u8 = &[_][]const u8{};
pub var _oa1_label_lens: []usize = &[_]usize{};
pub var _oa1_label_cap: usize = 0;
pub var _oa1_items: [][]const u8 = &[_][]const u8{};
pub var _oa1_items_lens: []usize = &[_]usize{};
pub var _oa1_items_cap: usize = 0;
pub var _oa1_len: usize = 0;
pub var _oa1_dirty: bool = false;

pub fn _oa1_ensureCapacity(needed: usize) void {
    if (needed <= _oa1_type_cap) return;
    const new_cap = @max(needed, if (_oa1_type_cap == 0) @as(usize, 64) else _oa1_type_cap * 2);
    if (_oa1_type_cap == 0) {
        _oa1_type = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_type, 0);
    } else {
        _oa1_type = _oa_alloc.realloc(_oa1_type.ptr[0.._oa1_type_cap], new_cap) catch return;
        @memset(_oa1_type[_oa1_type_cap..new_cap], 0);
    }
    _oa1_type_cap = new_cap;
    if (_oa1_groupId_cap == 0) {
        _oa1_groupId = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_groupId, 0);
    } else {
        _oa1_groupId = _oa_alloc.realloc(_oa1_groupId.ptr[0.._oa1_groupId_cap], new_cap) catch return;
        @memset(_oa1_groupId[_oa1_groupId_cap..new_cap], 0);
    }
    _oa1_groupId_cap = new_cap;
    if (_oa1_category_cap == 0) {
        _oa1_category = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_category, 0);
    } else {
        _oa1_category = _oa_alloc.realloc(_oa1_category.ptr[0.._oa1_category_cap], new_cap) catch return;
        @memset(_oa1_category[_oa1_category_cap..new_cap], 0);
    }
    _oa1_category_cap = new_cap;
    if (_oa1_count_cap == 0) {
        _oa1_count = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_count, 0);
    } else {
        _oa1_count = _oa_alloc.realloc(_oa1_count.ptr[0.._oa1_count_cap], new_cap) catch return;
        @memset(_oa1_count[_oa1_count_cap..new_cap], 0);
    }
    _oa1_count_cap = new_cap;
    if (_oa1_label_cap == 0) {
        _oa1_label = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_label_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_label[_j] = &[_]u8{};
        @memset(_oa1_label_lens, 0);
    } else {
        const _old_cap = _oa1_label_cap;
        _oa1_label = _oa_alloc.realloc(_oa1_label.ptr[0.._old_cap], new_cap) catch return;
        _oa1_label_lens = _oa_alloc.realloc(_oa1_label_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_label[_j] = &[_]u8{};
        @memset(_oa1_label_lens[_old_cap..new_cap], 0);
    }
    _oa1_label_cap = new_cap;
    if (_oa1_items_cap == 0) {
        _oa1_items = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_items_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_items[_j] = &[_]u8{};
        @memset(_oa1_items_lens, 0);
    } else {
        const _old_cap = _oa1_items_cap;
        _oa1_items = _oa_alloc.realloc(_oa1_items.ptr[0.._old_cap], new_cap) catch return;
        _oa1_items_lens = _oa_alloc.realloc(_oa1_items_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_items[_j] = &[_]u8{};
        @memset(_oa1_items_lens[_old_cap..new_cap], 0);
    }
    _oa1_items_cap = new_cap;
}

// [origin:d130_progress_group_collapse:oa:_oa1_unpack]
pub fn _oa1_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa1_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "type");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_type[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "groupId");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_groupId[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "category");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_category[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "count");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_count[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "label");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_label[_i], &_oa1_label_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_label[_i] = _oaDupString(sl); _oa1_label_lens[_i] = _oa1_label[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "items");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_items[_i], &_oa1_items_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_items[_i] = _oaDupString(sl); _oa1_items_lens[_i] = _oa1_items[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa1_len) {
        for (count.._oa1_len) |_trim_i| {
            _oaFreeString(&_oa1_label[_trim_i], &_oa1_label_lens[_trim_i]);
            _oaFreeString(&_oa1_items[_trim_i], &_oa1_items_lens[_trim_i]);
        }
    }
    _oa1_len = count;
    _oa1_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa2_value: []i64 = &[_]i64{};
pub var _oa2_value_cap: usize = 0;
pub var _oa2_len: usize = 0;
pub var _oa2_dirty: bool = false;

pub fn _oa2_ensureCapacity(needed: usize) void {
    if (needed <= _oa2_value_cap) return;
    const new_cap = @max(needed, if (_oa2_value_cap == 0) @as(usize, 64) else _oa2_value_cap * 2);
    if (_oa2_value_cap == 0) {
        _oa2_value = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa2_value, 0);
    } else {
        _oa2_value = _oa_alloc.realloc(_oa2_value.ptr[0.._oa2_value_cap], new_cap) catch return;
        @memset(_oa2_value[_oa2_value_cap..new_cap], 0);
    }
    _oa2_value_cap = new_cap;
}

// [origin:d130_progress_group_collapse:oa:_oa2_unpack]
pub fn _oa2_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa2_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, elem);
        _oa2_value[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    _oa2_len = count;
    _oa2_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa3_type = [_]i64{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
pub var _oa3_category = [_]i64{ 0, 0, 0, 1, 1, 3, 2, 0, 0, 1, 1, 1, 2, 2, 3, 0, 1 };
pub var _oa3_name = [_][]const u8{ "grep \"auth\" src/", "grep \"session\" src/", "grep \"token\" src/", "Read src/auth.ts", "Read src/session.ts", "Thinking about the auth flow...", "Edit src/auth.ts:42", "grep \"Bearer\" src/", "grep \"Authorization\" src/", "Read src/middleware.ts", "Read src/config.ts", "Read src/utils/jwt.ts", "Edit src/middleware.ts:15", "Edit src/middleware.ts:28", "Running tests...", "grep \"test\" __tests__/", "Read __tests__/auth.test.ts" };
pub var _oa3_name_lens = [_]usize{ 16, 19, 17, 16, 19, 31, 19, 18, 25, 22, 18, 21, 25, 25, 16, 22, 27 };
pub var _oa3_detail = [_][]const u8{ "12 matches", "8 matches", "5 matches", "142 lines", "89 lines", "", "fix token check", "3 matches", "7 matches", "67 lines", "34 lines", "56 lines", "add Bearer prefix", "add error handling", "npm test", "24 matches", "198 lines" };
pub var _oa3_detail_lens = [_]usize{ 10, 9, 9, 9, 8, 0, 15, 9, 9, 8, 8, 8, 17, 18, 8, 10, 9 };
pub var _oa3_groupId = [_]i64{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
pub var _oa3_len: usize = 17;
pub var _oa3_dirty: bool = false;


pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

