//! Generated by tsz compiler — d131_spinner_modes [app.zig]
//! Source: d131_spinner_modes.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const engine = api.engine;
const qjs_runtime = api.qjs_runtime;
const nodes = @import("nodes.zig");
const st = @import("state.zig");
const maps = @import("maps.zig");
const handlers = @import("handlers.zig");
const logic = @import("logic.zig");

fn _updateDynamicTexts() void {
    st._dyn_text_0 = std.fmt.bufPrint(&st._dyn_buf_0, "{s}", .{ state.getSlotString(10) }) catch "";
    nodes._arr_7[0].text = st._dyn_text_0;
    st._dyn_text_1 = std.fmt.bufPrint(&st._dyn_buf_1, "{s}", .{ state.getSlotString(9) }) catch "";
    nodes._arr_7[2].text = st._dyn_text_1;
    st._dyn_text_2 = std.fmt.bufPrint(&st._dyn_buf_2, "{d}s", .{ state.getSlot(1) }) catch "";
    nodes._arr_7[3].text = st._dyn_text_2;
    st._dyn_text_3 = std.fmt.bufPrint(&st._dyn_buf_3, "{d} tokens", .{ state.getSlot(2) }) catch "";
    nodes._arr_9[0].text = st._dyn_text_3;
    st._dyn_text_4 = std.fmt.bufPrint(&st._dyn_buf_4, "{s}", .{ state.getSlotString(5) }) catch "";
    nodes._arr_9[1].text = st._dyn_text_4;
    st._dyn_text_5 = std.fmt.bufPrint(&st._dyn_buf_5, "{s}", .{ if (state.getSlot(6) == 0) @as([]const u8, "auto") else @as([]const u8, if (state.getSlot(6) == 1) @as([]const u8, "low") else @as([]const u8, if (state.getSlot(6) == 2) @as([]const u8, "medium") else @as([]const u8, "high"))) }) catch "";
    nodes._arr_9[2].text = st._dyn_text_5;
    st._dyn_text_6 = std.fmt.bufPrint(&st._dyn_buf_6, "{s}", .{ if (state.getSlot(4) == 1) @as([]const u8, "Verbose") else @as([]const u8, "Normal") }) catch "";
    nodes._arr_15[0].text = st._dyn_text_6;
    st._dyn_text_7 = std.fmt.bufPrint(&st._dyn_buf_7, "{s}", .{ if (state.getSlot(6) == 0) @as([]const u8, "auto") else @as([]const u8, if (state.getSlot(6) == 1) @as([]const u8, "low") else @as([]const u8, if (state.getSlot(6) == 2) @as([]const u8, "med") else @as([]const u8, "high"))) }) catch "";
    nodes._arr_16[0].text = st._dyn_text_7;
    st._dyn_text_8 = std.fmt.bufPrint(&st._dyn_buf_8, "frame: {d}", .{ state.getSlot(8) }) catch "";
    nodes._arr_20[1].text = st._dyn_text_8;
    st._dyn_text_9 = std.fmt.bufPrint(&st._dyn_buf_9, "stall: {d}", .{ state.getSlot(7) }) catch "";
    nodes._arr_20[2].text = st._dyn_text_9;
    nodes._arr_6[0].style.background_color = if (state.getSlot(0) == 0) Color.rgb(71, 85, 105) else Color.rgb(30, 41, 59);
    nodes._arr_6[1].style.background_color = if (state.getSlot(0) == 1) Color.rgb(124, 58, 237) else Color.rgb(30, 41, 59);
    nodes._arr_6[2].style.background_color = if (state.getSlot(0) == 2) Color.rgb(30, 64, 175) else Color.rgb(30, 41, 59);
    nodes._arr_6[3].style.background_color = if (state.getSlot(0) == 3) Color.rgb(22, 101, 52) else Color.rgb(30, 41, 59);
    nodes._arr_6[4].style.background_color = if (state.getSlot(0) == 4) Color.rgb(146, 64, 14) else Color.rgb(30, 41, 59);
    nodes._arr_6[5].style.background_color = if (state.getSlot(0) == 5) Color.rgb(220, 38, 38) else Color.rgb(30, 41, 59);
    nodes._arr_7[2].text_color = if (state.getSlot(7) == 2) Color.rgb(239, 68, 68) else if (state.getSlot(7) == 1) Color.rgb(245, 158, 11) else if (state.getSlot(0) == 0) Color.rgb(71, 85, 105) else if (state.getSlot(0) == 1) Color.rgb(168, 85, 247) else if (state.getSlot(0) == 2) Color.rgb(59, 130, 246) else if (state.getSlot(0) == 3) Color.rgb(34, 197, 94) else if (state.getSlot(0) == 4) Color.rgb(245, 158, 11) else Color.rgb(239, 68, 68);
    nodes._arr_17[2].style.background_color = if (state.getSlot(4) == 1) Color.rgb(124, 58, 237) else Color.rgb(51, 65, 85);
    nodes._arr_18[0].style.background_color = if (state.getSlot(6) == 0) Color.rgb(71, 85, 105) else if (state.getSlot(6) == 1) Color.rgb(34, 197, 94) else if (state.getSlot(6) == 2) Color.rgb(245, 158, 11) else Color.rgb(239, 68, 68);
    nodes._arr_18[0].style.width = @as(f32, @floatFromInt(state.getSlot(6)));
}

fn _updateConditionals() void {
    nodes._arr_7[0].style.display = if ((state.getSlot(0) !=  0 and state.getSlot(0) !=  5)) .flex else .none;
    nodes._arr_7[1].style.display = if ((state.getSlot(0) ==  5)) .flex else .none;
    nodes._arr_7[3].style.display = if ((state.getSlot(1) >  0)) .flex else .none;
    nodes._arr_12[1].style.display = if ((state.getSlot(7) ==  1)) .flex else .none;
    nodes._arr_12[2].style.display = if ((state.getSlot(7) ==  2)) .flex else .none;
    nodes._arr_12[3].style.display = if ((state.getSlot(0) ==  5)) .flex else .none;
    nodes._arr_12[4].style.display = if ((state.getSlot(4) ==  1 and state.getSlot(0) !=  0)) .flex else .none;
    nodes._arr_12[5].style.display = if (((state.getSlot(0) ==  1 or state.getSlot(0) ==  2 or state.getSlot(0) ==  3))) .flex else .none;
}


fn _appInit() void {
    st._initState();
    qjs_runtime.registerHostFn("__setObjArr0", @ptrCast(&st._oa0_unpack), 1);
    _updateDynamicTexts();
    _updateConditionals();
    _ = maps._pool_arena.reset(.retain_capacity);
    maps._rebuildMap0();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts(); _updateConditionals();
        _ = maps._pool_arena.reset(.retain_capacity);
        maps._rebuildMap0();
 state.clearDirty(); }
}

export fn app_get_root() *Node { return &nodes._root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return logic.JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return logic.JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return logic.LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return logic.LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d131_spinner_modes"; }

export fn app_state_count() usize { return 11; }
const _slot_types = [_]u8{ 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 3 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

pub fn main() !void {
    try engine.run(.{
        .title = "d131_spinner_modes",
        .root = &nodes._root,
        .js_logic = logic.JS_LOGIC,
        .lua_logic = logic.LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}

// ── Smith debug log ──
// DBG: [INLINE PROBE] Inlining component: SpinnerDot bodyPos: 605 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: TaskRow bodyPos: 668 token: < kind: 41
