//! Generated by tsz compiler — 27_many_items [nodes.zig]
//! Source: 27_many_items.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:27_many_items:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:27_many_items.tsz:8 — <Box>
pub var _arr_0 = [_]Node{ .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(233, 30, 99) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(156, 39, 176) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(103, 58, 183) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(63, 81, 181) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(0, 188, 212) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(0, 150, 136) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(255, 152, 0) } }, .{ .style = .{ .flex_grow = 1, .height = 30, .background_color = Color.rgb(244, 67, 54) } } };
// tsz:27_many_items.tsz:22 — <Box>
pub var _arr_1 = [_]Node{ .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(233, 30, 99) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(156, 39, 176) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(103, 58, 183) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(63, 81, 181) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(0, 188, 212) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(0, 150, 136) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(205, 220, 57) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(255, 152, 0) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(255, 87, 34) } }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(244, 67, 54) } } };
// tsz:27_many_items.tsz:38 — <Box>
pub var _arr_2 = [_]Node{ .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(233, 30, 99) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(156, 39, 176) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(63, 81, 181) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(0, 150, 136) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(255, 152, 0) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(244, 67, 54) } } };
// tsz:27_many_items.tsz:3 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "WPT: many items stress" }, .{ .text = "VERIFY: 10 items equal grow, 12 items wrap 3-per-row, 8 column items equal", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "10 items in row — equal grow" }, .{ .style = .{ .flex_direction = .row, .width = 500, .height = 30, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_0 }, .{ .text = "12 items wrapping in 200px — 3 per row" }, .{ .style = .{ .flex_direction = .row, .flex_wrap = .wrap, .width = 200, .background_color = Color.rgb(51, 51, 51), .gap = 2 }, .children = &_arr_1 }, .{ .text = "8 items in column with gap" }, .{ .style = .{ .flex_direction = .column, .width = 80, .height = 250, .background_color = Color.rgb(51, 51, 51), .gap = 2, .overflow = .auto }, .children = &_arr_2 } };
// [origin:27_many_items:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 8, .overflow = .hidden }, .children = &_arr_3 };

