import {
  gitAdd,
  gitAheadBehind,
  gitAmend,
  gitBranchDelete,
  gitBranchList,
  gitCheckout,
  gitCherryPick,
  gitCommit,
  gitDiff,
  gitDiffStats,
  gitDiscard,
  gitLog,
  gitLogGraph,
  gitPull,
  gitPush,
  gitReset,
  gitRevert,
  gitStash,
  gitStashApply,
  gitStashDrop,
  gitStashList,
  gitStashPop,
  gitStatusList,
  type GitCommitInfo,
  type GitDiff,
  type GitGraphLine,
  type GitStashEntry,
} from '../../git-ops';

export type { GitCommitInfo, GitDiff, GitGraphLine, GitStashEntry };

export function useGitOps(workDir: string) {
  return {
    add: (path: string) => gitAdd(workDir, path),
    reset: (path: string) => gitReset(workDir, path),
    discard: (path: string, untracked?: boolean) => gitDiscard(workDir, path, untracked),
    commit: (message: string) => gitCommit(workDir, message),
    amend: (message?: string) => gitAmend(workDir, message),
    push: (remote?: string, branch?: string) => gitPush(workDir, remote, branch),
    pull: (remote?: string, branch?: string) => gitPull(workDir, remote, branch),
    diff: (staged?: boolean) => gitDiff(workDir, staged),
    diffStats: () => gitDiffStats(workDir),
    log: (count?: number) => gitLog(workDir, count),
    logGraph: (count?: number) => gitLogGraph(workDir, count),
    branchList: () => gitBranchList(workDir),
    checkout: (branch: string, create?: boolean) => gitCheckout(workDir, branch, create),
    branchDelete: (branch: string, force?: boolean) => gitBranchDelete(workDir, branch, force),
    aheadBehind: (branch: string) => gitAheadBehind(workDir, branch),
    statusList: () => gitStatusList(workDir),
    stash: (message?: string) => gitStash(workDir, message),
    stashPop: () => gitStashPop(workDir),
    stashList: () => gitStashList(workDir),
    stashApply: (ref: string) => gitStashApply(workDir, ref),
    stashDrop: (ref: string) => gitStashDrop(workDir, ref),
    cherryPick: (hash: string) => gitCherryPick(workDir, hash),
    revert: (hash: string) => gitRevert(workDir, hash),
  };
}
