//! Generated by tsz compiler — d128_tool_lifecycle [maps.zig]
//! Source: d128_tool_lifecycle.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const nodes = @import("nodes.zig");
const st = @import("state.zig");

// [origin:d128_tool_lifecycle:maps]
// ── Map pools ───────────────────────────────────────────────────
pub var _pool_arena: std.heap.ArenaAllocator = std.heap.ArenaAllocator.init(std.heap.page_allocator);
pub const MAX_MAP_0: usize = 4096;
pub var _map_pool_0: []Node = std.mem.zeroes([]Node);
pub var _map_count_0: usize = 0;
pub var _map_text_bufs_0_6: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_6: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_0: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_1: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_2: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_2: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_3: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_3: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_4: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_4: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_lua_bufs_0_0: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_0: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_0() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_0[_i][0..47], "__mapPress_0_0({d})", .{_i}) catch continue;
        _map_lua_bufs_0_0[_i][n.len] = 0;
        _map_lua_ptrs_0_0[_i] = @ptrCast(_map_lua_bufs_0_0[_i][0..n.len :0]);
    }
}
pub var _map_lua_bufs_0_1: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_1: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_1() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_1[_i][0..47], "__mapPress_0_1({d})", .{_i}) catch continue;
        _map_lua_bufs_0_1[_i][n.len] = 0;
        _map_lua_ptrs_0_1[_i] = @ptrCast(_map_lua_bufs_0_1[_i][0..n.len :0]);
    }
}
pub var _map_lua_bufs_0_2: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_2: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_2() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_2[_i][0..47], "__mapPress_0_2({d})", .{_i}) catch continue;
        _map_lua_bufs_0_2[_i][n.len] = 0;
        _map_lua_ptrs_0_2[_i] = @ptrCast(_map_lua_bufs_0_2[_i][0..n.len :0]);
    }
}
pub var _map_lua_bufs_0_3: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_3: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_3() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_3[_i][0..47], "__mapPress_0_3({d})", .{_i}) catch continue;
        _map_lua_bufs_0_3[_i][n.len] = 0;
        _map_lua_ptrs_0_3[_i] = @ptrCast(_map_lua_bufs_0_3[_i][0..n.len :0]);
    }
}
pub var _map_lua_bufs_0_4: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_4: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_4() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_4[_i][0..47], "__mapPress_0_4({d})", .{_i}) catch continue;
        _map_lua_bufs_0_4[_i][n.len] = 0;
        _map_lua_ptrs_0_4[_i] = @ptrCast(_map_lua_bufs_0_4[_i][0..n.len :0]);
    }
}
pub var _map_lua_bufs_0_5: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_5: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_5() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_5[_i][0..47], "__mapPress_0_5({d})", .{_i}) catch continue;
        _map_lua_bufs_0_5[_i][n.len] = 0;
        _map_lua_ptrs_0_5[_i] = @ptrCast(_map_lua_bufs_0_5[_i][0..n.len :0]);
    }
}
pub var _map_lua_bufs_0_6: [MAX_MAP_0][48]u8 = std.mem.zeroes([MAX_MAP_0][48]u8);
pub var _map_lua_ptrs_0_6: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
pub fn _initMapLuaPtrs0_6() void {
    for (0..MAX_MAP_0) |_i| {
        const n = std.fmt.bufPrint(_map_lua_bufs_0_6[_i][0..47], "__mapPress_0_6({d})", .{_i}) catch continue;
        _map_lua_bufs_0_6[_i][n.len] = 0;
        _map_lua_ptrs_0_6[_i] = @ptrCast(_map_lua_bufs_0_6[_i][0..n.len :0]);
    }
}
// [origin:d128_tool_lifecycle:map:_rebuildMap0]
pub fn _rebuildMap0() void {
    _map_count_0 = @min(st._oa0_len, MAX_MAP_0);
    _map_pool_0 = _pool_arena.allocator().alloc(Node, _map_count_0) catch unreachable;
    for (0.._map_count_0) |_i| {
        _map_texts_0_6[_i] = std.fmt.bufPrint(&_map_text_bufs_0_6[_i], "{s}", .{ state.getSlotString(9) }) catch "";
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ st._oa0_name[_i][0..st._oa0_name_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{s}", .{ st._oa0_cmd[_i][0..st._oa0_cmd_lens[_i]] }) catch "";
        _map_texts_0_2[_i] = std.fmt.bufPrint(&_map_text_bufs_0_2[_i], "Running {d}%", .{ st._oa0_progress[_i] }) catch "";
        _map_texts_0_3[_i] = std.fmt.bufPrint(&_map_text_bufs_0_3[_i], "{s}", .{ st._oa0_output[_i][0..st._oa0_output_lens[_i]] }) catch "";
        _map_texts_0_4[_i] = std.fmt.bufPrint(&_map_text_bufs_0_4[_i], "{d}ms", .{ st._oa0_duration[_i] }) catch "";
        const _pi__arr_11_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_11_0, &[_]Node{ .{ .text = _map_texts_0_6[_i], .font_size = 8, .text_color = Color.rgb(255, 255, 255) } });
        const _pi__arr_12_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_12_0, &[_]Node{ .{ .text = _map_texts_0_0[_i], .font_size = 10, .text_color = Color.rgb(226, 232, 240) }, .{ .text = _map_texts_0_1[_i], .font_size = 8, .text_color = Color.rgb(71, 85, 105) } });
        const _pi__arr_13_0 = _pool_arena.allocator().alloc(Node, 6) catch unreachable;
        @memcpy(_pi__arr_13_0, &[_]Node{ .{ .style = .{ .width = 8, .height = 8, .border_radius = 4, .background_color = if (st._oa0_state[_i] == 0) Color.rgb(71, 85, 105) else if (st._oa0_state[_i] == 1) Color.rgb(245, 158, 11) else if (st._oa0_state[_i] == 2) Color.rgb(59, 130, 246) else if (st._oa0_state[_i] == 3) Color.rgb(34, 197, 94) else Color.rgb(239, 68, 68) } }, .{ .text = "Queued", .font_size = 8, .text_color = Color.rgb(71, 85, 105) }, .{ .text = "Awaiting Permission", .font_size = 8, .text_color = Color.rgb(245, 158, 11) }, .{ .text = _map_texts_0_2[_i], .font_size = 8, .text_color = Color.rgb(59, 130, 246) }, .{ .text = "Complete", .font_size = 8, .text_color = Color.rgb(34, 197, 94) }, .{ .text = "Error", .font_size = 8, .text_color = Color.rgb(239, 68, 68) } });
        const _pi__arr_14_0 = _pool_arena.allocator().alloc(Node, 3) catch unreachable;
        @memcpy(_pi__arr_14_0, &[_]Node{ .{ .style = .{ .width = 20, .height = 20, .border_radius = 4, .background_color = if (std.mem.eql(u8, st._oa0_type[_i][0..st._oa0_type_lens[_i]], "bash")) Color.rgb(30, 64, 175) else if (std.mem.eql(u8, st._oa0_type[_i][0..st._oa0_type_lens[_i]], "read")) Color.rgb(6, 95, 70) else if (std.mem.eql(u8, st._oa0_type[_i][0..st._oa0_type_lens[_i]], "edit")) Color.rgb(124, 45, 18) else Color.rgb(74, 29, 150), .align_items = .center, .justify_content = .center, .overflow = .auto }, .children = _pi__arr_11_0 }, .{ .style = .{ .flex_grow = 1, .gap = 2, .overflow = .auto }, .children = _pi__arr_12_0 }, .{ .style = .{ .flex_direction = .row, .gap = 4, .align_items = .center }, .children = _pi__arr_13_0 } });
        const _pi__arr_15_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_15_0, &[_]Node{ .{ .text = "Allow", .font_size = 8, .text_color = Color.rgb(255, 255, 255) } });
        const _pi__arr_16_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_16_0, &[_]Node{ .{ .text = "Deny", .font_size = 8, .text_color = Color.rgb(255, 255, 255) } });
        const _pi__arr_17_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_17_0, &[_]Node{ .{ .style = .{ .padding_left = 8, .padding_right = 8, .padding_top = 4, .padding_bottom = 4, .background_color = Color.rgb(34, 197, 94), .border_radius = 4 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_1[_i] }, .children = _pi__arr_15_0 }, .{ .style = .{ .padding_left = 8, .padding_right = 8, .padding_top = 4, .padding_bottom = 4, .background_color = Color.rgb(239, 68, 68), .border_radius = 4 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_2[_i] }, .children = _pi__arr_16_0 } });
        const _pi__arr_18_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_18_0, &[_]Node{ .{ .style = .{ .height = 4, .border_radius = 2, .background_color = Color.rgb(59, 130, 246), .width = @as(f32, @floatFromInt(st._oa0_progress[_i])) } } });
        const _pi__arr_19_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_19_0, &[_]Node{ .{ .text = "Advance", .font_size = 8, .text_color = Color.rgb(255, 255, 255) } });
        const _pi__arr_20_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_20_0, &[_]Node{ .{ .text = "Fail", .font_size = 8, .text_color = Color.rgb(255, 255, 255) } });
        const _pi__arr_21_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_21_0, &[_]Node{ .{ .text = "Timeout", .font_size = 8, .text_color = Color.rgb(255, 255, 255) } });
        const _pi__arr_22_0 = _pool_arena.allocator().alloc(Node, 3) catch unreachable;
        @memcpy(_pi__arr_22_0, &[_]Node{ .{ .style = .{ .padding_left = 8, .padding_right = 8, .padding_top = 4, .padding_bottom = 4, .background_color = Color.rgb(59, 130, 246), .border_radius = 4 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_3[_i] }, .children = _pi__arr_19_0 }, .{ .style = .{ .padding_left = 8, .padding_right = 8, .padding_top = 4, .padding_bottom = 4, .background_color = Color.rgb(220, 38, 38), .border_radius = 4 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_4[_i] }, .children = _pi__arr_20_0 }, .{ .style = .{ .padding_left = 8, .padding_right = 8, .padding_top = 4, .padding_bottom = 4, .background_color = Color.rgb(146, 64, 14), .border_radius = 4 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_5[_i] }, .children = _pi__arr_21_0 } });
        const _pi__arr_23_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_23_0, &[_]Node{ .{ .style = .{ .height = 4, .background_color = Color.rgb(30, 41, 59), .border_radius = 2, .flex_grow = 1, .overflow = .auto }, .children = _pi__arr_18_0 }, .{ .style = .{ .flex_direction = .row, .gap = 6, .justify_content = .end }, .children = _pi__arr_22_0 } });
        const _pi__arr_24_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_24_0, &[_]Node{ .{ .text = "Run", .font_size = 8, .text_color = Color.rgb(148, 163, 184) } });
        const _pi__arr_25_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_25_0, &[_]Node{ .{ .style = .{ .padding_left = 8, .padding_right = 8, .padding_top = 4, .padding_bottom = 4, .background_color = Color.rgb(51, 65, 85), .border_radius = 4 }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_6[_i] }, .children = _pi__arr_24_0 } });
        const _pi__arr_26_0 = _pool_arena.allocator().alloc(Node, 5) catch unreachable;
        @memcpy(_pi__arr_26_0, &[_]Node{ .{ .text = _map_texts_0_3[_i], .font_size = 8, .text_color = if (st._oa0_state[_i] == 4) Color.rgb(252, 165, 165) else Color.rgb(148, 163, 184) }, .{ .text = "timeout", .font_size = 7, .text_color = Color.rgb(146, 64, 14) }, .{ .text = "rejected", .font_size = 7, .text_color = Color.rgb(239, 68, 68) }, .{ .text = "crashed", .font_size = 7, .text_color = Color.rgb(220, 38, 38) }, .{ .text = _map_texts_0_4[_i], .font_size = 7, .text_color = Color.rgb(71, 85, 105) } });
        const _pi__arr_27_0 = _pool_arena.allocator().alloc(Node, 5) catch unreachable;
        @memcpy(_pi__arr_27_0, &[_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 8, .align_items = .center }, .children = _pi__arr_14_0 }, .{ .style = .{ .flex_direction = .row, .gap = 6, .justify_content = .end }, .children = _pi__arr_17_0 }, .{ .style = .{ .gap = 4 }, .children = _pi__arr_23_0 }, .{ .style = .{ .flex_direction = .row, .justify_content = .end }, .children = _pi__arr_25_0 }, .{ .style = .{ .padding = 6, .background_color = Color.rgb(15, 23, 42), .border_radius = 4 }, .children = _pi__arr_26_0 } });
        _pi__arr_13_0[1].style.display = if (st._oa0_state[_i] ==  0) .flex else .none;
        _pi__arr_13_0[2].style.display = if (st._oa0_state[_i] ==  1) .flex else .none;
        _pi__arr_13_0[3].style.display = if (st._oa0_state[_i] ==  2) .flex else .none;
        _pi__arr_13_0[4].style.display = if (st._oa0_state[_i] ==  3) .flex else .none;
        _pi__arr_13_0[5].style.display = if (st._oa0_state[_i] ==  4) .flex else .none;
        _pi__arr_27_0[1].style.display = if (st._oa0_state[_i] ==  1) .flex else .none;
        _pi__arr_27_0[2].style.display = if (st._oa0_state[_i] ==  2) .flex else .none;
        _pi__arr_27_0[3].style.display = if (st._oa0_state[_i] ==  0) .flex else .none;
        _pi__arr_26_0[1].style.display = if (st._oa0_state[_i] ==  4 and st._oa0_errorType[_i] ==  0) .flex else .none;
        _pi__arr_26_0[2].style.display = if (st._oa0_state[_i] ==  4 and st._oa0_errorType[_i] ==  1) .flex else .none;
        _pi__arr_26_0[3].style.display = if (st._oa0_state[_i] ==  4 and st._oa0_errorType[_i] ==  2) .flex else .none;
        _pi__arr_26_0[4].style.display = if (st._oa0_duration[_i] >  0) .flex else .none;
        _pi__arr_27_0[4].style.display = if (st._oa0_expanded[_i] ==  1 and st._oa0_output[_i].len > 0) .flex else .none;
        const _inner_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_inner_0, &[_]Node{ .{ .style = .{ .padding = 10, .background_color = if (state.getSlot(4) == @as(i64, @intCast(_i))) Color.rgb(51, 65, 85) else Color.rgb(30, 41, 59), .border_radius = 8, .gap = 6, .border_width = if (st._oa0_state[_i] == 4) @as(f32, 1) else @as(f32, 0), .border_color = Color.rgb(239, 68, 68) }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_0[_i] }, .children = _pi__arr_27_0 } });
        _inner_0[0].style.display = if ((state.getSlot(8) ==  5 or state.getSlot(8) == st._oa0_state[_i])) .flex else .none;
        _map_pool_0[_i] = .{ .style = .{}, .children = _inner_0 };
        _map_pool_0[_i].style.display = _inner_0[0].style.display;
    }
    nodes._arr_29[0].children = _map_pool_0[0.._map_count_0];
}


