//! Generated by tsz compiler — 43_stretch_explicit_height [nodes.zig]
//! Source: 43_stretch_explicit_height.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:43_stretch_explicit_height:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:43_stretch_explicit_height.tsz:9 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "no h" } };
// tsz:43_stretch_explicit_height.tsz:12 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "no h" } };
// tsz:43_stretch_explicit_height.tsz:8 — <Box>
pub var _arr_2 = [_]Node{ .{ .style = .{ .width = 60, .background_color = Color.rgb(76, 175, 80) }, .children = &_arr_0 }, .{ .style = .{ .width = 60, .background_color = Color.rgb(33, 150, 243) }, .children = &_arr_1 } };
// tsz:43_stretch_explicit_height.tsz:19 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "h:30" } };
// tsz:43_stretch_explicit_height.tsz:22 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "h:50" } };
// tsz:43_stretch_explicit_height.tsz:25 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "stretch" } };
// tsz:43_stretch_explicit_height.tsz:18 — <Box>
pub var _arr_6 = [_]Node{ .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_3 }, .{ .style = .{ .width = 60, .height = 50, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_4 }, .{ .style = .{ .width = 60, .background_color = Color.rgb(255, 152, 0) }, .children = &_arr_5 } };
// tsz:43_stretch_explicit_height.tsz:32 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "no w = full" } };
// tsz:43_stretch_explicit_height.tsz:35 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "w:80" } };
// tsz:43_stretch_explicit_height.tsz:38 — <Box>
pub var _arr_9 = [_]Node{ .{ .text = "no w = full" } };
// tsz:43_stretch_explicit_height.tsz:31 — <Box>
pub var _arr_10 = [_]Node{ .{ .style = .{ .height = 30, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_7 }, .{ .style = .{ .height = 30, .width = 80, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_8 }, .{ .style = .{ .height = 30, .background_color = Color.rgb(255, 152, 0), .overflow = .auto }, .children = &_arr_9 } };
// tsz:43_stretch_explicit_height.tsz:45 — <Box>
pub var _arr_11 = [_]Node{ .{ .text = "start" } };
// tsz:43_stretch_explicit_height.tsz:48 — <Box>
pub var _arr_12 = [_]Node{ .{ .text = "stretch" } };
// tsz:43_stretch_explicit_height.tsz:51 — <Box>
pub var _arr_13 = [_]Node{ .{ .text = "start" } };
// tsz:43_stretch_explicit_height.tsz:44 — <Box>
pub var _arr_14 = [_]Node{ .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_11 }, .{ .style = .{ .width = 60, .background_color = Color.rgb(33, 150, 243), .align_self = .stretch }, .children = &_arr_12 }, .{ .style = .{ .width = 60, .height = 40, .background_color = Color.rgb(255, 152, 0), .overflow = .auto }, .children = &_arr_13 } };
// tsz:43_stretch_explicit_height.tsz:3 — <Box>
pub var _arr_15 = [_]Node{ .{ .text = "WPT: stretch vs explicit height" }, .{ .text = "VERIFY: Items WITHOUT height stretch, items WITH height do NOT stretch", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "alignItems:stretch — items WITHOUT height stretch to fill" }, .{ .style = .{ .flex_direction = .row, .align_items = .stretch, .width = 300, .height = 80, .background_color = Color.rgb(51, 51, 51), .gap = 4, .overflow = .auto }, .children = &_arr_2 }, .{ .text = "Items WITH explicit height should NOT stretch" }, .{ .style = .{ .flex_direction = .row, .align_items = .stretch, .width = 300, .height = 80, .background_color = Color.rgb(51, 51, 51), .gap = 4, .overflow = .auto }, .children = &_arr_6 }, .{ .text = "Column stretch — items WITHOUT width stretch to fill" }, .{ .style = .{ .flex_direction = .column, .align_items = .stretch, .width = 200, .height = 120, .background_color = Color.rgb(51, 51, 51), .gap = 4, .overflow = .auto }, .children = &_arr_10 }, .{ .text = "alignSelf:stretch on one item, others start" }, .{ .style = .{ .flex_direction = .row, .align_items = .start, .width = 300, .height = 80, .background_color = Color.rgb(51, 51, 51), .gap = 4, .overflow = .auto }, .children = &_arr_14 } };
// [origin:43_stretch_explicit_height:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 8, .overflow = .hidden }, .children = &_arr_15 };

