//! Generated by tsz compiler — 25_grow_shrink_column [state.zig]
//! Source: 25_grow_shrink_column.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

pub fn _initState() void {
}

