//! Generated by tsz compiler — s01b_counter [state.zig]
//! Source: s01b_counter.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:s01b_counter:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: count (int)
// slot 1: __jsExpr_1 (string)
comptime { if (2 != 2) @compileError("state slot count mismatch"); }

// [origin:s01b_counter:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [256]u8 = std.mem.zeroes([256]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_1: []const u8 = "";

pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlotString("");
}

