//! Generated by tsz compiler — 23_deep_nesting [logic.zig]
//! Source: 23_deep_nesting.tsz


// [origin:23_deep_nesting:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\
;

// [origin:23_deep_nesting:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

