//! Generated by tsz compiler — s06b_kanban [nodes.zig]
//! Source: s06b_kanban.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:s06b_kanban:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:s06b_kanban.tsz:53 — <Box>
pub var _arr_9 = [_]Node{ .{ .style = .{ .flex_direction = .row, .gap = 12 } } };
// tsz:s06b_kanban.tsz:51 — <Box>
pub var _arr_10 = [_]Node{ .{ .text = "Kanban Board", .font_size = 18, .text_color = Color.rgb(226, 232, 240) }, .{ .style = .{ .flex_direction = .row, .gap = 12, .flex_grow = 1, .overflow = .auto }, .children = &_arr_9 } };
pub var _arr_4 = [_]Node{ .{} };
// [origin:s06b_kanban:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(15, 23, 42), .width = -1, .height = -1, .padding = 16, .gap = 12, .overflow = .hidden }, .children = &_arr_10 };
