--[[
  managed_effects.lua — Lua-side effect lifecycle manager

  Replaces React's useEffect by managing effect lifecycles in love.update(dt).
  React hooks register/update/unregister effects via RPC; Lua owns the timing.

  Why this exists:
    React's useEffect runs in the commit phase — async, batched, not frame-synced.
    In ReactJIT, ALL side effects should run in Lua's love.update(dt) loop for
    frame-perfect timing and zero JS event loop jitter. Every setInterval,
    setTimeout, and subscription effect that lived in JS now lives here.

  Supported effect types:
    timer     — Accumulate dt, push event at interval (replaces setInterval)
    poll      — Signal React to re-fetch at interval (replaces polling patterns)
    tick      — Per-frame event with dt (replaces requestAnimationFrame patterns)
    mount     — Fire once on register (replaces useEffect(() => {...}, []))

  Usage from React (via useLuaEffect hook):
    bridge.rpc('effect:register', { id, type, config })
    bridge.rpc('effect:update',   { id, config, deps })
    bridge.rpc('effect:cleanup',  { id })
]]

local ManagedEffects = {}

-- Active effects: id -> { type, config, state }
local active = {}

-- ============================================================================
-- Effect type implementations
-- ============================================================================

local types = {}

-- Timer: accumulate dt, push event at interval
types.timer = {
  setup = function(id, config)
    return { elapsed = 0, count = 0 }
  end,
  tick = function(id, state, dt, pushEvent, config)
    local interval = (config.interval or 1000) / 1000  -- ms -> seconds
    if interval <= 0 then return end
    state.elapsed = state.elapsed + dt
    while state.elapsed >= interval do
      state.elapsed = state.elapsed - interval
      state.count = state.count + 1
      pushEvent({ type = "effect:" .. id, payload = { count = state.count } })
    end
  end,
  cleanup = function(id, state) end,
}

-- Poll: signal React to re-fetch at interval
types.poll = {
  setup = function(id, config)
    return { elapsed = 999999 }  -- fire immediately on first tick
  end,
  tick = function(id, state, dt, pushEvent, config)
    local interval = (config.interval or 5000) / 1000
    if interval <= 0 then return end
    state.elapsed = state.elapsed + dt
    if state.elapsed >= interval then
      state.elapsed = 0
      pushEvent({ type = "effect:" .. id, payload = { poll = true } })
    end
  end,
  cleanup = function(id, state) end,
}

-- Tick: per-frame event with dt
types.tick = {
  setup = function(id, config)
    return { frame = 0 }
  end,
  tick = function(id, state, dt, pushEvent, config)
    state.frame = state.frame + 1
    local every = config.every or 1
    if state.frame % every == 0 then
      pushEvent({ type = "effect:" .. id, payload = { dt = dt, frame = state.frame } })
    end
  end,
  cleanup = function(id, state) end,
}

-- Mount: fire setup event once, no per-frame work
types.mount = {
  setup = function(id, config)
    return {}
  end,
  tick = function(id, state, dt, pushEvent, config)
    -- no per-frame work
  end,
  cleanup = function(id, state) end,
}

-- ============================================================================
-- Public API (called from RPC handlers in init.lua)
-- ============================================================================

--- Register a new effect.
--- @param id string          Unique effect ID (generated by React hook)
--- @param effectType string  One of: timer, poll, tick, mount
--- @param config table       Type-specific configuration
--- @param pushEvent function Bridge event pusher
--- @return boolean success
function ManagedEffects.register(id, effectType, config, pushEvent)
  -- Cleanup existing effect with same ID (re-register)
  if active[id] then
    ManagedEffects.cleanup(id)
  end

  local impl = types[effectType]
  if not impl then
    io.write("[managed_effects] WARNING: unknown effect type '" .. tostring(effectType) .. "'\n")
    io.flush()
    return false
  end

  local state = impl.setup(id, config or {}) or {}
  active[id] = {
    type = effectType,
    impl = impl,
    config = config or {},
    state = state,
  }
  return true
end

--- Update an effect's config. Cleanup + re-setup.
--- @param id string
--- @param config table  New config
--- @param pushEvent function
function ManagedEffects.update(id, config, pushEvent)
  local eff = active[id]
  if not eff then return false end

  -- Full re-setup with new config
  eff.impl.cleanup(id, eff.state)
  local newConfig = config or eff.config
  local newState = eff.impl.setup(id, newConfig) or {}
  eff.config = newConfig
  eff.state = newState
  return true
end

--- Cleanup and remove an effect.
--- @param id string
function ManagedEffects.cleanup(id)
  local eff = active[id]
  if not eff then return end
  eff.impl.cleanup(id, eff.state)
  active[id] = nil
end

--- Per-frame tick. Called from love.update(dt) in init.lua.
--- @param dt number       Delta time
--- @param pushEvent function  Bridge event pusher
function ManagedEffects.tick(dt, pushEvent)
  for id, eff in pairs(active) do
    eff.impl.tick(id, eff.state, dt, pushEvent, eff.config)
  end
end

--- Return count of active effects (for diagnostics).
function ManagedEffects.count()
  local n = 0
  for _ in pairs(active) do n = n + 1 end
  return n
end

return ManagedEffects
