//! Generated by tsz compiler — d57_children_prop [logic.zig]
//! Source: d57_children_prop.tsz


// [origin:d57_children_prop:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\
;

// [origin:d57_children_prop:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

