//! Generated by tsz compiler — d57_children_prop [state.zig]
//! Source: d57_children_prop.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d57_children_prop:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: theme (int)
// slot 1: taps (int)
comptime { if (2 != 2) @compileError("state slot count mismatch"); }

// [origin:d57_children_prop:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_1: []const u8 = "";

pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

