//! Generated by tsz compiler — l06b_http_client [handlers.zig]
//! Source: l06b_http_client.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:l06b_http_client:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:l06b_http_client:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobal("demoGet");
}

// [origin:l06b_http_client:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobal("demoPost");
}

// [origin:l06b_http_client:handler:_handler_press_2]
pub fn _handler_press_2() void {
    qjs_runtime.callGlobal("demoPut");
}

// [origin:l06b_http_client:handler:_handler_press_3]
pub fn _handler_press_3() void {
    qjs_runtime.callGlobal("demoDel");
}

// [origin:l06b_http_client:handler:_handler_press_4]
pub fn _handler_press_4() void {
    qjs_runtime.callGlobal("clearLog");
}

