//! Generated by tsz compiler — 61_tw_layout [state.zig]
//! Source: 61_tw_layout.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

pub fn _initState() void {
}

