//! Generated by tsz compiler — d62_negative_numbers [maps.zig]
//! Source: d62_negative_numbers.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const nodes = @import("nodes.zig");
const st = @import("state.zig");

// [origin:d62_negative_numbers:maps]
// ── Map pools ───────────────────────────────────────────────────
pub var _pool_arena: std.heap.ArenaAllocator = std.heap.ArenaAllocator.init(std.heap.page_allocator);
pub const MAX_MAP_0: usize = 4096;
pub var _map_pool_0: []Node = std.mem.zeroes([]Node);
pub var _map_count_0: usize = 0;
pub var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_0: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_1: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
// [origin:d62_negative_numbers:map:_rebuildMap0]
pub fn _rebuildMap0() void {
    _map_count_0 = @min(st._oa0_len, MAX_MAP_0);
    _map_pool_0 = _pool_arena.allocator().alloc(Node, _map_count_0) catch unreachable;
    for (0.._map_count_0) |_i| {
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ st._oa0_label[_i][0..st._oa0_label_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{d}", .{ st._oa0_amount[_i] }) catch "";
        const _inner_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_inner_0, &[_]Node{ .{ .text = _map_texts_0_0[_i], .font_size = 11, .text_color = Color.rgb(226, 232, 240) }, .{ .text = _map_texts_0_1[_i], .font_size = 11, .text_color = if (st._oa0_amount[_i] >= 0) Color.rgb(34, 197, 94) else Color.rgb(239, 68, 68) } });
        _map_pool_0[_i] = .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .padding = 8, .background_color = Color{} }, .children = _inner_0 };
    }
    nodes._arr_5[0].children = _map_pool_0[0.._map_count_0];
}


