//! Generated by tsz compiler — horizontal_bar_chart [nodes.zig]
//! Source: horizontal_bar_chart.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:horizontal_bar_chart:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:horizontal_bar_chart.tsz:15 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "Jan", .text_color = Color.rgb(139, 148, 158), .font_size = 11 } };
// tsz:horizontal_bar_chart.tsz:14 — <Box>
pub var _arr_1 = [_]Node{ .{ .style = .{ .align_items = .end, .width = 36 }, .children = &_arr_0 }, .{ .style = .{ .width = 149, .height = 16, .background_color = Color.rgb(59, 130, 246), .border_radius = 3 } }, .{ .text = "42", .text_color = Color.rgb(148, 163, 184), .font_size = 10 } };
// tsz:horizontal_bar_chart.tsz:20 — <Box>
pub var _arr_2 = [_]Node{ .{ .text = "Feb", .text_color = Color.rgb(139, 148, 158), .font_size = 11 } };
// tsz:horizontal_bar_chart.tsz:19 — <Box>
pub var _arr_3 = [_]Node{ .{ .style = .{ .align_items = .end, .width = 36 }, .children = &_arr_2 }, .{ .style = .{ .width = 277, .height = 16, .background_color = Color.rgb(59, 130, 246), .border_radius = 3 } }, .{ .text = "78", .text_color = Color.rgb(148, 163, 184), .font_size = 10 } };
// tsz:horizontal_bar_chart.tsz:25 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "Mar", .text_color = Color.rgb(139, 148, 158), .font_size = 11 } };
// tsz:horizontal_bar_chart.tsz:24 — <Box>
pub var _arr_5 = [_]Node{ .{ .style = .{ .align_items = .end, .width = 36 }, .children = &_arr_4 }, .{ .style = .{ .width = 196, .height = 16, .background_color = Color.rgb(59, 130, 246), .border_radius = 3 } }, .{ .text = "55", .text_color = Color.rgb(148, 163, 184), .font_size = 10 } };
// tsz:horizontal_bar_chart.tsz:30 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "Apr", .text_color = Color.rgb(139, 148, 158), .font_size = 11 } };
// tsz:horizontal_bar_chart.tsz:29 — <Box>
pub var _arr_7 = [_]Node{ .{ .style = .{ .align_items = .end, .width = 36 }, .children = &_arr_6 }, .{ .style = .{ .width = 320, .height = 16, .background_color = Color.rgb(96, 165, 250), .border_radius = 3 } }, .{ .text = "90", .text_color = Color.rgb(148, 163, 184), .font_size = 10 } };
// tsz:horizontal_bar_chart.tsz:35 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "May", .text_color = Color.rgb(139, 148, 158), .font_size = 11 } };
// tsz:horizontal_bar_chart.tsz:34 — <Box>
pub var _arr_9 = [_]Node{ .{ .style = .{ .align_items = .end, .width = 36 }, .children = &_arr_8 }, .{ .style = .{ .width = 124, .height = 16, .background_color = Color.rgb(59, 130, 246), .border_radius = 3 } }, .{ .text = "35", .text_color = Color.rgb(148, 163, 184), .font_size = 10 } };
// tsz:horizontal_bar_chart.tsz:40 — <Box>
pub var _arr_10 = [_]Node{ .{ .text = "Jun", .text_color = Color.rgb(139, 148, 158), .font_size = 11 } };
// tsz:horizontal_bar_chart.tsz:39 — <Box>
pub var _arr_11 = [_]Node{ .{ .style = .{ .align_items = .end, .width = 36 }, .children = &_arr_10 }, .{ .style = .{ .width = 238, .height = 16, .background_color = Color.rgb(59, 130, 246), .border_radius = 3 } }, .{ .text = "67", .text_color = Color.rgb(148, 163, 184), .font_size = 10 } };
// tsz:horizontal_bar_chart.tsz:45 — <Box>
pub var _arr_12 = [_]Node{ .{ .text = "Jul", .text_color = Color.rgb(139, 148, 158), .font_size = 11 } };
// tsz:horizontal_bar_chart.tsz:44 — <Box>
pub var _arr_13 = [_]Node{ .{ .style = .{ .align_items = .end, .width = 36 }, .children = &_arr_12 }, .{ .style = .{ .width = 292, .height = 16, .background_color = Color.rgb(59, 130, 246), .border_radius = 3 } }, .{ .text = "82", .text_color = Color.rgb(148, 163, 184), .font_size = 10 } };
// tsz:horizontal_bar_chart.tsz:13 — <Box>
pub var _arr_14 = [_]Node{ .{ .style = .{ .height = 24, .gap = 8, .align_items = .center, .flex_direction = .row, .overflow = .auto }, .children = &_arr_1 }, .{ .style = .{ .height = 24, .gap = 8, .align_items = .center, .flex_direction = .row, .overflow = .auto }, .children = &_arr_3 }, .{ .style = .{ .height = 24, .gap = 8, .align_items = .center, .flex_direction = .row, .overflow = .auto }, .children = &_arr_5 }, .{ .style = .{ .height = 24, .gap = 8, .align_items = .center, .flex_direction = .row, .overflow = .auto }, .children = &_arr_7 }, .{ .style = .{ .height = 24, .gap = 8, .align_items = .center, .flex_direction = .row, .overflow = .auto }, .children = &_arr_9 }, .{ .style = .{ .height = 24, .gap = 8, .align_items = .center, .flex_direction = .row, .overflow = .auto }, .children = &_arr_11 }, .{ .style = .{ .height = 24, .gap = 8, .align_items = .center, .flex_direction = .row, .overflow = .auto }, .children = &_arr_13 } };
// tsz:horizontal_bar_chart.tsz:12 — <Box>
pub var _arr_15 = [_]Node{ .{ .style = .{ .flex_grow = 1, .gap = 6, .flex_direction = .column, .overflow = .auto }, .children = &_arr_14 } };
// tsz:horizontal_bar_chart.tsz:8 — <Box>
pub var _arr_16 = [_]Node{ .{ .text = "Horizontal Bar Chart", .text_color = Color.rgb(230, 237, 243), .font_size = 20 }, .{ .text = "Monthly revenue — horizontal bars, label-aligned, flex layout", .text_color = Color.rgb(139, 148, 158), .font_size = 12 }, .{ .style = .{ .gap = 8, .padding = 16, .border_color = Color.rgb(48, 54, 61), .border_width = 1, .border_radius = 8, .background_color = Color.rgb(22, 27, 34), .flex_direction = .column, .flex_grow = 1, .overflow = .auto }, .children = &_arr_15 } };
// [origin:horizontal_bar_chart:root]
pub var _root = Node{ .style = .{ .gap = 12, .padding = 24, .background_color = Color.rgb(13, 17, 23), .height = -1, .width = -1, .flex_direction = .column, .overflow = .hidden }, .children = &_arr_16 };

