//! Generated by tsz compiler — d61_map_ternary_branch [state.zig]
//! Source: d61_map_ternary_branch.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d61_map_ternary_branch:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: mode (int)
// slot 1: taps (int)
comptime { if (2 != 2) @compileError("state slot count mismatch"); }

// [origin:d61_map_ternary_branch:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";

pub const qjs = @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
pub const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// [origin:d61_map_ternary_branch:state]
// ── Object arrays ───────────────────────────────────────────────
pub const _oa_alloc = std.heap.page_allocator;

pub fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

pub fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

pub var _oa0_name: [][]const u8 = &[_][]const u8{};
pub var _oa0_name_lens: []usize = &[_]usize{};
pub var _oa0_name_cap: usize = 0;
pub var _oa0_size: []i64 = &[_]i64{};
pub var _oa0_size_cap: usize = 0;
pub var _oa0_len: usize = 0;
pub var _oa0_dirty: bool = false;

pub fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_name_cap) return;
    const new_cap = @max(needed, if (_oa0_name_cap == 0) @as(usize, 64) else _oa0_name_cap * 2);
    if (_oa0_name_cap == 0) {
        _oa0_name = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_name_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens, 0);
    } else {
        const _old_cap = _oa0_name_cap;
        _oa0_name = _oa_alloc.realloc(_oa0_name.ptr[0.._old_cap], new_cap) catch return;
        _oa0_name_lens = _oa_alloc.realloc(_oa0_name_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_name[_j] = &[_]u8{};
        @memset(_oa0_name_lens[_old_cap..new_cap], 0);
    }
    _oa0_name_cap = new_cap;
    if (_oa0_size_cap == 0) {
        _oa0_size = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_size, 0);
    } else {
        _oa0_size = _oa_alloc.realloc(_oa0_size.ptr[0.._oa0_size_cap], new_cap) catch return;
        @memset(_oa0_size[_oa0_size_cap..new_cap], 0);
    }
    _oa0_size_cap = new_cap;
}

// [origin:d61_map_ternary_branch:oa:_oa0_unpack]
pub fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "name");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_name[_i], &_oa0_name_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_name[_i] = _oaDupString(sl); _oa0_name_lens[_i] = _oa0_name[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "size");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_size[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa0_len) {
        for (count.._oa0_len) |_trim_i| _oaFreeString(&_oa0_name[_trim_i], &_oa0_name_lens[_trim_i]);
    }
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa1_msg: [][]const u8 = &[_][]const u8{};
pub var _oa1_msg_lens: []usize = &[_]usize{};
pub var _oa1_msg_cap: usize = 0;
pub var _oa1_author: [][]const u8 = &[_][]const u8{};
pub var _oa1_author_lens: []usize = &[_]usize{};
pub var _oa1_author_cap: usize = 0;
pub var _oa1_len: usize = 0;
pub var _oa1_dirty: bool = false;

pub fn _oa1_ensureCapacity(needed: usize) void {
    if (needed <= _oa1_msg_cap) return;
    const new_cap = @max(needed, if (_oa1_msg_cap == 0) @as(usize, 64) else _oa1_msg_cap * 2);
    if (_oa1_msg_cap == 0) {
        _oa1_msg = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_msg_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_msg[_j] = &[_]u8{};
        @memset(_oa1_msg_lens, 0);
    } else {
        const _old_cap = _oa1_msg_cap;
        _oa1_msg = _oa_alloc.realloc(_oa1_msg.ptr[0.._old_cap], new_cap) catch return;
        _oa1_msg_lens = _oa_alloc.realloc(_oa1_msg_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_msg[_j] = &[_]u8{};
        @memset(_oa1_msg_lens[_old_cap..new_cap], 0);
    }
    _oa1_msg_cap = new_cap;
    if (_oa1_author_cap == 0) {
        _oa1_author = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_author_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_author[_j] = &[_]u8{};
        @memset(_oa1_author_lens, 0);
    } else {
        const _old_cap = _oa1_author_cap;
        _oa1_author = _oa_alloc.realloc(_oa1_author.ptr[0.._old_cap], new_cap) catch return;
        _oa1_author_lens = _oa_alloc.realloc(_oa1_author_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_author[_j] = &[_]u8{};
        @memset(_oa1_author_lens[_old_cap..new_cap], 0);
    }
    _oa1_author_cap = new_cap;
}

// [origin:d61_map_ternary_branch:oa:_oa1_unpack]
pub fn _oa1_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa1_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "msg");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_msg[_i], &_oa1_msg_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_msg[_i] = _oaDupString(sl); _oa1_msg_lens[_i] = _oa1_msg[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "author");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_author[_i], &_oa1_author_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_author[_i] = _oaDupString(sl); _oa1_author_lens[_i] = _oa1_author[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa1_len) {
        for (count.._oa1_len) |_trim_i| {
            _oaFreeString(&_oa1_msg[_trim_i], &_oa1_msg_lens[_trim_i]);
            _oaFreeString(&_oa1_author[_trim_i], &_oa1_author_lens[_trim_i]);
        }
    }
    _oa1_len = count;
    _oa1_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa2_name = [_][]const u8{ "index.tsx", "styles.css", "utils.ts", "api.ts" };
pub var _oa2_name_lens = [_]usize{ 9, 10, 8, 6 };
pub var _oa2_size = [_]i64{ 4200, 1800, 920, 3100 };
pub var _oa2_len: usize = 4;
pub var _oa2_dirty: bool = false;

pub var _oa3_msg = [_][]const u8{ "fix auth flow", "add dark mode", "update deps", "perf: lazy load", "docs: api guide" };
pub var _oa3_msg_lens = [_]usize{ 13, 13, 11, 15, 15 };
pub var _oa3_author = [_][]const u8{ "alice", "bob", "carol", "alice", "dave" };
pub var _oa3_author_lens = [_]usize{ 5, 3, 5, 5, 4 };
pub var _oa3_len: usize = 5;
pub var _oa3_dirty: bool = false;


pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
}

