//! Generated by tsz compiler — s04b_dashboard [maps.zig]
//! Source: s04b_dashboard.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const nodes = @import("nodes.zig");
const st = @import("state.zig");

// [origin:s04b_dashboard:maps]
// ── Map pools ───────────────────────────────────────────────────
pub var _pool_arena: std.heap.ArenaAllocator = std.heap.ArenaAllocator.init(std.heap.page_allocator);
pub const MAX_MAP_0: usize = 4096;
pub var _map_pool_0: []Node = std.mem.zeroes([]Node);
pub var _map_count_0: usize = 0;
pub var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_0: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_1: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_2: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_2: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub const MAX_MAP_1: usize = 4096;
pub var _map_pool_1: []Node = std.mem.zeroes([]Node);
pub var _map_count_1: usize = 0;
pub var _map_text_bufs_1_3: [MAX_MAP_1][256]u8 = std.mem.zeroes([MAX_MAP_1][256]u8);
pub var _map_texts_1_3: [MAX_MAP_1][]const u8 = std.mem.zeroes([MAX_MAP_1][]const u8);
pub var _map_text_bufs_1_4: [MAX_MAP_1][256]u8 = std.mem.zeroes([MAX_MAP_1][256]u8);
pub var _map_texts_1_4: [MAX_MAP_1][]const u8 = std.mem.zeroes([MAX_MAP_1][]const u8);
pub var _map_text_bufs_1_5: [MAX_MAP_1][256]u8 = std.mem.zeroes([MAX_MAP_1][256]u8);
pub var _map_texts_1_5: [MAX_MAP_1][]const u8 = std.mem.zeroes([MAX_MAP_1][]const u8);
// [origin:s04b_dashboard:map:_rebuildMap0]
pub fn _rebuildMap0() void {
    _map_count_0 = @min(st._oa0_len, MAX_MAP_0);
    _map_pool_0 = _pool_arena.allocator().alloc(Node, _map_count_0) catch unreachable;
    for (0.._map_count_0) |_i| {
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ st._oa0_name[_i][0..st._oa0_name_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{d}", .{ st._oa0_value[_i] }) catch "";
        _map_texts_0_2[_i] = std.fmt.bufPrint(&_map_text_bufs_0_2[_i], "{s}", .{ st._oa0_change[_i][0..st._oa0_change_lens[_i]] }) catch "";
        const _inner_0 = _pool_arena.allocator().alloc(Node, 3) catch unreachable;
        @memcpy(_inner_0, &[_]Node{ .{ .text = _map_texts_0_0[_i], .font_size = 11, .text_color = Color.rgb(148, 163, 184) }, .{ .text = _map_texts_0_1[_i], .font_size = 24, .text_color = Color.rgb(248, 250, 252) }, .{ .text = _map_texts_0_2[_i], .font_size = 11, .text_color = if (st._oa0_up[_i] == 1) Color.rgb(34, 197, 94) else Color.rgb(239, 68, 68) } });
        _map_pool_0[_i] = .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 10, .padding = 16, .gap = 4, .min_width = 140, .flex_grow = 1, .overflow = .auto }, .children = _inner_0 };
    }
    nodes._arr_1[0].children = _map_pool_0[0.._map_count_0];
}

// [origin:s04b_dashboard:map:_rebuildMap1]
pub fn _rebuildMap1() void {
    _map_count_1 = @min(st._oa1_len, MAX_MAP_1);
    _map_pool_1 = _pool_arena.allocator().alloc(Node, _map_count_1) catch unreachable;
    for (0.._map_count_1) |_i| {
        _map_texts_1_3[_i] = std.fmt.bufPrint(&_map_text_bufs_1_3[_i], "{s}", .{ st._oa1_name[_i][0..st._oa1_name_lens[_i]] }) catch "";
        _map_texts_1_4[_i] = std.fmt.bufPrint(&_map_text_bufs_1_4[_i], "{s}", .{ st._oa1_status[_i][0..st._oa1_status_lens[_i]] }) catch "";
        _map_texts_1_5[_i] = std.fmt.bufPrint(&_map_text_bufs_1_5[_i], "${d}", .{ st._oa1_amount[_i] }) catch "";
        const _pi__arr_2_1 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_2_1, &[_]Node{ .{ .text = _map_texts_1_3[_i], .font_size = 13, .text_color = Color.rgb(226, 232, 240) }, .{ .text = _map_texts_1_4[_i], .font_size = 10, .text_color = if (std.mem.eql(u8, st._oa1_status[_i][0..st._oa1_status_lens[_i]], "Pending")) Color.rgb(245, 158, 11) else Color.rgb(34, 197, 94) } });
        const _inner_1 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_inner_1, &[_]Node{ .{ .style = .{ .gap = 2 }, .children = _pi__arr_2_1 }, .{ .text = _map_texts_1_5[_i], .font_size = 14, .text_color = Color.rgb(248, 250, 252) } });
        _map_pool_1[_i] = .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center, .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 12 }, .children = _inner_1 };
    }
    nodes._arr_4[0].children = _map_pool_1[0.._map_count_1];
}


