//! Module orchestrator for imperative .tsz files.
//!
//! Top-level code generator for .tsz files that have no App function
//! and no JSX — pure imperative TypeScript that compiles to a Zig module.
//!
//! Delegates to:
//!   typegen — enum, interface, type alias declarations
//!   stmtgen — function bodies (control flow, variable declarations)
//!   exprgen — expressions within statements
//!
//! Produces a complete .zig file as output.

const std = @import("std");
const lexer_mod = @import("lexer.zig");
const Lexer = lexer_mod.Lexer;
const Token = lexer_mod.Token;
const TokenKind = lexer_mod.TokenKind;
const typegen = @import("typegen.zig");
const stmtgen = @import("stmtgen.zig");
const exprgen = @import("exprgen.zig");

/// Generate a complete Zig module from an imperative .tsz file.
/// Called instead of codegen.Generator.generate() when the file has
/// no App function and no JSX.
pub fn generate(
    alloc: std.mem.Allocator,
    lex: *const Lexer,
    source: []const u8,
    input_file: []const u8,
) ![]const u8 {
    var out: std.ArrayListUnmanaged(u8) = .{};

    // ── File header ─────────────────────────────────────────────
    try out.appendSlice(alloc, "//! ──── GENERATED FILE — DO NOT EDIT ────\n");
    try out.appendSlice(alloc, "//!\n");
    try out.appendSlice(alloc, try std.fmt.allocPrint(alloc, "//! Source: {s}\n", .{input_file}));
    try out.appendSlice(alloc, "//! Generated by: tsz compile-runtime (imperative mode)\n");
    try out.appendSlice(alloc, "\nconst std = @import(\"std\");\n\n");

    // ── Phase 1: Type declarations ──────────────────────────────
    const type_decls = try typegen.emitTypeDeclarations(alloc, lex, source);
    if (type_decls.len > 0) {
        try out.appendSlice(alloc, "// ── Type definitions ────────────────────────────────\n");
        try out.appendSlice(alloc, type_decls);
        try out.appendSlice(alloc, "\n");
    }

    // ── Phase 2: Imports ────────────────────────────────────────
    try emitImports(alloc, lex, source, &out);

    // ── Phase 3: Module-level variables ─────────────────────────
    try emitModuleVars(alloc, lex, source, &out);

    // ── Phase 4: Functions ──────────────────────────────────────
    try emitFunctions(alloc, lex, source, &out);

    return try alloc.dupe(u8, out.items);
}

// ── Import handling ─────────────────────────────────────────────────

fn emitImports(alloc: std.mem.Allocator, lex: *const Lexer, source: []const u8, out: *std.ArrayListUnmanaged(u8)) !void {
    var pos: u32 = 0;
    var has_imports = false;

    while (pos < lex.count) {
        const tok = lex.get(pos);
        if (tok.kind == .identifier and std.mem.eql(u8, tok.text(source), "import")) {
            if (!has_imports) {
                try out.appendSlice(alloc, "// ── Imports ────────────────────────────────────────\n");
                has_imports = true;
            }
            // TODO: parse import { X } from './Y' → const Y = @import("Y.zig");
            // see tsz/compiler/plans/04-modulegen.md
            // Skip past the import statement for now
            while (pos < lex.count and lex.get(pos).kind != .semicolon) pos += 1;
            if (pos < lex.count) pos += 1;
            continue;
        }
        pos += 1;
    }
    if (has_imports) try out.appendSlice(alloc, "\n");
}

// ── Module-level variable emission ──────────────────────────────────

fn emitModuleVars(alloc: std.mem.Allocator, lex: *const Lexer, source: []const u8, out: *std.ArrayListUnmanaged(u8)) !void {
    var pos: u32 = 0;
    var has_vars = false;

    while (pos < lex.count) {
        const tok = lex.get(pos);
        if (tok.kind != .identifier) {
            pos += 1;
            continue;
        }
        const text = tok.text(source);

        // Skip if inside a function body (only want module-level)
        // Simple heuristic: let/const before any function keyword at top level
        if (std.mem.eql(u8, text, "function") or std.mem.eql(u8, text, "export")) break;

        if (std.mem.eql(u8, text, "let") or std.mem.eql(u8, text, "const")) {
            // Skip type declarations (enum, interface, type already handled)
            const next = lex.get(pos + 1);
            if (next.kind == .identifier) {
                const name = next.text(source);
                // Skip if this looks like it's inside a function (rough check)
                if (!std.mem.eql(u8, text, "enum") and
                    !std.mem.eql(u8, text, "interface") and
                    !std.mem.eql(u8, text, "type"))
                {
                    if (!has_vars) {
                        try out.appendSlice(alloc, "// ── Module state ───────────────────────────────────\n");
                        has_vars = true;
                    }
                    const zig_keyword = if (std.mem.eql(u8, text, "const")) "const" else "var";
                    const snake_name = try typegen.camelToSnake(alloc, name);
                    // TODO: parse type annotation and initializer
                    // see tsz/compiler/plans/04-modulegen.md
                    try out.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                        "{s} {s} = undefined; // TODO: type + init\n", .{ zig_keyword, snake_name }));
                }
            }
            // Skip to semicolon
            while (pos < lex.count and lex.get(pos).kind != .semicolon) pos += 1;
            if (pos < lex.count) pos += 1;
            continue;
        }

        pos += 1;
    }
    if (has_vars) try out.appendSlice(alloc, "\n");
}

// ── Function emission ───────────────────────────────────────────────

fn emitFunctions(alloc: std.mem.Allocator, lex: *const Lexer, source: []const u8, out: *std.ArrayListUnmanaged(u8)) !void {
    var pos: u32 = 0;

    while (pos < lex.count) {
        const tok = lex.get(pos);
        if (tok.kind != .identifier) {
            pos += 1;
            continue;
        }
        const text = tok.text(source);

        var is_pub = false;
        if (std.mem.eql(u8, text, "export")) {
            is_pub = true;
            pos += 1;
            if (pos >= lex.count) break;
        }

        if (pos < lex.count and lex.get(pos).kind == .identifier and
            std.mem.eql(u8, lex.get(pos).text(source), "function"))
        {
            pos += 1; // skip "function"
            if (pos >= lex.count) break;

            // Function name
            if (lex.get(pos).kind != .identifier) continue;
            const name = lex.get(pos).text(source);
            pos += 1;

            // Skip if this is a type-level function (rgb, rgba — utility constructors)
            // For now emit all functions

            const snake_name = try typegen.camelToSnake(alloc, name);
            const pub_prefix = if (is_pub) "pub " else "";

            // TODO: parse params with types, return type, body
            // see tsz/compiler/plans/04-modulegen.md

            // Skip params
            if (pos < lex.count and lex.get(pos).kind == .lparen) {
                var depth: u32 = 1;
                pos += 1;
                while (pos < lex.count and depth > 0) {
                    if (lex.get(pos).kind == .lparen) depth += 1;
                    if (lex.get(pos).kind == .rparen) depth -= 1;
                    pos += 1;
                }
            }

            // Skip optional return type annotation
            if (pos < lex.count and lex.get(pos).kind == .colon) {
                pos += 1;
                // Skip type tokens until {
                while (pos < lex.count and lex.get(pos).kind != .lbrace) pos += 1;
            }

            // Parse body
            var body: []const u8 = "    // TODO: function body\n";
            if (pos < lex.count and lex.get(pos).kind == .lbrace) {
                body = try stmtgen.emitBlock(alloc, lex, source, &pos, 1);
            }

            try out.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                "{s}fn {s}() void {{\n{s}}}\n\n", .{ pub_prefix, snake_name, body }));
            continue;
        }

        if (!is_pub) pos += 1;
    }
}
