const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    const args = try std.process.argsAlloc(alloc);
    if (args.len != 2 and args.len != 3) {
        std.debug.print("usage: smith_bundle <compiler-root> [out-path]\n", .{});
        return error.InvalidArguments;
    }

    const compiler_root = args[1];
    const manifest_path = try std.fs.path.join(alloc, &.{ compiler_root, "smith_LOAD_ORDER.txt" });
    const out_dir = try std.fs.path.join(alloc, &.{ compiler_root, "dist" });
    const dist_out_path = try std.fs.path.join(alloc, &.{ compiler_root, "dist", "smith.bundle.js" });
    const out_path = if (args.len == 3) args[2] else dist_out_path;

    const manifest_text = try std.fs.cwd().readFileAlloc(alloc, manifest_path, 1024 * 1024);

    var parts: std.ArrayList(u8) = .empty;
    defer parts.deinit(alloc);
    try parts.appendSlice(alloc, "// Generated by compiler/smith_bundle.zig\n");
    try parts.appendSlice(alloc, "// Source manifest: compiler/smith_LOAD_ORDER.txt\n");
    try parts.appendSlice(alloc, "\n");

    // Coverage infrastructure: injected at start of bundle
    try parts.appendSlice(alloc,
        \\// Line-level coverage — active when __smithTraceMode is set
        \\var __cov = null;
        \\if (globalThis.__smithTraceMode) {
        \\  __cov = globalThis.__smithCoverage = {};
        \\}
        \\
        \\
    );

    var entry_count: usize = 0;
    var cov_points: usize = 0;
    var lines = std.mem.splitScalar(u8, manifest_text, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \t\r");
        if (line.len == 0 or line[0] == '#') continue;
        entry_count += 1;

        const source_path = try std.fs.path.join(alloc, &.{ compiler_root, line });
        const source = try std.fs.cwd().readFileAlloc(alloc, source_path, 1024 * 1024);

        try parts.writer(alloc).print("// --- {s} ---\n", .{line});

        // Inject coverage markers at function entry points.
        // For each line containing a function definition, inject
        // __cov&&(__cov['file:line']=1); after the opening brace.
        var src_lines = std.mem.splitScalar(u8, source, '\n');
        var line_num: usize = 0;
        while (src_lines.next()) |src_line| {
            line_num += 1;
            try parts.appendSlice(alloc, src_line);
            try parts.append(alloc, '\n');

            // Check if this line defines a function (has opening brace)
            const trimmed = std.mem.trimLeft(u8, src_line, " \t");
            const is_fn = std.mem.startsWith(u8, trimmed, "function ") or
                std.mem.startsWith(u8, trimmed, "var ") or
                std.mem.startsWith(u8, trimmed, "const ") or
                std.mem.startsWith(u8, trimmed, "let ");

            if (is_fn and hasFunctionWithBrace(trimmed)) {
                // Inject coverage marker on next line
                try parts.writer(alloc).print("__cov&&(__cov['{s}:{d}']=(__cov['{s}:{d}']||0)+1);\n", .{ line, line_num, line, line_num });
                cov_points += 1;
            }
        }

        try parts.append(alloc, '\n');
    }

    if (entry_count == 0) {
        std.debug.print("smith bundle manifest is empty: {s}\n", .{manifest_path});
        return error.EmptyManifest;
    }

    try std.fs.cwd().makePath(out_dir);

    var file = try std.fs.cwd().createFile(out_path, .{});
    defer file.close();
    try file.writeAll(parts.items);

    std.debug.print("wrote {s} ({d} entries, {d} bytes, {d} coverage points)\n", .{ out_path, entry_count, parts.items.len, cov_points });
}

/// Check if a line contains a function definition with an opening brace.
/// Matches patterns like:
///   function foo() {
///   function foo(a, b) {
///   var foo = function() {
///   var foo = function(a) {
fn hasFunctionWithBrace(line: []const u8) bool {
    // Must contain "function" and end with "{"
    const has_fn = std.mem.indexOf(u8, line, "function");
    if (has_fn == null) return false;
    // Check line ends with { (possibly with trailing spaces/comments)
    var i = line.len;
    while (i > 0) {
        i -= 1;
        if (line[i] == '{') return true;
        if (line[i] != ' ' and line[i] != '\t' and line[i] != '\r') return false;
    }
    return false;
}
