//! Generated by tsz compiler — s02b_todo [nodes.zig]
//! Source: s02b_todo.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const handlers = @import("handlers.zig");

// [origin:s02b_todo:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:s02b_todo.tsz:58 — <Pressable>
pub var _arr_0 = [_]Node{ .{ .text = "Add Task", .font_size = 12, .text_color = Color.rgb(255, 255, 255) } };
// tsz:s02b_todo.tsz:57 — <Box>
pub var _arr_1 = [_]Node{ .{ .style = .{ .padding = 8, .background_color = Color.rgb(59, 130, 246), .border_radius = 6 }, .handlers = .{ .js_on_press = "addTodo()" }, .children = &_arr_0 } };
// tsz:s02b_todo.tsz:64 — <Pressable>
pub var _arr_2 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(226, 232, 240) } };
// tsz:s02b_todo.tsz:67 — <Pressable>
pub var _arr_3 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(226, 232, 240) } };
// tsz:s02b_todo.tsz:70 — <Pressable>
pub var _arr_4 = [_]Node{ .{ .text = "", .font_size = 10, .text_color = Color.rgb(226, 232, 240) } };
// tsz:s02b_todo.tsz:63 — <Box>
pub var _arr_5 = [_]Node{ .{ .style = .{ .padding = 6, .background_color = Color{}, .border_radius = 4 }, .handlers = .{ .on_press = handlers._handler_press_1 }, .children = &_arr_2 }, .{ .style = .{ .padding = 6, .background_color = Color{}, .border_radius = 4 }, .handlers = .{ .on_press = handlers._handler_press_2 }, .children = &_arr_3 }, .{ .style = .{ .padding = 6, .background_color = Color{}, .border_radius = 4 }, .handlers = .{ .on_press = handlers._handler_press_3 }, .children = &_arr_4 } };
// tsz:s02b_todo.tsz:75 — <ScrollView>
pub var _arr_16 = [_]Node{ .{ .style = .{ .gap = 4 } } };
// tsz:s02b_todo.tsz:54 — <Box>
pub var _arr_17 = [_]Node{ .{ .text = "Todo List", .font_size = 20, .text_color = Color.rgb(226, 232, 240) }, .{ .style = .{ .flex_direction = .row, .gap = 8 }, .children = &_arr_1 }, .{ .style = .{ .flex_direction = .row, .gap = 6 }, .children = &_arr_5 }, .{ .style = .{ .overflow = .scroll, .flex_grow = 1, .gap = 4 }, .children = &_arr_16 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } };
// [origin:s02b_todo:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(26, 26, 46), .width = -1, .height = -1, .padding = 20, .gap = 12, .overflow = .hidden }, .children = &_arr_17 };

