//! Generated by tsz compiler — d06_ternary_jsx_branches [logic.zig]
//! Source: d06_ternary_jsx_branches.tsz


// [origin:d06_ternary_jsx_branches:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\
;

// [origin:d06_ternary_jsx_branches:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

