//! Generated by tsz compiler — d97_jsx_prop_spread [maps.zig]
//! Source: d97_jsx_prop_spread.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const nodes = @import("nodes.zig");
const st = @import("state.zig");

// [origin:d97_jsx_prop_spread:maps]
// ── Map pools ───────────────────────────────────────────────────
pub var _pool_arena: std.heap.ArenaAllocator = std.heap.ArenaAllocator.init(std.heap.page_allocator);
pub const MAX_MAP_0: usize = 4096;
pub var _map_pool_0: []Node = std.mem.zeroes([]Node);
pub var _map_count_0: usize = 0;
pub var _map_text_bufs_0_0: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_0: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_1: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_1: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_text_bufs_0_2: [MAX_MAP_0][256]u8 = std.mem.zeroes([MAX_MAP_0][256]u8);
pub var _map_texts_0_2: [MAX_MAP_0][]const u8 = std.mem.zeroes([MAX_MAP_0][]const u8);
pub var _map_lua_bufs_0_0: [MAX_MAP_0][128]u8 = std.mem.zeroes([MAX_MAP_0][128]u8);
pub var _map_lua_ptrs_0_0: [MAX_MAP_0]?[*:0]const u8 = .{null} ** MAX_MAP_0;
// [origin:d97_jsx_prop_spread:map:_rebuildMap0]
pub fn _rebuildMap0() void {
    _map_count_0 = @min(st._oa0_len, MAX_MAP_0);
    _map_pool_0 = _pool_arena.allocator().alloc(Node, _map_count_0) catch unreachable;
    for (0.._map_count_0) |_i| {
        _map_texts_0_0[_i] = std.fmt.bufPrint(&_map_text_bufs_0_0[_i], "{s}", .{ st._oa0_label[_i][0..st._oa0_label_lens[_i]] }) catch "";
        _map_texts_0_1[_i] = std.fmt.bufPrint(&_map_text_bufs_0_1[_i], "{d}", .{ st._oa0_value[_i] }) catch "";
        _map_texts_0_2[_i] = std.fmt.bufPrint(&_map_text_bufs_0_2[_i], "{s}", .{ if ((if (state.getSlot(0)==st._oa0_id[_i]) @as(i64, 1) else @as(i64, 0)) == 1) @as([]const u8, "selected") else @as([]const u8, "idle") }) catch "";
        const _pi__arr_1_0 = _pool_arena.allocator().alloc(Node, 1) catch unreachable;
        @memcpy(_pi__arr_1_0, &[_]Node{ .{ .text = _map_texts_0_0[_i], .font_size = 8, .text_color = Color.rgb(255, 255, 255) } });
        const _pi__arr_2_0 = _pool_arena.allocator().alloc(Node, 2) catch unreachable;
        @memcpy(_pi__arr_2_0, &[_]Node{ .{ .text = "`M${@as(i64, @intCast(_i)) + 1}`", .font_size = 9, .text_color = Color.rgb(100, 116, 139) }, .{ .style = .{ .padding_left = 8, .padding_right = 8, .padding_top = 3, .padding_bottom = 3, .border_radius = 999, .background_color = if (st._oa0_tone[_i] == 0) Color.rgb(15, 118, 110) else if (st._oa0_tone[_i] == 1) Color.rgb(146, 64, 14) else Color.rgb(153, 27, 27) }, .children = _pi__arr_1_0 } });
        _pi__arr_1_0[0].text = std.fmt.bufPrint(&st._dyn_buf_1, "{s}", .{ state.getSlotString(3) }) catch "";
        const _inner_0 = _pool_arena.allocator().alloc(Node, 4) catch unreachable;
        @memcpy(_inner_0, &[_]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center }, .children = _pi__arr_2_0 }, .{ .text = _map_texts_0_0[_i], .font_size = 11, .text_color = Color.rgb(148, 163, 184) }, .{ .text = _map_texts_0_1[_i], .font_size = 20, .text_color = Color.rgb(249, 250, 251) }, .{ .text = _map_texts_0_2[_i], .font_size = 9, .text_color = Color.rgb(0, 0, 0) } });
        {
            const _n = std.fmt.bufPrint(_map_lua_bufs_0_0[_i][0..127], "__mapPress_0_0({d},{d},'{s}')", .{_i, st._oa0_id[_i], st._oa0_label[_i][0..st._oa0_label_lens[_i]]}) catch "";
            _map_lua_bufs_0_0[_i][_n.len] = 0;
            _map_lua_ptrs_0_0[_i] = @ptrCast(_map_lua_bufs_0_0[_i][0.._n.len :0]);
        }
        _map_pool_0[_i] = .{ .style = .{ .flex_grow = 1, .min_width = 150, .padding = 12, .gap = 8, .border_radius = 10, .border_width = 1, .border_color = Color.rgb(255, 255, 255), .background_color = Color.rgb(255, 255, 255) }, .handlers = .{ .js_on_press = _map_lua_ptrs_0_0[_i] }, .children = _inner_0 };
    }
    nodes._arr_4[0].children = _map_pool_0[0.._map_count_0];
}


