//! Generated by tsz compiler — rings [nodes.zig]
//! Source: rings.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const handlers = @import("handlers.zig");

// [origin:rings:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:rings.tsz:6 — <Box>
pub var _arr_0 = [_]Node{ .{ .style = .{ .flex_grow = 1 }, .effect_render = handlers._effect_render_0, .effect_shader = handlers._effect_shader_0 } };
// [origin:rings:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(0, 0, 0), .overflow = .hidden }, .children = &_arr_0 };

