//! Generated by tsz compiler — d121_variant_switching [logic.zig]
//! Source: d121_variant_switching.tsz

const api = @import("framework/api.zig");
const state = api.state;

// [origin:d121_variant_switching:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\var tiles = [];
    \\// OA initial data
    \\setTiles([ { title : "" , value : "" , caption : "" } ]);
    \\var activeVariant = 0;
    \\function setActiveVariant(v) { activeVariant = v; __setState(0, v); }
    \\const d121_data = 'init';
    \\
    \\function init(state) {
    \\  state.tiles = [
    \\    { title: 'Revenue', value: '$12.4k', caption: '+8% this month' },
    \\    { title: 'Users', value: '1,247', caption: '+23 today' },
    \\    { title: 'Orders', value: '89', caption: '12 pending' },
    \\  ];
    \\}
    \\
    \\
    \\
    \\function setTiles(v) { tiles = v; __setObjArr0(v); }
    \\if (typeof init === 'function') init({ set tiles(v) { setTiles(v); }, set activeVariant(v) { setActiveVariant(v); } });
    \\if (tiles && tiles.length > 0) setTiles(tiles);
    \\function setVariant(v) { __setVariant(v); }
    \\
;

// [origin:d121_variant_switching:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

