/**
 * TSL Boids Story — TypeScript-to-Lua transpiler in action.
 *
 * Write simulation logic in TSL (TypeScript-like), get LuaJIT-native code.
 * Side-by-side view shows the before/after transpilation.
 */

import React from 'react';
import { Box, Text } from '../../../packages/core/src';
import { useThemeColors } from '../../../packages/theme/src';

const TSL_SOURCE = `// boids.tsl
const PERCEPTION = 80
const SEP_RADIUS  = 25
const MAX_SPEED   = 180

function separation(boids, i, sepRadius): [number, number] {
  let sx = 0, sy = 0, count = 0
  const b = boids[i]
  for (let j = 1; j <= boids.length; j++) {
    if (j !== i) {
      const dx = b.x - boids[j].x
      const dy = b.y - boids[j].y
      const d  = vecLen(dx, dy)
      if (d > 0 && d < sepRadius) {
        sx += dx / d
        sy += dy / d
        count++
      }
    }
  }
  return count === 0 ? [0, 0] : vecNorm(sx/count, sy/count)
}

export function update(boids, dt, w, h, speedScale) {
  for (let i = 1; i <= boids.length; i++) {
    const [sx, sy] = separation(boids, i, SEP_RADIUS)
    const [ax, ay] = alignment(boids, i, PERCEPTION)
    const [cx, cy] = cohesion(boids, i, PERCEPTION)
    boids[i].vx += (sx * sep + ax * ali + cx * coh) * dt
    boids[i].x  += boids[i].vx * dt
  }
}`;

const LUA_OUTPUT = `-- boids.lua (generated by: reactjit tsl boids.tsl)
local PERCEPTION = 80
local SEP_RADIUS  = 25
local MAX_SPEED   = 180

local function separation(boids, i, sepRadius)
  local sx, sy, count = 0, 0, 0
  local b = boids[i]
  for j = 1, #boids do
    if j ~= i then
      local dx = b.x - boids[j].x
      local dy = b.y - boids[j].y
      local d  = vecLen(dx, dy)
      if d > 0 and d < sepRadius then
        sx = sx + dx/d
        sy = sy + dy/d
        count = count + 1
      end
    end
  end
  return count == 0 and {0, 0} or vecNorm(sx/count, sy/count)
end

local function update(boids, dt, w, h, speedScale)
  for i = 1, #boids do
    local _t = separation(boids, i, SEP_RADIUS)
    local sx, sy = _t[1], _t[2]
    local _t2 = alignment(boids, i, PERCEPTION)
    local ax, ay = _t2[1], _t2[2]
    local _t3 = cohesion(boids, i, PERCEPTION)
    local cx, cy = _t3[1], _t3[2]
    boids[i].vx = boids[i].vx + (sx*sep + ax*ali + cx*coh) * dt
    boids[i].x  = boids[i].x  + boids[i].vx * dt
  end
end`;

function CodePane({ label, badge, code, badgeColor }: { label: string; badge: string; code: string; badgeColor: string }) {
  const c = useThemeColors();
  const lines = code.split('\n');
  return (
    <Box style={{ flexDirection: 'column', flexGrow: 1, backgroundColor: c.base, borderRadius: 8, overflow: 'hidden' }}>
      {/* Header */}
      <Box style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: c.surface0,
        paddingLeft: 14, paddingRight: 14,
        paddingTop: 10, paddingBottom: 10,
        borderBottomWidth: 1,
        borderColor: c.overlay0,
      }}>
        <Text style={{ fontSize: 12, color: c.subtext1, fontWeight: 'normal' }}>{label}</Text>
        <Box style={{ backgroundColor: badgeColor, borderRadius: 4, paddingLeft: 8, paddingRight: 8, paddingTop: 2, paddingBottom: 2 }}>
          <Text style={{ fontSize: 10, color: c.base, fontWeight: 'normal' }}>{badge}</Text>
        </Box>
      </Box>
      {/* Code */}
      <Box style={{ flexGrow: 1, overflow: 'scroll', padding: 12 }}>
        {lines.map((line, i) => (
          <Box key={i} style={{ flexDirection: 'row', gap: 12, minHeight: 18 }}>
            <Text style={{ fontSize: 10, color: c.overlay1, width: 24, textAlign: 'right' }}>{String(i + 1)}</Text>
            <Text style={{ fontSize: 10, color: c.text, fontFamily: 'monospace' }}>{line || ' '}</Text>
          </Box>
        ))}
      </Box>
    </Box>
  );
}

export function TslBoidsStory() {
  const c = useThemeColors();
  return (
    <Box style={{ width: '100%', height: '100%', backgroundColor: c.base, flexDirection: 'column', gap: 0 }}>
      {/* Header */}
      <Box style={{ backgroundColor: c.mantle, borderBottomWidth: 1, borderColor: c.overlay0, paddingLeft: 20, paddingRight: 20, paddingTop: 14, paddingBottom: 14 }}>
        <Text style={{ fontSize: 16, color: c.text, fontWeight: 'normal' }}>{'TSL to Lua Transpilation'}</Text>
        <Text style={{ fontSize: 12, color: c.subtext1, marginTop: 4 }}>
          {'TypeScript-like source (left) becomes LuaJIT-native code (right)'}
        </Text>
      </Box>

      {/* Side-by-side code panels */}
      <Box style={{ flexGrow: 1, flexDirection: 'row', gap: 12, padding: 16, overflow: 'hidden' }}>
        <CodePane label={'boids.tsl'} badge={'TSL'} code={TSL_SOURCE} badgeColor={c.sapphire} />
        <CodePane label={'boids.lua (generated)'} badge={'LUA'} code={LUA_OUTPUT} badgeColor={c.yellow} />
      </Box>
    </Box>
  );
}
