/**
 * TSL Boids Story — demonstrates the TypeScript-to-Lua transpiler workflow.
 *
 * The simulation logic is written in TypeScript-like TSL, transpiled to
 * LuaJIT-native code by `reactjit tsl`, and then wired up as a declarative
 * React capability. The whole loop in three steps:
 *
 *   1. Write simulation logic in TypeScript: boids.tsl
 *   2. Transpile:  reactjit tsl boids.tsl -o lua/tsl/boids.lua
 *   3. Use it:     <Boids count={80} speed={1.2} />
 *
 * The Lua side runs the flocking math at LuaJIT speed (O(n²) per frame, zero GC).
 * The React side owns controls, pause state, and layout — as it should.
 */

import React, { useState } from 'react';
import { Box, Text, Pressable, Slider, Boids } from '../../../packages/core/src';
import { useThemeColors } from '../../../packages/theme/src';

// ── Inline code snippets ────────────────────────────────────────────────────

const TSL_SNIPPET = `// boids.tsl — runs inside the capability tick at LuaJIT speed
const PERCEPTION = 80
const SEP_RADIUS  = 25
const MAX_SPEED   = 180

function separation(boids, i, sepRadius): [number, number] {
  let sx = 0, sy = 0, count = 0
  const b = boids[i]
  for (let j = 1; j <= boids.length; j++) {
    if (j !== i) {
      const dx = b.x - boids[j].x
      const dy = b.y - boids[j].y
      const d  = vecLen(dx, dy)
      if (d > 0 && d < sepRadius) {
        sx += dx / d; sy += dy / d; count++
      }
    }
  }
  return count === 0 ? [0, 0] : vecNorm(sx/count, sy/count)
}

export function update(boids, dt, w, h, speedScale, ...) {
  for (let i = 1; i <= boids.length; i++) {
    const [sx, sy] = separation(boids, i, SEP_RADIUS)
    const [ax, ay] = alignment(boids, i, PERCEPTION)
    const [cx, cy] = cohesion(boids, i, PERCEPTION)
    // weighted sum → integrate
    boids[i].vx += (sx * sep + ax * ali + cx * coh) * dt
    boids[i].x  += boids[i].vx * dt
  }
}`;

const LUA_SNIPPET = `-- boids.lua  (generated by: reactjit tsl boids.tsl -o lua/tsl/boids.lua)
local PERCEPTION = 80
local SEP_RADIUS  = 25
local MAX_SPEED   = 180

local function separation(boids, i, sepRadius)
  local sx, sy, count = 0, 0, 0
  local b = boids[i]
  for j = 1, #boids do
    if j ~= i then
      local dx = b.x - boids[j].x
      local dy = b.y - boids[j].y
      local d  = vecLen(dx, dy)
      if d > 0 and d < sepRadius then
        sx = sx + dx/d; sy = sy + dy/d; count = count + 1
      end
    end
  end
  if count == 0 then return {0, 0} end
  return vecNorm(sx/count, sy/count)
end

local function update(boids, dt, w, h, speedScale, ...)
  for i = 1, #boids do
    local _t = separation(boids, i, SEP_RADIUS)
    local sx, sy = _t[1], _t[2]
    -- ... alignment, cohesion, integrate
    boids[i].vx = boids[i].vx + (sx*sep + ax*ali + cx*coh) * dt
    boids[i].x  = boids[i].x  + boids[i].vx * dt
  end
end`;

const REACT_SNIPPET = `import { Boids } from '@reactjit/core';

function App() {
  return (
    <Boids
      count={80}
      speed={1.2}
      separation={1.5}
      alignment={1.0}
      cohesion={1.0}
      style={{ flexGrow: 1 }}
    />
  );
}`;

// ── Sub-components ──────────────────────────────────────────────────────────

function CodePane({
  label,
  badge,
  badgeColor,
  code,
  width,
}: {
  label: string;
  badge: string;
  badgeColor: string;
  code: string;
  width?: number | string;
}) {
  const c = useThemeColors();
  const lines = code.split('\n');
  return (
    <Box style={{
      width: width ?? 320,
      backgroundColor: c.base,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.overlay0,
      overflow: 'hidden',
      flexShrink: 0,
    }}>
      {/* Header bar */}
      <Box style={{
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: c.surface0,
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderBottomWidth: 1,
        borderColor: c.overlay0,
        gap: 8,
      }}>
        <Text style={{ fontSize: 11, color: c.subtext1, fontWeight: 'bold' }}>{label}</Text>
        <Box style={{
          backgroundColor: badgeColor,
          borderRadius: 4,
          paddingHorizontal: 6,
          paddingVertical: 2,
        }}>
          <Text style={{ fontSize: 10, color: '#0a0a0a', fontWeight: 'bold' }}>{badge}</Text>
        </Box>
      </Box>
      {/* Code lines */}
      <Box style={{ padding: 10, gap: 0 }}>
        {lines.map((line, i) => (
          <Box key={i} style={{ flexDirection: 'row', gap: 8, minHeight: 14 }}>
            <Text style={{ fontSize: 10, color: c.overlay1, width: 18, textAlign: 'right' }}>
              {String(i + 1)}
            </Text>
            <Text style={{ fontSize: 10, color: c.text, flexShrink: 1 }}>{line || ' '}</Text>
          </Box>
        ))}
      </Box>
    </Box>
  );
}

function CommandBadge({ command }: { command: string }) {
  const c = useThemeColors();
  return (
    <Box style={{
      backgroundColor: c.surface1,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: c.sapphire,
      paddingHorizontal: 12,
      paddingVertical: 6,
      alignSelf: 'center',
    }}>
      <Text style={{ fontSize: 11, color: c.sapphire, fontWeight: 'bold' }}>{command}</Text>
    </Box>
  );
}

function SectionLabel({ text, color }: { text: string; color: string }) {
  return (
    <Text style={{ fontSize: 12, color, fontWeight: 'bold', marginBottom: 4 }}>{text}</Text>
  );
}

function ControlRow({
  label,
  value,
  min,
  max,
  step,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  onChange: (v: number) => void;
}) {
  const c = useThemeColors();
  return (
    <Box style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
      <Text style={{ fontSize: 11, color: c.subtext1, width: 80 }}>{label}</Text>
      <Box style={{ flexGrow: 1 }}>
        <Slider value={value} min={min} max={max} step={step} onChange={onChange} />
      </Box>
      <Text style={{ fontSize: 11, color: c.text, width: 36, textAlign: 'right' }}>
        {value.toFixed(1)}
      </Text>
    </Box>
  );
}

// ── Story root ──────────────────────────────────────────────────────────────

export function TslBoidsStory() {
  const c = useThemeColors();

  const [count, setCount]   = useState(60);
  const [speed, setSpeed]   = useState(1.0);
  const [sep, setSep]       = useState(1.5);
  const [ali, setAli]       = useState(1.0);
  const [coh, setCoh]       = useState(1.0);
  const [running, setRunning] = useState(true);
  const [tab, setTab]       = useState<'tsl' | 'lua' | 'react'>('tsl');

  return (
    <Box style={{ width: '100%', height: '100%', backgroundColor: c.base, flexDirection: 'column' }}>

      {/* ── Header ──────────────────────────────────────────── */}
      <Box style={{
        backgroundColor: c.mantle,
        borderBottomWidth: 1,
        borderColor: c.overlay0,
        paddingHorizontal: 20,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
      }}>
        <Box style={{ flexGrow: 1 }}>
          <Text style={{ fontSize: 16, color: c.text, fontWeight: 'bold' }}>{'TSL — Boids'}</Text>
          <Text style={{ fontSize: 12, color: c.subtext0 }}>
            {'TypeScript → Lua transpiler  |  simulation logic at LuaJIT speed'}
          </Text>
        </Box>
        <Pressable onPress={() => setRunning(r => !r)}>
          {({ hovered }) => (
            <Box style={{
              backgroundColor: running
                ? (hovered ? c.overlay1 : c.overlay0)
                : (hovered ? c.green : c.teal),
              borderRadius: 6,
              paddingHorizontal: 14,
              paddingVertical: 6,
            }}>
              <Text style={{ fontSize: 12, color: c.base, fontWeight: 'bold' }}>
                {running ? 'Pause' : 'Resume'}
              </Text>
            </Box>
          )}
        </Pressable>
      </Box>

      {/* ── Body ────────────────────────────────────────────── */}
      <Box style={{ flexGrow: 1, flexDirection: 'row', overflow: 'hidden' }}>

        {/* Left — workflow pane */}
        <Box style={{
          width: 420,
          flexShrink: 0,
          borderRightWidth: 1,
          borderColor: c.overlay0,
          flexDirection: 'column',
          overflow: 'scroll',
        }}>
          <Box style={{ padding: 16, gap: 14 }}>

            {/* Step 1 */}
            <Box style={{ gap: 6 }}>
              <Box style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                <Box style={{ width: 20, height: 20, borderRadius: 10, backgroundColor: c.sapphire, alignItems: 'center', justifyContent: 'center' }}>
                  <Text style={{ fontSize: 11, color: c.base, fontWeight: 'bold' }}>{'1'}</Text>
                </Box>
                <Text style={{ fontSize: 13, color: c.text, fontWeight: 'bold' }}>{'Write in TSL'}</Text>
              </Box>
              <Text style={{ fontSize: 11, color: c.subtext1 }}>
                {'TypeScript-like syntax. Types, destructuring, for-of loops — all transpile cleanly.'}
              </Text>
            </Box>

            {/* Step 2 */}
            <Box style={{ gap: 6 }}>
              <Box style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                <Box style={{ width: 20, height: 20, borderRadius: 10, backgroundColor: c.yellow, alignItems: 'center', justifyContent: 'center' }}>
                  <Text style={{ fontSize: 11, color: c.base, fontWeight: 'bold' }}>{'2'}</Text>
                </Box>
                <Text style={{ fontSize: 13, color: c.text, fontWeight: 'bold' }}>{'Transpile'}</Text>
              </Box>
              <CommandBadge command={'reactjit tsl boids.tsl -o lua/tsl/boids.lua'} />
            </Box>

            {/* Step 3 */}
            <Box style={{ gap: 6 }}>
              <Box style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
                <Box style={{ width: 20, height: 20, borderRadius: 10, backgroundColor: c.green, alignItems: 'center', justifyContent: 'center' }}>
                  <Text style={{ fontSize: 11, color: c.base, fontWeight: 'bold' }}>{'3'}</Text>
                </Box>
                <Text style={{ fontSize: 13, color: c.text, fontWeight: 'bold' }}>{'Use it in React'}</Text>
              </Box>
              <Text style={{ fontSize: 11, color: c.subtext1 }}>
                {'The capability tick calls the generated Lua each frame. React owns the controls.'}
              </Text>
            </Box>

            {/* Divider */}
            <Box style={{ height: 1, backgroundColor: c.overlay0 }} />

            {/* Code tabs */}
            <Box style={{ gap: 8 }}>
              <Box style={{ flexDirection: 'row', gap: 6 }}>
                {(['tsl', 'lua', 'react'] as const).map(t => (
                  <Pressable key={t} onPress={() => setTab(t)}>
                    {({ hovered }) => (
                      <Box style={{
                        paddingHorizontal: 10,
                        paddingVertical: 4,
                        borderRadius: 5,
                        backgroundColor: tab === t
                          ? (t === 'tsl' ? c.sapphire : t === 'lua' ? c.yellow : c.green)
                          : hovered ? c.surface1 : c.surface0,
                      }}>
                        <Text style={{
                          fontSize: 11,
                          fontWeight: 'bold',
                          color: tab === t ? c.base : c.subtext1,
                        }}>
                          {t === 'tsl' ? 'boids.tsl' : t === 'lua' ? 'boids.lua' : 'React'}
                        </Text>
                      </Box>
                    )}
                  </Pressable>
                ))}
              </Box>

              {tab === 'tsl' && (
                <Box style={{ gap: 4 }}>
                  <SectionLabel text={'Source — TypeScript-like'} color={c.sapphire} />
                  <CodePane
                    label={'storybook/src/tsl/boids.tsl'}
                    badge={'TSL'}
                    badgeColor={c.sapphire}
                    code={TSL_SNIPPET}
                    width={'100%'}
                  />
                </Box>
              )}

              {tab === 'lua' && (
                <Box style={{ gap: 4 }}>
                  <SectionLabel text={'Generated — LuaJIT native'} color={c.yellow} />
                  <CodePane
                    label={'lua/tsl/boids.lua  (generated)'}
                    badge={'LUA'}
                    badgeColor={c.yellow}
                    code={LUA_SNIPPET}
                    width={'100%'}
                  />
                </Box>
              )}

              {tab === 'react' && (
                <Box style={{ gap: 4 }}>
                  <SectionLabel text={'Usage — one-liner React component'} color={c.green} />
                  <CodePane
                    label={'App.tsx'}
                    badge={'TSX'}
                    badgeColor={c.green}
                    code={REACT_SNIPPET}
                    width={'100%'}
                  />
                </Box>
              )}
            </Box>

            {/* Divider */}
            <Box style={{ height: 1, backgroundColor: c.overlay0 }} />

            {/* Controls */}
            <Box style={{ gap: 10 }}>
              <Text style={{ fontSize: 12, color: c.text, fontWeight: 'bold' }}>{'Simulation Controls'}</Text>
              <ControlRow label={'Count'} value={count} min={10} max={200} step={5} onChange={v => setCount(Math.round(v))} />
              <ControlRow label={'Speed'} value={speed} min={0.1} max={3.0} step={0.1} onChange={setSpeed} />
              <ControlRow label={'Separation'} value={sep} min={0} max={3.0} step={0.1} onChange={setSep} />
              <ControlRow label={'Alignment'} value={ali} min={0} max={3.0} step={0.1} onChange={setAli} />
              <ControlRow label={'Cohesion'} value={coh} min={0} max={3.0} step={0.1} onChange={setCoh} />
            </Box>

          </Box>
        </Box>

        {/* Right — live simulation */}
        <Box style={{ flexGrow: 1, flexDirection: 'column' }}>
          {/* Label bar */}
          <Box style={{
            backgroundColor: c.mantle,
            borderBottomWidth: 1,
            borderColor: c.overlay0,
            paddingHorizontal: 14,
            paddingVertical: 6,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
          }}>
            <Box style={{ width: 8, height: 8, borderRadius: 4, backgroundColor: running ? c.green : c.overlay1 }} />
            <Text style={{ fontSize: 11, color: c.subtext1 }}>
              {running ? `${count} boids — running at LuaJIT speed` : `${count} boids — paused`}
            </Text>
          </Box>

          {/* The Boids capability — full GL rendering, zero React overhead per boid */}
          <Boids
            count={count}
            speed={speed}
            separation={sep}
            alignment={ali}
            cohesion={coh}
            running={running}
            color={'#66CCFF'}
            style={{ flexGrow: 1 }}
          />
        </Box>

      </Box>
    </Box>
  );
}
