//! Generated by tsz compiler — 50_column_wrap_height [nodes.zig]
//! Source: 50_column_wrap_height.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:50_column_wrap_height:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:50_column_wrap_height.tsz:12 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "1" } };
// tsz:50_column_wrap_height.tsz:15 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "2" } };
// tsz:50_column_wrap_height.tsz:18 — <Box>
pub var _arr_2 = [_]Node{ .{ .text = "3" } };
// tsz:50_column_wrap_height.tsz:21 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "4" } };
// tsz:50_column_wrap_height.tsz:24 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "5" } };
// tsz:50_column_wrap_height.tsz:27 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "6" } };
// tsz:50_column_wrap_height.tsz:11 — <Box>
pub var _arr_6 = [_]Node{ .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_0 }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_1 }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(255, 152, 0), .overflow = .auto }, .children = &_arr_2 }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(156, 39, 176), .overflow = .auto }, .children = &_arr_3 }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(244, 67, 54), .overflow = .auto }, .children = &_arr_4 }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(0, 188, 212), .overflow = .auto }, .children = &_arr_5 } };
// tsz:50_column_wrap_height.tsz:34 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "tall" } };
// tsz:50_column_wrap_height.tsz:37 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "short" } };
// tsz:50_column_wrap_height.tsz:40 — <Box>
pub var _arr_9 = [_]Node{ .{ .text = "taller" } };
// tsz:50_column_wrap_height.tsz:43 — <Box>
pub var _arr_10 = [_]Node{ .{ .text = "med" } };
// tsz:50_column_wrap_height.tsz:46 — <Box>
pub var _arr_11 = [_]Node{ .{ .text = "short" } };
// tsz:50_column_wrap_height.tsz:33 — <Box>
pub var _arr_12 = [_]Node{ .{ .style = .{ .width = 60, .height = 40, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_7 }, .{ .style = .{ .width = 60, .height = 20, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_8 }, .{ .style = .{ .width = 60, .height = 50, .background_color = Color.rgb(255, 152, 0), .overflow = .auto }, .children = &_arr_9 }, .{ .style = .{ .width = 60, .height = 30, .background_color = Color.rgb(156, 39, 176), .overflow = .auto }, .children = &_arr_10 }, .{ .style = .{ .width = 60, .height = 20, .background_color = Color.rgb(244, 67, 54), .overflow = .auto }, .children = &_arr_11 } };
// tsz:50_column_wrap_height.tsz:52 — <Box>
pub var _arr_13 = [_]Node{ .{ .style = .{ .width = 50, .height = 40, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .width = 50, .height = 40, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .width = 50, .height = 40, .background_color = Color.rgb(255, 152, 0) } }, .{ .style = .{ .width = 50, .height = 40, .background_color = Color.rgb(156, 39, 176) } } };
// tsz:50_column_wrap_height.tsz:3 — <Box>
pub var _arr_14 = [_]Node{ .{ .text = "WPT: column wrap" }, .{ .text = "VERIFY: Column+wrap items flow down then to next column, height determines wrap point", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "Note: column + wrap is partially supported" }, .{ .text = "Wrap point is determined by container height" }, .{ .text = "Column wrap — items flow down then wrap to next column" }, .{ .style = .{ .flex_direction = .column, .flex_wrap = .wrap, .width = 300, .height = 120, .background_color = Color.rgb(51, 51, 51), .gap = 4, .padding = 4, .overflow = .auto }, .children = &_arr_6 }, .{ .text = "Column wrap with unequal heights" }, .{ .style = .{ .flex_direction = .column, .flex_wrap = .wrap, .width = 300, .height = 100, .background_color = Color.rgb(51, 51, 51), .gap = 4, .padding = 4, .overflow = .auto }, .children = &_arr_12 }, .{ .text = "Small container forces each item to its own column" }, .{ .style = .{ .flex_direction = .column, .flex_wrap = .wrap, .width = 400, .height = 50, .background_color = Color.rgb(51, 51, 51), .gap = 4, .padding = 4, .overflow = .auto }, .children = &_arr_13 } };
// [origin:50_column_wrap_height:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 8, .overflow = .hidden }, .children = &_arr_14 };

