//! Generated by tsz compiler — d49_string_state [handlers.zig]
//! Source: d49_string_state.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:d49_string_state:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:d49_string_state:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobalStr("switchTab", "all");
}

// [origin:d49_string_state:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobalStr("switchTab", "home");
}

// [origin:d49_string_state:handler:_handler_press_2]
pub fn _handler_press_2() void {
    qjs_runtime.callGlobalStr("switchTab", "admin");
}

// [origin:d49_string_state:handler:_handler_press_3]
pub fn _handler_press_3() void {
    qjs_runtime.callGlobalStr("switchTab", "dev");
}

// [origin:d49_string_state:handler:_handler_press_4]
pub fn _handler_press_4() void {
    qjs_runtime.callGlobalStr("search", "User");
}

// [origin:d49_string_state:handler:_handler_press_5]
pub fn _handler_press_5() void {
    qjs_runtime.callGlobalStr("search", "API");
}

// [origin:d49_string_state:handler:_handler_press_6]
pub fn _handler_press_6() void {
    qjs_runtime.callGlobalStr("search", "");
}

