//! Generated by tsz compiler — d47_nested_ternary [state.zig]
//! Source: d47_nested_ternary.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d47_nested_ternary:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: level (int)
// slot 1: mode (int)
// slot 2: output (string)
comptime { if (3 != 3) @compileError("state slot count mismatch"); }

// [origin:d47_nested_ternary:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_2: []const u8 = "";
pub var _dyn_buf_3: [128]u8 = std.mem.zeroes([128]u8);
pub var _dyn_text_3: []const u8 = "";

pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
}

