//! Generated by tsz compiler — d100_named_slots [state.zig]
//! Source: d100_named_slots.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d100_named_slots:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: tab (int)
// slot 1: theme (int)
// slot 2: selected (string)
// slot 3: actionCount (int)
comptime { if (4 != 4) @compileError("state slot count mismatch"); }

// [origin:d100_named_slots:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [128]u8 = std.mem.zeroes([128]u8);
pub var _dyn_text_2: []const u8 = "";
pub var _dyn_buf_3: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_3: []const u8 = "";

pub const qjs = @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
pub const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// [origin:d100_named_slots:state]
// ── Object arrays ───────────────────────────────────────────────
pub const _oa_alloc = std.heap.page_allocator;

pub fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

pub fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

pub var _oa0_title: [][]const u8 = &[_][]const u8{};
pub var _oa0_title_lens: []usize = &[_]usize{};
pub var _oa0_title_cap: usize = 0;
pub var _oa0_group: []i64 = &[_]i64{};
pub var _oa0_group_cap: usize = 0;
pub var _oa0_len: usize = 0;
pub var _oa0_dirty: bool = false;

pub fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_title_cap) return;
    const new_cap = @max(needed, if (_oa0_title_cap == 0) @as(usize, 64) else _oa0_title_cap * 2);
    if (_oa0_title_cap == 0) {
        _oa0_title = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_title_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_title[_j] = &[_]u8{};
        @memset(_oa0_title_lens, 0);
    } else {
        const _old_cap = _oa0_title_cap;
        _oa0_title = _oa_alloc.realloc(_oa0_title.ptr[0.._old_cap], new_cap) catch return;
        _oa0_title_lens = _oa_alloc.realloc(_oa0_title_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_title[_j] = &[_]u8{};
        @memset(_oa0_title_lens[_old_cap..new_cap], 0);
    }
    _oa0_title_cap = new_cap;
    if (_oa0_group_cap == 0) {
        _oa0_group = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_group, 0);
    } else {
        _oa0_group = _oa_alloc.realloc(_oa0_group.ptr[0.._oa0_group_cap], new_cap) catch return;
        @memset(_oa0_group[_oa0_group_cap..new_cap], 0);
    }
    _oa0_group_cap = new_cap;
}

// [origin:d100_named_slots:oa:_oa0_unpack]
pub fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "title");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_title[_i], &_oa0_title_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_title[_i] = _oaDupString(sl); _oa0_title_lens[_i] = _oa0_title[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "group");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_group[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa0_len) {
        for (count.._oa0_len) |_trim_i| _oaFreeString(&_oa0_title[_trim_i], &_oa0_title_lens[_trim_i]);
    }
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa1_title = [_][]const u8{ "Review the launch checklist", "Reply to support thread #288", "Patch billing dashboard padding", "Ship analytics export to staging", "Trim stale feature flags" };
pub var _oa1_title_lens = [_]usize{ 27, 28, 31, 32, 24 };
pub var _oa1_group = [_]i64{ 0, 0, 1, 1, 2 };
pub var _oa1_len: usize = 5;
pub var _oa1_dirty: bool = false;


pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
    _ = state.createSlot(0);
}

