//! Generated by tsz compiler — d08_map_classifier_components [state.zig]
//! Source: d08_map_classifier_components.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// ── State manifest ──

