//! Generated by tsz compiler — 75_text_align_justify [logic.zig]
//! Source: 75_text_align_justify.tsz


// [origin:75_text_align_justify:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\
;

// [origin:75_text_align_justify:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

