//! Generated by tsz compiler — s07b_node_editor [logic.zig]
//! Source: s07b_node_editor.tsz


// [origin:s07b_node_editor:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\var nodes = [];
    \\var edges = [];
    \\// OA initial data
    \\setNodes([ { id : 0 , title : "" , x : 0 , y : 0 , color : "" } ]);
    \\setEdges([ { from : 0 , to : 0 } ]);
    \\var selected = -1;
    \\function setSelected(v) { selected = v; __setState(0, v); }
    \\var nodeCount = 0;
    \\function setNodeCount(v) { nodeCount = v; __setState(1, v); }
    \\var nodeList = [
    \\  { id: 0, title: 'Input', x: 60, y: 80, color: '#3b82f6' },
    \\  { id: 1, title: 'Process', x: 220, y: 160, color: '#8b5cf6' },
    \\  { id: 2, title: 'Output', x: 380, y: 80, color: '#22c55e' }
    \\];
    \\var edgeList = [
    \\  { from: 0, to: 1 },
    \\  { from: 1, to: 2 }
    \\];
    \\sync();
    \\
    \\function sync() {
    \\  setNodes(nodeList);
    \\  setEdges(edgeList);
    \\  setNodeCount(nodeList.length);
    \\}
    \\
    \\var nextId = 3;
    \\var colors = ['#3b82f6', '#8b5cf6', '#ef4444', '#f59e0b', '#22c55e', '#06b6d4'];
    \\
    \\function addNode() {
    \\  var id = nextId;
    \\  nodeList.push({ id: id, title: 'Node ' + id, x: 60 + (id * 80) % 360, y: 60 + (id * 60) % 200, color: colors[id % colors.length] });
    \\  nextId++;
    \\  sync();
    \\}
    \\
    \\function removeNode(idx) {
    \\  var removed = nodeList[idx].id;
    \\  var result = [];
    \\  for (var i = 0; i < nodeList.length; i++) {
    \\    if (i !== idx) result.push(nodeList[i]);
    \\  }
    \\  nodeList = result;
    \\  var newEdges = [];
    \\  for (var j = 0; j < edgeList.length; j++) {
    \\    if (edgeList[j].from !== removed && edgeList[j].to !== removed) newEdges.push(edgeList[j]);
    \\  }
    \\  edgeList = newEdges;
    \\  setSelected(-1);
    \\  sync();
    \\}
    \\
    \\function connectSelected(toIdx) {
    \\  if (selected < 0 || selected === toIdx) return;
    \\  edgeList.push({ from: nodeList[selected].id, to: nodeList[toIdx].id });
    \\  setSelected(-1);
    \\  sync();
    \\}
    \\function setNodes(v) { nodes = v; __setObjArr0(v); }
    \\function setEdges(v) { edges = v; __setObjArr1(v); }
    \\if (nodes && nodes.length > 0) setNodes(nodes);
    \\if (edges && edges.length > 0) setEdges(edges);
    \\function __mapPress_0_0(idx) {
    \\  var node = nodes[idx];
    \\  var idx = idx;
    \\  selected >= 0?connectSelected(idx):setSelected(idx);
    \\}
    \\function __mapPress_0_1(idx) {
    \\  var node = nodes[idx];
    \\  var idx = idx;
    \\  removeNode(idx);
    \\}
    \\
;

// [origin:s07b_node_editor:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

