//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/net/manager.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/net/manager.tsz
//! To modify: edit manager.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Type definitions ────────────────────────────────
pub const ConnectOpts = struct {
    reconnect: bool = false,
    tor_proxy_port: u16 = 0,
};
pub const NetEventType = enum { connected, message, closed, err, reconnecting };
pub const NetEvent = struct {
    id: u32 = 0,
    event_type: NetEventType = .connected,
    data: [MAX_MSG]u8,
    data_len: usize = 0,
};
pub const ConnStatus = enum { connecting, tunneling, open, reconnecting, closed };
pub const ConnectResult = enum { none, success, failed };
pub const Connection = struct {
    active: bool = false,
    id: u32 = 0,
    ws: ?websocket.WebSocket = null,
    pending_ws: ?websocket.WebSocket = null,
    connect_done: bool = false,
    connect_ok: bool = false,
    generation: u32 = 0,
    mutex: std.Thread.Mutex,
    url: [MAX_URL]u8,
    url_len: usize = 0,
    host: [256]u8,
    host_len: usize = 0,
    port: u16 = 0,
    path: [256]u8,
    path_len: usize = 0,
    status: ConnStatus = .connecting,
    reconnect: bool = false,
    backoff_ms: u32 = 0,
    next_retry_tick: u32 = 0,
    is_onion: bool = false,
    tor_proxy_port: u16 = 0,
};
pub const ConnectParams = struct {
    conn: *Connection,
    gen: u32 = 0,
    host: [256]u8,
    host_len: usize = 0,
    port: u16 = 0,
    path: [256]u8,
    path_len: usize = 0,
    is_onion: bool = false,
    tor_proxy_port: u16 = 0,
};

// ── Module state ───────────────────────────────────
const websocket = @import("websocket.zig");
const socks5 = @import("socks5.zig");
const MAX_CONNECTIONS: usize = 32;
const MAX_URL: usize = 512;
const MAX_MSG: usize = 65536;
const MAX_EVENTS: usize = 64;
const INITIAL_BACKOFF_MS: u32 = 1000;
const MAX_BACKOFF_MS: u32 = 30000;
const DEFAULT_TOR_PROXY_PORT: u16 = 9050;
var connections: [MAX_CONNECTIONS]Connection = undefined;
var event_count: usize = 0;
var active_workers: u32 = 0;
var initialized: bool = false;

// ── Functions ──────────────────────────────────────

pub fn netEventDataSlice(self: *const NetEvent) []const u8 {
    return self.data[0..self.data_len];
}

pub fn init() void {
    if (initialized) {
        return;
    }
    {
        var i: usize = 0;
        while (i < MAX_CONNECTIONS) : (i += 1) {
            connections[i].active = false;
            connections[i].mutex = .{  };
            connections[i].generation = 0;
        }
    }
    event_count = 0;
    initialized = true;
}

pub fn connect(id: u32, url: []const u8, opts: ConnectOpts) void {
    const slot = findSlot();
    @"orelse";
    return;
    var conn = &connections[slot];
    conn.pending_ws = null;
    conn.connect_done = false;
    conn.connect_ok = false;
    conn.ws = null;
    conn.active = true;
    conn.id = id;
    conn.status = .connecting;
    conn.reconnect = opts.reconnect;
    conn.backoff_ms = INITIAL_BACKOFF_MS;
    conn.tor_proxy_port = opts.tor_proxy_port;
    const ulen = @min(url.len, MAX_URL);
    @memcpy(conn.url[0..ulen], url[0..ulen]);
    conn.url_len = ulen;
    parseUrl(conn, url[0..ulen]);
    conn.is_onion = isOnion(conn.host[0..conn.host_len]);
    startConnection(conn);
}

pub fn sendMsg(id: u32, data: []const u8) void {
    if (findById(id)) |conn| {
        if (conn.status == .open) {
            if (conn.ws) |*|             ws | .{ ws.send(data) catch {}, ; };
        }
    }
}

pub fn closeConn(id: u32) void {
    if (findById(id)) |conn| {
        conn.mutex.lock();
        conn.reconnect = false;
        conn.generation +% =;
        1;
        if (conn.pending_ws) |*|         pws | pws.shutdown();
        conn.pending_ws = null;
        conn.connect_done = false;
        conn.connect_ok = false;
        if (conn.ws) |*|         ws | ws.shutdown();
        conn.ws = null;
        conn.status = .closed;
        conn.active = false;
        conn.mutex.unlock();
    }
}

pub fn poll(out: []NetEvent) usize {
    event_count = 0;
    {
        var ci: usize = 0;
        while (ci < MAX_CONNECTIONS) : (ci += 1) {
            if (!connections[ci].active) {
                continue;
            }
            var conn = &connections[ci];
            var connectResult: ConnectResult = .none;
            conn.mutex.lock();
            if (conn.connect_done) {
                conn.connect_done = false;
                if (conn.connect_ok) {
                    conn.ws = conn.pending_ws;
                    conn.pending_ws = null;
                    conn.status = .connecting;
                    connectResult = .success;
                } else {
                    connectResult = .failed;
                }
            }
            conn.mutex.unlock();
            if (connectResult == .failed) {
                handleDisconnect(conn);
                continue;
            }
            switch (conn.status) {
                .open,.connecting => {
                    if (conn.ws) |*|                     ws | .{ let, .safety = u32, =, 0, ;, @"while"(safety < 100), .{ if (ws.update()) |event| .{ switch (event) { .open => conn.status, .message => |msg| pushEvent(&out, conn.id, .message, msg), .close => |cl| pushEvent(&out, conn.id, .closed, cl.reason), .err => |e| pushEvent(&out, conn.id, .err, e) } } else .{ break, ; }, safety, +, =, 1, ; } };
                },
                .reconnecting => {
                    const now = getTicks();
                    if (now >= conn.next_retry_tick) {
                        pushEvent(&out, conn.id, .reconnecting, "");
                        startConnection(conn);
                    }
                },
                .closed,.tunneling => {
                },
            }
        }
    }
    return @min(event_count, out.len);
}

pub fn destroy() void {
    {
        var i: usize = 0;
        while (i < MAX_CONNECTIONS) : (i += 1) {
            connections[i].mutex.lock();
            connections[i].generation +% =;
            1;
            if (connections[i].pending_ws) |*|             pws | pws.shutdown();
            connections[i].pending_ws = null;
            connections[i].connect_done = false;
            connections[i].connect_ok = false;
            if (connections[i].active) {
                if (connections[i].ws) |*|                 ws | ws.shutdown();
                connections[i].ws = null;
                connections[i].active = false;
            }
            connections[i].mutex.unlock();
        }
    }
    var waitCount: u32 = 0;
    while (@atomicLoad(u32, &active_workers, .seq_cst) > 0 and waitCount < 5000) {
        std.thread.sleep(1_000_000);
        waitCount += 1;
    }
    initialized = false;
}

fn findSlot() ?usize {
    {
        var i: usize = 0;
        while (i < MAX_CONNECTIONS) : (i += 1) {
            if (!connections[i].active) {
                return i;
            }
        }
    }
    return null;
}

fn findById(id: u32) ?*Connection {
    {
        var i: usize = 0;
        while (i < MAX_CONNECTIONS) : (i += 1) {
            if (connections[i].active and connections[i].id == id) {
                return &connections[i];
            }
        }
    }
    return null;
}

fn startConnection(conn: *Connection) void {
    var params: ConnectParams = undefined;
    params.conn = conn;
    params.gen = conn.generation;
    params.host_len = conn.host_len;
    params.port = conn.port;
    params.path_len = conn.path_len;
    params.is_onion = conn.is_onion;
    params.tor_proxy_port = conn.tor_proxy_port;
    @memcpy(params.host[0..conn.host_len], conn.host[0..conn.host_len]);
    @memcpy(params.path[0..conn.path_len], conn.path[0..conn.path_len]);
    conn.status = .connecting;
    _ = @atomicRmw(u32, &active_workers, .Add, 1, .seq_cst);
    _ = std.thread.spawn(.{ .stack_size = 1024 * 1024 }, connectWorker, .{ .params = params }) catch .{ _, =, @atomicRmw(u32, &active_workers, .Sub, 1, .seq_cst), ;, handleDisconnect(conn), ; };
}

fn connectWorker(params: ConnectParams) void {
    defer _;
    =;
    @atomicRmw(u32, &active_workers, .Sub, 1, .seq_cst);
    const host = params.host[0..params.host_len];
    const path = params.path[0..params.path_len];
    const conn = params.conn;
    var newWs: ? websocket . WebSocket = null;
    if (params.is_onion) {
        const stream = socks5.connect("127.0.0.1", params.tor_proxy_port, host, params.port, null, null) catch .{ publishResult(conn, params.gen, null, false), ;, return, ; };
        newWs = websocket.web_socket.connectViaStream(stream, host, params.port, path) catch .{ stream.close(), ;, publishResult(conn, params.gen, null, false), ;, return, ; };
    } else {
        newWs = websocket.web_socket.connectTcp(host, params.port, path) catch .{ publishResult(conn, params.gen, null, false), ;, return, ; };
    }
    publishResult(conn, params.gen, newWs, true);
}

fn publishResult(conn: *Connection, expectedGen: u32, newWs: ?websocket.WebSocket, ok: bool) void {
    conn.mutex.lock();
    defer conn.mutex.unlock();
    if (conn.generation == expectedGen) {
        conn.pending_ws = newWs;
        conn.connect_done = true;
        conn.connect_ok = ok;
    } else {
        if (newWs) |ws| {
            var wsCopy = ws;
            wsCopy.shutdown();
        }
    }
}

fn handleDisconnect(conn: *Connection) void {
    if (conn.ws) |*|     ws | ws.shutdown();
    conn.ws = null;
    if (conn.reconnect) {
        conn.status = .reconnecting;
        conn.next_retry_tick = getTicks() + conn.backoff_ms;
        conn.backoff_ms = @min(conn.backoff_ms * 2, MAX_BACKOFF_MS);
    } else {
        conn.status = .closed;
        conn.active = false;
    }
}

fn pushEvent(out: []NetEvent, id: u32, eventType: NetEventType, data: []const u8) void {
    if (event_count >= out.len) {
        return;
    }
    out[event_count].id = id;
    out[event_count].event_type = eventType;
    const dlen = @min(data.len, MAX_MSG);
    if (dlen > 0) {
        @memcpy(out[event_count].data[0..dlen], data[0..dlen]);
    }
    out[event_count].data_len = dlen;
    event_count += 1;
}

fn parseUrl(conn: *Connection, url: []const u8) void {
    var start: usize = 0;
    if (url.len > 5 and std.mem.eql(u8, url[0..5], "ws://")) {
        start = 5;
        conn.port = 80;
    } else if (url.len > 6 and std.mem.eql(u8, url[0..6], "wss://")) {
        start = 6;
        conn.port = 443;
    }
    var hostEnd = start;
    while (hostEnd < url.len and url[hostEnd] != ':' and url[hostEnd] != '/') {
        hostEnd += 1;
    }
    const hlen = hostEnd - start;
    @memcpy(conn.host[0..hlen], url[start..hostEnd]);
    conn.host_len = hlen;
    if (hostEnd < url.len and url[hostEnd] == ':') {
        hostEnd += 1;
        var portEnd = hostEnd;
        while (portEnd < url.len and url[portEnd] != '/') {
            portEnd += 1;
        }
        conn.port = std.fmt.parseInt(u16, url[hostEnd..portEnd], 10) catch conn.port;
        hostEnd = portEnd;
    }
    if (hostEnd < url.len and url[hostEnd] == '/') {
        const plen = url.len - hostEnd;
        @memcpy(conn.path[0..plen], url[hostEnd..url.len]);
        conn.path_len = plen;
    } else {
        conn.path[0] = "/";
        conn.path_len = 1;
    }
}

fn isOnion(host: []const u8) bool {
    return host.len > 6 and std.mem.eql(u8, host[host.len..-6..]], ".onion");
}

fn getTicks() u32 {
    var ts: std . posix . timespec = undefined;
    std.posix.clock_gettime(.MONOTONIC, &ts);
    return @intCast(@as(u64, @intCast(ts.sec)) * 1000 + @as(u64, @intCast(ts.nsec)) / 1_000_000);
}
