export {
  createPresentationComponentNode,
  createPresentationDocument,
  createPresentationGroupNode,
  createPresentationImageNode,
  createPresentationShapeNode,
  createPresentationSlide,
  createPresentationTextNode,
  createPresentationVideoNode,
  findPresentationNode,
  findPresentationSlide,
  getSlideStepCount,
  normalizePresentationDocument,
  visitPresentationNodes,
  type CreatePresentationComponentNodeOptions,
  type CreatePresentationDocumentOptions,
  type CreatePresentationGroupNodeOptions,
  type CreatePresentationImageNodeOptions,
  type CreatePresentationNodeOptions,
  type CreatePresentationShapeNodeOptions,
  type CreatePresentationSlideOptions,
  type CreatePresentationTextNodeOptions,
  type CreatePresentationVideoNodeOptions,
  type PresentationFactoryOptions,
} from './document.ts';
export {
  applyPresentationPatch,
  applyPresentationPatches,
  getSelectionSlide,
  type ApplyPresentationPatchOptions,
  type PresentationDocumentChanges,
  type PresentationEditorCommand,
  type PresentationEditorEvent,
  type PresentationNodeChanges,
  type PresentationPatch,
  type PresentationSlideChanges,
} from './patches.ts';

export type {
  PresentationAspectRatio,
  PresentationAsset,
  PresentationAuthoringMode,
  PresentationBaseNode,
  PresentationCamera,
  PresentationComponentNode,
  PresentationDocument,
  PresentationEasing,
  PresentationFragment,
  PresentationFrame,
  PresentationGroupNode,
  PresentationImageNode,
  PresentationNode,
  PresentationNodeKind,
  PresentationSelection,
  PresentationSettings,
  PresentationShapeKind,
  PresentationShapeNode,
  PresentationSlide,
  PresentationStageSize,
  PresentationTextNode,
  PresentationTheme,
  PresentationTransition,
  PresentationTransitionKind,
  PresentationVideoNode,
} from './types.ts';
