export { useAPI, useAPIMutation, rateLimitedFetch, bearer, qs } from './base';
export type { FetchOptions, FetchResult, MutationResult, HTTPMethod } from './base';
export { isRateLimited, recordRequest, rateLimitRemaining, resetRateLimit } from './rateLimit';
export { useServiceKey, getServiceKey, setServiceKey, deleteServiceKey, isServiceEnabled } from './useServiceKey';
export type { ServiceKeys } from './useServiceKey';
export { builtinServices, spotify, tmdb, plex, trakt, lastfm, polypizza, github, steam, nasa, openai, anthropic, homeassistant, hue, notion, todoist, google, ynab, coingecko, telegram, weather } from './registry';
export type { ServiceDefinition, ServiceField, ServiceCategory } from './registry';

export { useGitHub } from './useGitHub';
export { useSpotify } from './useSpotify';
export { useTMDB } from './useTMDB';
export { useWeather } from './useWeather';
export { useHomeAssistant } from './useHomeAssistant';
export { useLastFM } from './useLastFM';
export { usePlex } from './usePlex';
export { useTrakt } from './useTrakt';
export { useNotion } from './useNotion';
export { useTodoist } from './useTodoist';
export { useYNAB } from './useYNAB';
export { useGoogle } from './useGoogle';
export { useHue } from './useHue';
export { useNASA } from './useNASA';
export { useCoinGecko } from './useCoinGecko';
export { useSteam } from './useSteam';
export { useTelegram } from './useTelegram';
export { usePolyPizza } from './usePolyPizza';
export { useOpenAI } from './useOpenAI';
export { useAnthropic } from './useAnthropic';
