//! Generated by tsz compiler — d32_deep_nesting [nodes.zig]
//! Source: d32_deep_nesting.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d32_deep_nesting:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d32_deep_nesting.tsz:15 — <Box>
pub var _arr_20 = [_]Node{ .{ .style = .{ .gap = 8 } } };
// tsz:d32_deep_nesting.tsz:13 — <Box>
pub var _arr_21 = [_]Node{ .{ .text = "Deep Nesting Test", .font_size = 16, .text_color = Color.rgb(226, 232, 240) }, .{ .style = .{ .gap = 8 }, .children = &_arr_20 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } };
// [origin:d32_deep_nesting:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(15, 23, 42), .padding = 16, .width = -1, .height = -1, .gap = 8, .overflow = .hidden }, .children = &_arr_21 };

