export const SYMBOL_MAP: Record<string, string> = {
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ε',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  iota: 'ι',
  kappa: 'κ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  pi: 'π',
  rho: 'ρ',
  sigma: 'σ',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Xi: 'Ξ',
  Pi: 'Π',
  Sigma: 'Σ',
  Phi: 'Φ',
  Psi: 'Ψ',
  Omega: 'Ω',
  pm: '±',
  times: '×',
  cdot: '·',
  div: '÷',
  ast: '∗',
  star: '⋆',
  bullet: '•',
  circ: '∘',
  cap: '∩',
  cup: '∪',
  subset: '⊂',
  superset: '⊃',
  subseteq: '⊆',
  supseteq: '⊇',
  in: '∈',
  notin: '∉',
  to: '→',
  rightarrow: '→',
  leftarrow: '←',
  leftrightarrow: '↔',
  mapsto: '↦',
  iff: '⇔',
  implies: '⇒',
  leq: '≤',
  geq: '≥',
  neq: '≠',
  approx: '≈',
  sim: '∼',
  propto: '∝',
  forall: '∀',
  exists: '∃',
  partial: '∂',
  nabla: '∇',
  infinity: '∞',
  int: '∫',
  sum: '∑',
  prod: '∏',
  sqrt: '√',
  ldots: '…',
  cdots: '⋯',
  prime: '′',
  deg: '°',
  there4: '∴',
  because: '∵',
  overline: '‾',
  text: '',
};

const ALIASES: Record<string, string> = {
  varepsilon: 'ε',
  vartheta: 'θ',
  varphi: 'φ',
  varpi: 'π',
  varrho: 'ρ',
  varsigma: 'σ',
  lte: '≤',
  gte: '≥',
  lt: '<',
  gt: '>',
  perp: '⊥',
  angle: '∠',
  ell: 'ℓ',
  hbar: 'ℏ',
};

export function resolveSymbol(name: string): string | null {
  const key = String(name || '').replace(/^\s+|\s+$/g, '');
  if (!key) return null;
  if (key in SYMBOL_MAP && SYMBOL_MAP[key]) return SYMBOL_MAP[key];
  if (key in ALIASES) return ALIASES[key];
  return null;
}
