import type { FlowEdge, FlowNode } from './types';

export const FLOW_EDITOR_DEMO_NODES: FlowNode[] = [
  {
    id: 'TRG',
    label: 'Webhook Trigger',
    x: -430,
    y: -190,
    data: {
      kind: 'trigger',
      role: 'TRG',
      state: 'ok',
      stripe: 'trigger',
      kv: [
        { key: 'event', value: 'repo.push' },
        { key: 'auth', value: 'hmac' },
        { key: 'source', value: 'github' },
      ],
      meta: { runs: '912', ms: '8', cost: '0.000', model: 'edge', version: 'v12', lastRun: '09:41' },
    },
  },
  {
    id: 'A01',
    label: 'Fetch Build Plan',
    x: -160,
    y: -190,
    data: {
      kind: 'action',
      role: 'HTTP',
      roleGlyph: '->',
      state: 'run',
      kv: [
        { key: 'method', value: 'POST' },
        { key: 'url', value: '/api/plan' },
        { key: 'auth', value: 'bearer' },
        { key: 'timeout', value: '12s' },
      ],
      ports: [
        { id: 'in', side: 'in', kind: 'flow', label: 'control flow in' },
        { id: 'payload', side: 'out', kind: 'data', label: 'structured plan payload' },
        { id: 'err', side: 'out', kind: 'error', label: 'HTTP exception' },
      ],
      meta: { runs: '279', ms: '41', cost: '0.001', model: 'fetch', version: 'v4', lastRun: 'now' },
    },
  },
  {
    id: 'B02',
    label: 'Normalize + Score',
    x: 150,
    y: -190,
    data: {
      kind: 'sequence',
      state: 'run',
      draft: true,
      steps: [
        { id: 'parse', label: 'parse payload', glyph: '1', state: 'done', metric: '6ms' },
        { id: 'enrich', label: 'join repo context', glyph: '2', state: 'run', metric: '18ms' },
        { id: 'rank', label: 'rank actions', glyph: '3', state: 'wait', metric: '--' },
        { id: 'emit', label: 'emit scored plan', glyph: '4', state: 'skip', metric: '--' },
      ],
      ports: [
        { id: 'payload', side: 'in', kind: 'data', label: 'scored payload in' },
        { id: 'out', side: 'out', kind: 'flow', label: 'continue after sequence' },
        { id: 'err', side: 'out', kind: 'error', label: 'sequence exception' },
      ],
      meta: { runs: '214', ms: '33', cost: '0.004', model: 'local', version: 'v7', lastRun: '09:42' },
    },
  },
  {
    id: 'C03',
    label: 'Should Deploy?',
    x: 430,
    y: -190,
    data: {
      kind: 'if',
      state: 'wait',
      code: ['return score > 0.82', '  && tests.ok', '  && budget.left > cost'],
      hitRate: { true: '68%', false: '32%' },
      meta: { runs: '214', ms: '2', cost: '0.000', model: 'expr', version: 'v3', lastRun: '09:42' },
    },
  },
  {
    id: 'D04',
    label: 'Compare Lanes',
    x: -250,
    y: 90,
    data: {
      kind: 'lanes',
      state: 'ok',
      lanes: [
        { id: 'canary', label: 'canary', state: 'run', metric: '14/20', lines: ['2 regions', 'slow ramp'] },
        { id: 'stable', label: 'stable', state: 'ok', metric: 'ready', lines: ['all regions', 'fast cut'] },
      ],
      ports: [
        { id: 'true', side: 'in', kind: 'cond-true', label: 'true branch in' },
        { id: 'winner', side: 'out', kind: 'data', label: 'winner lane payload' },
        { id: 'err', side: 'out', kind: 'error', label: 'lane exception' },
      ],
      meta: { runs: '146', ms: '25', cost: '0.002', model: 'lane', version: 'v5', lastRun: '09:42' },
    },
  },
  {
    id: 'C05',
    label: 'Route Failure Class',
    x: 95,
    y: 105,
    data: {
      kind: 'switch',
      state: 'ok',
      activeCaseId: 'retry',
      cases: [
        { id: 'retry', label: 'network retryable', hitRate: '41%', active: true },
        { id: 'hold', label: 'quota hold', hitRate: '18%' },
        { id: 'page', label: 'human page', hitRate: '9%' },
        { id: 'drop', label: 'drop noisy', hitRate: '32%' },
      ],
      meta: { runs: '68', ms: '4', cost: '0.000', model: 'case', version: 'v2', lastRun: '09:40' },
    },
  },
  {
    id: 'D06',
    label: 'Deploy Loop',
    x: 400,
    y: 95,
    data: {
      kind: 'loop',
      state: 'run',
      kv: [
        { key: 'collection', value: 'regions' },
        { key: 'parallel', value: '2' },
        { key: 'retry', value: '3x' },
      ],
      loop: { current: 7, total: 12, label: 'regions' },
      meta: { runs: '38', ms: '122', cost: '0.018', model: 'deploy', version: 'v9', lastRun: 'now' },
    },
  },
  {
    id: 'E07',
    label: 'LLM Summarizer',
    x: 95,
    y: 250,
    data: {
      kind: 'token',
      role: 'AI',
      state: 'run',
      quickActions: ['◉', '⌖', '⚑', '⏸', '⋯'],
      ports: [
        { id: 'prompt', side: 'in', kind: 'data', label: 'prompt payload' },
        { id: 'ctx', side: 'in', kind: 'ctx', label: 'runtime context' },
        { id: 'tools', side: 'in', kind: 'tool', label: 'tool bindings' },
        { id: 'tokens', side: 'out', kind: 'data', label: 'token stream' },
        { id: 'output', side: 'out', kind: 'flow', label: 'summarized output' },
        { id: 'err', side: 'out', kind: 'error', label: 'model exception' },
      ],
      meta: { runs: '92', ms: '841', cost: '0.027', model: 'gpt', version: 'v11', lastRun: 'now' },
    },
  },
  {
    id: 'END',
    label: 'Terminal',
    x: 420,
    y: 250,
    data: {
      kind: 'end',
      state: 'idle',
      stripe: 'end',
      kv: [
        { key: 'result', value: 'archive' },
        { key: 'notify', value: 'slack' },
      ],
      meta: { runs: '279', ms: '3', cost: '0.000', model: 'sink', version: 'v1', lastRun: '09:42' },
    },
  },
];

export const FLOW_EDITOR_DEMO_EDGES: FlowEdge[] = [
  { id: 'e1', from: 'TRG', fromPort: 'out', to: 'A01', toPort: 'in', kind: 'flow' },
  { id: 'e2', from: 'A01', fromPort: 'payload', to: 'B02', toPort: 'payload', kind: 'data' },
  { id: 'e3', from: 'B02', fromPort: 'out', to: 'C03', toPort: 'in', kind: 'flow' },
  { id: 'e4', from: 'C03', fromPort: 'true', to: 'D04', toPort: 'true', kind: 'cond-true' },
  { id: 'e5', from: 'C03', fromPort: 'false', to: 'C05', toPort: 'in', kind: 'cond-false' },
  { id: 'e6', from: 'D04', fromPort: 'winner', to: 'D06', toPort: 'in', kind: 'data' },
  { id: 'e7', from: 'C05', fromPort: 'retry', to: 'D06', toPort: 'in', kind: 'cond-true' },
  { id: 'e8', from: 'D06', fromPort: 'item', to: 'E07', toPort: 'ctx', kind: 'loop' },
  { id: 'e9', from: 'E07', fromPort: 'output', to: 'END', toPort: 'in', kind: 'flow' },
  { id: 'e10', from: 'A01', fromPort: 'err', to: 'END', toPort: 'err', kind: 'error' },
  { id: 'e11', from: 'E07', fromPort: 'err', to: 'END', toPort: 'err', kind: 'error' },
  { id: 'e12', from: 'TRG', fromPort: 'ctx', to: 'E07', toPort: 'tools', kind: 'tool' },
];
