//! Generated by tsz compiler — d116_the_hydra [nodes.zig]
//! Source: d116_the_hydra.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d116_the_hydra:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d116_the_hydra.tsz:118 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "Projects", .font_size = 12, .text_color = Color.rgb(115, 115, 115) }, .{ .style = .{ .gap = 8 } }, .{ .style = .{ .height = 1, .background_color = Color.rgb(38, 38, 38) } }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(64, 64, 64) }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(64, 64, 64) }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(64, 64, 64) } }; // Sidebar
// tsz:d116_the_hydra.tsz:151 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "The Hydra", .font_size = 16, .text_color = Color.rgb(229, 229, 229) }, .{ .text = "", .font_size = 9, .text_color = Color.rgb(64, 64, 64) } };
// tsz:d116_the_hydra.tsz:155 — <ScrollView>
pub var _arr_25 = [_]Node{ .{ .style = .{ .gap = 8 } } };
// tsz:d116_the_hydra.tsz:150 — <Box>
pub var _arr_26 = [_]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center }, .children = &_arr_6 }, .{ .style = .{ .overflow = .scroll, .flex_grow = 1, .gap = 8 }, .children = &_arr_25 } };
// tsz:d116_the_hydra.tsz:147 — <Box>
pub var _arr_27 = [_]Node{ .{ .style = .{ .width = 140, .gap = 8 }, .children = &_arr_5 }, .{ .style = .{ .width = 1, .background_color = Color.rgb(38, 38, 38) } }, .{ .style = .{ .flex_grow = 1, .padding = 12, .gap = 8, .overflow = .auto }, .children = &_arr_26 } };
// [origin:d116_the_hydra:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(10, 10, 10), .flex_direction = .row, .gap = 0, .overflow = .hidden }, .children = &_arr_27 };

