//! Generated by tsz compiler — l05b_data_pipeline [handlers.zig]
//! Source: l05b_data_pipeline.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:l05b_data_pipeline:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:l05b_data_pipeline:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobal("demoFilter");
}

// [origin:l05b_data_pipeline:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobal("demoSort");
}

// [origin:l05b_data_pipeline:handler:_handler_press_2]
pub fn _handler_press_2() void {
    qjs_runtime.callGlobal("demoMap");
}

// [origin:l05b_data_pipeline:handler:_handler_press_3]
pub fn _handler_press_3() void {
    qjs_runtime.callGlobal("demoChain");
}

// [origin:l05b_data_pipeline:handler:_handler_press_4]
pub fn _handler_press_4() void {
    qjs_runtime.callGlobal("clearLog");
}

