//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/c.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/c.mod.tsz
//! To modify: edit c.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Module state ───────────────────────────────────
const builtin = @import("builtin");
pub const imports = @cImport({ if(builtin.os.tag == .windows) { @cInclude("SDL.h") ; @cInclude("SDL_syswm.h") ; } else { @cInclude("SDL2/SDL.h") ; @cInclude("SDL2/SDL_syswm.h") ; } @cInclude("ft2build.h") ; @cInclude("freetype/freetype.h") ; @cInclude("stb/stb_image.h") ; });

