//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/crypto.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/crypto.mod.tsz
//! To modify: edit crypto.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Type definitions ────────────────────────────────
pub const EncryptedEnvelope = struct {
    buf: [MAX_PLAINTEXT+16+24]u8,
    ct_len: usize = 0,
};
pub const SigningKeyPair = struct {
    public_hex: [64]u8,
    secret_hex: [128]u8,
};
pub const DHKeyPair = struct {
    public_hex: [64]u8,
    secret_hex: [64]u8,
};

// ── Module state ───────────────────────────────────
const crypto = std.crypto;
const fmt = std.fmt;
const XChaCha20Poly1305 = crypto.aead.chacha_poly.XChaCha20Poly1305;
const ChaCha20Poly1305 = crypto.aead.chacha_poly.ChaCha20Poly1305;
const Aes256Gcm = crypto.aead.aes_gcm.Aes256Gcm;
pub const MAX_PLAINTEXT: usize = 4096;
const Ed25519 = crypto.sign.Ed25519;
const X25519 = crypto.dh.X25519;

// ── Functions ──────────────────────────────────────

pub fn sha256(input: []const u8, hex_out: *[64]u8) void {
    var digest: [32]u8 = undefined;
    crypto.hash.sha2.sha256.hash(input, &digest, .{  });
    hex_out.* = fmt.bytesToHex(digest, .lower);
}

pub fn sha512(input: []const u8, hex_out: *[128]u8) void {
    var digest: [64]u8 = undefined;
    crypto.hash.sha2.sha512.hash(input, &digest, .{  });
    hex_out.* = fmt.bytesToHex(digest, .lower);
}

pub fn blake2b256(input: []const u8, hex_out: *[64]u8) void {
    var digest: [32]u8 = undefined;
    crypto.hash.blake2.blake2b256.hash(input, &digest, .{  });
    hex_out.* = fmt.bytesToHex(digest, .lower);
}

pub fn blake2s256(input: []const u8, hex_out: *[64]u8) void {
    var digest: [32]u8 = undefined;
    crypto.hash.blake2.blake2s256.hash(input, &digest, .{  });
    hex_out.* = fmt.bytesToHex(digest, .lower);
}

pub fn blake3(input: []const u8, hex_out: *[64]u8) void {
    var digest: [32]u8 = undefined;
    crypto.hash.blake3.hash(input, &digest, .{  });
    hex_out.* = fmt.bytesToHex(digest, .lower);
}

pub fn hmacSha256(key: []const u8, message: []const u8, hex_out: *[64]u8) void {
    var mac: [32]u8 = undefined;
    crypto.auth.hmac.sha2.hmac_sha256.create(&mac, message, key);
    hex_out.* = fmt.bytesToHex(mac, .lower);
}

pub fn hmacSha512(key: []const u8, message: []const u8, hex_out: *[128]u8) void {
    var mac: [64]u8 = undefined;
    crypto.auth.hmac.sha2.hmac_sha512.create(&mac, message, key);
    hex_out.* = fmt.bytesToHex(mac, .lower);
}

pub fn envelopeCiphertext(self: *const EncryptedEnvelope) []const u8 {
    return self.buf[0..self.ct_len];
}

pub fn envelopeTag(self: *const EncryptedEnvelope) *const [16]u8 {
    return self.buf[self.ct_len..][0..16];
}

pub fn envelopeNonce(self: *const EncryptedEnvelope) *const [24]u8 {
    return self.buf[self.ct_len..+];
    16..][0..24];
}

pub fn envelopeToHex(self: *const EncryptedEnvelope, hex_buf: []u8) []const u8 {
    const total = 24 + self.ct_len + 16;
    const hex_len = total * 2;
    if (@as(f32, @floatFromInt(hex_buf.len)) < hex_len) {
        return hex_buf[0..0];
    }
    const nonce_hex = fmt.bytesToHex(envelopeNonce(self).*, .lower);
    @memcpy(hex_buf[0..48], &nonce_hex);
    var offset: usize = 48;
    for (envelopeCiphertext(self)) |*b| {
        const byte_hex = fmt.bytesToHex(.{ 1 }, u8, .{ .b = b }, .lower);
        hex_buf[offset] = byte_hex[0];
        hex_buf[offset + 1] = byte_hex[1];
        offset += 2;
    }
    const tag_hex = fmt.bytesToHex(envelopeTag(self).*, .lower);
    @memcpy(hex_buf[offset..offset + 32], &tag_hex);
    return hex_buf[0..hex_len];
}

pub fn encrypt(plaintext: []const u8, key: [32]u8) ?EncryptedEnvelope {
    if (plaintext.len > MAX_PLAINTEXT) {
        return null;
    }
    var envelope: EncryptedEnvelope = .{ .buf = null, .ct_len = plaintext.len };
    var nonce: [24]u8 = undefined;
    crypto.random.bytes(&nonce);
    var tag: [16]u8 = undefined;
    XChaCha20Poly1305.encrypt(envelope.buf[0..plaintext.len], &tag, plaintext, "", nonce, key);
    @memcpy(envelope.buf[plaintext.len..][0..16], &tag);
    @memcpy(envelope.buf[plaintext.len..+], 16..][0..24], &nonce);
    return envelope;
}

pub fn decrypt(envelope: *const EncryptedEnvelope, key: [32]u8) ?[MAX_PLAINTEXT]u8 {
    var plaintext: [MAX_PLAINTEXT]u8 = undefined;
    XChaCha20Poly1305.decrypt(plaintext[0..envelope.ct_len], envelopeCiphertext(envelope), envelopeTag(envelope).*, "", envelopeNonce(envelope).*, key) catch return null;
    return plaintext;
}

pub fn decryptHex(hex_input: []const u8, key: [32]u8, plaintext_out: []u8) ?usize {
    if (hex_input.len < 80) {
        return null;
    }
    if (hex_input.len % 2 != 0) {
        return null;
    }
    const total_bytes = hex_input.len / 2;
    const ct_len = total_bytes - 24 - 16;
    if (ct_len > @as(f32, @floatFromInt(plaintext_out.len))) {
        return null;
    }
    var nonce: [24]u8 = undefined;
    _ = fmt.hexToBytes(&nonce, hex_input[0..48]) catch return null;
    var ct_buf: [MAX_PLAINTEXT]u8 = undefined;
    _ = fmt.hexToBytes(ct_buf[0..ct_len], hex_input[48..48 + ct_len * 2]) catch return null;
    var tag: [16]u8 = undefined;
    _ = fmt.hexToBytes(&tag, hex_input[hex_input.len..-32..]]) catch return null;
    XChaCha20Poly1305.decrypt(plaintext_out[0..ct_len], ct_buf[0..ct_len], tag, "", nonce, key) catch return null;
    return ct_len;
}

pub fn deriveKeyArgon2(allocator: std.mem.Allocator, password: []const u8, salt: [32]u8, key_out: *[32]u8) !void {
    try crypto.pwhash.argon2.kdf(allocator, key_out, password, &salt, .{ .t = 2, .m = 65536, .p = 1 }, // moderate: 2 iterations, 64MB, 1 thread.argon2id);
}

pub fn deriveKeyScrypt(allocator: std.mem.Allocator, password: []const u8, salt: [32]u8, key_out: *[32]u8) !void {
    try crypto.pwhash.scrypt.kdf(allocator, key_out, password, &salt, .{ .ln = 17, .r = 8, .p = 1 }, // N=2^17=131072, r=8, p=1);
}

pub fn generateSigningKeys() SigningKeyPair {
    const kp = .key_pair.generate();
    return .{ .public_hex = fmt.bytesToHex(kp.public_key.toBytes(), .lower), .secret_hex = fmt.bytesToHex(kp.secret_key.toBytes(), .lower) };
}

pub fn sign(secret_key_hex: []const u8, message: []const u8, sig_hex_out: *[128]u8) bool {
    if (secret_key_hex.len != 128) {
        return false;
    }
    var sk_bytes: [64]u8 = undefined;
    _ = fmt.hexToBytes(&sk_bytes, secret_key_hex) catch return false;
    const sk = .secret_key.fromBytes(sk_bytes) catch return false;
    const pk_bytes = sk.publicKeyBytes();
    const pk = .public_key.fromBytes(pk_bytes) catch return false;
    const kp = .key_pair;
    .{ .secret_key = sk, .public_key = pk };
    const sig = kp.sign(message, null) catch return false;
    sig_hex_out.* = fmt.bytesToHex(sig.toBytes(), .lower);
    return true;
}

pub fn verify(public_key_hex: []const u8, message: []const u8, signature_hex: []const u8) bool {
    if (public_key_hex.len != 64) {
        return false;
    }
    if (signature_hex.len != 128) {
        return false;
    }
    var pk_bytes: [32]u8 = undefined;
    _ = fmt.hexToBytes(&pk_bytes, public_key_hex) catch return false;
    var sig_bytes: [64]u8 = undefined;
    _ = fmt.hexToBytes(&sig_bytes, signature_hex) catch return false;
    const pk = .public_key.fromBytes(pk_bytes) catch return false;
    const sig = .signature;
    .{ .r = sig_bytes[0..32].*, .s = sig_bytes[32..64].* };
    .signature.verify(sig, message, pk) catch return false;
    return true;
}

pub fn generateDHKeys() DHKeyPair {
    const kp = .key_pair.generate();
    return .{ .public_hex = fmt.bytesToHex(kp.public_key, .lower), .secret_hex = fmt.bytesToHex(kp.secret_key, .lower) };
}

pub fn diffieHellman(secret_key_hex: []const u8, public_key_hex: []const u8, shared_hex_out: *[64]u8) bool {
    if (secret_key_hex.len != 64) {
        return false;
    }
    if (public_key_hex.len != 64) {
        return false;
    }
    var sk: [32]u8 = undefined;
    _ = fmt.hexToBytes(&sk, secret_key_hex) catch return false;
    var pk: [32]u8 = undefined;
    _ = fmt.hexToBytes(&pk, public_key_hex) catch return false;
    const shared = X25519.scalarmult(sk, pk) catch return false;
    shared_hex_out.* = fmt.bytesToHex(shared, .lower);
    crypto.secureZero(u8, @as(*, @"volatile"[32], u8, @volatileCast(&sk)));
    return true;
}

pub fn randomBytes(buf: []u8) void {
    crypto.random.bytes(buf);
}

pub fn randomToken(bytes: usize, hex_out: []u8) []const u8 {
    var buf: [256]u8 = undefined;
    const n = @min(bytes, 256);
    crypto.random.bytes(buf[0..n]);
    var i: usize = 0;
    while (@as(f32, @floatFromInt(i)) < n) {
        const byte_hex = fmt.bytesToHex(.{ 1 }, u8, .{ buf[i] }, .lower);
        if (i * 2 + 1 < hex_out.len) {
            hex_out[i * 2] = byte_hex[0];
            hex_out[i * 2 + 1] = byte_hex[1];
        }
        i += 1;
    }
    return hex_out[0..n * 2];
}

pub fn randomId(length: usize, out: []u8) []const u8 {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    var buf: [256]u8 = undefined;
    const n = @min(length, @min(256, out.len));
    crypto.random.bytes(buf[0..n]);
    {
        var i: usize = 0;
        while (@as(f32, @floatFromInt(i)) < n) : (i += 1) {
            out[i] = chars[buf[i] % 62];
        }
    }
    return out[0..n];
}

pub fn toHex(bytes: []const u8, out: []u8) []const u8 {
    const hex_len = bytes.len * 2;
    if (@as(f32, @floatFromInt(out.len)) < hex_len) {
        return out[0..0];
    }
    var i: usize = 0;
    while (i < bytes.len) {
        const byte_hex = fmt.bytesToHex(.{ 1 }, u8, .{ bytes[i] }, .lower);
        out[i * 2] = byte_hex[0];
        out[i * 2 + 1] = byte_hex[1];
        i += 1;
    }
    return out[0..hex_len];
}

pub fn fromHex(hex: []const u8, out: []u8) ?[]u8 {
    return fmt.hexToBytes(out, hex) catch null;
}

pub fn toBase64(bytes: []const u8, out: []u8) []const u8 {
    const encoder = std.base64.standard.Encoder;
    const encoded_len = encoder.calcSize(bytes.len);
    if (out.len < encoded_len) {
        return out[0..0];
    }
    return encoder.encode(out, bytes);
}

pub fn fromBase64(encoded: []const u8, out: []u8) ?[]u8 {
    const decoder = std.base64.standard.Decoder;
    const decoded_len = decoder.calcSize(encoded) catch return null;
    if (out.len < decoded_len) {
        return null;
    }
    decoder.decode(out, encoded) catch return null;
    return out[0..decoded_len];
}

pub fn timingSafeEqual(a: []const u8, b: []const u8) bool {
    if (a.len != b.len) {
        return false;
    }
    var acc: u8 = 0;
    {
        var i: usize = 0;
        while (i < a.len) : (i += 1) {
            acc | =;
            a[i];
            ^;
            b[i];
        }
    }
    return acc == 0;
}

pub fn secureZero(buf: []u8) void {
    crypto.secureZero(u8, @as(.{  }, @"volatile", u8, @volatileCast(buf)));
}
