//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/focus.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/focus.mod.tsz
//! To modify: edit focus.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Imports ────────────────────────────────────────
const layout = @import("layout.zig");
const Node = layout.Node;

// ── Type definitions ────────────────────────────────
pub const InputMode = enum { mouse, controller };
pub const NavDirection = enum { up, down, left, right };
pub const PlayerColor = struct {
    r: f32 = 0,
    g: f32 = 0,
    b: f32 = 0,
    a: f32 = 0,
};
pub const FocusGroup = struct {
    active: bool = false,
    node_id: u32 = 0,
    focused_idx: ?usize = null,
    last_focused_idx: ?usize = null,
    controller_id: ?u8 = null,
    members: [MAX_FOCUSABLE]u16,
    member_count: usize = 0,
};
pub const FocusableEntry = struct {
    active: bool = false,
    node: ?*Node = null,
    group_idx: ?usize = null,
    cx: f32 = 0,
    cy: f32 = 0,
};
pub const StickState = struct {
    dir: ?NavDirection = null,
    timer: f32 = 0,
    repeating: bool = false,
};

// ── Module state ───────────────────────────────────
const STICK_DEADZONE: f32 = 0.3;
const REPEAT_INITIAL: f32 = 0.4;
const REPEAT_RATE: f32 = 0.15;
const MAX_FOCUSABLE: usize = 256;
const MAX_GROUPS: usize = 16;
const MAX_CONTROLLERS: usize = 4;
const PLAYER_COLORS: [4]PlayerColor = .{.{ r : 0.3, g : 0.6, b : 1.0, a : 0.9 }, // P1: blue.{ r : 1.0, g : 0.3, b : 0.3, a : 0.9 }, // P2: red.{ r : 0.3, g : 1.0, b : 0.5, a : 0.9 }, // P3: green.{ r : 1.0, g : 0.8, b : 0.2, a : 0.9 }, // P4: yellow };
var input_mode: InputMode = .mouse;
var focusables: [MAX_FOCUSABLE]FocusableEntry = undefined;
var focusable_count: usize = 0;
var default_focused: ?usize = null;
var default_last_focused: ?usize = null;
var groups: [MAX_GROUPS]FocusGroup = undefined;
var group_count: usize = 0;
var stick_states: [MAX_CONTROLLERS]StickState = undefined;
var ring_x: f32 = 0;
var ring_y: f32 = 0;
var ring_w: f32 = 0;
var ring_h: f32 = 0;
var ring_visible: bool = false;

// ── Functions ──────────────────────────────────────

pub fn getInputMode() InputMode {
    return input_mode;
}

pub fn setInputMode(mode: InputMode) void {
    if (mode == input_mode) {
        return;
    }
    input_mode = mode;
    if (mode == .controller) {
        if (default_focused == null and default_last_focused != null) {
            default_focused = default_last_focused.?;
            updateRing();
        }
    }
}

pub fn registerFocusable(node: *Node, groupIdx: ?usize) ?usize {
    if (focusable_count >= MAX_FOCUSABLE) {
        return null;
    }
    const idx = focusable_count;
    focusables[idx].active = true;
    focusables[idx].node = node;
    focusables[idx].group_idx = groupIdx;
    focusables[idx].cx = node.computed.x + node.computed.w / 2.0;
    focusables[idx].cy = node.computed.y + node.computed.h / 2.0;
    focusable_count += 1;
    if (groupIdx) |gi| {
        if (gi < group_count and groups[gi].member_count < MAX_FOCUSABLE) {
            groups[gi].members[groups[gi].member_count] = @intCast(idx);
            groups[gi].member_count += 1;
        }
    }
    return idx;
}

pub fn clearFocusables() void {
    focusable_count = 0;
    {
        var i: usize = 0;
        while (i < group_count) : (i += 1) {
            groups[i].member_count = 0;
        }
    }
}

pub fn createGroup(nodeId: u32, controllerId: ?u8) ?usize {
    if (group_count >= MAX_GROUPS) {
        return null;
    }
    const idx = group_count;
    groups[idx].active = true;
    groups[idx].node_id = nodeId;
    groups[idx].focused_idx = null;
    groups[idx].last_focused_idx = null;
    groups[idx].controller_id = controllerId;
    groups[idx].member_count = 0;
    group_count += 1;
    return idx;
}

pub fn getFocused() ?*Node {
    if (default_focused) |idx| {
        if (idx < focusable_count and focusables[idx].active) {
            return focusables[idx].node;
        }
    }
    return null;
}

pub fn setFocus(idx: usize) void {
    if (idx >= focusable_count) {
        return;
    }
    default_last_focused = default_focused;
    default_focused = idx;
    updateRing();
}

pub fn clearFocus() void {
    default_last_focused = default_focused;
    default_focused = null;
    ring_visible = false;
}

pub fn navigate(dir: NavDirection) void {
    if (focusable_count == 0) {
        return;
    }
    if (default_focused == null) {
        if (focusable_count > 0) {
            setFocus(0);
        }
        return;
    }
    const currentIdx = default_focused.?;
    const current = &focusables[currentIdx];
    var bestIdx: ? usize = null;
    var bestScore = std.math.floatMax(f32);
    {
        var i: usize = 0;
        while (i < focusable_count) : (i += 1) {
            if (i == currentIdx) {
                continue;
            }
            if (!focusables[i].active) {
                continue;
            }
            const cand = &focusables[i];
            const dx = cand.cx - current.cx;
            const dy = cand.cy - current.cy;
            const inDirection = switch (dir) {  };
            if (!inDirection) {
                continue;
            }
            const primary = switch (dir) {  };
            const perp = switch (dir) {  };
            const score = primary + perp * 3.0;
            if (score < bestScore) {
                bestScore = score;
                bestIdx = i;
            }
        }
    }
    if (bestIdx) |idx| {
        setFocus(idx);
    }
}

pub fn processStick(controllerId: u8, x: f32, y: f32, dt: f32) bool {
    if (controllerId >= MAX_CONTROLLERS) {
        return false;
    }
    var ss = &stick_states[controllerId];
    var dir: ? NavDirection = null;
    if (@abs(x) > @as(f32, @floatFromInt(STICK_DEADZONE)) or @abs(y) > @as(f32, @floatFromInt(STICK_DEADZONE))) {
        if (@abs(x) > @abs(y)) {
            dir = if (x > 0) .right else .left;
        } else {
            dir = if (y > 0) .down else .up;
        }
    }
    if (dir == null) {
        ss.dir = null;
        ss.timer = 0;
        ss.repeating = false;
        return false;
    }
    if (ss.dir == null or dir.? != ss.dir.?) {
        ss.dir = dir;
        ss.timer = 0;
        ss.repeating = false;
        setInputMode(.controller);
        navigate(dir.?);
        return true;
    }
    ss.timer += dt;
    const threshold = if (ss.repeating) REPEAT_RATE else REPEAT_INITIAL;
    if (ss.timer >= threshold) {
        ss.timer = 0;
        ss.repeating = true;
        navigate(dir.?);
        return true;
    }
    return false;
}

fn updateRing() void {
    if (default_focused) |idx| {
        if (idx < focusable_count) {
            if (focusables[idx].node) |node| {
                ring_x = node.computed.x;
                ring_y = node.computed.y;
                ring_w = node.computed.w;
                ring_h = node.computed.h;
                ring_visible = true;
                return;
            }
        }
    }
    ring_visible = false;
}

pub fn getRingRect() ?struct {
    x;
    :;
    f32;
    ,;
    y;
    :;
    f32;
    ,;
    w;
    :;
    f32;
    ,;
    h;
    :;
    f32;
}

pub fn getPlayerColor(controllerId: u8) PlayerColor {
    if (controllerId >= 4) {
        return PLAYER_COLORS[0];
    }
    return PLAYER_COLORS[controllerId];
}

pub fn reset() void {
    input_mode = .mouse;
    focusable_count = 0;
    group_count = 0;
    default_focused = null;
    default_last_focused = null;
    ring_visible = false;
    {
        var i: usize = 0;
        while (i < MAX_CONTROLLERS) : (i += 1) {
            stick_states[i].dir = null;
            stick_states[i].timer = 0;
            stick_states[i].repeating = false;
        }
    }
}
