//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/layout.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/layout.mod.tsz
//! To modify: edit layout.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Imports ────────────────────────────────────────
const events = @import("events.zig");
const EventHandler = events.EventHandler;

// ── Type definitions ────────────────────────────────
pub const FlexDirection = enum { row, column };
pub const JustifyContent = enum { start, center, end, space_between, space_around, space_evenly };
pub const AlignItems = enum { start, center, end, stretch };
pub const AlignSelf = enum { auto, start, center, end, stretch };
pub const FlexWrap = enum { no_wrap, wrap };
pub const Position = enum { relative, absolute };
pub const Display = enum { flex, none };
pub const Overflow = enum { visible, hidden, scroll };
pub const TextAlign = enum { left, center, right };
pub const CodeLanguage = enum { none, zig, type_script, json, bash, markdown, plain };
pub const GradientDirection = enum { none, vertical, horizontal };
pub const DevtoolsViz = enum { none, sparkline, wireframe, node_tree, inspector_overlay };
pub const Color = struct {
    r: u8 = 0,
    g: u8 = 0,
    b: u8 = 0,
    a: u8 = 0,

    pub fn rgb(r: u8, g: u8, b: u8) Color {
        return .{ .r = r, .g = g, .b = b, .a = 255 };
    }
    pub fn rgba(r: u8, g: u8, b: u8, a: u8) Color {
        return .{ .r = r, .g = g, .b = b, .a = a };
    }
};
pub const TextMetrics = struct {
    width: f32 = 0,
    height: f32 = 0,
    ascent: f32 = 0,
};
pub const ImageDims = struct {
    width: f32 = 0,
    height: f32 = 0,
};
pub const LayoutRect = struct {
    x: f32 = 0,
    y: f32 = 0,
    w: f32 = 0,
    h: f32 = 0,
};
pub const Style = struct {
    width: ?f32 = null,
    height: ?f32 = null,
    min_width: ?f32 = null,
    max_width: ?f32 = null,
    min_height: ?f32 = null,
    max_height: ?f32 = null,
    flex_direction: FlexDirection = .column,
    flex_grow: f32 = 0,
    flex_shrink: ?f32 = null,
    flex_basis: ?f32 = null,
    flex_wrap: FlexWrap = .no_wrap,
    justify_content: JustifyContent = .start,
    align_items: AlignItems = .stretch,
    align_self: AlignSelf = .auto,
    gap: f32 = 0,
    position: Position = .relative,
    top: ?f32 = null,
    left: ?f32 = null,
    right: ?f32 = null,
    bottom: ?f32 = null,
    aspect_ratio: ?f32 = null,
    padding: f32 = 0,
    padding_left: ?f32 = null,
    padding_right: ?f32 = null,
    padding_top: ?f32 = null,
    padding_bottom: ?f32 = null,
    margin: f32 = 0,
    margin_left: ?f32 = null,
    margin_right: ?f32 = null,
    margin_top: ?f32 = null,
    margin_bottom: ?f32 = null,
    display: Display = .flex,
    overflow: Overflow = .visible,
    text_align: TextAlign = .left,
    background_color: ?Color = null,
    border_radius: f32 = 0,
    opacity: f32 = 1.0,
    rotation: f32 = 0,
    scale_x: f32 = 1.0,
    scale_y: f32 = 1.0,
    border_width: f32 = 0,
    border_color: ?Color = null,
    z_index: i16 = 0,
    gradient_color_end: ?Color = null,
    gradient_direction: GradientDirection = .none,
    shadow_offset_x: f32 = 0,
    shadow_offset_y: f32 = 0,
    shadow_blur: f32 = 0,
    shadow_color: ?Color = null,

    pub fn padLeft(self: Style) f32 { return self.padding_left orelse self.padding; }
    pub fn padRight(self: Style) f32 { return self.padding_right orelse self.padding; }
    pub fn padTop(self: Style) f32 { return self.padding_top orelse self.padding; }
    pub fn padBottom(self: Style) f32 { return self.padding_bottom orelse self.padding; }
    pub fn marLeft(self: Style) f32 { return self.margin_left orelse self.margin; }
    pub fn marRight(self: Style) f32 { return self.margin_right orelse self.margin; }
    pub fn marTop(self: Style) f32 { return self.margin_top orelse self.margin; }
    pub fn marBottom(self: Style) f32 { return self.margin_bottom orelse self.margin; }
};
pub const Node = struct {
    style: Style = .{},
    children: []Node = &.{},
    computed: LayoutRect = .{},
    text: ?[]const u8 = null,
    font_size: u16 = 16,
    text_color: ?Color = null,
    letter_spacing: f32 = 0,
    line_height: f32 = 0,
    number_of_lines: u16 = 0,
    no_wrap: bool = false,
    code_language: CodeLanguage = .none,
    image_src: ?[]const u8 = null,
    input_id: ?u8 = null,
    placeholder: ?[]const u8 = null,
    debug_name: ?[]const u8 = null,
    test_id: ?[]const u8 = null,
    handlers: EventHandler = .{},
    scroll_x: f32 = 0,
    scroll_y: f32 = 0,
    content_height: f32 = 0,
    devtools_viz: DevtoolsViz = .none,
    canvas_type: ?[]const u8 = null,
    _flex_w: ?f32 = null,
    _stretch_h: ?f32 = null,
    _parent_inner_w: ?f32 = null,
    _parent_inner_h: ?f32 = null,
};
pub const MeasureTextFn = *const fn (text: []const u8, font_size: u16, max_width: f32, letter_spacing: f32, line_height: f32, max_lines: u16, no_wrap: bool) TextMetrics;
pub const MeasureImageFn = *const fn (path: []const u8) ImageDims;

// ── Module state ───────────────────────────────────
var measureFn: ?MeasureTextFn = null;
var measureImageFn: ?MeasureImageFn = null;
const LAYOUT_BUDGET: usize = 100000;
var layoutCount: f32 = 0;

// ── Functions ──────────────────────────────────────

fn rgb(r: u8, g: u8, b: u8) Color {
    return .{ .r = r, .g = g, .b = b, .a = 255 };
}

fn rgba(r: u8, g: u8, b: u8, a: u8) Color {
    return .{ .r = r, .g = g, .b = b, .a = a };
}

pub fn setMeasureFn(f: ?MeasureTextFn) void {
    measureFn = f;
}

pub fn setMeasureImageFn(f: ?MeasureImageFn) void {
    measureImageFn = f;
}

fn padLeft(s: Style) f32 {
    return s.padding_left orelse s.padding;
}

fn padRight(s: Style) f32 {
    return s.padding_right orelse s.padding;
}

fn padTop(s: Style) f32 {
    return s.padding_top orelse s.padding;
}

fn padBottom(s: Style) f32 {
    return s.padding_bottom orelse s.padding;
}

fn marLeft(s: Style) f32 {
    return s.margin_left orelse s.margin;
}

fn marRight(s: Style) f32 {
    return s.margin_right orelse s.margin;
}

fn marTop(s: Style) f32 {
    return s.margin_top orelse s.margin;
}

fn marBottom(s: Style) f32 {
    return s.margin_bottom orelse s.margin;
}

fn resolveMaybePct(val: ?f32, parent: f32) ?f32 {
    if (val == null) {
        return null;
    }
    if (val.? < 0) {
        return (-val.?) * parent;
    }
    return val.?;
}

fn clampVal(val: f32, minVal: ?f32, maxVal: ?f32) f32 {
    var v = val;
    if (minVal != null and asF32(v) < asF32(minVal.?)) {
        v = minVal.?;
    }
    if (maxVal != null and asF32(v) > asF32(maxVal.?)) {
        v = maxVal.?;
    }
    return v;
}

fn measureNodeImage(node: *Node) ImageDims {
    if (node.image_src != null and measureImageFn != null) {
        return measureImageFn.?(node.image_src.?);
    }
    return .{ .width = 0, .height = 0 };
}

fn measureNodeText(node: *Node) TextMetrics {
    return measureNodeTextW(&node, 0);
}

fn measureNodeTextW(node: *Node, maxWidth: f32) TextMetrics {
    if (node.text != null and measureFn != null) {
        return measureFn.?(node.text.?, node.font_size, maxWidth, node.letter_spacing, node.line_height, node.number_of_lines, node.no_wrap);
    }
    return .{ .width = 0, .height = 0, .ascent = 0 };
}

fn estimateIntrinsicWidth(node: *Node) f32 {
    const s = node.style;
    if (s.width != null) {
        return s.width.?;
    }
    const pl = padLeft(&s);
    const pr = padRight(&s);
    const g = s.gap;
    const isRow = s.flex_direction == .row;
    if (node.text != null) {
        const m = measureNodeText(&node);
        return m.width + pl + pr;
    }
    if (node.image_src != null) {
        const dims = measureNodeImage(&node);
        return dims.width + pl + pr;
    }
    if (node.children.len == 0) {
        return pl + pr;
    }
    var total: f32 = 0;
    var maxCross: f32 = 0;
    var visibleCount: usize = 0;
    for (node.children) |child| {
        if (child.style.display == .none) {
            continue;
        }
        const cw = estimateIntrinsicWidth(&child);
        const cmL = marLeft(&child.style);
        const cmR = marRight(&child.style);
        if (isRow) {
            total += cw + cmL + cmR;
            visibleCount += 1;
        } else {
            const cross = cw + cmL + cmR;
            if (cross > maxCross) {
                maxCross = cross;
            }
        }
    }
    if (isRow) {
        const gaps = if (visibleCount > 1) g * @as(f32, @floatFromInt((visibleCount - 1))) else 0;
        return total + gaps + pl + pr;
    }
    return maxCross + pl + pr;
}

fn estimateIntrinsicHeight(node: *Node, availableWidth: f32) f32 {
    const s = node.style;
    if (s.height != null) {
        return s.height.?;
    }
    if (s.aspect_ratio != null and s.aspect_ratio.? > 0 and s.width != null) {
        return s.width.? / s.aspect_ratio.?;
    }
    const pt = padTop(&s);
    const pb = padBottom(&s);
    const pl = padLeft(&s);
    const pr = padRight(&s);
    const g = s.gap;
    const isRow = s.flex_direction == .row;
    const innerW = if (s.width != null) s.width.? - pl - pr else if (availableWidth > 0) availableWidth - pl - pr else 0;
    if (node.text != null) {
        const m = measureNodeTextW(&node, innerW);
        return m.height + pt + pb;
    }
    if (node.image_src != null) {
        const dims = measureNodeImage(&node);
        return dims.height + pt + pb;
    }
    if (node.input_id != null) {
        return @as(f32, @floatFromInt(node.font_size)) + pt + pb;
    }
    if (node.children.len == 0) {
        return pt + pb;
    }
    var total: f32 = 0;
    var maxCross: f32 = 0;
    var visibleCount: usize = 0;
    for (node.children) |child| {
        if (child.style.display == .none) {
            continue;
        }
        const ch = estimateIntrinsicHeight(&child, innerW);
        const cmT = marTop(&child.style);
        const cmB = marBottom(&child.style);
        if (!isRow) {
            total += ch + cmT + cmB;
            visibleCount += 1;
        } else {
            const cross = ch + cmT + cmB;
            if (cross > maxCross) {
                maxCross = cross;
            }
        }
    }
    if (!isRow) {
        const gaps = if (visibleCount > 1) g * @as(f32, @floatFromInt((visibleCount - 1))) else 0;
        return total + gaps + pt + pb;
    }
    if (s.flex_wrap == .wrap and innerW > 0) {
        var lineMain: f32 = 0;
        var lineCrossMax: f32 = 0;
        var totalCross: f32 = 0;
        var itemsOnLine: usize = 0;
        var lineCount: usize = 0;
        for (node.children) |child| {
            if (child.style.display == .none) {
                continue;
            }
            if (child.style.position == .absolute) {
                continue;
            }
            const cw = estimateIntrinsicWidth(&child);
            const cmL = marLeft(&child.style);
            const cmR = marRight(&child.style);
            const itemMain = cw + cmL + cmR;
            const gapBefore = if (itemsOnLine > 0) g else 0;
            if (itemsOnLine > 0 and (lineMain + gapBefore + itemMain) > innerW) {
                totalCross += lineCrossMax;
                lineCount += 1;
                lineMain = itemMain;
                lineCrossMax = estimateIntrinsicHeight(&child, innerW) + marTop(&child.style) + marBottom(&child.style);
                itemsOnLine = 1;
            } else {
                lineMain += gapBefore + itemMain;
                const chCross = estimateIntrinsicHeight(&child, innerW) + marTop(&child.style) + marBottom(&child.style);
                if (chCross > lineCrossMax) {
                    lineCrossMax = chCross;
                }
                itemsOnLine += 1;
            }
        }
        if (itemsOnLine > 0) {
            totalCross += lineCrossMax;
            lineCount += 1;
        }
        const lineGaps = if (lineCount > 1) g * @as(f32, @floatFromInt((lineCount - 1))) else 0;
        return totalCross + lineGaps + pt + pb;
    }
    return maxCross + pt + pb;
}

fn computeMinContentW(node: *Node) f32 {
    const s = node.style;
    const pl = padLeft(&s);
    const pr = padRight(&s);
    if (s.width != null) {
        return s.width.?;
    }
    if (node.text != null and measureFn != null) {
        var maxWordW: f32 = 0;
        var i: usize = 0;
        while (i < node.text.?.len) {
            while (i < node.text.?.len and (node.text.?[i] == ' ' or node.text.?[i] == '\n')) : (i += 1) {}
            if (i >= node.text.?.len) {
                break;
            }
            const wordStart = i;
            while (i < node.text.?.len and node.text.?[i] != ' ' and node.text.?[i] != '\n') : (i += 1) {}
            const word = node.text.?[@intCast(wordStart)..@intCast(i)];
            const m = measureFn.?(word, node.font_size, 0, node.letter_spacing, node.line_height, node.number_of_lines, false);
            if (m.width > maxWordW) {
                maxWordW = m.width;
            }
        }
        return maxWordW + pl + pr;
    }
    if (node.children.len == 0) {
        return pl + pr;
    }
    const isRow = s.flex_direction == .row;
    const g = s.gap;
    var minW: f32 = 0;
    var visCount: usize = 0;
    for (node.children) |child| {
        if (child.style.display == .none) {
            continue;
        }
        if (child.style.position == .absolute) {
            continue;
        }
        const childMin = computeMinContentW(&child);
        if (isRow) {
            minW += childMin;
            visCount += 1;
        } else {
            if (childMin > minW) {
                minW = childMin;
            }
        }
    }
    if (isRow and visCount > 1) {
        minW += @as(f32, @floatFromInt((visCount - 1))) * g;
    }
    return minW + pl + pr;
}

pub fn layoutNode(node: *Node, px: f32, py: f32, pw: f32, ph: f32) void {
    layoutCount += 1;
    if (layoutCount > LAYOUT_BUDGET) {
        return;
    }
    const s = node.style;
    if (s.display == .none) {
        node.computed = .{ .x = px, .y = py, .w = 0, .h = 0 };
        return;
    }
    var w: f32 = undefined;
    var h: ?f32 = null;
    if (node._flex_w != null) {
        w = node._flex_w.?;
        node._flex_w = null;
    } else {
        const resolved = resolveMaybePct(s.width, pw);
        w = if (resolved != null) resolved.? else pw;
    }
    w = clampVal(w, resolveMaybePct(s.min_width, pw), resolveMaybePct(s.max_width, pw));
    if (node._stretch_h != null) {
        h = node._stretch_h.?;
        node._stretch_h = null;
    } else {
        h = resolveMaybePct(s.height, ph);
    }
    if (h != null) {
        h.? = clampVal(h.?, resolveMaybePct(s.min_height, ph), resolveMaybePct(s.max_height, ph));
    }
    if (s.aspect_ratio != null and s.aspect_ratio.? > 0) {
        if (s.width != null and s.height == null and h == null) {
            h = w / s.aspect_ratio.?;
        } else if (s.height != null and s.width == null and node._flex_w == null) {
            if (h != null) {
                w = h.? * s.aspect_ratio.?;
                w = clampVal(w, resolveMaybePct(s.min_width, pw), resolveMaybePct(s.max_width, pw));
            }
        }
    }
    const pl = padLeft(&s);
    const pr = padRight(&s);
    const pt = padTop(&s);
    const pb = padBottom(&s);
    const ml = marLeft(&s);
    const mt = marTop(&s);
    const x = px + ml;
    const y = py + mt;
    const innerW = w - pl - pr;
    const innerH = if (h != null) h.? - pt - pb else 9999;
    const isRow = s.flex_direction == .row;
    const gap = s.gap;
    const justify = s.justify_content;
    const @"align" = s.align_items;
    const mainSize = if (isRow) innerW else innerH;
    const MAX_CHILDREN = 512;
    var childBasis: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childGrow: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childShrink: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childMainSize: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childCrossSize: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childMainMarginStart: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childMainMarginEnd: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childCrossMarginStart: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var childCrossMarginEnd: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
    var visibleIndices: []f32 = std.mem.zeroes([MAX_CHILDREN]usize);
    var visibleCount: usize = 0;
    var absoluteIndices: []f32 = std.mem.zeroes([MAX_CHILDREN]usize);
    var absoluteCount: usize = 0;
    {
        var i: usize = 0;
        while (i < node.children.len) : (i += 1) {
            const child = node.children[i];
            if (child.style.display == .none) {
                child.computed = .{ .x = 0, .y = 0, .w = 0, .h = 0 };
                continue;
            }
            if (child.style.position == .absolute) {
                if (absoluteCount < MAX_CHILDREN) {
                    absoluteIndices[absoluteCount] = i;
                    absoluteCount += 1;
                }
                continue;
            }
            if (visibleCount >= MAX_CHILDREN) {
                break;
            }
            const cs = child.style;
            const cw = resolveMaybePct(cs.width, innerW) orelse estimateIntrinsicWidth(&child);
            const chVal = resolveMaybePct(cs.height, innerH) orelse estimateIntrinsicHeight(&child, innerW);
            const cwClamped = clampVal(cw, resolveMaybePct(cs.min_width, innerW), resolveMaybePct(cs.max_width, innerW));
            const chClamped = clampVal(chVal, resolveMaybePct(cs.min_height, innerH), resolveMaybePct(cs.max_height, innerH));
            const grow = cs.flex_grow;
            const shrink = cs.flex_shrink orelse 1.0;
            const basis = resolveMaybePct(cs.flex_basis, if (isRow) innerW else innerH) orelse (if (isRow) cwClamped else chClamped);
            const cmL = marLeft(&cs);
            const cmR = marRight(&cs);
            const cmT = marTop(&cs);
            const cmB = marBottom(&cs);
            visibleIndices[visibleCount] = i;
            childBasis[visibleCount] = basis;
            childGrow[visibleCount] = grow;
            childShrink[visibleCount] = shrink;
            childMainSize[visibleCount] = if (isRow) cwClamped else chClamped;
            childCrossSize[visibleCount] = if (isRow) chClamped else cwClamped;
            childMainMarginStart[visibleCount] = if (isRow) cmL else cmT;
            childMainMarginEnd[visibleCount] = if (isRow) cmR else cmB;
            childCrossMarginStart[visibleCount] = if (isRow) cmT else cmL;
            childCrossMarginEnd[visibleCount] = if (isRow) cmB else cmR;
            visibleCount += 1;
        }
    }
    const MAX_LINES = 64;
    var lineStarts: []f32 = std.mem.zeroes([MAX_LINES]usize);
    var lineCounts: []f32 = std.mem.zeroes([MAX_LINES]usize);
    var numLines: usize = 0;
    if (s.flex_wrap == .wrap and visibleCount > 0) {
        var lineMain: f32 = 0;
        var lineStartIdx: usize = 0;
        var itemsOnLine: usize = 0;
        {
            var i: usize = 0;
            while (i < visibleCount) : (i += 1) {
                const itemMain = childBasis[i] + childMainMarginStart[i] + childMainMarginEnd[i];
                const gapBefore = if (itemsOnLine > 0) gap else 0;
                if (itemsOnLine > 0 and (lineMain + gapBefore + itemMain) > mainSize) {
                    if (numLines < MAX_LINES) {
                        lineStarts[numLines] = lineStartIdx;
                        lineCounts[numLines] = itemsOnLine;
                        numLines += 1;
                    }
                    lineStartIdx = i;
                    lineMain = itemMain;
                    itemsOnLine = 1;
                } else {
                    lineMain += gapBefore + itemMain;
                    itemsOnLine += 1;
                }
            }
        }
        if (itemsOnLine > 0 and numLines < MAX_LINES) {
            lineStarts[numLines] = lineStartIdx;
            lineCounts[numLines] = itemsOnLine;
            numLines += 1;
        }
    } else {
        lineStarts[0] = 0;
        lineCounts[0] = visibleCount;
        numLines = if (visibleCount > 0) 1 else 0;
    }
    var crossCursor: f32 = 0;
    var contentMainEnd: f32 = 0;
    var contentCrossEnd: f32 = 0;
    {
        var lineIdx: usize = 0;
        while (lineIdx < numLines) : (lineIdx += 1) {
            const ls = lineStarts[lineIdx];
            const lc = lineCounts[lineIdx];
            var totalBasis: f32 = 0;
            var totalFlex: f32 = 0;
            var totalMainMargin: f32 = 0;
            {
                var i = ls;
                while (i < ls + lc) : (i += 1) {
                    totalBasis += childBasis[@intCast(i)];
                    totalMainMargin += childMainMarginStart[@intCast(i)] + childMainMarginEnd[@intCast(i)];
                    if (childGrow[@intCast(i)] > 0) {
                        totalFlex += childGrow[@intCast(i)];
                    }
                }
            }
            const lineGaps = if (lc > 1) gap * (lc - 1) else 0;
            const freeSpace = mainSize - totalBasis - lineGaps - totalMainMargin;
            if (freeSpace > 0 and totalFlex > 0) {
                var frozen: []bool = std.mem.zeroes([MAX_CHILDREN]bool);
                var savedBasis: []f32 = std.mem.zeroes([MAX_CHILDREN]f32);
                {
                    var i = ls;
                    while (i < ls + lc) : (i += 1) {
                        frozen[@intCast(i)] = childGrow[@intCast(i)] <= 0;
                        savedBasis[@intCast(i)] = childBasis[@intCast(i)];
                    }
                }
                var passes: usize = 0;
                while (passes < 10) {
                    passes += 1;
                    var used: f32 = 0;
                    var activeFlex: f32 = 0;
                    {
                        var i = ls;
                        while (i < ls + lc) : (i += 1) {
                            if (frozen[@intCast(i)]) {
                                used += childBasis[@intCast(i)];
                            } else {
                                used += savedBasis[@intCast(i)];
                                activeFlex += childGrow[@intCast(i)];
                            }
                        }
                    }
                    if (activeFlex <= 0) {
                        break;
                    }
                    const space = mainSize - used - lineGaps - totalMainMargin;
                    if (space <= 0) {
                        break;
                    }
                    var anyClamped = false;
                    {
                        var i = ls;
                        while (i < ls + lc) : (i += 1) {
                            if (frozen[@intCast(i)]) {
                                continue;
                            }
                            childBasis[@intCast(i)] = savedBasis[@intCast(i)] + (childGrow[@intCast(i)] / activeFlex) * space;
                            const ci = visibleIndices[@intCast(i)];
                            const csG = node.children[@intCast(ci)].style;
                            const mn = resolveMaybePct(if (isRow) csG.min_width else csG.min_height, if (isRow) innerW else innerH);
                            const mx = resolveMaybePct(if (isRow) csG.max_width else csG.max_height, if (isRow) innerW else innerH);
                            const clampedVal = clampVal(childBasis[@intCast(i)], mn, mx);
                            if (clampedVal != childBasis[@intCast(i)]) {
                                childBasis[@intCast(i)] = clampedVal;
                                frozen[@intCast(i)] = true;
                                anyClamped = true;
                            }
                        }
                    }
                    if (!anyClamped) {
                        break;
                    }
                }
            } else if (freeSpace < 0) {
                var totalShrinkScaled: f32 = 0;
                {
                    var i = ls;
                    while (i < ls + lc) : (i += 1) {
                        totalShrinkScaled += childShrink[@intCast(i)] * childBasis[@intCast(i)];
                    }
                }
                if (totalShrinkScaled > 0) {
                    const shrinkOverflow = -freeSpace;
                    {
                        var i = ls;
                        while (i < ls + lc) : (i += 1) {
                            const amount = (childShrink[@intCast(i)] * childBasis[@intCast(i)] / totalShrinkScaled) * shrinkOverflow;
                            childBasis[@intCast(i)] -= amount;
                        }
                    }
                }
                if (isRow) {
                    {
                        var i = ls;
                        while (i < ls + lc) : (i += 1) {
                            const childIdx = visibleIndices[@intCast(i)];
                            const childNode = node.children[@intCast(childIdx)];
                            if (childNode.style.min_width != null) {
                                continue;
                            }
                            const mcw = computeMinContentW(&childNode);
                            if (childBasis[@intCast(i)] < mcw) {
                                childBasis[@intCast(i)] = mcw;
                            }
                        }
                    }
                }
            }
            {
                var i = ls;
                while (i < ls + lc) : (i += 1) {
                    const childIdx = visibleIndices[@intCast(i)];
                    const child = node.children[@intCast(childIdx)];
                    if (child.text == null) {
                        continue;
                    }
                    if (isRow) {
                        if (child.style.height != null) {
                            continue;
                        }
                        const finalW = clampVal(childBasis[@intCast(i)], resolveMaybePct(child.style.min_width, innerW), resolveMaybePct(child.style.max_width, innerW));
                        const prevW = childMainSize[@intCast(i)];
                        if (@abs(finalW - prevW) > 0.5) {
                            const cpl = padLeft(&child.style);
                            const cpr = padRight(&child.style);
                            const cpt = padTop(&child.style);
                            const cpb = padBottom(&child.style);
                            const constrainW = finalW - cpl - cpr;
                            const m = measureNodeTextW(&child, if (constrainW > 0) constrainW else 0);
                            childCrossSize[@intCast(i)] = clampVal(m.height + cpt + cpb, resolveMaybePct(child.style.min_height, innerH), resolveMaybePct(child.style.max_height, innerH));
                        }
                    } else {
                        const effAlign = resolveAlign(child.style.align_self, @"align");
                        const finalW = resolveMaybePct(child.style.width, innerW) orelse (if (effAlign == .stretch) innerW else childCrossSize[@intCast(i)]);
                        const cpl = padLeft(&child.style);
                        const cpr = padRight(&child.style);
                        const cpt = padTop(&child.style);
                        const cpb = padBottom(&child.style);
                        const constrainW = asF32(finalW) - asF32(cpl) - cpr;
                        const m = measureNodeTextW(&child, if (constrainW > 0) constrainW else 0);
                        const newH = clampVal(m.height + cpt + cpb, resolveMaybePct(child.style.min_height, innerH), resolveMaybePct(child.style.max_height, innerH));
                        if (child.style.height == null) {
                            childBasis[@intCast(i)] = newH;
                            childMainSize[@intCast(i)] = newH;
                        }
                        childCrossSize[@intCast(i)] = finalW;
                    }
                }
            }
            var lineCross: f32 = 0;
            {
                var i = ls;
                while (i < ls + lc) : (i += 1) {
                    const childCross = childCrossSize[@intCast(i)] + childCrossMarginStart[@intCast(i)] + childCrossMarginEnd[@intCast(i)];
                    if (childCross > lineCross) {
                        lineCross = childCross;
                    }
                }
            }
            if (numLines == 1) {
                if (isRow and h != null) {
                    lineCross = innerH;
                } else if (isRow and h == null) {
                    const mh = resolveMaybePct(s.min_height, ph);
                    if (mh != null) {
                        const minInner = mh.? - pt - pb;
                        if (minInner > lineCross) {
                            lineCross = minInner;
                        }
                    }
                } else if (!isRow) {
                    lineCross = innerW;
                }
            }
            var usedMain: f32 = 0;
            {
                var i = ls;
                while (i < ls + lc) : (i += 1) {
                    usedMain += childBasis[@intCast(i)] + childMainMarginStart[@intCast(i)] + childMainMarginEnd[@intCast(i)];
                }
            }
            const freeMain = mainSize - usedMain - lineGaps;
            var mainOffset: f32 = 0;
            var extraGap: f32 = 0;
            switch (justify) {
                .center => {
                    mainOffset = freeMain / 2;
                },
                .end => {
                    mainOffset = freeMain;
                },
                .space_between => {
                    if (lc > 1) {
                        extraGap = freeMain / (lc - 1);
                    }
                },
                .space_around => {
                    if (lc > 0) {
                        extraGap = freeMain / lc;
                        mainOffset = extraGap / 2;
                    }
                },
                .space_evenly => {
                    if (lc > 0) {
                        extraGap = freeMain / (lc + 1);
                        mainOffset = extraGap;
                    }
                },
                .start => {
                },
            }
            var cursor = mainOffset;
            {
                var i = ls;
                while (i < ls + lc) : (i += 1) {
                    const childIdx = visibleIndices[@intCast(i)];
                    const child = node.children[@intCast(childIdx)];
                    var cx: f32 = undefined;
                    var cy: f32 = undefined;
                    var cwFinal: f32 = undefined;
                    var chFinal: f32 = undefined;
                    const effAlign = resolveAlign(child.style.align_self, @"align");
                    if (isRow) {
                        cx = x + pl + cursor;
                        cwFinal = clampVal(childBasis[@intCast(i)], resolveMaybePct(child.style.min_width, innerW), resolveMaybePct(child.style.max_width, innerW));
                        chFinal = childCrossSize[@intCast(i)];
                        const crossAvail = lineCross - childCrossMarginStart[@intCast(i)] - childCrossMarginEnd[@intCast(i)];
                        switch (effAlign) {
                            .center => {
                                cy = y + pt + crossCursor + (crossAvail - chFinal) / 2;
                            },
                            .end => {
                                cy = y + pt + crossCursor + crossAvail - chFinal;
                            },
                            .stretch => {
                                cy = y + pt + crossCursor;
                                if (child.style.height == null) {
                                    chFinal = clampVal(crossAvail, resolveMaybePct(child.style.min_height, innerH), resolveMaybePct(child.style.max_height, innerH));
                                }
                            },
                            .start => {
                                cy = y + pt + crossCursor;
                            },
                        }
                    } else {
                        cy = y + pt + cursor;
                        chFinal = clampVal(childBasis[@intCast(i)], resolveMaybePct(child.style.min_height, innerH), resolveMaybePct(child.style.max_height, innerH));
                        cwFinal = childCrossSize[@intCast(i)];
                        const crossAvail = lineCross - childCrossMarginStart[@intCast(i)] - childCrossMarginEnd[@intCast(i)];
                        switch (effAlign) {
                            .center => {
                                cx = x + pl + crossCursor + (crossAvail - cwFinal) / 2;
                            },
                            .end => {
                                cx = x + pl + crossCursor + crossAvail - cwFinal;
                            },
                            .stretch => {
                                cx = x + pl + crossCursor;
                                if (child.style.width == null) {
                                    cwFinal = clampVal(crossAvail, resolveMaybePct(child.style.min_width, innerW), resolveMaybePct(child.style.max_width, innerW));
                                }
                            },
                            .start => {
                                cx = x + pl + crossCursor;
                            },
                        }
                    }
                    if (isRow) {
                        if (child.style.width == null or cwFinal != (child.style.width orelse 0)) {
                            child._flex_w = cwFinal;
                        }
                        if (child.style.height == null and effAlign == .stretch) {
                            child._stretch_h = chFinal;
                        }
                    } else {
                        if (child.style.height == null and child.style.flex_grow > 0) {
                            child._stretch_h = chFinal;
                        }
                        if (child.style.width == null and effAlign == .stretch) {
                            child._flex_w = cwFinal;
                        }
                    }
                    if (child.style.text_align == .left and s.text_align != .left) {
                        child.style.text_align = s.text_align;
                    }
                    child._parent_inner_w = innerW;
                    child._parent_inner_h = innerH;
                    layoutNode(&child, cx, cy, cwFinal, chFinal);
                    const actualMain = if (isRow) child.computed.w else child.computed.h;
                    cursor += childMainMarginStart[@intCast(i)] + actualMain + childMainMarginEnd[@intCast(i)] + gap + extraGap;
                    if (isRow) {
                        const me = (child.computed.x - x) + child.computed.w + childMainMarginEnd[@intCast(i)];
                        const ce = (child.computed.y - y) + child.computed.h + childCrossMarginEnd[@intCast(i)];
                        if (me > contentMainEnd) {
                            contentMainEnd = me;
                        }
                        if (ce > contentCrossEnd) {
                            contentCrossEnd = ce;
                        }
                    } else {
                        const me = (child.computed.y - y) + child.computed.h + childMainMarginEnd[@intCast(i)];
                        const ce = (child.computed.x - x) + child.computed.w + childCrossMarginEnd[@intCast(i)];
                        if (me > contentMainEnd) {
                            contentMainEnd = me;
                        }
                        if (ce > contentCrossEnd) {
                            contentCrossEnd = ce;
                        }
                    }
                }
            }
            crossCursor += lineCross + (if (lineIdx + 1 < numLines) gap else 0);
        }
    }
    if (h == null) {
        if (node.input_id != null) {
            h = @as(f32, @floatFromInt(node.font_size)) + pt + pb;
        } else if (node.text != null) {
            const m = measureNodeTextW(&node, innerW);
            h = m.height + pt + pb;
        } else if (isRow) {
            h = contentCrossEnd + pb;
        } else {
            h = contentMainEnd + pb;
        }
        if (h != null) {
            h.? = clampVal(h.?, resolveMaybePct(s.min_height, ph), resolveMaybePct(s.max_height, ph));
        }
    }
    if (s.overflow == .scroll or s.overflow == .hidden) {
        const fullContent = if (isRow) contentCrossEnd + pb else contentMainEnd + pb;
        node.content_height = fullContent;
    }
    const resolvedH = h orelse 0;
    {
        var ai: usize = 0;
        while (ai < absoluteCount) : (ai += 1) {
            const absIdx = absoluteIndices[ai];
            const absChild = node.children[@intCast(absIdx)];
            const acs = absChild.style;
            var absW: f32 = undefined;
            const resolvedW = resolveMaybePct(acs.width, innerW);
            if (resolvedW != null) {
                absW = resolvedW.?;
            } else if (acs.left != null and acs.right != null) {
                absW = innerW - (acs.left orelse 0) - (acs.right orelse 0);
            } else {
                absW = estimateIntrinsicWidth(&absChild);
            }
            absW = clampVal(absW, resolveMaybePct(acs.min_width, innerW), resolveMaybePct(acs.max_width, innerW));
            const absInnerH = resolvedH - pt - pb;
            var absH: f32 = undefined;
            const resolvedAH = resolveMaybePct(acs.height, absInnerH);
            if (resolvedAH != null) {
                absH = resolvedAH.?;
            } else if (acs.top != null and acs.bottom != null) {
                absH = absInnerH - (acs.top orelse 0) - (acs.bottom orelse 0);
            } else {
                absH = estimateIntrinsicHeight(&absChild, absW);
            }
            absH = clampVal(absH, resolveMaybePct(acs.min_height, absInnerH), resolveMaybePct(acs.max_height, absInnerH));
            var absX = x + pl;
            var absY = y + pt;
            if (acs.left != null) {
                absX = x + pl + acs.left.?;
            } else if (acs.right != null) {
                absX = asF32(x + pl + innerW - absW) - asF32(acs.right);
            }
            if (acs.top != null) {
                absY = y + pt + acs.top.?;
            } else if (acs.bottom != null) {
                absY = asF32(y + pt + absInnerH - absH) - asF32(acs.bottom);
            }
            absChild._flex_w = absW;
            absChild._stretch_h = absH;
            layoutNode(&absChild, absX, absY, absW, absH);
        }
    }
    node.computed = .{ .x = x, .y = y, .w = w, .h = resolvedH };
}

fn resolveAlign(self: AlignSelf, parent: AlignItems) AlignItems {
    switch (self) {
        .auto => {
            return parent;
        },
        .start => {
            return .start;
        },
        .center => {
            return .center;
        },
        .end => {
            return .end;
        },
        .stretch => {
            return .stretch;
        },
    }
}

pub fn layout(root: *Node, x: f32, y: f32, w: f32, h: f32) void {
    layoutCount = 0;
    root._flex_w = w;
    root._stretch_h = h;
    layoutNode(&root, x, y, w, h);
}
