//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/math_utils.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/math_utils.mod.tsz
//! To modify: edit math_utils.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Type definitions ────────────────────────────────
pub const Vec2 = struct {
    x: f32 = 0,
    y: f32 = 0,
};
pub const Vec3 = struct {
    x: f32 = 0,
    y: f32 = 0,
    z: f32 = 0,
};
pub const Vec4 = struct {
    x: f32 = 0,
    y: f32 = 0,
    z: f32 = 0,
    w: f32 = 0,
};
pub const Mat4 = [16]f32;
pub const Quat = Vec4;
pub const BBox2 = struct {
    min: Vec2 = .{},
    max: Vec2 = .{},
};
pub const BBox3 = struct {
    min: Vec3 = .{},
    max: Vec3 = .{},
};

// ── Module state ───────────────────────────────────
const EPSILON: f32 = 1e-6;
const PI: f32 = std.math.pi;

// ── Functions ──────────────────────────────────────

pub fn v2(x: f32, y: f32) Vec2 {
    return .{ .x = x, .y = y };
}

pub fn v2zero() Vec2 {
    return .{ .x = 0, .y = 0 };
}

pub fn v2one() Vec2 {
    return .{ .x = 1, .y = 1 };
}

pub fn v2add(a: Vec2, b: Vec2) Vec2 {
    return .{ .x = a.x + b.x, .y = a.y + b.y };
}

pub fn v2sub(a: Vec2, b: Vec2) Vec2 {
    return .{ .x = a.x - b.x, .y = a.y - b.y };
}

pub fn v2mul(a: Vec2, b: Vec2) Vec2 {
    return .{ .x = a.x * b.x, .y = a.y * b.y };
}

pub fn v2scale(v: Vec2, s: f32) Vec2 {
    return .{ .x = v.x * s, .y = v.y * s };
}

pub fn v2negate(v: Vec2) Vec2 {
    return .{ .x = -v.x, .y = -v.y };
}

pub fn v2dot(a: Vec2, b: Vec2) f32 {
    return a.x * b.x + a.y * b.y;
}

pub fn v2cross(a: Vec2, b: Vec2) f32 {
    return a.x * b.y - a.y * b.x;
}

pub fn v2length(v: Vec2) f32 {
    return @sqrt(v.x * v.x + v.y * v.y);
}

pub fn v2lengthSq(v: Vec2) f32 {
    return v.x * v.x + v.y * v.y;
}

pub fn v2distance(a: Vec2, b: Vec2) f32 {
    const dx = a.x - b.x;
    const dy = a.y - b.y;
    return @sqrt(dx * dx + dy * dy);
}

pub fn v2normalize(v: Vec2) Vec2 {
    const len = @sqrt(v.x * v.x + v.y * v.y);
    if (len > @as(f32, @floatFromInt(EPSILON))) {
        return .{ .x = v.x / len, .y = v.y / len };
    }
    return v2zero();
}

pub fn v2lerp(a: Vec2, b: Vec2, t: f32) Vec2 {
    return .{ .x = a.x + (b.x - a.x) * t, .y = a.y + (b.y - a.y) * t };
}

pub fn v2smoothstep(a: Vec2, b: Vec2, t: f32) Vec2 {
    const s = t * t * (3.0 - 2.0 * t);
    return .{ .x = a.x + (b.x - a.x) * s, .y = a.y + (b.y - a.y) * s };
}

pub fn v2angle(v: Vec2) f32 {
    return std.math.atan2(f32, v.y, v.x);
}

pub fn v2fromAngle(radians: f32) Vec2 {
    return .{ .x = @cos(radians), .y = @sin(radians) };
}

pub fn v2rotate(v: Vec2, radians: f32) Vec2 {
    const c = @cos(radians);
    const s = @sin(radians);
    return .{ .x = v.x * c - v.y * s, .y = v.x * s + v.y * c };
}

pub fn v2min(a: Vec2, b: Vec2) Vec2 {
    return .{ .x = @min(a.x, b.x), .y = @min(a.y, b.y) };
}

pub fn v2max(a: Vec2, b: Vec2) Vec2 {
    return .{ .x = @max(a.x, b.x), .y = @max(a.y, b.y) };
}

pub fn v2almostEquals(a: Vec2, b: Vec2, eps: f32) bool {
    return @abs(a.x - b.x) < eps and @abs(a.y - b.y) < eps;
}

pub fn v3(x: f32, y: f32, z: f32) Vec3 {
    return .{ .x = x, .y = y, .z = z };
}

pub fn v3zero() Vec3 {
    return .{ .x = 0, .y = 0, .z = 0 };
}

pub fn v3one() Vec3 {
    return .{ .x = 1, .y = 1, .z = 1 };
}

pub fn v3up() Vec3 {
    return .{ .x = 0, .y = 1, .z = 0 };
}

pub fn v3forward() Vec3 {
    return .{ .x = 0, .y = 0, .z = -1 };
}

pub fn v3right() Vec3 {
    return .{ .x = 1, .y = 0, .z = 0 };
}

pub fn v3add(a: Vec3, b: Vec3) Vec3 {
    return .{ .x = a.x + b.x, .y = a.y + b.y, .z = a.z + b.z };
}

pub fn v3sub(a: Vec3, b: Vec3) Vec3 {
    return .{ .x = a.x - b.x, .y = a.y - b.y, .z = a.z - b.z };
}

pub fn v3mul(a: Vec3, b: Vec3) Vec3 {
    return .{ .x = a.x * b.x, .y = a.y * b.y, .z = a.z * b.z };
}

pub fn v3scale(v: Vec3, s: f32) Vec3 {
    return .{ .x = v.x * s, .y = v.y * s, .z = v.z * s };
}

pub fn v3negate(v: Vec3) Vec3 {
    return .{ .x = -v.x, .y = -v.y, .z = -v.z };
}

pub fn v3dot(a: Vec3, b: Vec3) f32 {
    return a.x * b.x + a.y * b.y + a.z * b.z;
}

pub fn v3cross(a: Vec3, b: Vec3) Vec3 {
    return .{ .x = a.y * b.z - a.z * b.y, .y = a.z * b.x - a.x * b.z, .z = a.x * b.y - a.y * b.x };
}

pub fn v3length(v: Vec3) f32 {
    return @sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
}

pub fn v3lengthSq(v: Vec3) f32 {
    return v.x * v.x + v.y * v.y + v.z * v.z;
}

pub fn v3distance(a: Vec3, b: Vec3) f32 {
    const dx = a.x - b.x;
    const dy = a.y - b.y;
    const dz = a.z - b.z;
    return @sqrt(dx * dx + dy * dy + dz * dz);
}

pub fn v3normalize(v: Vec3) Vec3 {
    const len = @sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
    if (len > @as(f32, @floatFromInt(EPSILON))) {
        return .{ .x = v.x / len, .y = v.y / len, .z = v.z / len };
    }
    return v3zero();
}

pub fn v3lerp(a: Vec3, b: Vec3, t: f32) Vec3 {
    return .{ .x = a.x + (b.x - a.x) * t, .y = a.y + (b.y - a.y) * t, .z = a.z + (b.z - a.z) * t };
}

pub fn v3reflect(v: Vec3, normal: Vec3) Vec3 {
    const d = 2.0 * v3dot(&v, &normal);
    return .{ .x = v.x - d * normal.x, .y = v.y - d * normal.y, .z = v.z - d * normal.z };
}

pub fn v3min(a: Vec3, b: Vec3) Vec3 {
    return .{ .x = @min(a.x, b.x), .y = @min(a.y, b.y), .z = @min(a.z, b.z) };
}

pub fn v3max(a: Vec3, b: Vec3) Vec3 {
    return .{ .x = @max(a.x, b.x), .y = @max(a.y, b.y), .z = @max(a.z, b.z) };
}

pub fn v3almostEquals(a: Vec3, b: Vec3, eps: f32) bool {
    return @abs(a.x - b.x) < eps and @abs(a.y - b.y) < eps and @abs(a.z - b.z) < eps;
}

pub fn v4(x: f32, y: f32, z: f32, w: f32) Vec4 {
    return .{ .x = x, .y = y, .z = z, .w = w };
}

pub fn v4zero() Vec4 {
    return .{ .x = 0, .y = 0, .z = 0, .w = 0 };
}

pub fn v4add(a: Vec4, b: Vec4) Vec4 {
    return .{ .x = a.x + b.x, .y = a.y + b.y, .z = a.z + b.z, .w = a.w + b.w };
}

pub fn v4sub(a: Vec4, b: Vec4) Vec4 {
    return .{ .x = a.x - b.x, .y = a.y - b.y, .z = a.z - b.z, .w = a.w - b.w };
}

pub fn v4scale(v: Vec4, s: f32) Vec4 {
    return .{ .x = v.x * s, .y = v.y * s, .z = v.z * s, .w = v.w * s };
}

pub fn v4dot(a: Vec4, b: Vec4) f32 {
    return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
}

pub fn v4length(v: Vec4) f32 {
    return @sqrt(v.x * v.x + v.y * v.y + v.z * v.z + v.w * v.w);
}

pub fn v4normalize(v: Vec4) Vec4 {
    const len = @sqrt(v.x * v.x + v.y * v.y + v.z * v.z + v.w * v.w);
    if (len > @as(f32, @floatFromInt(EPSILON))) {
        return .{ .x = v.x / len, .y = v.y / len, .z = v.z / len, .w = v.w / len };
    }
    return v4zero();
}

pub fn v4lerp(a: Vec4, b: Vec4, t: f32) Vec4 {
    return .{ .x = a.x + (b.x - a.x) * t, .y = a.y + (b.y - a.y) * t, .z = a.z + (b.z - a.z) * t, .w = a.w + (b.w - a.w) * t };
}

pub fn m4identity() Mat4 {
    return .{ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 };
}

pub fn m4multiply(a: Mat4, b: Mat4) Mat4 {
    return .{ a[0] * b[0] + a[1] * b[4] + a[2] * b[8] + a[3] * b[12], a[0] * b[1] + a[1] * b[5] + a[2] * b[9] + a[3] * b[13], a[0] * b[2] + a[1] * b[6] + a[2] * b[10] + a[3] * b[14], a[0] * b[3] + a[1] * b[7] + a[2] * b[11] + a[3] * b[15], a[4] * b[0] + a[5] * b[4] + a[6] * b[8] + a[7] * b[12], a[4] * b[1] + a[5] * b[5] + a[6] * b[9] + a[7] * b[13], a[4] * b[2] + a[5] * b[6] + a[6] * b[10] + a[7] * b[14], a[4] * b[3] + a[5] * b[7] + a[6] * b[11] + a[7] * b[15], a[8] * b[0] + a[9] * b[4] + a[10] * b[8] + a[11] * b[12], a[8] * b[1] + a[9] * b[5] + a[10] * b[9] + a[11] * b[13], a[8] * b[2] + a[9] * b[6] + a[10] * b[10] + a[11] * b[14], a[8] * b[3] + a[9] * b[7] + a[10] * b[11] + a[11] * b[15], a[12] * b[0] + a[13] * b[4] + a[14] * b[8] + a[15] * b[12], a[12] * b[1] + a[13] * b[5] + a[14] * b[9] + a[15] * b[13], a[12] * b[2] + a[13] * b[6] + a[14] * b[10] + a[15] * b[14], a[12] * b[3] + a[13] * b[7] + a[14] * b[11] + a[15] * b[15] };
}

pub fn m4transpose(m: Mat4) Mat4 {
    return .{ m[0], m[4], m[8], m[12], m[1], m[5], m[9], m[13], m[2], m[6], m[10], m[14], m[3], m[7], m[11], m[15] };
}

pub fn m4determinant(m: Mat4) f32 {
    const b0 = m[0] * m[5] - m[1] * m[4];
    const b1 = m[0] * m[6] - m[2] * m[4];
    const b2 = m[0] * m[7] - m[3] * m[4];
    const b3 = m[1] * m[6] - m[2] * m[5];
    const b4 = m[1] * m[7] - m[3] * m[5];
    const b5 = m[2] * m[7] - m[3] * m[6];
    const b6 = m[8] * m[13] - m[9] * m[12];
    const b7 = m[8] * m[14] - m[10] * m[12];
    const b8 = m[8] * m[15] - m[11] * m[12];
    const b9 = m[9] * m[14] - m[10] * m[13];
    const b10 = m[9] * m[15] - m[11] * m[13];
    const b11 = m[10] * m[15] - m[11] * m[14];
    return b0 * b11 - b1 * b10 + b2 * b9 + b3 * b8 - b4 * b7 + b5 * b6;
}

pub fn m4translate(m: Mat4, v: Vec3) Mat4 {
    var out = m;
    out[3] = m[0] * v.x + m[1] * v.y + m[2] * v.z + m[3];
    out[7] = m[4] * v.x + m[5] * v.y + m[6] * v.z + m[7];
    out[11] = m[8] * v.x + m[9] * v.y + m[10] * v.z + m[11];
    out[15] = m[12] * v.x + m[13] * v.y + m[14] * v.z + m[15];
    return out;
}

pub fn m4scale(m: Mat4, v: Vec3) Mat4 {
    return .{ m[0] * v.x, m[1] * v.y, m[2] * v.z, m[3], m[4] * v.x, m[5] * v.y, m[6] * v.z, m[7], m[8] * v.x, m[9] * v.y, m[10] * v.z, m[11], m[12] * v.x, m[13] * v.y, m[14] * v.z, m[15] };
}

pub fn m4lookAt(eye: Vec3, target: Vec3, up: Vec3) Mat4 {
    var fx = eye.x - target.x;
    var fy = eye.y - target.y;
    var fz = eye.z - target.z;
    var len = @sqrt(fx * fx + fy * fy + fz * fz);
    if (len > @as(f32, @floatFromInt(EPSILON))) {
        fx;
        / = len;
        fy;
        / = len;
        fz;
        / = len;
    }
    var sx = up.y * fz - up.z * fy;
    var sy = up.z * fx - up.x * fz;
    var sz = up.x * fy - up.y * fx;
    len = @sqrt(sx * sx + sy * sy + sz * sz);
    if (len > @as(f32, @floatFromInt(EPSILON))) {
        sx;
        / = len;
        sy;
        / = len;
        sz;
        / = len;
    }
    const ux = fy * sz - fz * sy;
    const uy = fz * sx - fx * sz;
    const uz = fx * sy - fy * sx;
    return .{ .sx = sx, .sy = sy, .sz = sz, -(sx * eye.x + sy * eye.y + sz * eye.z), .ux = ux, .uy = uy, .uz = uz, -(ux * eye.x + uy * eye.y + uz * eye.z), .fx = fx, .fy = fy, .fz = fz, -(fx * eye.x + fy * eye.y + fz * eye.z), 0, 0, 0, 1 };
}

pub fn m4perspective(fov_radians: f32, aspect: f32, near: f32, far: f32) Mat4 {
    const f = 1.0 / @tan(fov_radians / 2.0);
    const ri = 1.0 / (near - far);
    return .{ f, /, .aspect = aspect, 0, 0, 0, 0, .f = f, 0, 0, 0, 0, (near + far) * ri, 2.0 * near * far * ri, 0, 0, -1, 0 };
}

pub fn m4ortho(left: f32, right: f32, bottom: f32, top: f32, near: f32, far: f32) Mat4 {
    const rl = 1.0 / (right - left);
    const tb = 1.0 / (top - bottom);
    const nf = 1.0 / (near - far);
    return .{ 2.0 * rl, 0, 0, -(right + left) * rl, 0, 2.0 * tb, 0, -(top + bottom) * tb, 0, 0, 2.0 * nf, (far + near) * nf, 0, 0, 0, 1 };
}

pub fn m4transformPoint(m: Mat4, v: Vec3) Vec3 {
    const w = m[12] * v.x + m[13] * v.y + m[14] * v.z + m[15];
    const inv_w = if (@abs(w) > @as(f32, @floatFromInt(EPSILON))) 1.0 / w else 1.0;
    return .{ .x = (m[0] * v.x + m[1] * v.y + m[2] * v.z + m[3]) * inv_w, .y = (m[4] * v.x + m[5] * v.y + m[6] * v.z + m[7]) * inv_w, .z = (m[8] * v.x + m[9] * v.y + m[10] * v.z + m[11]) * inv_w };
}

pub fn m4transformDir(m: Mat4, v: Vec3) Vec3 {
    return .{ .x = m[0] * v.x + m[1] * v.y + m[2] * v.z, .y = m[4] * v.x + m[5] * v.y + m[6] * v.z, .z = m[8] * v.x + m[9] * v.y + m[10] * v.z };
}

pub fn quatIdentity() Quat {
    return .{ .x = 0, .y = 0, .z = 0, .w = 1 };
}

pub fn quatMultiply(a: Quat, b: Quat) Quat {
    return .{ .x = a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y, .y = a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x, .z = a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w, .w = a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z };
}

pub fn quatConjugate(q: Quat) Quat {
    return .{ .x = -q.x, .y = -q.y, .z = -q.z, .w = q.w };
}

pub fn quatInverse(q: Quat) Quat {
    const len_sq = q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w;
    if (len_sq < @as(f32, @floatFromInt(EPSILON))) {
        return quatIdentity();
    }
    const inv = 1.0 / len_sq;
    return .{ .x = -q.x * inv, .y = -q.y * inv, .z = -q.z * inv, .w = q.w * inv };
}

pub fn quatNormalize(q: Quat) Quat {
    const len = @sqrt(q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w);
    if (len > @as(f32, @floatFromInt(EPSILON))) {
        return .{ .x = q.x / len, .y = q.y / len, .z = q.z / len, .w = q.w / len };
    }
    return quatIdentity();
}

pub fn quatFromAxisAngle(axis: Vec3, radians: f32) Quat {
    const half = radians * 0.5;
    const s = @sin(half);
    const len = @sqrt(axis.x * axis.x + axis.y * axis.y + axis.z * axis.z);
    if (len < @as(f32, @floatFromInt(EPSILON))) {
        return quatIdentity();
    }
    const inv = s / len;
    return .{ .x = axis.x * inv, .y = axis.y * inv, .z = axis.z * inv, .w = @cos(half) };
}

pub fn quatFromEuler(x: f32, y: f32, z: f32) Quat {
    const cx = @cos(x * 0.5);
    const sx = @sin(x * 0.5);
    const cy = @cos(y * 0.5);
    const sy = @sin(y * 0.5);
    const cz = @cos(z * 0.5);
    const sz = @sin(z * 0.5);
    return .{ .x = sx * cy * cz + cx * sy * sz, .y = cx * sy * cz - sx * cy * sz, .z = cx * cy * sz + sx * sy * cz, .w = cx * cy * cz - sx * sy * sz };
}

pub fn quatSlerp(a: Quat, b: Quat, t: f32) Quat {
    var d = a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
    var bx = b.x;
    var by = b.y;
    var bz = b.z;
    var bw = b.w;
    if (d < 0.0) {
        d = -d;
        bx = -bx;
        by = -by;
        bz = -bz;
        bw = -bw;
    }
    if (d > @as(f32, @floatFromInt(1.0 - EPSILON))) {
        return quatNormalize(&.{ .x = a.x + (bx - a.x) * t, .y = a.y + (by - a.y) * t, .z = a.z + (bz - a.z) * t, .w = a.w + (bw - a.w) * t });
    }
    const theta = std.math.acos(d);
    const sin_theta = @sin(theta);
    const wa = @sin((1.0 - t) * theta) / sin_theta;
    const wb = @sin(t * theta) / sin_theta;
    return .{ .x = a.x * wa + bx * wb, .y = a.y * wa + by * wb, .z = a.z * wa + bz * wb, .w = a.w * wa + bw * wb };
}

pub fn quatRotateVec3(q: Quat, v: Vec3) Vec3 {
    const tx = 2.0 * (q.y * v.z - q.z * v.y);
    const ty = 2.0 * (q.z * v.x - q.x * v.z);
    const tz = 2.0 * (q.x * v.y - q.y * v.x);
    return .{ .x = v.x + q.w * tx + q.y * tz - q.z * ty, .y = v.y + q.w * ty + q.z * tx - q.x * tz, .z = v.z + q.w * tz + q.x * ty - q.y * tx };
}

pub fn bbox2(min_x: f32, min_y: f32, max_x: f32, max_y: f32) BBox2 {
    return .{ .min = .{ .x = min_x, .y = min_y }, .max = .{ .x = max_x, .y = max_y } };
}

pub fn bbox2width(b: BBox2) f32 {
    return b.max.x - b.min.x;
}

pub fn bbox2height(b: BBox2) f32 {
    return b.max.y - b.min.y;
}

pub fn bbox2center(b: BBox2) Vec2 {
    return .{ .x = (b.min.x + b.max.x) / 2.0, .y = (b.min.y + b.max.y) / 2.0 };
}

pub fn bbox2containsPoint(b: BBox2, p: Vec2) bool {
    return p.x >= b.min.x and p.x <= b.max.x and p.y >= b.min.y and p.y <= b.max.y;
}

pub fn bbox2intersects(a: BBox2, b: BBox2) bool {
    return a.min.x <= b.max.x and a.max.x >= b.min.x and a.min.y <= b.max.y and a.max.y >= b.min.y;
}

pub fn bbox2union(a: BBox2, b: BBox2) BBox2 {
    return .{ .min = .{ .x = @min(a.min.x, b.min.x), .y = @min(a.min.y, b.min.y) }, .max = .{ .x = @max(a.max.x, b.max.x), .y = @max(a.max.y, b.max.y) } };
}

pub fn bbox2expand(b: BBox2, amount: f32) BBox2 {
    return .{ .min = .{ .x = b.min.x - amount, .y = b.min.y - amount }, .max = .{ .x = b.max.x + amount, .y = b.max.y + amount } };
}

pub fn bbox3(min_x: f32, min_y: f32, min_z: f32, max_x: f32, max_y: f32, max_z: f32) BBox3 {
    return .{ .min = .{ .x = min_x, .y = min_y, .z = min_z }, .max = .{ .x = max_x, .y = max_y, .z = max_z } };
}

pub fn bbox3containsPoint(b: BBox3, p: Vec3) bool {
    return p.x >= b.min.x and p.x <= b.max.x and p.y >= b.min.y and p.y <= b.max.y and p.z >= b.min.z and p.z <= b.max.z;
}

pub fn bbox3intersects(a: BBox3, b: BBox3) bool {
    return a.min.x <= b.max.x and a.max.x >= b.min.x and a.min.y <= b.max.y and a.max.y >= b.min.y and a.min.z <= b.max.z and a.max.z >= b.min.z;
}

pub fn lerp(a: f32, b: f32, t: f32) f32 {
    return a + (b - a) * t;
}

pub fn smoothstep(edge0: f32, edge1: f32, x: f32) f32 {
    const t = std.math.clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);
    return t * t * (3.0 - 2.0 * t);
}

pub fn inverseLerp(a: f32, b: f32, v: f32) f32 {
    if (@abs(b - a) < @as(f32, @floatFromInt(EPSILON))) {
        return 0.0;
    }
    return (v - a) / (b - a);
}

pub fn remap(in_min: f32, in_max: f32, out_min: f32, out_max: f32, v: f32) f32 {
    const t = inverseLerp(in_min, in_max, v);
    return lerp(out_min, out_max, t);
}

pub fn clamp(v: f32, lo: f32, hi: f32) f32 {
    return std.math.clamp(v, lo, hi);
}

pub fn toRadians(degrees: f32) f32 {
    return degrees * @as(f32, @floatFromInt(PI)) / 180.0;
}

pub fn toDegrees(radians: f32) f32 {
    return radians * 180.0 / @as(f32, @floatFromInt(PI));
}
