//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/mpv.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/mpv.mod.tsz
//! To modify: edit mpv.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Module state ───────────────────────────────────
var g_handle: ?*c.mpv_handle = null;

// ── Functions ──────────────────────────────────────

fn ensureInit() bool {
    if (g_handle != null) {
        return true;
    }
    const handle = c.mpv_create() orelse return false;
    _ = c.mpv_set_option_string(handle, "vo", "gpu");
    _ = c.mpv_set_option_string(handle, "hwdec", "auto");
    _ = c.mpv_set_option_string(handle, "keep-open", "yes");
    _ = c.mpv_set_option_string(handle, "osd-level", "1");
    _ = c.mpv_set_option_string(handle, "terminal", "no");
    _ = c.mpv_set_option_string(handle, "input-default-bindings", "yes");
    _ = c.mpv_set_option_string(handle, "input-vo-keyboard", "yes");
    if (c.mpv_initialize(handle) < 0) {
        c.mpv_terminate_destroy(handle);
        return false;
    }
    g_handle = handle;
    std.debug.print("[mpv] Initialized\n", .{  });
    return true;
}

pub fn play(path: [*:0]const u8) void {
    if (!ensureInit()) {
        std.debug.print("[mpv] Failed to initialize\n", .{  });
        return;
    }
    const handle = g_handle.?;
    var cmd: [3:null]?[*:0]const u8 = .{ "loadfile", .path = path, "replace" };
    const err = c.mpv_command(handle, @ptrCast(&cmd));
    if (err < 0) {
        std.debug.print("[mpv] loadfile failed: {s}\n", .{ c.mpv_error_string(err) });
        return;
    }
    _ = c.mpv_set_option_string(handle, "pause", "no");
    std.debug.print("[mpv] Playing: {s}\n", .{ .path = path });
}

pub fn stop() void {
    if (g_handle) |handle| {
        var cmd: [1:null]?[*:0]const u8 = .{ "stop" };
        _ = c.mpv_command(handle, @ptrCast(&cmd));
    }
}

pub fn setPaused(paused: bool) void {
    if (g_handle) |handle| {
        _ = c.mpv_set_option_string(handle, "pause", if (paused) "yes" else "no");
    }
}

pub fn poll() void {
    if (g_handle) |handle| {
        while (true) {
            const ev = c.mpv_wait_event(handle, 0);
            if (ev.*.event_id == c.MPV_EVENT_NONE) {
                break;
            }
            if (ev.*.event_id == c.MPV_EVENT_SHUTDOWN) {
                c.mpv_terminate_destroy(handle);
                g_handle = null;
                std.debug.print("[mpv] Window closed by user\n", .{  });
                return;
            }
        }
    }
}

pub fn deinit() void {
    if (g_handle) |handle| {
        c.mpv_terminate_destroy(handle);
        g_handle = null;
        std.debug.print("[mpv] Destroyed\n", .{  });
    }
}
