//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/permit.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/permit.mod.tsz
//! To modify: edit permit.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Type definitions ────────────────────────────────
pub const Category = enum { clipboard, storage, gpu, sysmon, browse, network, filesystem, ipc, process };
pub const PermitEntry = struct {
    buf: [MAX_ENTRY_LEN]u8,
    len: u8 = 0,
};
pub const CategoryPermit = struct {
    enabled: bool = false,
    is_bool: bool = false,
    bool_value: bool = false,
    entries: [MAX_ENTRIES_PER_CATEGORY]PermitEntry,
    entry_count: u8 = 0,
};

// ── Module state ───────────────────────────────────
const MAX_CATEGORIES: usize = 9;
const MAX_ENTRIES_PER_CATEGORY: usize = 32;
const MAX_ENTRY_LEN: usize = 128;
var permits: [MAX_CATEGORIES]CategoryPermit = undefined;
var minted: bool = false;
var enforcing: bool = false;
var quarantined: bool = false;
var quarantine_reason_buf: [256]u8 = undefined;
var quarantine_reason_len: u8 = 0;
var user_overrides: [MAX_CATEGORIES]bool = undefined;
var user_override_set: [MAX_CATEGORIES]bool = undefined;

// ── Functions ──────────────────────────────────────

pub fn init() void {
    minted = false;
    enforcing = false;
    quarantined = false;
    quarantine_reason_len = 0;
    {
        var i: usize = 0;
        while (i < MAX_CATEGORIES) : (i += 1) {
            permits[i] = .{ .enabled = false, .is_bool = false, .bool_value = false, .entries = null, .entry_count = 0 };
            user_overrides[i] = false;
            user_override_set[i] = false;
        }
    }
}

pub fn setCapBool(cat: Category, value: bool) void {
    if (minted) {
        return;
    }
    const idx: usize = @intFromEnum(cat);
    permits[idx].enabled = true;
    permits[idx].is_bool = true;
    permits[idx].bool_value = value;
}

pub fn addCapEntry(cat: Category, entry: []const u8) void {
    if (minted) {
        return;
    }
    const idx: usize = @intFromEnum(cat);
    permits[idx].enabled = true;
    permits[idx].is_bool = false;
    const ec = permits[idx].entry_count;
    if (ec >= MAX_ENTRIES_PER_CATEGORY) {
        return;
    }
    const copy_len: u8 = @intCast(@min(entry.len, MAX_ENTRY_LEN));
    @memcpy(permits[idx].entries[ec].buf[0..copy_len], entry[0..copy_len]);
    permits[idx].entries[ec].len = copy_len;
    permits[idx].entry_count = ec + 1;
}

pub fn freeze() void {
    if (minted) {
        return;
    }
    minted = true;
    enforcing = true;
    std.debug.print("[permit] Permit table minted — enforcement active\n", .{  });
}

pub fn check(cat: Category) bool {
    if (quarantined) {
        return false;
    }
    const idx: usize = @intFromEnum(cat);
    if (user_override_set[idx] and !user_overrides[idx]) {
        return false;
    }
    if (!enforcing) {
        return true;
    }
    if (!permits[idx].enabled) {
        return false;
    }
    if (permits[idx].is_bool) {
        return permits[idx].bool_value;
    }
    return permits[idx].entry_count > 0;
}

pub fn checkEntry(cat: Category, entry: []const u8) bool {
    if (quarantined) {
        return false;
    }
    const idx: usize = @intFromEnum(cat);
    if (user_override_set[idx] and !user_overrides[idx]) {
        return false;
    }
    if (!enforcing) {
        return true;
    }
    if (!permits[idx].enabled) {
        return false;
    }
    if (permits[idx].is_bool) {
        return permits[idx].bool_value;
    }
    {
        var i: usize = 0;
        while (i < permits[idx].entry_count) : (i += 1) {
            const e = &permits[idx].entries[i];
            const e_str = e.buf[0..e.len];
            if (std.mem.eql(u8, e_str, entry) or std.mem.eql(u8, e_str, "*")) {
                return true;
            }
            if (cat == .filesystem and entry.len >= e_str.len) {
                if (std.mem.startsWith(u8, entry, e_str)) {
                    return true;
                }
            }
        }
    }
    return false;
}

pub fn setUserOverride(cat: Category, blocked: bool) void {
    const idx: usize = @intFromEnum(cat);
    user_override_set[idx] = true;
    user_overrides[idx] = !blocked;
}

pub fn clearUserOverride(cat: Category) void {
    const idx: usize = @intFromEnum(cat);
    user_override_set[idx] = false;
}

pub fn clearAllUserOverrides() void {
    {
        var i: usize = 0;
        while (i < MAX_CATEGORIES) : (i += 1) {
            user_override_set[i] = false;
        }
    }
}

pub fn quarantine(reason: []const u8) void {
    quarantined = true;
    quarantine_reason_len = @intCast(@min(reason.len, 256));
    @memcpy(quarantine_reason_buf[0..quarantine_reason_len], reason[0..quarantine_reason_len]);
}

pub fn isQuarantined() bool {
    return quarantined;
}

pub fn getQuarantineReason() []const u8 {
    return quarantine_reason_buf[0..quarantine_reason_len];
}

pub fn isEnforcing() bool {
    return enforcing;
}

pub fn isFrozen() bool {
    return minted;
}

pub fn isCategoryEnabled(cat: Category) bool {
    return permits[@intFromEnum(cat)].enabled;
}
