//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/syntax.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/syntax.mod.tsz
//! To modify: edit syntax.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Imports ────────────────────────────────────────
const layout = @import("layout.zig");
const Color = layout.Color;
const text = @import("text.zig");
const ColorSpan = text.ColorSpan;

// ── Type definitions ────────────────────────────────
pub const Language = enum { zig, typescript, json, bash, markdown, plain };

// ── Module state ───────────────────────────────────
const C_keyword = Color.rgb(203, 166, 247);
const C_string = Color.rgb(166, 227, 161);
const C_number = Color.rgb(250, 179, 135);
const C_comment = Color.rgb(108, 112, 134);
const C_function_name = Color.rgb(137, 180, 250);
const C_type_name = Color.rgb(148, 226, 213);
const C_operator = Color.rgb(148, 226, 213);
const C_punctuation = Color.rgb(147, 153, 178);
const C_text = Color.rgb(205, 214, 244);
const C_tag = Color.rgb(137, 180, 250);
const C_attribute = Color.rgb(250, 179, 135);
const C_builtin = Color.rgb(250, 179, 135);
const C_variable = Color.rgb(243, 139, 168);
const C_heading = Color.rgb(137, 180, 250);
const C_bold_text = Color.rgb(250, 179, 135);
const C_link = Color.rgb(148, 226, 213);
const ts_keywords = [_] string { "const", "let", "var", "function", "return", "if", "else", "for", "while", "switch", "case", "break", "continue", "import", "export", "from", "default", "class", "extends", "new", "this", "typeof", "instanceof", "in", "of", "async", "await", "try", "catch", "throw", "finally", "yield", "true", "false", "null", "undefined", "void", "type", "interface", "enum", "declare", "readonly", "as", "do", "delete", "super", "with", "static", "implements", "abstract", "private", "protected", "public", "satisfies", };
const zig_keywords = [_] string { "const", "var", "fn", "return", "if", "else", "while", "for", "switch", "break", "continue", "pub", "struct", "enum", "union", "error", "try", "catch", "defer", "errdefer", "comptime", "inline", "test", "usingnamespace", "orelse", "and", "or", "unreachable", "undefined", "true", "false", "null", "threadlocal", "extern", "align", "volatile", "allowzero", "noalias", "nosuspend", "suspend", "resume", "async", "await", "anyframe", "anytype", "anyerror", "linksection", };
const zig_types = [_] string { "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64", "i128", "isize", "f16", "f32", "f64", "f128", "bool", "void", "noreturn", "type", "comptime_int", "comptime_float", };
const bash_keywords = [_] string { "if", "then", "else", "elif", "fi", "for", "while", "do", "done", "case", "esac", "function", "in", "return", "export", "local", "source", "declare", "readonly", "unset", "set", "shift", "select", "until", "trap", "break", "continue", "exit", "eval", "exec", };

// ── Functions ──────────────────────────────────────

pub fn languageFromString(s: []const u8) Language {
    if (std.mem.eql(u8, s, "zig")) {
        return .zig;
    }
    if (std.mem.eql(u8, s, "typescript") or std.mem.eql(u8, s, "ts") or std.mem.eql(u8, s, "tsx") or std.mem.eql(u8, s, "jsx") or std.mem.eql(u8, s, "javascript") or std.mem.eql(u8, s, "js")) {
        return .typescript;
    }
    if (std.mem.eql(u8, s, "json")) {
        return .json;
    }
    if (std.mem.eql(u8, s, "bash") or std.mem.eql(u8, s, "sh") or std.mem.eql(u8, s, "shell") or std.mem.eql(u8, s, "zsh")) {
        return .bash;
    }
    if (std.mem.eql(u8, s, "markdown") or std.mem.eql(u8, s, "md")) {
        return .markdown;
    }
    return .plain;
}

pub fn tokenizeLine(line: []const u8, lang: Language, out: []ColorSpan) usize {
    return switch (lang) { .typescript => tokenizeTypeScript(line, &out), .zig => tokenizeZig(line, &out), .json => tokenizeJSON(line, &out), .bash => tokenizeBash(line, &out), .markdown => tokenizeMarkdown(line, &out), .plain => tokenizePlain(line, &out) };
}

fn isAlpha(ch: u8) bool {
    return (ch >= "a" and ch <= "z") or (ch >= "A" and ch <= "Z") or ch == '_';
}

fn isDigit(ch: u8) bool {
    return ch >= "0" and ch <= "9";
}

fn isAlnum(ch: u8) bool {
    return isAlpha(ch) or isDigit(ch);
}

fn isHexDigit(ch: u8) bool {
    return isDigit(ch) or (ch >= "a" and ch <= "f") or (ch >= "A" and ch <= "F");
}

fn isUpper(ch: u8) bool {
    return ch >= "A" and ch <= "Z";
}

fn isSpace(ch: u8) bool {
    return ch == ' ' or ch == '\t';
}

fn emit(out: []ColorSpan, count: *usize, text: []const u8, color: Color) void {
    if (count.* < out.len and text.len > 0) {
        out[count.*] = .{ .text = text, .color = color };
        count.* += 1;
    }
}

fn inWordList(word: []const u8, list: []const string) bool {
    for (list) |kw| {
        if (std.mem.eql(u8, word, kw)) {
            return true;
        }
    }
    return false;
}

fn tokenizeTypeScript(line: []const u8, out: []ColorSpan) usize {
    var count: usize = 0;
    var i: usize = 0;
    while (i < line.len and count < out.len) {
        const ch = line[i];
        if (isSpace(ch)) {
            const start = i;
            while (i < line.len and isSpace(line[i])) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_text);
            continue;
        }
        if (ch == '/' and i + 1 < line.len and line[i + 1] == '/') {
            emit(&out, &count, line[i..], C_comment);
            return count;
        }
        if (ch == '/' and i + 1 < line.len and line[i + 1] == '*') {
            const start = i;
            i += 2;
            while (i + 1 < line.len) {
                if (line[i] == '*' and line[i + 1] == '/') {
                    i += 2;
                    break;
                }
                i += 1;
            }
            @"else";
            .{ i, =, line.len, ;, // unclosed — rest of line is comment };
            emit(&out, &count, line[start..i], C_comment);
            continue;
        }
        if (ch == '"' or ch == '\'' or ch == '`') {
            const start = i;
            const quote = ch;
            i += 1;
            while (i < line.len) {
                if (line[i] == '\\' and i + 1 < line.len) {
                    i += 2;
                } else if (line[i] == quote) {
                    i += 1;
                    break;
                } else {
                    i += 1;
                }
            }
            emit(&out, &count, line[start..i], C_string);
            continue;
        }
        if (isDigit(ch) or (ch == '.' and i + 1 < line.len and isDigit(line[i + 1]))) {
            const start = i;
            if (ch == '0' and i + 1 < line.len and (line[i + 1] == 'x' or line[i + 1] == 'X')) {
                i += 2;
                while (i < line.len and isHexDigit(line[i])) {
                    i += 1;
                }
            } else if (ch == '0' and i + 1 < line.len and (line[i + 1] == 'b' or line[i + 1] == 'B')) {
                i += 2;
                while (i < line.len and (line[i] == '0' or line[i] == '1')) {
                    i += 1;
                }
            } else {
                while (i < line.len and (isDigit(line[i]) or line[i] == '.')) {
                    i += 1;
                }
                if (i < line.len and (line[i] == 'e' or line[i] == 'E')) {
                    i += 1;
                    if (i < line.len and (line[i] == '+' or line[i] == '-')) {
                        i += 1;
                    }
                    while (i < line.len and isDigit(line[i])) {
                        i += 1;
                    }
                }
            }
            if (i < line.len and line[i] == 'n') {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_number);
            continue;
        }
        if (ch == '<') {
            if (i + 1 < line.len and (isUpper(line[i + 1]) or line[i + 1] == '/')) {
                const start = i;
                i += 1;
                if (i < line.len and line[i] == '/') {
                    i += 1;
                }
                while (i < line.len and isAlnum(line[i])) {
                    i += 1;
                }
                emit(&out, &count, line[start..i], C_tag);
                while (i < line.len and line[i] != '>') {
                    if (isAlpha(line[i])) {
                        const attr_start = i;
                        while (i < line.len and isAlnum(line[i])) {
                            i += 1;
                        }
                        emit(&out, &count, line[attr_start..i], C_attribute);
                    } else if (line[i] == '=' or line[i] == '{' or line[i] == '}') {
                        emit(&out, &count, line[i..i + 1], C_punctuation);
                        i += 1;
                    } else if (line[i] == '"' or line[i] == '\'') {
                        const qs = i;
                        const q = line[i];
                        i += 1;
                        while (i < line.len and line[i] != q) {
                            i += 1;
                        }
                        if (i < line.len) {
                            i += 1;
                        }
                        emit(&out, &count, line[qs..i], C_string);
                    } else if (line[i] == '/') {
                        emit(&out, &count, line[i..i + 1], C_tag);
                        i += 1;
                    } else if (isSpace(line[i])) {
                        const ws = i;
                        while (i < line.len and isSpace(line[i])) {
                            i += 1;
                        }
                        emit(&out, &count, line[ws..i], C_text);
                    } else {
                        i += 1;
                    }
                }
                if (i < line.len and line[i] == '>') {
                    emit(&out, &count, line[i..i + 1], C_tag);
                    i += 1;
                }
                continue;
            }
        }
        if (isAlpha(ch)) {
            const start = i;
            while (i < line.len and isAlnum(line[i])) {
                i += 1;
            }
            const word = line[start..i];
            if (inWordList(word, &ts_keywords)) {
                emit(&out, &count, word, C_keyword);
            } else if (isUpper(word[0])) {
                emit(&out, &count, word, C_type_name);
            } else if (i < line.len and line[i] == '(') {
                emit(&out, &count, word, C_function_name);
            } else {
                emit(&out, &count, word, C_text);
            }
            continue;
        }
        if (ch == '=' or ch == '!' or ch == '+' or ch == '-' or ch == '*' or ch == '/' or ch == '%' or ch == '&' or ch == '|' or ch == '^' or ch == '~' or ch == '<' or ch == '>' or ch == '?') {
            const start = i;
            i += 1;
            while (i < line.len and (line[i] == '=' or line[i] == '>' or line[i] == '&' or line[i] == '|' or line[i] == '?')) {
                if (i > start + 2) {
                    break;
                }
                i += 1;
            }
            emit(&out, &count, line[start..i], C_operator);
            continue;
        }
        if (ch == '(' or ch == ')' or ch == '{' or ch == '}' or ch == '[' or ch == ']' or ch == ';' or ch == ':' or ch == ',' or ch == '.') {
            emit(&out, &count, line[i..i + 1], C_punctuation);
            i += 1;
            continue;
        }
        emit(&out, &count, line[i..i + 1], C_text);
        i += 1;
    }
    return count;
}

fn tokenizeZig(line: []const u8, out: []ColorSpan) usize {
    var count: usize = 0;
    var i: usize = 0;
    while (i < line.len and count < out.len) {
        const ch = line[i];
        if (isSpace(ch)) {
            const start = i;
            while (i < line.len and isSpace(line[i])) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_text);
            continue;
        }
        if (ch == '/' and i + 1 < line.len and line[i + 1] == '/') {
            emit(&out, &count, line[i..], C_comment);
            return count;
        }
        if (ch == '"') {
            const start = i;
            i += 1;
            while (i < line.len) {
                if (line[i] == '\\' and i + 1 < line.len) {
                    i += 2;
                } else if (line[i] == '"') {
                    i += 1;
                    break;
                } else {
                    i += 1;
                }
            }
            emit(&out, &count, line[start..i], C_string);
            continue;
        }
        if (ch == '\'') {
            const start = i;
            i += 1;
            if (i < line.len and line[i] == '\\') {
                i += 2;
            } else if (i < line.len) {
                i += 1;
            }
            if (i < line.len and line[i] == '\'') {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_string);
            continue;
        }
        if (ch == '@' and i + 1 < line.len and isAlpha(line[i + 1])) {
            const start = i;
            i += 1;
            while (i < line.len and isAlnum(line[i])) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_builtin);
            continue;
        }
        if (isDigit(ch)) {
            const start = i;
            if (ch == '0' and i + 1 < line.len) {
                if (line[i + 1] == 'x') {
                    i += 2;
                    while (i < line.len and (isHexDigit(line[i]) or line[i] == '_')) {
                        i += 1;
                    }
                } else if (line[i + 1] == 'b') {
                    i += 2;
                    while (i < line.len and (line[i] == '0' or line[i] == '1' or line[i] == '_')) {
                        i += 1;
                    }
                } else if (line[i + 1] == 'o') {
                    i += 2;
                    while (i < line.len and ((line[i] >= "0" and line[i] <= "7") or line[i] == '_')) {
                        i += 1;
                    }
                } else {
                    while (i < line.len and (isDigit(line[i]) or line[i] == '_' or line[i] == '.')) {
                        i += 1;
                    }
                }
            } else {
                while (i < line.len and (isDigit(line[i]) or line[i] == '_' or line[i] == '.')) {
                    i += 1;
                }
            }
            emit(&out, &count, line[start..i], C_number);
            continue;
        }
        if (isAlpha(ch)) {
            const start = i;
            while (i < line.len and isAlnum(line[i])) {
                i += 1;
            }
            const word = line[start..i];
            if (inWordList(word, &zig_keywords)) {
                emit(&out, &count, word, C_keyword);
            } else if (inWordList(word, &zig_types)) {
                emit(&out, &count, word, C_type_name);
            } else if (isUpper(word[0])) {
                emit(&out, &count, word, C_type_name);
            } else if (i < line.len and line[i] == '(') {
                emit(&out, &count, word, C_function_name);
            } else {
                emit(&out, &count, word, C_text);
            }
            continue;
        }
        if (ch == '=' or ch == '!' or ch == '+' or ch == '-' or ch == '*' or ch == '/' or ch == '%' or ch == '&' or ch == '|' or ch == '^' or ch == '~' or ch == '<' or ch == '>') {
            const start = i;
            i += 1;
            while (i < line.len and (line[i] == '=' or line[i] == '>' or line[i] == '.' or line[i] == '*' or line[i] == '+')) {
                if (i > start + 2) {
                    break;
                }
                i += 1;
            }
            emit(&out, &count, line[start..i], C_operator);
            continue;
        }
        if (ch == '(' or ch == ')' or ch == '{' or ch == '}' or ch == '[' or ch == ']' or ch == ';' or ch == ':' or ch == ',' or ch == '.') {
            emit(&out, &count, line[i..i + 1], C_punctuation);
            i += 1;
            continue;
        }
        emit(&out, &count, line[i..i + 1], C_text);
        i += 1;
    }
    return count;
}

fn tokenizeJSON(line: []const u8, out: []ColorSpan) usize {
    var count: usize = 0;
    var i: usize = 0;
    while (i < line.len and count < out.len) {
        const ch = line[i];
        if (isSpace(ch)) {
            const start = i;
            while (i < line.len and isSpace(line[i])) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_text);
            continue;
        }
        if (ch == '"') {
            const start = i;
            i += 1;
            while (i < line.len) {
                if (line[i] == '\\' and i + 1 < line.len) {
                    i += 2;
                } else if (line[i] == '"') {
                    i += 1;
                    break;
                } else {
                    i += 1;
                }
            }
            var j = i;
            while (j < line.len and isSpace(line[j])) {
                j += 1;
            }
            const color = if (j < line.len and line[j] == ':') C_type_name else C_string;
            emit(&out, &count, line[start..i], color);
            continue;
        }
        if (isDigit(ch) or (ch == '-' and i + 1 < line.len and isDigit(line[i + 1]))) {
            const start = i;
            if (ch == '-') {
                i += 1;
            }
            while (i < line.len and (isDigit(line[i]) or line[i] == '.')) {
                i += 1;
            }
            if (i < line.len and (line[i] == 'e' or line[i] == 'E')) {
                i += 1;
                if (i < line.len and (line[i] == '+' or line[i] == '-')) {
                    i += 1;
                }
                while (i < line.len and isDigit(line[i])) {
                    i += 1;
                }
            }
            emit(&out, &count, line[start..i], C_number);
            continue;
        }
        if (isAlpha(ch)) {
            const start = i;
            while (i < line.len and isAlpha(line[i])) {
                i += 1;
            }
            const word = line[start..i];
            if (std.mem.eql(u8, word, "true") or std.mem.eql(u8, word, "false") or std.mem.eql(u8, word, "null")) {
                emit(&out, &count, word, C_keyword);
            } else {
                emit(&out, &count, word, C_text);
            }
            continue;
        }
        if (ch == '{' or ch == '}' or ch == '[' or ch == ']' or ch == ':' or ch == ',') {
            emit(&out, &count, line[i..i + 1], C_punctuation);
            i += 1;
            continue;
        }
        emit(&out, &count, line[i..i + 1], C_text);
        i += 1;
    }
    return count;
}

fn tokenizeBash(line: []const u8, out: []ColorSpan) usize {
    var count: usize = 0;
    var i: usize = 0;
    while (i < line.len and count < out.len) {
        const ch = line[i];
        if (isSpace(ch)) {
            const start = i;
            while (i < line.len and isSpace(line[i])) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_text);
            continue;
        }
        if (ch == '#') {
            emit(&out, &count, line[i..], C_comment);
            return count;
        }
        if (ch == '$') {
            const start = i;
            i += 1;
            if (i < line.len and line[i] == '{') {
                i += 1;
                while (i < line.len and line[i] != '}') {
                    i += 1;
                }
                if (i < line.len) {
                    i += 1;
                }
            } else if (i < line.len and line[i] == '(') {
                i += 1;
                emit(&out, &count, line[start..i], C_variable);
                continue;
            } else {
                while (i < line.len and (isAlnum(line[i]) or line[i] == '?' or line[i] == '!' or line[i] == '@' or line[i] == '*' or line[i] == '#')) {
                    i += 1;
                    if (i == start + 2 and !isAlnum(line[i - 1])) {
                        break;
                    }
                }
            }
            emit(&out, &count, line[start..i], C_variable);
            continue;
        }
        if (ch == '"' or ch == '\'') {
            const start = i;
            const quote = ch;
            i += 1;
            while (i < line.len) {
                if (quote == '"' and line[i] == '\\' and i + 1 < line.len) {
                    i += 2;
                } else if (line[i] == quote) {
                    i += 1;
                    break;
                } else {
                    i += 1;
                }
            }
            emit(&out, &count, line[start..i], C_string);
            continue;
        }
        if (isDigit(ch)) {
            const start = i;
            while (i < line.len and isDigit(line[i])) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_number);
            continue;
        }
        if (isAlpha(ch)) {
            const start = i;
            while (i < line.len and (isAlnum(line[i]) or line[i] == '-')) {
                i += 1;
            }
            const word = line[start..i];
            if (inWordList(word, &bash_keywords)) {
                emit(&out, &count, word, C_keyword);
            } else {
                emit(&out, &count, word, C_text);
            }
            continue;
        }
        if (ch == '|' or ch == '&' or ch == '>' or ch == '<' or ch == ';' or ch == '!') {
            const start = i;
            i += 1;
            if (i < line.len and (line[i] == '|' or line[i] == '&' or line[i] == '>')) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_operator);
            continue;
        }
        if (ch == '(' or ch == ')' or ch == '{' or ch == '}' or ch == '[' or ch == ']' or ch == '=' or ch == ',') {
            emit(&out, &count, line[i..i + 1], C_punctuation);
            i += 1;
            continue;
        }
        emit(&out, &count, line[i..i + 1], C_text);
        i += 1;
    }
    return count;
}

fn tokenizeMarkdown(line: []const u8, out: []ColorSpan) usize {
    var count: usize = 0;
    var leading: usize = 0;
    while (leading < line.len and isSpace(line[leading])) {
        leading += 1;
    }
    if (leading > 0) {
        emit(&out, &count, line[0..leading], C_text);
    }
    if (leading < line.len and line[leading] == '#') {
        emit(&out, &count, line[leading..], C_heading);
        return count;
    }
    if (leading < line.len and (line[leading] == '`' or line[leading] == '~')) {
        var fence_count: usize = 0;
        var j = leading;
        while (j < line.len and line[j] == line[leading]) {
            fence_count += 1;
            j += 1;
        }
        if (fence_count >= 3) {
            emit(&out, &count, line[leading..], C_comment);
            return count;
        }
    }
    var i: usize = leading;
    while (i < line.len and count < out.len) {
        const ch = line[i];
        if (ch == '`') {
            const start = i;
            i += 1;
            while (i < line.len and line[i] != '`') {
                i += 1;
            }
            if (i < line.len) {
                i += 1;
            }
            emit(&out, &count, line[start..i], C_string);
            continue;
        }
        if (ch == '*' and i + 1 < line.len and line[i + 1] == '*') {
            const start = i;
            i += 2;
            while (i + 1 < line.len) {
                if (line[i] == '*' and line[i + 1] == '*') {
                    i += 2;
                    break;
                }
                i += 1;
            }
            @"else";
            .{ i, =, line.len, ; };
            emit(&out, &count, line[start..i], C_bold_text);
            continue;
        }
        if (ch == '[') {
            const start = i;
            i += 1;
            while (i < line.len and line[i] != ']') {
                i += 1;
            }
            if (i < line.len) {
                i += 1;
            }
            if (i < line.len and line[i] == '(') {
                i += 1;
                while (i < line.len and line[i] != ')') {
                    i += 1;
                }
                if (i < line.len) {
                    i += 1;
                }
                emit(&out, &count, line[start..i], C_link);
                continue;
            }
            emit(&out, &count, line[start..i], C_text);
            continue;
        }
        if ((ch == '-' or ch == '*' or ch == '+') and i == leading and i + 1 < line.len and line[i + 1] == ' ') {
            emit(&out, &count, line[i..i + 1], C_punctuation);
            i += 1;
            continue;
        }
        const start = i;
        while (i < line.len and line[i] != '`' and line[i] != '*' and line[i] != '[' and line[i] != '#') {
            i += 1;
        }
        if (i > start) {
            emit(&out, &count, line[start..i], C_text);
        } else {
            emit(&out, &count, line[i..i + 1], C_text);
            i += 1;
        }
    }
    return count;
}

fn tokenizePlain(line: []const u8, out: []ColorSpan) usize {
    if (line.len == 0 or out.len == 0) {
        return 0;
    }
    out[0] = .{ .text = line, .color = C_text };
    return 1;
}
