//! ──── GENERATED FILE — DO NOT EDIT ────
//!
//! Source: tsz/runtime/tsz/window_ipc.mod.tsz
//! Generated by: tsz compile-runtime (imperative mode)
//!
//! To regenerate: tsz compile-runtime tsz/runtime/tsz/window_ipc.mod.tsz
//! To modify: edit window_ipc.mod.tsz and recompile

const std = @import("std");

inline fn asF32(val: anytype) f32 {
    return switch (@typeInfo(@TypeOf(val))) {
        .int, .comptime_int => @floatFromInt(val),
        .comptime_float => val,
        .float => if (@TypeOf(val) == f32) val else @floatCast(val),
        .optional => blk: {
            const v = val orelse 0;
            break :blk switch (@typeInfo(@TypeOf(v))) {
                .int, .comptime_int => @as(f32, @floatFromInt(v)),
                .comptime_float => @as(f32, v),
                .float => if (@TypeOf(v) == f32) v else @floatCast(v),
                else => @compileError("asF32: unsupported optional inner type"),
            };
        },
        else => @compileError("asF32: unsupported type"),
    };
}

// ── Type definitions ────────────────────────────────
pub const MessageType = enum { init, mutations, event, resize, ready, quit, custom };
pub const Message = struct {
    active: bool = false,
    msg_type: MessageType = .init,
    source_window: u8 = 0,
    target_window: u8 = 0,
    data: [MAX_MSG_DATA]u8,
    data_len: u16 = 0,
};
pub const Channel = struct {
    active: bool = false,
    window_idx: u8 = 0,
    messages: [MAX_MESSAGES]Message,
    head: usize = 0,
    tail: usize = 0,
    count: usize = 0,
};

// ── Module state ───────────────────────────────────
const MAX_MESSAGES: usize = 256;
const MAX_MSG_DATA: usize = 4096;
const MAX_CHANNELS: usize = 8;
var channels: [MAX_CHANNELS]Channel = undefined;
var channel_count: usize = 0;

// ── Functions ──────────────────────────────────────

pub fn openChannel(windowIdx: u8) ?usize {
    if (channel_count >= MAX_CHANNELS) {
        return null;
    }
    const idx = channel_count;
    channels[idx].active = true;
    channels[idx].window_idx = windowIdx;
    channels[idx].head = 0;
    channels[idx].tail = 0;
    channels[idx].count = 0;
    channel_count += 1;
    return idx;
}

pub fn closeChannel(idx: usize) void {
    if (idx >= MAX_CHANNELS) {
        return;
    }
    channels[idx].active = false;
    channels[idx].count = 0;
}

pub fn findChannel(windowIdx: u8) ?usize {
    {
        var i: usize = 0;
        while (i < channel_count) : (i += 1) {
            if (channels[i].active and channels[i].window_idx == windowIdx) {
                return i;
            }
        }
    }
    return null;
}

pub fn send(targetWindow: u8, msgType: MessageType, data: []const u8) bool {
    const chIdx = findChannel(targetWindow);
    @"orelse";
    return false;
    const ch = &channels[@intCast(chIdx)];
    if (ch.count >= MAX_MESSAGES) {
        return false;
    }
    const idx = ch.tail;
    ch.messages[idx].active = true;
    ch.messages[idx].msg_type = msgType;
    ch.messages[idx].source_window = 0;
    ch.messages[idx].target_window = targetWindow;
    const dlen: u16 = @intCast(@min(data.len, MAX_MSG_DATA));
    if (dlen > 0) {
        @memcpy(ch.messages[idx].data[0..dlen], data[0..dlen]);
    }
    ch.messages[idx].data_len = dlen;
    ch.tail = (ch.tail + 1) % MAX_MESSAGES;
    ch.count += 1;
    return true;
}

pub fn sendSignal(targetWindow: u8, msgType: MessageType) bool {
    return send(targetWindow, msgType, "");
}

pub fn recv(channelIdx: usize) ?*const Message {
    if (channelIdx >= MAX_CHANNELS) {
        return null;
    }
    const ch = &channels[channelIdx];
    if (ch.count == 0) {
        return null;
    }
    const idx = ch.head;
    ch.head = (ch.head + 1) % MAX_MESSAGES;
    ch.count -= 1;
    return &ch.messages[idx];
}

pub fn drain(channelIdx: usize, out: []Message) usize {
    if (channelIdx >= MAX_CHANNELS) {
        return 0;
    }
    const ch = &channels[channelIdx];
    var count: usize = 0;
    while (ch.count > 0 and count < out.len) {
        const idx = ch.head;
        out[count] = ch.messages[idx];
        ch.head = (ch.head + 1) % MAX_MESSAGES;
        ch.count -= 1;
        count += 1;
    }
    return count;
}

pub fn hasPending(channelIdx: usize) bool {
    if (channelIdx >= MAX_CHANNELS) {
        return false;
    }
    return channels[channelIdx].count > 0;
}

pub fn pendingCount(channelIdx: usize) usize {
    if (channelIdx >= MAX_CHANNELS) {
        return 0;
    }
    return channels[channelIdx].count;
}

pub fn broadcast(msgType: MessageType, data: []const u8) void {
    {
        var i: usize = 0;
        while (i < channel_count) : (i += 1) {
            if (channels[i].active) {
                send(channels[i].window_idx, msgType, data);
            }
        }
    }
}

pub fn reset() void {
    {
        var i: usize = 0;
        while (i < MAX_CHANNELS) : (i += 1) {
            channels[i].active = false;
            channels[i].count = 0;
        }
    }
    channel_count = 0;
}
