//! Generated by tsz compiler — d05_dynamic_style_in_map [logic.zig]
//! Source: d05_dynamic_style_in_map.tsz


// [origin:d05_dynamic_style_in_map:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\var bars = [];
    \\// OA initial data
    \\setBars([ { pct : 0 , color : 0x000000 , label : "" } ]);
    \\var highlight = 0;
    \\function setHighlight(v) { highlight = v; __setState(0, v); }
    \\var b = [
    \\  { pct: 85, color: 0x03dac6, label: 'Rust' },
    \\  { pct: 72, color: 0xbb86fc, label: 'Zig' },
    \\  { pct: 60, color: 0xcf6679, label: 'C' },
    \\  { pct: 45, color: 0x018786, label: 'Go' },
    \\  { pct: 30, color: 0x3700b3, label: 'JS' }
    \\];
    \\setBars(b);
    \\
    \\
    \\
    \\function setBars(v) { bars = v; __setObjArr0(v); }
    \\if (bars && bars.length > 0) setBars(bars);
    \\function __mapPress_0_0(idx) {
    \\  var bar = bars[idx];
    \\  var i = idx;
    \\  setHighlight(i);
    \\}
    \\
;

// [origin:d05_dynamic_style_in_map:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

