//! Generated by tsz compiler — d26a_timer_script [app.zig]
//! Source: d26a_timer_script.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const engine = api.engine;
const nodes = @import("nodes.zig");
const st = @import("state.zig");
const handlers = @import("handlers.zig");
const logic = @import("logic.zig");

fn _updateDynamicTexts() void {
    st._dyn_text_0 = std.fmt.bufPrint(&st._dyn_buf_0, "{d}", .{ state.getSlot(0) }) catch "";
    nodes._arr_4[1].text = st._dyn_text_0;
    st._dyn_text_1 = std.fmt.bufPrint(&st._dyn_buf_1, "elapsed: {d}s", .{ state.getSlot(3) }) catch "";
    nodes._arr_4[2].text = st._dyn_text_1;
    st._dyn_text_2 = std.fmt.bufPrint(&st._dyn_buf_2, "{s}", .{ state.getSlotString(2) }) catch "";
    nodes._arr_4[6].text = st._dyn_text_2;
}

fn _updateConditionals() void {
    nodes._arr_4[4].style.display = if ((state.getSlot(1) ==  1)) .flex else .none;
    nodes._arr_4[5].style.display = if ((state.getSlot(1) ==  0)) .flex else .none;
}


fn _appInit() void {
    st._initState();
    _updateDynamicTexts();
    _updateConditionals();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts(); _updateConditionals(); state.clearDirty(); }
}

export fn app_get_root() *Node { return &nodes._root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return logic.JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return logic.JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return logic.LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return logic.LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d26a_timer_script"; }

export fn app_state_count() usize { return 4; }
const _slot_types = [_]u8{ 0, 0, 3, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

pub fn main() !void {
    try engine.run(.{
        .title = "d26a_timer_script",
        .root = &nodes._root,
        .js_logic = logic.JS_LOGIC,
        .lua_logic = logic.LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}
