//! Generated by tsz compiler — 38_flex_basis_content [nodes.zig]
//! Source: 38_flex_basis_content.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:38_flex_basis_content:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:38_flex_basis_content.tsz:9 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "w80+g1" } };
// tsz:38_flex_basis_content.tsz:12 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "w40+g1" } };
// tsz:38_flex_basis_content.tsz:8 — <Box>
pub var _arr_2 = [_]Node{ .{ .style = .{ .width = 80, .flex_grow = 1, .height = 40, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_0 }, .{ .style = .{ .width = 40, .flex_grow = 1, .height = 40, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_1 } };
// tsz:38_flex_basis_content.tsz:19 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "b0+g1" } };
// tsz:38_flex_basis_content.tsz:22 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "b0+g1" } };
// tsz:38_flex_basis_content.tsz:18 — <Box>
pub var _arr_5 = [_]Node{ .{ .style = .{ .width = 80, .flex_basis = 0, .flex_grow = 1, .height = 40, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_3 }, .{ .style = .{ .width = 40, .flex_basis = 0, .flex_grow = 1, .height = 40, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_4 } };
// tsz:38_flex_basis_content.tsz:29 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "w200 b100" } };
// tsz:38_flex_basis_content.tsz:32 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "w50 b200" } };
// tsz:38_flex_basis_content.tsz:28 — <Box>
pub var _arr_8 = [_]Node{ .{ .style = .{ .width = 200, .flex_basis = 100, .height = 40, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_6 }, .{ .style = .{ .width = 50, .flex_basis = 200, .height = 40, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_7 } };
// tsz:38_flex_basis_content.tsz:39 — <Box>
pub var _arr_9 = [_]Node{ .{ .text = "b0" } };
// tsz:38_flex_basis_content.tsz:42 — <Box>
pub var _arr_10 = [_]Node{ .{ .text = "grow fills" } };
// tsz:38_flex_basis_content.tsz:38 — <Box>
pub var _arr_11 = [_]Node{ .{ .style = .{ .flex_basis = 0, .height = 40, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_9 }, .{ .style = .{ .flex_grow = 1, .height = 40, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_10 } };
// tsz:38_flex_basis_content.tsz:49 — <Box>
pub var _arr_12 = [_]Node{ .{ .text = "b40" } };
// tsz:38_flex_basis_content.tsz:52 — <Box>
pub var _arr_13 = [_]Node{ .{ .text = "b0+g1" } };
// tsz:38_flex_basis_content.tsz:55 — <Box>
pub var _arr_14 = [_]Node{ .{ .text = "b60" } };
// tsz:38_flex_basis_content.tsz:48 — <Box>
pub var _arr_15 = [_]Node{ .{ .style = .{ .flex_basis = 40, .background_color = Color.rgb(76, 175, 80) }, .children = &_arr_12 }, .{ .style = .{ .flex_basis = 0, .flex_grow = 1, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_13 }, .{ .style = .{ .flex_basis = 60, .background_color = Color.rgb(255, 152, 0) }, .children = &_arr_14 } };
// tsz:38_flex_basis_content.tsz:3 — <Box>
pub var _arr_16 = [_]Node{ .{ .text = "WPT: flex-basis auto vs 0 vs explicit" }, .{ .text = "VERIFY: No basis uses width, basis:0 ignores width, basis overrides width", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "No basis (auto) — uses width as basis" }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 40, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_2 }, .{ .text = "basis:0 — ignores width, pure grow ratio" }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 40, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_5 }, .{ .text = "basis:100 overrides width:200" }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 40, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_8 }, .{ .text = "basis:0 with no grow — item collapses to zero" }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 40, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_11 }, .{ .text = "Column: basis sets initial height" }, .{ .style = .{ .flex_direction = .column, .width = 100, .height = 200, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_15 } };
// [origin:38_flex_basis_content:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 8, .overflow = .hidden }, .children = &_arr_16 };

