//! Generated by tsz compiler — 38_flex_basis_content [state.zig]
//! Source: 38_flex_basis_content.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

pub fn _initState() void {
}

