//! Generated by tsz compiler — d16_state_stress [app.zig]
//! Source: d16_state_stress.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const state = api.state;
const engine = api.engine;
const nodes = @import("nodes.zig");
const st = @import("state.zig");
const handlers = @import("handlers.zig");
const logic = @import("logic.zig");

fn _updateDynamicTexts() void {
    st._dyn_text_0 = std.fmt.bufPrint(&st._dyn_buf_0, "total:{d} phase:{d} history:{d}", .{ state.getSlot(8), state.getSlot(9), state.getSlot(10) }) catch "";
    nodes._arr_23[1].text = st._dyn_text_0;
    st._dyn_text_1 = std.fmt.bufPrint(&st._dyn_buf_1, "a:{d}", .{ state.getSlot(0) }) catch "";
    nodes._arr_0[0].text = st._dyn_text_1;
    st._dyn_text_2 = std.fmt.bufPrint(&st._dyn_buf_2, "b:{d}", .{ state.getSlot(1) }) catch "";
    nodes._arr_1[0].text = st._dyn_text_2;
    st._dyn_text_3 = std.fmt.bufPrint(&st._dyn_buf_3, "c:{d}", .{ state.getSlot(2) }) catch "";
    nodes._arr_2[0].text = st._dyn_text_3;
    st._dyn_text_4 = std.fmt.bufPrint(&st._dyn_buf_4, "d:{d}", .{ state.getSlot(3) }) catch "";
    nodes._arr_3[0].text = st._dyn_text_4;
    st._dyn_text_5 = std.fmt.bufPrint(&st._dyn_buf_5, "e:{d}", .{ state.getSlot(4) }) catch "";
    nodes._arr_4[0].text = st._dyn_text_5;
    st._dyn_text_6 = std.fmt.bufPrint(&st._dyn_buf_6, "f:{d}", .{ state.getSlot(5) }) catch "";
    nodes._arr_5[0].text = st._dyn_text_6;
    st._dyn_text_7 = std.fmt.bufPrint(&st._dyn_buf_7, "g:{d}", .{ state.getSlot(6) }) catch "";
    nodes._arr_6[0].text = st._dyn_text_7;
    st._dyn_text_8 = std.fmt.bufPrint(&st._dyn_buf_8, "h:{d}", .{ state.getSlot(7) }) catch "";
    nodes._arr_7[0].text = st._dyn_text_8;
    st._dyn_text_9 = std.fmt.bufPrint(&st._dyn_buf_9, "{d}", .{ (((state.getSlot(0) + state.getSlot(1)) + state.getSlot(2)) + state.getSlot(3)) }) catch "";
    nodes._arr_9[1].text = st._dyn_text_9;
    st._dyn_text_10 = std.fmt.bufPrint(&st._dyn_buf_10, "{d}", .{ (((state.getSlot(4) + state.getSlot(5)) + state.getSlot(6)) + state.getSlot(7)) }) catch "";
    nodes._arr_10[1].text = st._dyn_text_10;
    st._dyn_text_11 = std.fmt.bufPrint(&st._dyn_buf_11, "{d}", .{ state.getSlot(8) }) catch "";
    nodes._arr_11[1].text = st._dyn_text_11;
    st._dyn_text_12 = std.fmt.bufPrint(&st._dyn_buf_12, "{d}", .{ (((((((state.getSlot(0) + state.getSlot(1)) + state.getSlot(2)) + state.getSlot(3)) + state.getSlot(4)) + state.getSlot(5)) + state.getSlot(6)) + state.getSlot(7)) }) catch "";
    nodes._arr_12[1].text = st._dyn_text_12;
    st._dyn_text_13 = std.fmt.bufPrint(&st._dyn_buf_13, "{d}px", .{ state.getSlot(11) }) catch "";
    nodes._arr_16[3].text = st._dyn_text_13;
    st._dyn_text_14 = std.fmt.bufPrint(&st._dyn_buf_14, "Phase {d} → {d} (history will be {d})", .{ state.getSlot(9), state.getSlot(9) + 1, state.getSlot(10) + state.getSlot(9) }) catch "";
    nodes._arr_17[0].text = st._dyn_text_14;
    st._dyn_text_15 = std.fmt.bufPrint(&st._dyn_buf_15, "{d}", .{ state.getSlot(9) }) catch "";
    nodes._arr_19[1].text = st._dyn_text_15;
    st._dyn_text_16 = std.fmt.bufPrint(&st._dyn_buf_16, "{d}", .{ state.getSlot(10) }) catch "";
    nodes._arr_20[1].text = st._dyn_text_16;
    st._dyn_text_17 = std.fmt.bufPrint(&st._dyn_buf_17, "{d}", .{ state.getSlot(11) }) catch "";
    nodes._arr_21[1].text = st._dyn_text_17;
    nodes._arr_9[1].text_color = Color.rgb(59, 130, 246);
    nodes._arr_10[1].text_color = Color.rgb(139, 92, 246);
    nodes._arr_11[1].text_color = Color.rgb(34, 197, 94);
    nodes._arr_12[1].text_color = Color.rgb(245, 158, 11);
    nodes._arr_16[1].style.width = @as(f32, @floatFromInt(state.getSlot(11)));
    nodes._arr_19[1].text_color = Color.rgb(236, 72, 153);
    nodes._arr_20[1].text_color = Color.rgb(20, 184, 166);
    nodes._arr_21[1].text_color = Color.rgb(249, 115, 22);
}


fn _appInit() void {
    st._initState();
    _updateDynamicTexts();
}

fn _appTick(now: u32) void {
    _ = now;
    if (state.isDirty()) { _updateDynamicTexts();
 state.clearDirty(); }
}

export fn app_get_root() *Node { return &nodes._root; }
export fn app_get_init() ?*const fn () void { return _appInit; }
export fn app_get_tick() ?*const fn (u32) void { return _appTick; }
export fn app_get_js_logic() [*]const u8 { return logic.JS_LOGIC.ptr; }
export fn app_get_js_logic_len() usize { return logic.JS_LOGIC.len; }
export fn app_get_lua_logic() [*]const u8 { return logic.LUA_LOGIC.ptr; }
export fn app_get_lua_logic_len() usize { return logic.LUA_LOGIC.len; }
export fn app_get_title() [*:0]const u8 { return "d16_state_stress"; }

export fn app_state_count() usize { return 12; }
const _slot_types = [_]u8{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
export fn app_state_slot_type(id: usize) u8 { if (id < _slot_types.len) return _slot_types[id]; return 0; }
export fn app_state_get_int(id: usize) i64 { return state.getSlot(id); }
export fn app_state_set_int(id: usize, val: i64) void { state.setSlot(id, val); }
export fn app_state_get_float(id: usize) f64 { return state.getSlotFloat(id); }
export fn app_state_set_float(id: usize, val: f64) void { state.setSlotFloat(id, val); }
export fn app_state_get_bool(id: usize) u8 { return if (state.getSlotBool(id)) 1 else 0; }
export fn app_state_set_bool(id: usize, val: u8) void { state.setSlotBool(id, val != 0); }
export fn app_state_get_string_ptr(id: usize) [*]const u8 { return state.getSlotString(id).ptr; }
export fn app_state_get_string_len(id: usize) usize { return state.getSlotString(id).len; }
export fn app_state_set_string(id: usize, ptr: [*]const u8, len: usize) void { state.setSlotString(id, ptr[0..len]); }
export fn app_state_mark_dirty() void { state.markDirty(); }

pub fn main() !void {
    try engine.run(.{
        .title = "d16_state_stress",
        .root = &nodes._root,
        .js_logic = logic.JS_LOGIC,
        .lua_logic = logic.LUA_LOGIC,
        .init = _appInit,
        .tick = _appTick,
    });
}

// ── Smith debug log ──
// DBG: [INLINE PROBE] Inlining component: StatBox bodyPos: 159 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: StatBox bodyPos: 159 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: StatBox bodyPos: 159 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: StatBox bodyPos: 159 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: StatBox bodyPos: 159 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: StatBox bodyPos: 159 token: < kind: 41
// DBG: [INLINE PROBE] Inlining component: StatBox bodyPos: 159 token: < kind: 41
