//! Generated by tsz compiler — d24_chained_state [state.zig]
//! Source: d24_chained_state.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d24_chained_state:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: step (int)
// slot 1: name (string)
// slot 2: email (string)
// slot 3: plan (int)
// slot 4: confirmed (int)
// slot 5: error (string)
comptime { if (6 != 6) @compileError("state slot count mismatch"); }

// [origin:d24_chained_state:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_0: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_0: []const u8 = "";
pub var _dyn_buf_1: [138]u8 = std.mem.zeroes([138]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [138]u8 = std.mem.zeroes([138]u8);
pub var _dyn_text_2: []const u8 = "";
pub var _dyn_buf_3: [134]u8 = std.mem.zeroes([134]u8);
pub var _dyn_text_3: []const u8 = "";
pub var _dyn_buf_4: [135]u8 = std.mem.zeroes([135]u8);
pub var _dyn_text_4: []const u8 = "";
pub var _dyn_buf_5: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_5: []const u8 = "";
pub var _dyn_buf_6: [128]u8 = std.mem.zeroes([128]u8);
pub var _dyn_text_6: []const u8 = "";

pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlotString("");
    _ = state.createSlotString("");
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
}

