//! Generated by tsz compiler — d103b_glyphs_minimal [nodes.zig]
//! Source: d103b_glyphs_minimal.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d103b_glyphs_minimal:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d103b_glyphs_minimal.tsz:6 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "Status:\x01Active", .inline_glyphs = &[_]layout.InlineGlyph{ .{ .d = "M 0,-10 L 8.66,5 L -8.66,5 Z", .fill = Color.rgb(34, 197, 94), .stroke = Color.rgba(0, 0, 0, 0), .stroke_width = 0, .scale = 1.0 } }, .font_size = 20, .text_color = Color.rgb(226, 232, 240) }, .{ .text = "Warning\x01Level 3", .inline_glyphs = &[_]layout.InlineGlyph{ .{ .d = "M 0,-10 L 10,0 L 0,10 L -10,0 Z", .fill = Color.rgb(245, 158, 11), .stroke = Color.rgba(0, 0, 0, 0), .stroke_width = 0, .scale = 1.0 } }, .font_size = 20, .text_color = Color.rgb(226, 232, 240) }, .{ .text = "BIG\x01TEXT", .inline_glyphs = &[_]layout.InlineGlyph{ .{ .d = "M 0,-10 L 9.51,-3.09 L 5.88,8.09 L -5.88,8.09 L -9.51,-3.09 Z", .fill = Color.rgb(239, 68, 68), .stroke = Color.rgba(0, 0, 0, 0), .stroke_width = 0, .scale = 1.0 } }, .font_size = 32, .text_color = Color.rgb(248, 250, 252) } };
// tsz:d103b_glyphs_minimal.tsz:3 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "Inline Glyph Minimal Test", .font_size = 24, .text_color = Color.rgb(241, 245, 249) }, .{ .style = .{ .background_color = Color.rgb(30, 41, 59), .border_radius = 12, .padding = 16, .gap = 14 }, .children = &_arr_0 } };
// [origin:d103b_glyphs_minimal:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(15, 23, 42), .padding = 32, .gap = 24, .overflow = .hidden }, .children = &_arr_1 };

