//! Generated by tsz compiler — 26_gap_with_justify [state.zig]
//! Source: 26_gap_with_justify.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

pub fn _initState() void {
}

