//! Generated by tsz compiler — d58_dynamic_styles [logic.zig]
//! Source: d58_dynamic_styles.tsz


// [origin:d58_dynamic_styles:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\
;

// [origin:d58_dynamic_styles:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

