//! Generated by tsz compiler — d58_dynamic_styles [nodes.zig]
//! Source: d58_dynamic_styles.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const handlers = @import("handlers.zig");

// [origin:d58_dynamic_styles:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d58_dynamic_styles.tsz:17 — <Pressable>
pub var _arr_0 = [_]Node{ .{ .text = "", .font_size = 11, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d58_dynamic_styles.tsz:20 — <Pressable>
pub var _arr_1 = [_]Node{ .{ .text = "", .font_size = 11, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d58_dynamic_styles.tsz:23 — <Pressable>
pub var _arr_2 = [_]Node{ .{ .text = "", .font_size = 11, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d58_dynamic_styles.tsz:26 — <Pressable>
pub var _arr_3 = [_]Node{ .{ .text = "", .font_size = 11, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d58_dynamic_styles.tsz:16 — <Box>
pub var _arr_4 = [_]Node{ .{ .style = .{ .padding = 8, .background_color = Color.rgb(51, 65, 85), .border_radius = 6 }, .handlers = .{ .on_press = handlers._handler_press_0 }, .children = &_arr_0 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(51, 65, 85), .border_radius = 6 }, .handlers = .{ .on_press = handlers._handler_press_1 }, .children = &_arr_1 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(51, 65, 85), .border_radius = 6 }, .handlers = .{ .on_press = handlers._handler_press_2 }, .children = &_arr_2 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(51, 65, 85), .border_radius = 6 }, .handlers = .{ .on_press = handlers._handler_press_3 }, .children = &_arr_3 } };
// tsz:d58_dynamic_styles.tsz:32 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "", .font_size = 9, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d58_dynamic_styles.tsz:42 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "derived", .font_size = 8, .text_color = Color.rgb(148, 163, 184) } };
// tsz:d58_dynamic_styles.tsz:31 — <Box>
pub var _arr_7 = [_]Node{ .{ .style = .{ .width = 0, .height = 0, .border_radius = 0, .background_color = Color{}, .padding = 0, .overflow = .auto }, .children = &_arr_5 }, .{ .style = .{ .width = 0, .height = 0, .border_radius = 0, .background_color = Color.rgb(30, 41, 59), .padding = 0, .border_width = 2, .border_color = Color{}, .overflow = .auto }, .children = &_arr_6 } };
// tsz:d58_dynamic_styles.tsz:55 — <Box>
pub var _arr_8 = [_]Node{ .{ .style = .{ .width = 0, .height = 8, .border_radius = 4, .background_color = Color.rgb(59, 130, 246) } }, .{ .style = .{ .width = 0, .height = 8, .border_radius = 4, .background_color = Color.rgb(34, 197, 94) } }, .{ .style = .{ .width = 0, .height = 8, .border_radius = 4, .background_color = Color.rgb(245, 158, 11) } } };
// tsz:d58_dynamic_styles.tsz:14 — <Box>
pub var _arr_9 = [_]Node{ .{ .text = "Dynamic Styles", .font_size = 16, .text_color = Color.rgb(226, 232, 240) }, .{ .style = .{ .flex_direction = .row, .gap = 8, .flex_wrap = .wrap }, .children = &_arr_4 }, .{ .style = .{ .flex_direction = .row, .gap = 16, .align_items = .center, .justify_content = .center, .padding = 20 }, .children = &_arr_7 }, .{ .style = .{ .gap = 4 }, .children = &_arr_8 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(100, 116, 139) } };
// [origin:d58_dynamic_styles:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(15, 23, 42), .padding = 20, .width = -1, .height = -1, .gap = 12, .overflow = .hidden }, .children = &_arr_9 };

