//! Generated by tsz compiler — 70_flex_interaction_stress [logic.zig]
//! Source: 70_flex_interaction_stress.tsz


// [origin:70_flex_interaction_stress:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\
;

// [origin:70_flex_interaction_stress:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

