//! Generated by tsz compiler — 70_flex_interaction_stress [nodes.zig]
//! Source: 70_flex_interaction_stress.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:70_flex_interaction_stress:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:70_flex_interaction_stress.tsz:9 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "g1 s1 b100 min60 max150", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:70_flex_interaction_stress.tsz:12 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "g2 s0 b50", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:70_flex_interaction_stress.tsz:8 — <Box>
pub var _arr_2 = [_]Node{ .{ .style = .{ .flex_grow = 1, .flex_shrink = 1, .flex_basis = 100, .min_width = 60, .max_width = 150, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_0 }, .{ .style = .{ .flex_grow = 2, .flex_shrink = 0, .flex_basis = 50, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_1 } };
// tsz:70_flex_interaction_stress.tsz:18 — <Box>
pub var _arr_3 = [_]Node{ .{ .style = .{ .width = 40, .height = 30, .background_color = Color.rgb(76, 175, 80), .margin = 4 } }, .{ .style = .{ .width = 40, .height = 50, .background_color = Color.rgb(33, 150, 243), .margin = 4 } }, .{ .style = .{ .width = 40, .height = 20, .background_color = Color.rgb(255, 152, 0), .margin = 4 } } };
// tsz:70_flex_interaction_stress.tsz:25 — <Box>
pub var _arr_4 = [_]Node{ .{ .style = .{ .flex_grow = 1, .flex_basis = 80, .height = 30, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .flex_grow = 1, .flex_basis = 80, .height = 30, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .flex_grow = 1, .flex_basis = 80, .height = 30, .background_color = Color.rgb(255, 152, 0) } }, .{ .style = .{ .flex_grow = 1, .flex_basis = 80, .height = 30, .background_color = Color.rgb(156, 39, 176) } } };
// tsz:70_flex_interaction_stress.tsz:34 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "fixed 30px", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:70_flex_interaction_stress.tsz:37 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "20%", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:70_flex_interaction_stress.tsz:40 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "grow", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:70_flex_interaction_stress.tsz:43 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "fixed 40px", .text_color = Color.rgb(255, 255, 255), .font_size = 9 } };
// tsz:70_flex_interaction_stress.tsz:33 — <Box>
pub var _arr_9 = [_]Node{ .{ .style = .{ .height = 30, .background_color = Color.rgb(21, 101, 192), .overflow = .auto }, .children = &_arr_5 }, .{ .style = .{ .height = 0.2, .background_color = Color.rgb(46, 125, 50), .overflow = .auto }, .children = &_arr_6 }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(55, 71, 79), .overflow = .auto }, .children = &_arr_7 }, .{ .style = .{ .height = 40, .background_color = Color.rgb(69, 39, 160), .overflow = .auto }, .children = &_arr_8 } };
// tsz:70_flex_interaction_stress.tsz:50 — <Box>
pub var _arr_10 = [_]Node{ .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(76, 175, 80) } }, .{ .style = .{ .flex_grow = 2, .background_color = Color.rgb(46, 125, 50) } } };
// tsz:70_flex_interaction_stress.tsz:54 — <Box>
pub var _arr_11 = [_]Node{ .{ .style = .{ .flex_grow = 3, .background_color = Color.rgb(33, 150, 243) } }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(21, 101, 192) } } };
// tsz:70_flex_interaction_stress.tsz:49 — <Box>
pub var _arr_12 = [_]Node{ .{ .style = .{ .flex_grow = 1, .flex_direction = .row, .gap = 2, .overflow = .auto }, .children = &_arr_10 }, .{ .style = .{ .flex_grow = 1, .flex_direction = .row, .gap = 2, .overflow = .auto }, .children = &_arr_11 } };
// tsz:70_flex_interaction_stress.tsz:3 — <Box>
pub var _arr_13 = [_]Node{ .{ .text = "WPT: flex property interaction stress", .font_size = 18 }, .{ .text = "VERIFY: grow+shrink+basis+min+max all interact, nested grow chains distribute correctly", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "grow + shrink + basis + min + max — all at once", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 40, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_2 }, .{ .text = "justify + align + gap + padding + margin — all at once", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center, .width = 300, .height = 80, .background_color = Color.rgb(51, 51, 51), .gap = 8, .padding = 12, .overflow = .auto }, .children = &_arr_3 }, .{ .text = "Wrap + grow + shrink + gap + justify:center", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .flex_wrap = .wrap, .justify_content = .center, .width = 250, .background_color = Color.rgb(51, 51, 51), .gap = 6, .padding = 6 }, .children = &_arr_4 }, .{ .text = "Column: fixed + grow + % + aspect-ratio mixed", .font_size = 11 }, .{ .style = .{ .flex_direction = .column, .width = 200, .height = 250, .background_color = Color.rgb(51, 51, 51), .overflow = .auto }, .children = &_arr_9 }, .{ .text = "Deeply nested grow chains", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .width = 400, .height = 60, .background_color = Color.rgb(34, 34, 34), .overflow = .auto }, .children = &_arr_12 } };
// [origin:70_flex_interaction_stress:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 6, .overflow = .hidden }, .children = &_arr_13 };

