//! Generated by tsz compiler — d02_component_returning_map [logic.zig]
//! Source: d02_component_returning_map.tsz


// [origin:d02_component_returning_map:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\var tags = [];
    \\// OA initial data
    \\setTags([ { name : "" , color : 0x000000 } ]);
    \\var picked = 0;
    \\function setPicked(v) { picked = v; __setState(0, v); }
    \\var t = [
    \\  { name: 'bug', color: 0xd73a4a },
    \\  { name: 'feature', color: 0x0075ca },
    \\  { name: 'docs', color: 0x0e8a16 },
    \\  { name: 'wontfix', color: 0x6a737d },
    \\  { name: 'duplicate', color: 0xcfd3d7 }
    \\];
    \\setTags(t);
    \\
    \\
    \\
    \\function setTags(v) { tags = v; __setObjArr0(v); }
    \\if (tags && tags.length > 0) setTags(tags);
    \\function __mapPress_0_0(idx) {
    \\  var tag = tags[idx];
    \\  var i = idx;
    \\  setPicked(i);
    \\}
    \\
;

// [origin:d02_component_returning_map:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

