//! Generated by tsz compiler — 65_tw_typography [nodes.zig]
//! Source: 65_tw_typography.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:65_tw_typography:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:65_tw_typography.tsz:8 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "text-xs (12px)", .font_size = 12 }, .{ .text = "text-sm (14px)", .font_size = 14 }, .{ .text = "text-base (16px)", .font_size = 16 }, .{ .text = "text-lg (18px)", .font_size = 18 }, .{ .text = "text-xl (20px)", .font_size = 20 }, .{ .text = "text-2xl (24px)", .font_size = 24 }, .{ .text = "text-3xl (30px)", .font_size = 30 } };
// tsz:65_tw_typography.tsz:19 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "text-slate-50", .font_size = 12, .text_color = Color.rgb(248, 250, 252) }, .{ .text = "text-slate-400", .font_size = 12, .text_color = Color.rgb(148, 163, 184) }, .{ .text = "text-slate-500", .font_size = 12, .text_color = Color.rgb(100, 116, 139) }, .{ .text = "text-slate-600", .font_size = 12, .text_color = Color.rgb(71, 85, 105) }, .{ .text = "text-red-500", .font_size = 12, .text_color = Color.rgb(239, 68, 68) }, .{ .text = "text-green-500", .font_size = 12, .text_color = Color.rgb(34, 197, 94) }, .{ .text = "text-blue-500", .font_size = 12, .text_color = Color.rgb(59, 130, 246) } };
// tsz:65_tw_typography.tsz:31 — <Box>
pub var _arr_2 = [_]Node{ .{ .text = "Left (default)", .font_size = 11, .text_color = Color.rgb(255, 255, 255) } };
// tsz:65_tw_typography.tsz:34 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "Center", .font_size = 11, .text_color = Color.rgb(255, 255, 255) } };
// tsz:65_tw_typography.tsz:37 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "Right", .font_size = 11, .text_color = Color.rgb(255, 255, 255) } };
// tsz:65_tw_typography.tsz:30 — <Box>
pub var _arr_5 = [_]Node{ .{ .style = .{ .padding = 4 }, .children = &_arr_2 }, .{ .style = .{ .padding = 4, .text_align = .center }, .children = &_arr_3 }, .{ .style = .{ .padding = 4, .text_align = .right }, .children = &_arr_4 } };
// tsz:65_tw_typography.tsz:43 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "This very long text will be truncated to one line", .font_size = 11, .text_color = Color.rgb(255, 255, 255) } };
// tsz:65_tw_typography.tsz:3 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "Tailwind verification: typography", .font_size = 18 }, .{ .text = "VERIFY: Font sizes xs through 3xl, text colors match palette, truncation works", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "Font sizes mapped from Tailwind scale", .font_size = 11 }, .{ .style = .{ .flex_direction = .column, .gap = 2 }, .children = &_arr_0 }, .{ .text = "Text colors from TW palette", .font_size = 11 }, .{ .style = .{ .flex_direction = .column, .gap = 2, .background_color = Color.rgb(51, 51, 51), .padding = 8, .border_radius = 4 }, .children = &_arr_1 }, .{ .text = "Text alignment: text-left, text-center, text-right", .font_size = 11 }, .{ .style = .{ .flex_direction = .column, .width = 250, .background_color = Color.rgb(51, 51, 51), .gap = 2 }, .children = &_arr_5 }, .{ .text = "Truncation: truncate = numberOfLines:1", .font_size = 11 }, .{ .style = .{ .width = 200, .background_color = Color.rgb(51, 51, 51), .padding = 8 }, .children = &_arr_6 } };
// [origin:65_tw_typography:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 6, .overflow = .hidden }, .children = &_arr_7 };

