//! Generated by tsz compiler — d25_map_conditional_classifier [nodes.zig]
//! Source: d25_map_conditional_classifier.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d25_map_conditional_classifier:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d25_map_conditional_classifier.tsz:19 — <Box>
pub var _arr_14 = [_]Node{ .{ .style = .{ .gap = 8 } } };
// tsz:d25_map_conditional_classifier.tsz:17 — <Box>
pub var _arr_15 = [_]Node{ .{ .text = "Service Monitor", .font_size = 16, .text_color = Color.rgb(201, 209, 217) }, .{ .style = .{ .gap = 8 }, .children = &_arr_14 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(72, 79, 88) } };
// [origin:d25_map_conditional_classifier:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(13, 17, 23), .padding = 20, .width = -1, .height = -1, .gap = 10, .overflow = .hidden }, .children = &_arr_15 };

