//! Generated by tsz compiler — d36_nullish_bitwise [logic.zig]
//! Source: d36_nullish_bitwise.tsz


// [origin:d36_nullish_bitwise:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\var flags = 0;
    \\function setFlags(v) { flags = v; __setState(0, v); }
    \\var colorVal = 3900150;
    \\function setColorVal(v) { colorVal = v; __setState(1, v); }
    \\var result = 0;
    \\function setResult(v) { result = v; __setState(2, v); }
    \\var output = '';
    \\function setOutput(v) { output = v; __setStateString(3, v); }
    \\setFlags(0);
    \\setColorVal(0x3b82f6);
    \\
    \\function toggleFlag(bit) {
    \\  var current = flags;
    \\  var mask = 1 << bit;
    \\  if ((current & mask) != 0) {
    \\    setFlags(current & ~mask);
    \\    setOutput('cleared bit ' + bit);
    \\  } else {
    \\    setFlags(current | mask);
    \\    setOutput('set bit ' + bit);
    \\  }
    \\}
    \\
    \\function extractChannels() {
    \\  var c = colorVal;
    \\  var r = (c >> 16) & 0xFF;
    \\  var g = (c >> 8) & 0xFF;
    \\  var b = c & 0xFF;
    \\  setResult(r + g + b);
    \\  setOutput('R:' + r + ' G:' + g + ' B:' + b);
    \\}
    \\
    \\function xorColor() {
    \\  setColorVal(colorVal ^ 0xFFFFFF);
    \\  setOutput('inverted color');
    \\}
    \\
    \\function shiftTest() {
    \\  var val = 1;
    \\  val = val << 4;
    \\  setResult(val);
    \\  setOutput('1 << 4 = ' + val);
    \\}
    \\
;

// [origin:d36_nullish_bitwise:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

