//! Generated by tsz compiler — d103c_glyphs_effects [nodes.zig]
//! Source: d103c_glyphs_effects.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;
const handlers = @import("handlers.zig");

// [origin:d103c_glyphs_effects:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d103c_glyphs_effects.tsz:3 — <Box>
pub var _arr_0 = [_]Node{ .{ .style = .{ .width = 200, .height = 100, .position = .absolute }, .effect_name = "plasma", .effect_render = handlers._effect_render_0 }, .{ .text = "Effect + Glyph Test", .font_size = 24, .text_color = Color.rgb(241, 245, 249) }, .{ .text = "Status:\x01Active", .inline_glyphs = &[_]layout.InlineGlyph{ .{ .d = "M 0,-10 L 8.66,5 L -8.66,5 Z", .fill = Color.rgb(34, 197, 94), .stroke = Color.rgba(0, 0, 0, 0), .stroke_width = 0, .scale = 1.0 } }, .font_size = 20, .text_color = Color.rgb(226, 232, 240) }, .{ .text = "Plasma\x01star", .inline_glyphs = &[_]layout.InlineGlyph{ .{ .d = "M 0,-10 L 9.51,-3.09 L 5.88,8.09 L -5.88,8.09 L -9.51,-3.09 Z", .fill = Color.rgb(255, 255, 255), .stroke = Color.rgba(0, 0, 0, 0), .stroke_width = 0, .scale = 1.0, .fill_effect = "plasma" } }, .font_size = 24, .text_color = Color.rgb(226, 232, 240) } };
// [origin:d103c_glyphs_effects:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .background_color = Color.rgb(15, 23, 42), .padding = 32, .gap = 24, .overflow = .hidden }, .children = &_arr_0 };

