//! Generated by tsz compiler — d03_conditional_wrapping_map [handlers.zig]
//! Source: d03_conditional_wrapping_map.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d03_conditional_wrapping_map:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:d03_conditional_wrapping_map:handler:_handler_press_0]
pub fn _handler_press_0() void {
    state.setSlot(0, (if ((state.getSlot(0) == 0)) @as(i32, 1) else @as(i32, 0)));
}

