//! Generated by tsz compiler — 37_absolute_in_flex [nodes.zig]
//! Source: 37_absolute_in_flex.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:37_absolute_in_flex:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:37_absolute_in_flex.tsz:9 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "flow" } };
// tsz:37_absolute_in_flex.tsz:12 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "abs" } };
// tsz:37_absolute_in_flex.tsz:15 — <Box>
pub var _arr_2 = [_]Node{ .{ .text = "flow" } };
// tsz:37_absolute_in_flex.tsz:18 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "grow" } };
// tsz:37_absolute_in_flex.tsz:8 — <Box>
pub var _arr_4 = [_]Node{ .{ .style = .{ .width = 60, .height = 60, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_0 }, .{ .style = .{ .width = 60, .height = 60, .background_color = Color.rgb(244, 67, 54), .position = .absolute, .overflow = .auto }, .children = &_arr_1 }, .{ .style = .{ .width = 60, .height = 60, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_2 }, .{ .style = .{ .flex_grow = 1, .height = 60, .background_color = Color.rgb(255, 152, 0), .overflow = .auto }, .children = &_arr_3 } };
// tsz:37_absolute_in_flex.tsz:25 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "1" } };
// tsz:37_absolute_in_flex.tsz:28 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "2" } };
// tsz:37_absolute_in_flex.tsz:31 — <Box>
pub var _arr_7 = [_]Node{ .{ .text = "abs" } };
// tsz:37_absolute_in_flex.tsz:34 — <Box>
pub var _arr_8 = [_]Node{ .{ .text = "3" } };
// tsz:37_absolute_in_flex.tsz:24 — <Box>
pub var _arr_9 = [_]Node{ .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_5 }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(33, 150, 243), .overflow = .auto }, .children = &_arr_6 }, .{ .style = .{ .width = 40, .height = 40, .background_color = Color.rgb(244, 67, 54), .position = .absolute, .overflow = .auto }, .children = &_arr_7 }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(255, 152, 0), .overflow = .auto }, .children = &_arr_8 } };
// tsz:37_absolute_in_flex.tsz:41 — <Box>
pub var _arr_10 = [_]Node{ .{ .text = "Header" } };
// tsz:37_absolute_in_flex.tsz:44 — <Box>
pub var _arr_11 = [_]Node{ .{ .text = "Body" } };
// tsz:37_absolute_in_flex.tsz:47 — <Box>
pub var _arr_12 = [_]Node{ .{ .text = "overlay" } };
// tsz:37_absolute_in_flex.tsz:40 — <Box>
pub var _arr_13 = [_]Node{ .{ .style = .{ .height = 40, .background_color = Color.rgb(76, 175, 80), .overflow = .auto }, .children = &_arr_10 }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(55, 71, 79), .overflow = .auto }, .children = &_arr_11 }, .{ .style = .{ .width = 80, .height = 30, .background_color = Color.rgb(244, 67, 54), .position = .absolute, .overflow = .auto }, .children = &_arr_12 } };
// tsz:37_absolute_in_flex.tsz:3 — <Box>
pub var _arr_14 = [_]Node{ .{ .text = "WPT: position absolute in flex" }, .{ .text = "VERIFY: Absolute child removed from flow, other items fill space, column overlay", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "Absolute child removed from flow — other items fill space" }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 80, .background_color = Color.rgb(51, 51, 51), .padding = 4, .gap = 4, .overflow = .auto }, .children = &_arr_4 }, .{ .text = "All flow items — absolute doesn't consume space" }, .{ .style = .{ .flex_direction = .row, .width = 300, .height = 60, .background_color = Color.rgb(51, 51, 51), .gap = 4, .overflow = .auto }, .children = &_arr_9 }, .{ .text = "Column with absolute overlay" }, .{ .style = .{ .flex_direction = .column, .width = 200, .height = 150, .background_color = Color.rgb(51, 51, 51), .gap = 4, .overflow = .auto }, .children = &_arr_13 } };
// [origin:37_absolute_in_flex:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 8, .overflow = .hidden }, .children = &_arr_14 };

