//! Generated by tsz compiler — 37_absolute_in_flex [state.zig]
//! Source: 37_absolute_in_flex.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

pub fn _initState() void {
}

