//! Generated by tsz compiler — d23_empty_array [handlers.zig]
//! Source: d23_empty_array.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:d23_empty_array:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:d23_empty_array:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobal("loadInbox");
}

// [origin:d23_empty_array:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobal("loadSpam");
}

// [origin:d23_empty_array:handler:_handler_press_2]
pub fn _handler_press_2() void {
    qjs_runtime.callGlobal("clearAll");
}

