//! Generated by tsz compiler — 11_padding_margin [logic.zig]
//! Source: 11_padding_margin.tsz


// [origin:11_padding_margin:logic]
// ── Embedded JS logic ────────────────────────────────────────
pub const JS_LOGIC =
    \\
;

// [origin:11_padding_margin:logic]
// ── Embedded Lua logic ───────────────────────────────────────
pub const LUA_LOGIC =
    \\
;

