//! Generated by tsz compiler — 10_flex_basis [state.zig]
//! Source: 10_flex_basis.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

pub fn _initState() void {
}

