//! Generated by tsz compiler — d71_increment_decrement [nodes.zig]
//! Source: d71_increment_decrement.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:d71_increment_decrement:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:d71_increment_decrement.tsz:76 — <Pressable>
pub var _arr_0 = [_]Node{ .{ .text = "++ All", .font_size = 11, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d71_increment_decrement.tsz:79 — <Pressable>
pub var _arr_1 = [_]Node{ .{ .text = "-- All", .font_size = 11, .text_color = Color.rgb(255, 255, 255) } };
// tsz:d71_increment_decrement.tsz:82 — <Pressable>
pub var _arr_2 = [_]Node{ .{ .text = "Count to 100", .font_size = 11, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d71_increment_decrement.tsz:85 — <Pressable>
pub var _arr_3 = [_]Node{ .{ .text = "Down from 50", .font_size = 11, .text_color = Color.rgb(226, 232, 240) } };
// tsz:d71_increment_decrement.tsz:75 — <Box>
pub var _arr_4 = [_]Node{ .{ .style = .{ .padding = 8, .background_color = Color.rgb(34, 197, 94), .border_radius = 6 }, .handlers = .{ .js_on_press = "incrementAll()" }, .children = &_arr_0 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(220, 38, 38), .border_radius = 6 }, .handlers = .{ .js_on_press = "decrementAll()" }, .children = &_arr_1 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(51, 65, 85), .border_radius = 6 }, .handlers = .{ .js_on_press = "countUp(100)" }, .children = &_arr_2 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(51, 65, 85), .border_radius = 6 }, .handlers = .{ .js_on_press = "countDown(50)" }, .children = &_arr_3 } };
// tsz:d71_increment_decrement.tsz:89 — <Box>
pub var _arr_8 = [_]Node{ .{ .style = .{ .gap = 4 } } };
// tsz:d71_increment_decrement.tsz:72 — <Box>
pub var _arr_9 = [_]Node{ .{ .text = "Increment / Decrement", .font_size = 16, .text_color = Color.rgb(226, 232, 240) }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(100, 116, 139) }, .{ .style = .{ .flex_direction = .row, .gap = 6 }, .children = &_arr_4 }, .{ .style = .{ .gap = 4 }, .children = &_arr_8 }, .{ .text = "", .font_size = 10, .text_color = Color.rgb(110, 231, 183) } };
// [origin:d71_increment_decrement:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(15, 23, 42), .padding = 20, .width = -1, .height = -1, .gap = 12, .overflow = .hidden }, .children = &_arr_9 };

