//! Generated by tsz compiler — 41_aspect_ratio [state.zig]
//! Source: 41_aspect_ratio.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

pub fn _initState() void {
}

