// Cockpit classifiers — ported from tsz/carts/cockpit/style_cls.tsz.
// Token scheme: `theme-xxx` → `theme:xxx` (new classifier uses `:` delimiter).
// Importing this module registers every named primitive once.

import { classifier } from '@reactjit/runtime/classifier';

classifier({
  Root: {
    type: 'Box',
    style: { width: '100%', height: '100%', flexDirection: 'column', backgroundColor: 'theme:bg' },
  },
  Filler: { type: 'Box', style: { flexGrow: 1, flexBasis: 0 } },

  Shell: {
    type: 'Box',
    style: {
      flexGrow: 1, flexBasis: 0,
      padding: 'theme:spaceXxl',
      backgroundColor: 'theme:bg',
    },
  },
  Page: {
    type: 'Box',
    style: {
      flexGrow: 1, flexBasis: 0,
      flexDirection: 'column',
      borderRadius: 'theme:radiusLg',
      backgroundColor: 'theme:bgRaised',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderLight',
      overflow: 'hidden',
    },
  },

  SegmentsRow: {
    type: 'Box',
    style: { flexDirection: 'row', height: 48 },
  },
  Segment1: { type: 'Box', style: { flexGrow: 1, flexBasis: 0, backgroundColor: 'theme:bgSunken' } },
  Segment2: { type: 'Box', style: { flexGrow: 1, flexBasis: 0, backgroundColor: 'theme:bgAlt' } },
  Segment3: { type: 'Box', style: { flexGrow: 1, flexBasis: 0, backgroundColor: 'theme:bgTint' } },

  PageCanvasWrap: {
    type: 'Box',
    style: { flexGrow: 1, flexBasis: 0, backgroundColor: '#080d14' },
  },

  ActionBar: {
    type: 'Box',
    style: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 'theme:spaceSm',
      marginLeft: 'theme:spaceLg',
      marginRight: 'theme:spaceLg',
      marginBottom: 'theme:spaceSm',
      paddingTop: 2, paddingBottom: 2,
    },
  },
  ActionSlot: {
    type: 'Pressable',
    style: {
      width: 62, height: 62,
      borderRadius: 'theme:radiusLg',
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: 'theme:bgAlt',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderLight',
    },
  },
  ActionSlotFrame: {
    type: 'Box',
    style: {
      width: 56, height: 56,
      alignItems: 'center', justifyContent: 'center',
      borderRadius: 'theme:radiusMd',
      backgroundColor: 'theme:bgSunken',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
    },
  },
  ActionSlotFrameHover: {
    type: 'Box',
    style: {
      width: 56, height: 56,
      alignItems: 'center', justifyContent: 'center',
      borderRadius: 'theme:radiusMd',
      backgroundColor: 'theme:bgRaised',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderFocus',
    },
  },
  ActionSlotGlow: {
    type: 'Box',
    style: {
      position: 'absolute',
      top: 3, left: 3, right: 3, bottom: 3,
      borderRadius: 'theme:radiusSm',
      backgroundColor: 'theme:primary',
      opacity: 0.22,
    },
  },
  ActionSlotGlyph: { type: 'Text', fontSize: 20, color: 'theme:textPrimary' },
  ActionSlotKey:   { type: 'Text', fontSize: 10, color: 'theme:textAccent' },
  ActionSlotLabel: { type: 'Text', fontSize: 9, color: 'theme:textDim' },

  TermInputBar: {
    type: 'Box',
    style: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 'theme:spaceSm',
      marginLeft: 'theme:spaceLg',
      marginRight: 'theme:spaceLg',
      marginBottom: 'theme:spaceLg',
      paddingLeft: 'theme:spaceMd',
      paddingRight: 'theme:spaceMd',
      paddingTop: 6, paddingBottom: 6,
      borderRadius: 'theme:radiusLg',
      backgroundColor: 'theme:bgFloat',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderFocus',
    },
  },
  TermInputPrompt: { type: 'Text', fontSize: 'theme:fontMd', color: 'theme:textAccent' },

  MsgCard: {
    type: 'Box',
    style: {
      width: '100%',
      height: 460,
      flexDirection: 'column',
      borderRadius: 'theme:radiusLg',
      backgroundColor: 'theme:bgFloat',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderLight',
      overflow: 'hidden',
    },
  },

  MsgHeader: {
    type: 'Box',
    style: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 'theme:spaceMd',
      paddingRight: 'theme:spaceMd',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      gap: 'theme:spaceMd',
      backgroundColor: 'theme:bgRaised',
      borderBottomWidth: 'theme:borderW1',
      borderBottomColor: 'theme:borderHair',
    },
  },
  HeaderAvatar: {
    type: 'Pressable',
    style: {
      width: 30, height: 30,
      borderRadius: 'theme:radiusSm',
      alignItems: 'center', justifyContent: 'center',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderFocus',
    },
  },
  HeaderAvatarLetter: { type: 'Text', fontSize: 14, color: '#0b0f16' },
  HeaderTextCol: { type: 'Box', style: { flexDirection: 'column', gap: 1, flexGrow: 1, flexBasis: 0 } },
  HeaderName:    { type: 'Text', fontSize: 'theme:fontMd', color: 'theme:textPrimary' },
  HeaderModel:   { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textPrimary' },
  HeaderStatusDot: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:success' },
  },
  HeaderStatusConnecting: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:warning' },
  },

  MsgBody: {
    type: 'Box',
    style: {
      flexGrow: 1, flexBasis: 0,
      flexDirection: 'column',
      padding: 'theme:spaceMd',
      gap: 'theme:spaceMd',
      backgroundColor: 'theme:bgFloat',
    },
  },
  SpawnPanel: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'column',
      gap: 'theme:spaceXs',
      paddingLeft: 'theme:spaceSm',
      paddingRight: 'theme:spaceSm',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      borderRadius: 'theme:radiusMd',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderLight',
      backgroundColor: 'theme:bgRaised',
    },
  },
  SpawnPanelHeader: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 'theme:spaceSm',
    },
  },
  SpawnPanelTitle: { type: 'Text', fontSize: 14, color: 'theme:textPrimary', fontWeight: '600' },
  SpawnPanelStatus: { type: 'Text', fontSize: 11, color: 'theme:textDim' },
  SpawnPanelHint:  { type: 'Text', fontSize: 10, color: 'theme:textDim' },
  SpawnPanelGrid: {
    type: 'Box',
    style: { width: '100%', flexDirection: 'column', gap: 'theme:spaceSm' },
  },
  SpawnSection: {
    type: 'Box',
    style: { flexDirection: 'column', gap: 4 },
  },
  SpawnSectionHeader: {
    type: 'Box',
    style: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  },
  SpawnSectionTitle: { type: 'Text', fontSize: 11, color: 'theme:textAccent' },
  SpawnSectionDivider: {
    type: 'Box',
    style: {
      flexGrow: 1,
      height: 1,
      backgroundColor: 'theme:borderMid',
    },
  },
  SpawnActiveBadge: {
    type: 'Text',
    fontSize: 10,
    color: 'theme:textSuccess',
    marginTop: 2,
  },
  SpawnLiveGrid: {
    type: 'Box',
    style: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', gap: 'theme:spaceXs' },
  },
  SpawnSoonGrid: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 'theme:spaceXs',
      paddingTop: 'theme:spaceSm',
      borderTopWidth: 'theme:borderW1',
      borderTopColor: 'theme:borderHair',
    },
  },
  SpawnGridItem: {
    type: 'Pressable',
    style: {
      width: '48%',
      flexDirection: 'column',
      gap: 3,
      paddingLeft: 8,
      paddingRight: 6,
      paddingTop: 7,
      paddingBottom: 7,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
      backgroundColor: 'theme:bgAlt',
      shadowOpacity: 0.2,
    },
  },
  SpawnGridItemSmall: {
    type: 'Pressable',
    style: {
      width: '31%',
      flexDirection: 'column',
      gap: 3,
      paddingLeft: 6,
      paddingRight: 4,
      paddingTop: 6,
      paddingBottom: 6,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
      backgroundColor: 'theme:bgAlt',
    },
  },
  GridItemBrandRow: {
    type: 'Box',
    style: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  },
  GridItemBrand:  { type: 'Text', fontSize: 10, color: 'theme:textDim' },
  GridItemStatusLive: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textSuccess' },
  GridItemStatusSoon: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textDim' },
  GridItemName:   { type: 'Text', fontSize: 13, color: 'theme:textPrimary', fontWeight: '600' },
  GridItemId:     { type: 'Text', fontSize: 10, color: 'theme:textDim' },
  GridItemDesc:   { type: 'Text', fontSize: 9, color: 'theme:textDim' },
  GridItemNameSmall: { type: 'Text', fontSize: 11, color: 'theme:textPrimary', fontWeight: '600' },
  GridItemIdSmall:   { type: 'Text', fontSize: 9, color: 'theme:textDim' },
  ChatGutterDivider: {
    type: 'Box',
    style: { width: 14, height: 1, backgroundColor: 'theme:borderMid', marginTop: 2, marginBottom: 2 },
  },
  SpawnPanelClosed: {
    type: 'Pressable',
    style: {
      width: '100%',
      alignItems: 'center', justifyContent: 'center',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      borderRadius: 'theme:radiusMd',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderLight',
      backgroundColor: 'theme:bgRaised',
    },
  },
  SpawnPanelDismiss: {
    type: 'Pressable',
    style: {
      width: 22, height: 22,
      alignItems: 'center', justifyContent: 'center',
      borderRadius: 'theme:radiusSm',
      backgroundColor: 'theme:bgSunken',
    },
  },

  MsgStack: {
    type: 'Box',
    style: {
      flexDirection: 'column',
      gap: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
    },
  },
  MsgStatusStrip: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
      paddingLeft: 'theme:spaceSm',
      paddingRight: 'theme:spaceSm',
      paddingTop: 6,
      paddingBottom: 6,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderHair',
      backgroundColor: 'theme:bgSunken',
    },
  },
  MsgStatusDivider: {
    type: 'Box',
    style: {
      width: 1,
      height: 12,
      backgroundColor: 'theme:borderMid',
    },
  },
  MsgTimelineRow: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 'theme:spaceSm',
    },
  },
  MsgLane: {
    type: 'Box',
    style: {
      width: 18,
      alignItems: 'center',
      paddingTop: 2,
    },
  },
  MsgLaneLine: {
    type: 'Box',
    style: {
      width: 1,
      flexGrow: 1,
      marginTop: 4,
      marginBottom: 2,
      backgroundColor: 'theme:borderHair',
    },
  },
  MsgLaneGlyph: {
    type: 'Box',
    style: {
      width: 16,
      height: 16,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 'theme:radiusXs',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
      backgroundColor: 'theme:bgSunken',
    },
  },
  MsgEntry: {
    type: 'Box',
    style: {
      flexGrow: 1,
      flexBasis: 0,
    },
  },
  MsgEntryCard: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'column',
      gap: 6,
      paddingLeft: 'theme:spaceSm',
      paddingRight: 'theme:spaceSm',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
      borderLeftWidth: 2,
      borderLeftColor: 'theme:borderFocus',
      backgroundColor: 'theme:bgRaised',
    },
  },
  MsgEntryHeader: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
    },
  },
  MsgInlineBadge: {
    type: 'Box',
    style: {
      paddingLeft: 6,
      paddingRight: 6,
      paddingTop: 2,
      paddingBottom: 2,
      borderRadius: 'theme:radiusFull',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
      backgroundColor: 'theme:bgSunken',
    },
  },
  MsgMetaBadge: {
    type: 'Box',
    style: {
      paddingLeft: 5,
      paddingRight: 5,
      paddingTop: 1,
      paddingBottom: 1,
      borderRadius: 'theme:radiusXs',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
      backgroundColor: 'theme:bgSunken',
    },
  },
  MsgLabelRow: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
  },
  MsgThinkingPanel: {
    type: 'Box',
    style: {
      width: '100%',
      marginTop: 4,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: 7,
      paddingBottom: 7,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderHair',
      backgroundColor: 'rgba(0, 0, 0, 0.18)',
    },
  },
  MsgToolHeader: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
  },
  MsgToolBar: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: 7,
      paddingBottom: 7,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderHair',
      backgroundColor: 'rgba(0, 0, 0, 0.22)',
    },
  },
  MsgCodeBlock: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'column',
      gap: 4,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: 7,
      paddingBottom: 7,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: '#243041',
      backgroundColor: '#11161f',
    },
  },
  MsgCodeHeader: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingBottom: 4,
      borderBottomWidth: 'theme:borderW1',
      borderBottomColor: '#243041',
    },
  },
  MsgEmptyState: {
    type: 'Box',
    style: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 40,
      paddingBottom: 16,
    },
  },
  MsgRow: { type: 'Box', style: { width: '100%', flexDirection: 'row' } },
  MsgBlockAssistant: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'column',
      gap: 2,
      paddingLeft: 'theme:spaceSm',
      paddingRight: 'theme:spaceSm',
      paddingTop: 'theme:spaceXs',
      paddingBottom: 'theme:spaceSm',
      borderLeftWidth: 2,
      borderLeftColor: 'theme:primary',
      backgroundColor: 'theme:bgRaised',
    },
  },
  MsgBlockUser: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'column',
      gap: 2,
      paddingLeft: 'theme:spaceSm',
      paddingRight: 'theme:spaceSm',
      paddingTop: 'theme:spaceXs',
      paddingBottom: 'theme:spaceSm',
      borderLeftWidth: 2,
      borderLeftColor: 'theme:accent',
      backgroundColor: 'theme:bgAlt',
    },
  },
  MsgBlockSystem: {
    type: 'Box',
    style: {
      width: '100%',
      paddingTop: 'theme:spaceXs',
      paddingBottom: 'theme:spaceXs',
    },
  },
  MsgAuthorAssistant: { type: 'Text', fontSize: 'theme:fontXs', color: 'theme:textAccent' },
  MsgAuthorUser:      { type: 'Text', fontSize: 'theme:fontXs', color: 'theme:textInfo' },
  MsgAuthorMeta:      { type: 'Text', fontSize: 'theme:fontXs', color: 'theme:textWarning' },
  MsgText:            { type: 'Text', fontSize: 'theme:fontSm', color: 'theme:textPrimary', lineHeight: 14 },
  MsgTextUser:        { type: 'Text', fontSize: 'theme:fontSm', color: 'theme:textPrimary', lineHeight: 14 },
  MsgSystemLine:      { type: 'Text', fontSize: 'theme:fontXs', color: 'theme:textDim' },

  ChatFrame: {
    type: 'Box',
    style: {
      width: '100%', height: '100%',
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 'theme:spaceSm',
      paddingRight: 'theme:spaceXs',
      paddingLeft: 'theme:spaceXs',
    },
  },
  ChatCenterCol: {
    type: 'Box',
    style: {
      flexGrow: 1,
      flexBasis: 0,
      flexDirection: 'column',
      gap: 'theme:spaceSm',
      minHeight: 0,
    },
  },
  ChatGutterLeft: {
    type: 'Box',
    style: { width: 22, flexDirection: 'column', alignItems: 'center', gap: 'theme:spaceXs' },
  },
  ChatGutterCol: {
    type: 'Box',
    style: { width: 22, flexDirection: 'column', alignItems: 'center', gap: 2 },
  },
  ChatGutterItem: {
    type: 'Pressable',
    style: {
      width: 18, height: 18,
      alignItems: 'center', justifyContent: 'center',
      borderRadius: 'theme:radiusXs',
      backgroundColor: 'theme:bgSunken',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
    },
  },
  ChatGutterItemActive: {
    type: 'Pressable',
    style: {
      width: 18, height: 18,
      alignItems: 'center', justifyContent: 'center',
      borderRadius: 'theme:radiusXs',
      backgroundColor: 'theme:primary',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderFocus',
    },
  },
  ChatGutterItemLabel: { type: 'Text', fontSize: 9, color: 'theme:textDim' },
  ChatGutterItemLabelActive: { type: 'Text', fontSize: 9, color: '#0b0f16' },
  ChatGutterRight: {
    type: 'Box',
    style: { width: 14, height: 460, alignSelf: 'flex-start', flexDirection: 'column', gap: 2 },
  },

  ChatSignalOn: {
    type: 'Box',
    style: { flexGrow: 1, flexBasis: 0, width: '100%', borderRadius: 2, backgroundColor: 'theme:primary' },
  },
  ChatSignalOff: {
    type: 'Box',
    style: { flexGrow: 1, flexBasis: 0, width: '100%', borderRadius: 2, backgroundColor: 'theme:bgSunken' },
  },

  SegmentFlip: {
    type: 'Pressable',
    style: {
      flexGrow: 1, flexBasis: 0,
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: 'theme:bgAlt',
    },
  },
  SegmentFlipLabel: { type: 'Text', fontSize: 'theme:fontSm', color: 'theme:textPrimary' },

  MsgFoot: {
    type: 'Box',
    style: {
      flexDirection: 'column',
      gap: 'theme:spaceXxs',
      paddingLeft: 'theme:spaceMd',
      paddingRight: 'theme:spaceMd',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      backgroundColor: 'theme:bgRaised',
      borderTopWidth: 'theme:borderW1',
      borderTopColor: 'theme:borderHair',
    },
  },
  MsgFootLabelRow: {
    type: 'Box',
    style: { flexDirection: 'row', alignItems: 'center', gap: 'theme:spaceSm' },
  },
  MsgFootLabel: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textPrimary' },
  MsgFootValue: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textPrimary' },
  WorkerQuestCard: {
    type: 'Box',
    style: {
      width: '100%',
      height: 176,
      flexDirection: 'column',
      gap: 'theme:spaceSm',
      paddingLeft: 'theme:spaceMd',
      paddingRight: 'theme:spaceMd',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      borderRadius: 'theme:radiusMd',
      backgroundColor: '#1b2029',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderHair',
    },
  },
  WorkerQuestHeader: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 'theme:spaceSm',
    },
  },
  WorkerQuestBar: {
    type: 'Box',
    style: {
      width: '100%',
      height: 6,
      flexDirection: 'row',
      borderRadius: 2,
      backgroundColor: '#0f141d',
      overflow: 'hidden',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderHair',
    },
  },
  WorkerQuestBarFill: {
    type: 'Box',
    style: {
      height: '100%',
      backgroundColor: 'theme:success',
    },
  },
  WorkerQuestBarGap: {
    type: 'Box',
    style: {
      height: '100%',
    },
  },
  WorkerQuestStepList: {
    type: 'Box',
    style: {
      flexDirection: 'column',
      gap: 4,
    },
  },
  WorkerQuestStepRow: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingLeft: 6,
      paddingRight: 6,
      paddingTop: 5,
      paddingBottom: 5,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'transparent',
    },
  },
  WorkerQuestAddRow: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingLeft: 6,
      paddingRight: 6,
      paddingTop: 5,
      paddingBottom: 5,
      borderRadius: 'theme:radiusSm',
      backgroundColor: 'rgba(0, 0, 0, 0.16)',
    },
  },
  WorkerQuestComposer: {
    type: 'Box',
    style: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingLeft: 6,
      paddingRight: 6,
      paddingTop: 5,
      paddingBottom: 5,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'rgba(52, 211, 153, 0.30)',
      backgroundColor: 'rgba(0, 0, 0, 0.20)',
    },
  },

  BottomBar: {
    type: 'Box',
    style: {
      height: 28,
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 'theme:spaceMd',
      paddingRight: 'theme:spaceMd',
      gap: 'theme:spaceMd',
      backgroundColor: 'theme:bgRaised',
      borderTopWidth: 'theme:borderW1',
      borderTopColor: 'theme:borderHair',
    },
  },
  BarLabel: { type: 'Text', fontSize: 'theme:fontSm', color: 'theme:textPrimary' },
  Spacer: { type: 'Box', style: { flexGrow: 1 } },

  ThemeButton: {
    type: 'Pressable',
    style: {
      paddingLeft: 'theme:spaceMd',
      paddingRight: 'theme:spaceMd',
      paddingTop: 3, paddingBottom: 3,
      borderRadius: 'theme:radiusSm',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderFocus',
      backgroundColor: 'theme:primary',
    },
  },
  ThemeButtonLabel: { type: 'Text', fontSize: 'theme:fontSm', color: 'theme:textOnAccent' },

  RaidColumn: {
    type: 'Box',
    style: {
      flexDirection: 'column',
      gap: 'theme:spaceSm',
      paddingLeft: 'theme:spaceLg',
      paddingTop: 'theme:spaceLg',
      paddingBottom: 'theme:spaceLg',
      width: 220,
    },
  },
  RaidHeader: {
    type: 'Box',
    style: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 'theme:spaceSm',
      paddingLeft: 4,
      paddingBottom: 2,
    },
  },
  RaidHeaderText: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textDim' },
  RaidFrame: {
    type: 'Pressable',
    style: {
      width: 196,
      flexDirection: 'column',
      gap: 4,
      paddingLeft: 'theme:spaceSm',
      paddingRight: 'theme:spaceSm',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      borderRadius: 'theme:radiusMd',
      backgroundColor: 'theme:bgFloat',
    },
  },
  RaidFrameBorderActive: {
    type: 'Box',
    style: {
      position: 'absolute',
      top: 0, left: 0, right: 0, bottom: 0,
      borderRadius: 'theme:radiusMd',
      borderWidth: 2,
      borderColor: 'theme:borderFocus',
    },
  },
  RaidFrameBorderIdle: {
    type: 'Box',
    style: {
      position: 'absolute',
      top: 0, left: 0, right: 0, bottom: 0,
      borderRadius: 'theme:radiusMd',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
    },
  },
  RaidFrameHead: {
    type: 'Box',
    style: { flexDirection: 'row', alignItems: 'center', gap: 'theme:spaceSm' },
  },
  RaidFrameClassPill: {
    type: 'Box',
    style: {
      width: 22, height: 22,
      borderRadius: 'theme:radiusFull',
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: 'theme:primary',
    },
  },
  RaidFrameClassLetter: { type: 'Text', fontSize: 12, color: '#0b0f16' },
  RaidFrameNameCol: {
    type: 'Box',
    style: { flexDirection: 'column', gap: 1, flexGrow: 1, flexBasis: 0 },
  },
  RaidFrameName: { type: 'Text', fontSize: 'theme:fontSm', color: 'theme:textPrimary' },
  RaidFrameMeta: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textDim' },
  RaidFrameStatusOn: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:success' },
  },
  RaidFrameStatusOff: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:bgSunken' },
  },
  RaidFrameHpBar: {
    type: 'Box',
    style: {
      width: '100%', height: 8,
      flexDirection: 'row',
      borderRadius: 2,
      backgroundColor: 'theme:bgSunken',
      overflow: 'hidden',
    },
  },
  RaidFrameHpFill: { type: 'Box', style: { height: '100%', backgroundColor: 'theme:success' } },
  RaidFrameHpGap:  { type: 'Box', style: { height: '100%' } },
  RaidFramePowerBar: {
    type: 'Box',
    style: {
      width: '100%', height: 4,
      flexDirection: 'row',
      borderRadius: 2,
      backgroundColor: 'theme:bgSunken',
      overflow: 'hidden',
    },
  },
  RaidFramePowerFill: { type: 'Box', style: { height: '100%', backgroundColor: 'theme:info' } },
  RaidFramePowerGap:  { type: 'Box', style: { height: '100%' } },
  RaidFrameFoot: {
    type: 'Box',
    style: { flexDirection: 'row', alignItems: 'center', gap: 'theme:spaceSm' },
  },
  RaidFrameFootText: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textDim' },

  RaidFrameEmpty: {
    type: 'Pressable',
    style: {
      width: 196, height: 58,
      flexDirection: 'row',
      alignItems: 'center', justifyContent: 'center',
      gap: 'theme:spaceSm',
      borderRadius: 'theme:radiusMd',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderHair',
      backgroundColor: 'theme:bgSunken',
    },
  },
  RaidFrameEmptyPlus: { type: 'Text', fontSize: 14, color: 'theme:textDim' },
  RaidFrameEmptyText: { type: 'Text', fontSize: 'theme:fontXs', color: 'theme:textDim' },

  QuestColumn: {
    type: 'Box',
    style: {
      flexDirection: 'column',
      gap: 'theme:spaceSm',
      paddingLeft: 'theme:spaceLg',
      paddingRight: 'theme:spaceLg',
      paddingTop: 'theme:spaceLg',
      paddingBottom: 'theme:spaceLg',
      width: 260,
    },
  },
  QuestHeader: {
    type: 'Box',
    style: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 'theme:spaceSm',
      paddingLeft: 4,
      paddingBottom: 2,
    },
  },
  QuestHeaderText: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textDim' },
  QuestCard: {
    type: 'Pressable',
    style: {
      width: 236,
      flexDirection: 'column',
      gap: 4,
      paddingLeft: 'theme:spaceSm',
      paddingRight: 'theme:spaceSm',
      paddingTop: 'theme:spaceSm',
      paddingBottom: 'theme:spaceSm',
      borderRadius: 'theme:radiusMd',
      backgroundColor: 'theme:bgFloat',
    },
  },
  QuestCardBorderActive: {
    type: 'Box',
    style: {
      position: 'absolute',
      top: 0, left: 0, right: 0, bottom: 0,
      borderRadius: 'theme:radiusMd',
      borderWidth: 2,
      borderColor: 'theme:borderFocus',
    },
  },
  QuestCardBorderIdle: {
    type: 'Box',
    style: {
      position: 'absolute',
      top: 0, left: 0, right: 0, bottom: 0,
      borderRadius: 'theme:radiusMd',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
    },
  },
  QuestTitleRow: {
    type: 'Box',
    // paddingRight reserves a lane for the absolute-positioned state icon
    // (a direct child of QuestCard) so the title text doesn't run under it.
    style: { width: '100%', paddingRight: 24, flexDirection: 'row', alignItems: 'center', gap: 'theme:spaceSm' },
  },
  QuestTitle: {
    type: 'Text',
    fontSize: 'theme:fontSm', color: 'theme:textPrimary',
    flexGrow: 1, flexBasis: 0,
  },
  // State icons — single glyph pinned to the card's top-right corner.
  // Icons sidestep the text-measurement sizing that was overflowing the old
  // colored text-pill variants.
  QuestStateIconActive: {
    type: 'Text',
    position: 'absolute', top: 'theme:spaceSm', right: 'theme:spaceSm',
    fontSize: 14, color: 'theme:info',
  },
  QuestStateIconPending: {
    type: 'Text',
    position: 'absolute', top: 'theme:spaceSm', right: 'theme:spaceSm',
    fontSize: 14, color: 'theme:textDim',
  },
  QuestStateIconDone: {
    type: 'Text',
    position: 'absolute', top: 'theme:spaceSm', right: 'theme:spaceSm',
    fontSize: 14, color: 'theme:success',
  },
  QuestStateIconFailed: {
    type: 'Text',
    position: 'absolute', top: 'theme:spaceSm', right: 'theme:spaceSm',
    fontSize: 14, color: 'theme:error',
  },
  QuestMetaRow: {
    type: 'Box',
    style: { flexDirection: 'row', alignItems: 'center', gap: 'theme:spaceSm' },
  },
  QuestMetaText: { type: 'Text', fontSize: 'theme:fontXxs', color: 'theme:textDim' },
  QuestProgressBar: {
    type: 'Box',
    style: {
      width: '100%', height: 6,
      flexDirection: 'row',
      borderRadius: 2,
      backgroundColor: 'theme:bgSunken',
      overflow: 'hidden',
    },
  },
  QuestProgressFill: { type: 'Box', style: { height: '100%', backgroundColor: 'theme:primary' } },
  QuestProgressGap:  { type: 'Box', style: { height: '100%' } },
  QuestPartyRow: {
    type: 'Box',
    style: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  },
  QuestPartyDot: {
    type: 'Box',
    style: {
      width: 12, height: 12,
      borderRadius: 'theme:radiusFull',
      backgroundColor: 'theme:primary',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderMid',
    },
  },
  QuestStepList: {
    type: 'Box',
    style: { flexDirection: 'column', gap: 3, paddingTop: 'theme:spaceXs' },
  },
  QuestStepRow: {
    type: 'Box',
    style: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingTop: 1, paddingBottom: 1,
    },
  },
  QuestStepOrd: {
    type: 'Text',
    fontSize: 'theme:fontXxs', color: 'theme:textDim',
    width: 14,
  },
  QuestStepText: {
    type: 'Text',
    fontSize: 'theme:fontXxs', color: 'theme:textPrimary',
    flexGrow: 1, flexBasis: 0,
  },
  QuestStepPipPending: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:bgSunken' },
  },
  QuestStepPipActive: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:info' },
  },
  QuestStepPipVerifyPending: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:warning' },
  },
  QuestStepPipVerifyPassed: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:accent' },
  },
  QuestStepPipPlannerConfirmed: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:success' },
  },
  QuestStepPipDone: {
    type: 'Box',
    style: {
      width: 8, height: 8,
      borderRadius: 'theme:radiusFull',
      backgroundColor: 'theme:success',
      borderWidth: 'theme:borderW1',
      borderColor: 'theme:borderFocus',
    },
  },
  QuestStepPipRejected: {
    type: 'Box',
    style: { width: 8, height: 8, borderRadius: 'theme:radiusFull', backgroundColor: 'theme:error' },
  },
});

export { classifiers as C } from '@reactjit/runtime/classifier';
