//! Generated by tsz compiler — d127_schema_driven_form [state.zig]
//! Source: d127_schema_driven_form.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const state = api.state;

// [origin:d127_schema_driven_form:state]
// ── State manifest ──────────────────────────────────────────────
// slot 0: activeQuestion (int)
// slot 1: answeredCount (int)
// slot 2: totalQuestions (int)
// slot 3: submitted (int)
// slot 4: summaryText (string)
// slot 5: __jsExpr_5 (string)
comptime { if (6 != 6) @compileError("state slot count mismatch"); }

// [origin:d127_schema_driven_form:state]
// ── Dynamic text buffers ─────────────────────────────────────────
pub var _dyn_buf_1: [128]u8 = std.mem.zeroes([128]u8);
pub var _dyn_text_1: []const u8 = "";
pub var _dyn_buf_2: [64]u8 = std.mem.zeroes([64]u8);
pub var _dyn_text_2: []const u8 = "";

pub const qjs = @cImport({ @cDefine("_GNU_SOURCE", "1"); @cDefine("QUICKJS_NG_BUILD", "1"); @cInclude("quickjs.h"); });
pub const QJS_UNDEFINED = qjs.JSValue{ .u = .{ .int32 = 0 }, .tag = 3 };

// [origin:d127_schema_driven_form:state]
// ── Object arrays ───────────────────────────────────────────────
pub const _oa_alloc = std.heap.page_allocator;

pub fn _oaDupString(src: []const u8) []const u8 {
    if (src.len == 0) return &[_]u8{};
    return _oa_alloc.dupe(u8, src) catch &[_]u8{};
}

pub fn _oaFreeString(slot: *[]const u8, len_slot: *usize) void {
    if (len_slot.* > 0) _oa_alloc.free(@constCast(slot.*));
    slot.* = &[_]u8{};
    len_slot.* = 0;
}

pub var _oa0_text: [][]const u8 = &[_][]const u8{};
pub var _oa0_text_lens: []usize = &[_]usize{};
pub var _oa0_text_cap: usize = 0;
pub var _oa0_header: [][]const u8 = &[_][]const u8{};
pub var _oa0_header_lens: []usize = &[_]usize{};
pub var _oa0_header_cap: usize = 0;
pub var _oa0_multiSelect: []i64 = &[_]i64{};
pub var _oa0_multiSelect_cap: usize = 0;
pub var _oa0_options: [][]const u8 = &[_][]const u8{};
pub var _oa0_options_lens: []usize = &[_]usize{};
pub var _oa0_options_cap: usize = 0;
pub var _oa0_len: usize = 0;
pub var _oa0_dirty: bool = false;

pub fn _oa0_ensureCapacity(needed: usize) void {
    if (needed <= _oa0_text_cap) return;
    const new_cap = @max(needed, if (_oa0_text_cap == 0) @as(usize, 64) else _oa0_text_cap * 2);
    if (_oa0_text_cap == 0) {
        _oa0_text = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_text_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_text[_j] = &[_]u8{};
        @memset(_oa0_text_lens, 0);
    } else {
        const _old_cap = _oa0_text_cap;
        _oa0_text = _oa_alloc.realloc(_oa0_text.ptr[0.._old_cap], new_cap) catch return;
        _oa0_text_lens = _oa_alloc.realloc(_oa0_text_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_text[_j] = &[_]u8{};
        @memset(_oa0_text_lens[_old_cap..new_cap], 0);
    }
    _oa0_text_cap = new_cap;
    if (_oa0_header_cap == 0) {
        _oa0_header = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_header_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_header[_j] = &[_]u8{};
        @memset(_oa0_header_lens, 0);
    } else {
        const _old_cap = _oa0_header_cap;
        _oa0_header = _oa_alloc.realloc(_oa0_header.ptr[0.._old_cap], new_cap) catch return;
        _oa0_header_lens = _oa_alloc.realloc(_oa0_header_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_header[_j] = &[_]u8{};
        @memset(_oa0_header_lens[_old_cap..new_cap], 0);
    }
    _oa0_header_cap = new_cap;
    if (_oa0_multiSelect_cap == 0) {
        _oa0_multiSelect = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa0_multiSelect, 0);
    } else {
        _oa0_multiSelect = _oa_alloc.realloc(_oa0_multiSelect.ptr[0.._oa0_multiSelect_cap], new_cap) catch return;
        @memset(_oa0_multiSelect[_oa0_multiSelect_cap..new_cap], 0);
    }
    _oa0_multiSelect_cap = new_cap;
    if (_oa0_options_cap == 0) {
        _oa0_options = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa0_options_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa0_options[_j] = &[_]u8{};
        @memset(_oa0_options_lens, 0);
    } else {
        const _old_cap = _oa0_options_cap;
        _oa0_options = _oa_alloc.realloc(_oa0_options.ptr[0.._old_cap], new_cap) catch return;
        _oa0_options_lens = _oa_alloc.realloc(_oa0_options_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa0_options[_j] = &[_]u8{};
        @memset(_oa0_options_lens[_old_cap..new_cap], 0);
    }
    _oa0_options_cap = new_cap;
}

// [origin:d127_schema_driven_form:oa:_oa0_unpack]
pub fn _oa0_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa0_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "text");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_text[_i], &_oa0_text_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_text[_i] = _oaDupString(sl); _oa0_text_lens[_i] = _oa0_text[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "header");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_header[_i], &_oa0_header_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_header[_i] = _oaDupString(sl); _oa0_header_lens[_i] = _oa0_header[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "multiSelect");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa0_multiSelect[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "options");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa0_options[_i], &_oa0_options_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa0_options[_i] = _oaDupString(sl); _oa0_options_lens[_i] = _oa0_options[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa0_len) {
        for (count.._oa0_len) |_trim_i| {
            _oaFreeString(&_oa0_text[_trim_i], &_oa0_text_lens[_trim_i]);
            _oaFreeString(&_oa0_header[_trim_i], &_oa0_header_lens[_trim_i]);
            _oaFreeString(&_oa0_options[_trim_i], &_oa0_options_lens[_trim_i]);
        }
    }
    _oa0_len = count;
    _oa0_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa1_qIdx: []i64 = &[_]i64{};
pub var _oa1_qIdx_cap: usize = 0;
pub var _oa1_label: [][]const u8 = &[_][]const u8{};
pub var _oa1_label_lens: []usize = &[_]usize{};
pub var _oa1_label_cap: usize = 0;
pub var _oa1_description: [][]const u8 = &[_][]const u8{};
pub var _oa1_description_lens: []usize = &[_]usize{};
pub var _oa1_description_cap: usize = 0;
pub var _oa1_selected: []i64 = &[_]i64{};
pub var _oa1_selected_cap: usize = 0;
pub var _oa1_len: usize = 0;
pub var _oa1_dirty: bool = false;

pub fn _oa1_ensureCapacity(needed: usize) void {
    if (needed <= _oa1_qIdx_cap) return;
    const new_cap = @max(needed, if (_oa1_qIdx_cap == 0) @as(usize, 64) else _oa1_qIdx_cap * 2);
    if (_oa1_qIdx_cap == 0) {
        _oa1_qIdx = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_qIdx, 0);
    } else {
        _oa1_qIdx = _oa_alloc.realloc(_oa1_qIdx.ptr[0.._oa1_qIdx_cap], new_cap) catch return;
        @memset(_oa1_qIdx[_oa1_qIdx_cap..new_cap], 0);
    }
    _oa1_qIdx_cap = new_cap;
    if (_oa1_label_cap == 0) {
        _oa1_label = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_label_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_label[_j] = &[_]u8{};
        @memset(_oa1_label_lens, 0);
    } else {
        const _old_cap = _oa1_label_cap;
        _oa1_label = _oa_alloc.realloc(_oa1_label.ptr[0.._old_cap], new_cap) catch return;
        _oa1_label_lens = _oa_alloc.realloc(_oa1_label_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_label[_j] = &[_]u8{};
        @memset(_oa1_label_lens[_old_cap..new_cap], 0);
    }
    _oa1_label_cap = new_cap;
    if (_oa1_description_cap == 0) {
        _oa1_description = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa1_description_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa1_description[_j] = &[_]u8{};
        @memset(_oa1_description_lens, 0);
    } else {
        const _old_cap = _oa1_description_cap;
        _oa1_description = _oa_alloc.realloc(_oa1_description.ptr[0.._old_cap], new_cap) catch return;
        _oa1_description_lens = _oa_alloc.realloc(_oa1_description_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa1_description[_j] = &[_]u8{};
        @memset(_oa1_description_lens[_old_cap..new_cap], 0);
    }
    _oa1_description_cap = new_cap;
    if (_oa1_selected_cap == 0) {
        _oa1_selected = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa1_selected, 0);
    } else {
        _oa1_selected = _oa_alloc.realloc(_oa1_selected.ptr[0.._oa1_selected_cap], new_cap) catch return;
        @memset(_oa1_selected[_oa1_selected_cap..new_cap], 0);
    }
    _oa1_selected_cap = new_cap;
}

// [origin:d127_schema_driven_form:oa:_oa1_unpack]
pub fn _oa1_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa1_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "qIdx");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_qIdx[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "label");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_label[_i], &_oa1_label_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_label[_i] = _oaDupString(sl); _oa1_label_lens[_i] = _oa1_label[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "description");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa1_description[_i], &_oa1_description_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa1_description[_i] = _oaDupString(sl); _oa1_description_lens[_i] = _oa1_description[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "selected");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa1_selected[_i] = _n;
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa1_len) {
        for (count.._oa1_len) |_trim_i| {
            _oaFreeString(&_oa1_label[_trim_i], &_oa1_label_lens[_trim_i]);
            _oaFreeString(&_oa1_description[_trim_i], &_oa1_description_lens[_trim_i]);
        }
    }
    _oa1_len = count;
    _oa1_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa2_qIdx: []i64 = &[_]i64{};
pub var _oa2_qIdx_cap: usize = 0;
pub var _oa2_answer: [][]const u8 = &[_][]const u8{};
pub var _oa2_answer_lens: []usize = &[_]usize{};
pub var _oa2_answer_cap: usize = 0;
pub var _oa2_len: usize = 0;
pub var _oa2_dirty: bool = false;

pub fn _oa2_ensureCapacity(needed: usize) void {
    if (needed <= _oa2_qIdx_cap) return;
    const new_cap = @max(needed, if (_oa2_qIdx_cap == 0) @as(usize, 64) else _oa2_qIdx_cap * 2);
    if (_oa2_qIdx_cap == 0) {
        _oa2_qIdx = _oa_alloc.alloc(i64, new_cap) catch return;
        @memset(_oa2_qIdx, 0);
    } else {
        _oa2_qIdx = _oa_alloc.realloc(_oa2_qIdx.ptr[0.._oa2_qIdx_cap], new_cap) catch return;
        @memset(_oa2_qIdx[_oa2_qIdx_cap..new_cap], 0);
    }
    _oa2_qIdx_cap = new_cap;
    if (_oa2_answer_cap == 0) {
        _oa2_answer = _oa_alloc.alloc([]const u8, new_cap) catch return;
        _oa2_answer_lens = _oa_alloc.alloc(usize, new_cap) catch return;
        for (0..new_cap) |_j| _oa2_answer[_j] = &[_]u8{};
        @memset(_oa2_answer_lens, 0);
    } else {
        const _old_cap = _oa2_answer_cap;
        _oa2_answer = _oa_alloc.realloc(_oa2_answer.ptr[0.._old_cap], new_cap) catch return;
        _oa2_answer_lens = _oa_alloc.realloc(_oa2_answer_lens.ptr[0.._old_cap], new_cap) catch return;
        for (_old_cap..new_cap) |_j| _oa2_answer[_j] = &[_]u8{};
        @memset(_oa2_answer_lens[_old_cap..new_cap], 0);
    }
    _oa2_answer_cap = new_cap;
}

// [origin:d127_schema_driven_form:oa:_oa2_unpack]
pub fn _oa2_unpack(ctx: ?*qjs.JSContext, _: qjs.JSValue, _: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const c2 = ctx orelse return QJS_UNDEFINED;
    const arr = argv[0];
    const len_val = qjs.JS_GetPropertyStr(c2, arr, "length");
    var arr_len: i32 = 0;
    _ = qjs.JS_ToInt32(c2, &arr_len, len_val);
    qjs.JS_FreeValue(c2, len_val);
    const count: usize = @intCast(@max(0, arr_len));
    _oa2_ensureCapacity(count);
    for (0..count) |_i| {
        const elem = qjs.JS_GetPropertyUint32(c2, arr, @intCast(_i));
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "qIdx");
        var _n: i64 = 0; _ = qjs.JS_ToInt64(c2, &_n, _v);
        qjs.JS_FreeValue(c2, _v); _oa2_qIdx[_i] = _n;
        }
        { const _v = qjs.JS_GetPropertyStr(c2, elem, "answer");
        const _s = qjs.JS_ToCString(c2, _v);
        qjs.JS_FreeValue(c2, _v);
        _oaFreeString(&_oa2_answer[_i], &_oa2_answer_lens[_i]);
        if (_s) |ss| { const sl = std.mem.span(ss); _oa2_answer[_i] = _oaDupString(sl); _oa2_answer_lens[_i] = _oa2_answer[_i].len; qjs.JS_FreeCString(c2, _s); }
        }
        qjs.JS_FreeValue(c2, elem);
    }
    if (count < _oa2_len) {
        for (count.._oa2_len) |_trim_i| _oaFreeString(&_oa2_answer[_trim_i], &_oa2_answer_lens[_trim_i]);
    }
    _oa2_len = count;
    _oa2_dirty = true;
    state.markDirty();
    return QJS_UNDEFINED;
}

pub var _oa3_text = [_][]const u8{ "Which library should we use for date formatting?", "Which features do you want to enable?", "What auth method should we implement?", "Which test frameworks should we set up?" };
pub var _oa3_text_lens = [_]usize{ 48, 37, 37, 39 };
pub var _oa3_header = [_][]const u8{ "Library", "Features", "Auth", "Testing" };
pub var _oa3_header_lens = [_]usize{ 7, 8, 4, 7 };
pub var _oa3_multiSelect = [_]i64{ 0, 1, 0, 1 };
pub var _oa3_options = [_][]const u8{ "date-fns|dayjs|luxon", "dark-mode|i18n|analytics|a11y", "JWT|OAuth2|Session|API-Key", "vitest|playwright|storybook" };
pub var _oa3_options_lens = [_]usize{ 20, 29, 26, 27 };
pub var _oa3_len: usize = 4;
pub var _oa3_dirty: bool = false;


pub fn _initState() void {
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlot(0);
    _ = state.createSlotString("");
    _ = state.createSlotString("");
}

