//! Generated by tsz compiler — l08b_timer_scheduler [nodes.zig]
//! Source: l08b_timer_scheduler.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:l08b_timer_scheduler:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:l08b_timer_scheduler.tsz:79 — <Box>
pub var _arr_0 = [_]Node{ .{ .text = "Timer Scheduler", .font_size = 16, .text_color = Color.rgb(226, 232, 240) }, .{ .text = "", .font_size = 12, .text_color = Color.rgb(96, 165, 250) } };
// tsz:l08b_timer_scheduler.tsz:85 — <Box>
pub var _arr_1 = [_]Node{ .{ .text = "", .font_size = 20, .text_color = Color.rgb(167, 139, 250) }, .{ .text = "debounce fires", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } };
// tsz:l08b_timer_scheduler.tsz:89 — <Box>
pub var _arr_2 = [_]Node{ .{ .text = "", .font_size = 20, .text_color = Color.rgb(251, 191, 36) }, .{ .text = "throttle fires", .font_size = 10, .text_color = Color.rgb(71, 85, 105) } };
// tsz:l08b_timer_scheduler.tsz:84 — <Box>
pub var _arr_3 = [_]Node{ .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 10, .align_items = .center, .gap = 2, .overflow = .auto }, .children = &_arr_1 }, .{ .style = .{ .flex_grow = 1, .background_color = Color.rgb(30, 41, 59), .border_radius = 8, .padding = 10, .align_items = .center, .gap = 2, .overflow = .auto }, .children = &_arr_2 } };
// tsz:l08b_timer_scheduler.tsz:96 — <Pressable>
pub var _arr_4 = [_]Node{ .{ .text = "+tick", .font_size = 11, .text_color = Color.rgb(96, 165, 250) } };
// tsz:l08b_timer_scheduler.tsz:99 — <Pressable>
pub var _arr_5 = [_]Node{ .{ .text = "debounce()", .font_size = 11, .text_color = Color.rgb(167, 139, 250) } };
// tsz:l08b_timer_scheduler.tsz:102 — <Pressable>
pub var _arr_6 = [_]Node{ .{ .text = "throttle()", .font_size = 11, .text_color = Color.rgb(251, 191, 36) } };
// tsz:l08b_timer_scheduler.tsz:105 — <Pressable>
pub var _arr_7 = [_]Node{ .{ .text = "rate limit demo", .font_size = 11, .text_color = Color.rgb(52, 211, 153) } };
// tsz:l08b_timer_scheduler.tsz:108 — <Pressable>
pub var _arr_8 = [_]Node{ .{ .text = "clear", .font_size = 11, .text_color = Color.rgb(100, 116, 139) } };
// tsz:l08b_timer_scheduler.tsz:95 — <Box>
pub var _arr_9 = [_]Node{ .{ .style = .{ .padding = 8, .background_color = Color.rgb(30, 58, 95), .border_radius = 6 }, .handlers = .{ .js_on_press = "step()" }, .children = &_arr_4 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(45, 30, 95), .border_radius = 6 }, .handlers = .{ .js_on_press = "fireDebounce()" }, .children = &_arr_5 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(59, 42, 10), .border_radius = 6 }, .handlers = .{ .js_on_press = "fireThrottle()" }, .children = &_arr_6 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(30, 59, 45), .border_radius = 6 }, .handlers = .{ .js_on_press = "demoRateLimit()" }, .children = &_arr_7 }, .{ .style = .{ .padding = 8, .background_color = Color.rgb(30, 41, 59), .border_radius = 6 }, .handlers = .{ .js_on_press = "clearLog()" }, .children = &_arr_8 } };
// tsz:l08b_timer_scheduler.tsz:115 — <ScrollView>
pub var _arr_11 = [_]Node{ .{ .style = .{ .gap = 2 } } };
// tsz:l08b_timer_scheduler.tsz:78 — <Box>
pub var _arr_12 = [_]Node{ .{ .style = .{ .flex_direction = .row, .justify_content = .space_between, .align_items = .center }, .children = &_arr_0 }, .{ .style = .{ .flex_direction = .row, .gap = 10 }, .children = &_arr_3 }, .{ .style = .{ .flex_direction = .row, .gap = 6, .flex_wrap = .wrap }, .children = &_arr_9 }, .{ .text = "Debounce: fires 3 ticks after last call. Throttle: max once per 5 ticks.", .font_size = 10, .text_color = Color.rgb(71, 85, 105) }, .{ .style = .{ .overflow = .scroll, .flex_grow = 1, .gap = 2 }, .children = &_arr_11 } };
// [origin:l08b_timer_scheduler:root]
pub var _root = Node{ .style = .{ .background_color = Color.rgb(15, 23, 42), .width = -1, .height = -1, .padding = 16, .gap = 12, .overflow = .hidden }, .children = &_arr_12 };

