//! Generated by tsz compiler — 74_per_corner_border_radius [nodes.zig]
//! Source: 74_per_corner_border_radius.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const layout = api;
const Node = api.Node;
const Style = api.Style;
const Color = api.Color;

// [origin:74_per_corner_border_radius:nodes]
// ── Generated node tree ─────────────────────────────────────────
// tsz:74_per_corner_border_radius.tsz:8 — <Box>
pub var _arr_0 = [_]Node{ .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(76, 175, 80), .border_top_left_radius = 20 } }, .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(33, 150, 243), .border_top_right_radius = 20 } }, .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(255, 152, 0), .border_bottom_right_radius = 20 } }, .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(244, 67, 54), .border_bottom_left_radius = 20 } } };
// tsz:74_per_corner_border_radius.tsz:16 — <Box>
pub var _arr_1 = [_]Node{ .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(156, 39, 176), .border_top_left_radius = 20, .border_bottom_right_radius = 20 } }, .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(0, 188, 212), .border_top_right_radius = 20, .border_bottom_left_radius = 20 } } };
// tsz:74_per_corner_border_radius.tsz:22 — <Box>
pub var _arr_2 = [_]Node{ .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(233, 30, 99), .border_top_left_radius = 16, .border_top_right_radius = 16, .border_bottom_right_radius = 16 } }, .{ .style = .{ .width = 80, .height = 80, .background_color = Color.rgb(103, 58, 183), .border_top_left_radius = 16, .border_top_right_radius = 16, .border_bottom_left_radius = 16 } } };
// tsz:74_per_corner_border_radius.tsz:28 — <Box>
pub var _arr_3 = [_]Node{ .{ .text = "0, 10, 30, 50", .text_color = Color.rgb(255, 255, 255), .font_size = 10 } };
// tsz:74_per_corner_border_radius.tsz:33 — <Box>
pub var _arr_4 = [_]Node{ .{ .text = "Tab shape", .text_color = Color.rgb(255, 255, 255), .font_size = 12 } };
// tsz:74_per_corner_border_radius.tsz:38 — <Box>
pub var _arr_5 = [_]Node{ .{ .text = "Bordered", .text_color = Color.rgb(255, 255, 255), .font_size = 10 } };
// tsz:74_per_corner_border_radius.tsz:3 — <Box>
pub var _arr_6 = [_]Node{ .{ .text = "WPT: per-corner border-radius", .font_size = 18 }, .{ .text = "VERIFY: Individual corners round independently", .font_size = 10, .text_color = Color.rgb(136, 136, 136) }, .{ .text = "borderTopLeftRadius only", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .gap = 8 }, .children = &_arr_0 }, .{ .text = "Diagonal corners rounded", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .gap = 8 }, .children = &_arr_1 }, .{ .text = "Three corners rounded — one sharp", .font_size = 11 }, .{ .style = .{ .flex_direction = .row, .gap = 8 }, .children = &_arr_2 }, .{ .text = "Different radii per corner", .font_size = 11 }, .{ .style = .{ .width = 120, .height = 80, .background_color = Color.rgb(76, 175, 80), .border_top_left_radius = 0, .border_top_right_radius = 10, .border_bottom_right_radius = 30, .border_bottom_left_radius = 50, .overflow = .auto }, .children = &_arr_3 }, .{ .text = "Pill top-half — only top corners rounded", .font_size = 11 }, .{ .style = .{ .width = 200, .height = 40, .background_color = Color.rgb(33, 150, 243), .border_top_left_radius = 20, .border_top_right_radius = 20, .overflow = .auto }, .children = &_arr_4 }, .{ .text = "Per-corner with border", .font_size = 11 }, .{ .style = .{ .width = 100, .height = 60, .background_color = Color.rgb(51, 51, 51), .border_width = 2, .border_color = Color.rgb(255, 152, 0), .border_top_left_radius = 20, .border_bottom_right_radius = 20, .overflow = .auto }, .children = &_arr_5 } };
// [origin:74_per_corner_border_radius:root]
pub var _root = Node{ .style = .{ .width = -1, .height = -1, .flex_direction = .column, .padding = 10, .gap = 8, .overflow = .hidden }, .children = &_arr_6 };

