//! Generated by tsz compiler — d38_arrow_default_params [handlers.zig]
//! Source: d38_arrow_default_params.tsz

const std = @import("std");
const api = @import("framework/api.zig");
const qjs_runtime = api.qjs_runtime;

// [origin:d38_arrow_default_params:handlers]
// ── Event handlers ──────────────────────────────────────────────
// [origin:d38_arrow_default_params:handler:_handler_press_0]
pub fn _handler_press_0() void {
    qjs_runtime.callGlobal("runTests");
}

// [origin:d38_arrow_default_params:handler:_handler_press_1]
pub fn _handler_press_1() void {
    qjs_runtime.callGlobal("addMore");
}

